### ISSUE TITLE
Add "Provides: VIRTUALBOX-GUEST-MODULES, WIREGUARD-MODULE" for linux 5.6

### ISSUE THREAD

**Issue by barfin** [Frogging-Family/linux-tkg#1]
since these modules are now in upstream

**Comment by Tk-Glitch** [comment]
Both are already built as modules in linux56-tkg.

Virtualbox guest: https://github.com/Frogging-Family/linux-tkg/blob/master/linux56-tkg/linux56-tkg-config/config.x86_64#L8233

Wireguard: https://github.com/Frogging-Family/linux-tkg/blob/master/linux56-tkg/linux56-tkg-config/config.x86_64#L2909

**Comment by openglfreak** [comment]
See `provides` of https://www.archlinux.org/packages/staging/x86_64/linux/

**Comment by Tk-Glitch** [comment]
Oh, *sigh* I was being distracted
