### ISSUE TITLE
PATCH-RFC-x86-mm-pat-Restore-large-pages-after-fragmentation.mypatch FAILED

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#10]
-> Applying your own linux-5.6 patch /mnt/BigData/linux-tkg/linux56-tkg/PATCH-RFC-x86-mm-pat-Restore-large-pages-after-fragmentation.mypatch
  -> 
  -> ######################################################
patching file arch/x86/include/asm/pgtable_types.h
patching file arch/x86/mm/pat/set_memory.c
Hunk #1 FAILED at 340.
Hunk #2 succeeded at 1072 (offset 1 line).
Hunk #3 succeeded at 2082 (offset 4 lines).
1 out of 3 hunks FAILED -- saving rejects to file arch/x86/mm/pat/set_memory.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done

**Comment by openglfreak** [comment]
Should be solved by commit Frogging-Family/community-patches@d803a6bd8557461ef6f68743031a95f452fa28be

**Comment by Tk-Glitch** [comment]
Thank you @openglfreak ❤️
