### ISSUE TITLE
graysky2 kernel_compiler_patch do not work anymore

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#1002]
graysky2 kernel compiler patches have changed. They do not work anymore because keywords have changed.

e.g.

```
  44. Intel-x86-64-v2 (MINTEL_CPU_V2) (NEW)
  45. Intel-x86-64-v3 (MINTEL_CPU_V3) (NEW)
  46. Intel-x86-64-v4 (MINTEL_CPU_V4) (NEW)
```
https://github.com/graysky2/kernel_compiler_patch/commit/28b622810a5568407666d030906e72382f28eabb

**Comment by mabod** [comment]
This is not fixed. At least not for `_processor_opt="generic_v3"`. This was working before. But now it results only in 
`-march=x86-64`

This is probably because the keywords in graysky2's patch have changed. it is now called `MINTEL_CPU_V3`

**Comment by mabod** [comment]
I did experiment with the "prepare" script. It works fine if I do the following:

add `INTEL_CPU_V3` to `_cpu_marchs`:

`_cpu_marchs+=("generic_cpu" "generic_cpu2" "INTEL_CPU_V3" "generic_cpu4")`

and change `_generic_march_map` to

`["generic_v3"]="INTEL_CPU_V3"`

When I do this the kernel is compiled with `-march=x86-64-v3`

**Comment by Tk-Glitch** [comment]
Generic_vx is gone so yeah obviously you'll now want to specify the intel or amd _vx target.
Those entries will get nuked contextually in the next couple commits and will only be available on some legacy trees.

In your case, setting `_processor_opt="intel_cpu_v3"` should give the expected result.
