### ISSUE TITLE
[Feature Request] Add support for genpatches

### ISSUE THREAD

**Issue by blackteahamburger** [Frogging-Family/linux-tkg#1006]
[genpatches](https://dev.gentoo.org/~mpagano/genpatches/) is applied to Gentoo's Linux kernel packages. It will be good to support it (and make it default for `_distro=Gentoo`). This will solve:

> If you're running openrc, you'll want to set _configfile="running-kernel" to use your current kernel's defconfig instead of Arch's. Else the resulting kernel won't boot.

Download via: https://dev.gentoo.org/~mpagano/dist/genpatches/genpatches-${KV_MAJOR}.${KV_MINOR}-${K_GENPATCHES_VER}.{base, extras}.tar.xz (e.g. https://dev.gentoo.org/~mpagano/dist/genpatches/genpatches-6.11-1.{base, extra}.tar.xz). There's also experimental patch to enable cpu optimizations but not necessary because it has already been included.

**Comment by mabod** [comment]
I am just a user commenting here. My guess is, that the gentoo kernel patch will not easily apply. 

E.g. the patch for kernel 6.10.11. https://gitweb.gentoo.org/proj/linux-patches.git/commit/?h=6.10

It starts with:

```
+diff --git a/Makefile b/Makefile
+index 9b4614c0fcbb68..447856c43b3275 100644
+--- a/Makefile
++++ b/Makefile
+@@ -1,7 +1,7 @@
+ # SPDX-License-Identifier: GPL-2.0
+ VERSION = 6
+ PATCHLEVEL = 10
+-SUBLEVEL = 10
++SUBLEVEL = 11
+ EXTRAVERSION =
+ NAME = Baby Opossum Posse
```

It looks like that this patch needs kernel 6.10.10 as the base. 

Same is true for the patch for 6.6.52. It need 6.6.51 as the base. 

Have you tried to apply the gentoo patches as user patches with linux-tkg? I pretty sure this will fail.

**Comment by Tk-Glitch** [comment]
I just pushed a "test" for kernel 6.11 only for now. Setting `Gentoo` as distro will trigger the kconfig patch (and a couple minor ones that should improve compat).
There's a pending question from me about `GENTOO_LINUX_INIT_SYSTEMD`. If nobody will ever use that on Gentoo we could simply leave it as is (disabled, same as Gentoo's own).
Please give feedback and if it's all fine I'll propagate the patch to other kernel revisions.

**Comment by blackteahamburger** [comment]
> I just pushed a "test" for kernel 6.11 only for now. Setting `Gentoo` as distro will trigger the kconfig patch (and a couple minor ones that should improve compat). There's a pending question from me about `GENTOO_LINUX_INIT_SYSTEMD`. If nobody will ever use that on Gentoo we could simply leave it as is (disabled, same as Gentoo's own). Please give feedback and if it's all fine I'll propagate the patch to other kernel revisions.

"No one uses `GENTOO_LINUX_INIT_SYSTEMD`" has no basis because Gentoo has official support for systemd (and by the way I use systemd). Users should be allowed to choose between `GENTOO_LINUX_INIT_SCRIPT` and `GENTOO_LINUX_INIT_SYSTEMD`

**Comment by Tk-Glitch** [comment]
Thanks! You could change it easily with a config fragment, it's just a question about what should we default to. If it's common practice to switch it, indeed we should make that a simple switch. Thanks for the input!
