### ISSUE TITLE
6.11 failed to compile - RPM build errors Bad exit status from /var/tmp/rpm-tmp.rjB4zg

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#1009]
Hello, any evidence about this issue?

![Screenshot_20240920_024031](https://github.com/user-attachments/assets/8725b708-5325-40cc-a40b-0cd34cddde0b)

[customization.cfg.txt](https://github.com/user-attachments/files/17070352/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/17070353/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/17070354/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/17070355/system-info.txt)

Operating System: Fedora Linux 41
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.10.9_tkg_pds (64-bit)
Graphics Platform: Wayland

**Comment by Tk-Glitch** [comment]
Signing being a pita again? :disappointed:

**Comment by Everest10** [comment]
> Signing being a pita again? 😞

Hello, trying to compile the EEVDF the same raise same issue.

**Comment by Everest10** [comment]
failed to compile 6.11.1 on fedora 41

![Screenshot_20240930_142104](https://github.com/user-attachments/assets/e5bce07e-9d24-4883-91bf-7b849590a28a)
[system-info.txt](https://github.com/user-attachments/files/17193924/system-info.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/17193925/shell-output.log.txt)
[customization.cfg.txt](https://github.com/user-attachments/files/17193926/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/17193927/prepare.log.txt)

**Comment by Everest10** [comment]
$ sudo dnf install openssl-devel-engine hostname perl bison ccache dwarves elfutils-devel elfutils-libelf-devel fedora-packager fedpkg flex gcc-c++ git libXi-devel lz4 make ncurses-devel openssl openssl-devel perl-devel perl-generators pesign python3-devel qt5-qtbase-devel rpm-build rpmdevtools schedtool zstd bc rsync -y ${clang_deps} -y

Is compiling after run the command above.
