### ISSUE TITLE
_x86_64_isalvl config value?

### ISSUE THREAD

**Issue by damachine** [Frogging-Family/linux-tkg#1011]
hi, i am little confuse what is the right value, because in the .cfg for _x86_64_isalvl="" i should enter value 3 for x86-64-v3. but when i let it blank the promt give me only this options? thx
......
  -> Applying Sched_ext support patch
  -> Applying Glitched CFS/EEVDF patch
  -> Using archlinux's default config file for kernel 6.11
    Please select the desired x86_64 compiler ISA level
    You can find the best version for your CPU by running one of the following:
  -> /lib/ld-linux-x86-64.so.2 --help | grep supported
  -> /lib64/ld-linux-x86-64.so.2 --help | grep supported
      > 0) x86-64-v1
        1) x86-64-v2
        2) x86-64-v3
[0-2]: 3
Wrong selection: select any number in 0-2

**Comment by Tk-Glitch** [comment]
The prompt asks for the number in the options array, so values `0`, `1` or `2`. The config file asks for the level directly, so values `1`, `2` or `3`.
