### ISSUE TITLE
Can't install kernel after the installtion on Arch

### ISSUE THREAD

**Issue by blunelsongamer** [Frogging-Family/linux-tkg#1013]
Devel was installed, and I also followed the troubleshoot guide, and nothing work out.

**Everything work fine, until when it supposed to say exit cleanup. Both the makepkg -si and install.sh script**
 - Arch
 - Defaulting to kernel.org git mirror
 -> Argument not recognised, options are:
        - config : interactive script that shallow clones the linux kernel git tree into the folder $_kernel_work_folder, then applies extra patches and prepares the .config file
                   by copying the one from the currently running linux system and updates it.
        - install : does the config step, proceeds to compile, then prompts to install
                    - 'DEB' distros: it creates .deb packages that will be installed then stored in the DEBS folder.
                    - 'RPM' distros: it creates .rpm packages that will be installed then stored in the RPMS folder.
                    - 'Generic' distro: it uses 'make modules_install' and 'make install', uses 'dracut' to create an initramfs, then updates grub's boot entry.
        - uninstall-help : [RPM and DEB based distros only], lists the installed kernels in this system, then gives hints on how to uninstall them manually.
 -> exit cleanup done
(install.sh script)
 - Too long to do so.

**Comment by blunelsongamer** [comment]
NEW LOG from makepkg -si


           .---.`               `.---.
        `/syhhhyso-           -osyhhhys/`
       .syNMdhNNhss/``.---.``/sshNNhdMNys.
       +sdMh.`+MNsssssssssssssssNM+`.hMds+
       :syNNdhNNhssssssssssssssshNNhdNNys:
        /ssyhhhysssssssssssssssssyhhhyss/
        .ossssssssssssssssssssssssssssso.
       :sssssssssssssssssssssssssssssssss:
      /sssssssssssssssssssssssssssssssssss/   Linux-tkg
     :sssssssssssssoosssssssoosssssssssssss:        kernels
     osssssssssssssoosssssssoossssssssssssso
     osssssssssssyyyyhhhhhhhyyyyssssssssssso
     /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
      smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
       /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
        `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
           `-+shdNNNNNNNNNNNNNNNdhs+-`
                 `.-:///////:-.`
Defaulting to kernel.org git mirror
  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
      > 0) v6.11
        1) v6.10.11
        2) v6.9.12
        3) v6.8.12
        4) v6.7.12
        5) v6.6.52
        6) v6.5.13
        7) v6.4.16
        8) v6.1.111
        9) v5.15.167
        10) Another (no longer maintained upstream)
[0-10]: 
    Selected: v6.11
  -> Which CPU sched variant do you want to build/install?
  -> Project C (pds) / BMQ (bmq) is usually a good balance for gaming.
  -> Select "eevdf" (linux kernel's default) if unsure.
      > 0) EEVDF (Earliest Eligible Virtual Deadline First scheduler) Linux kernel's default for ≥ 6.6
        1) BORE (Burst-Oriented Response Enhancer) CPU Scheduler
        2) Project C / PDS
        3) Project C / BMQ
[0-3]: 
    Selected: EEVDF (Earliest Eligible Virtual Deadline First scheduler) Linux kernel's default for ≥ 6.6
    Which compiler do you want to use?
      > 0) GCC (recommended)
        1) Clang/LLVM
[0-1]: 
    Selected: GCC (recommended)
github.com      https://github.com/gregkh/linux.git (fetch)
github.com      https://github.com/gregkh/linux.git (push)
torvalds        https://github.com/torvalds/linux.git (fetch)
torvalds        https://github.com/torvalds/linux.git (push)
googlesource.com        https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable (fetch)
googlesource.com        https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable (push)
kernel.org      https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (fetch)
kernel.org      https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (push)
torvalds        https://github.com/torvalds/linux.git (fetch)
torvalds        https://github.com/torvalds/linux.git (push)
  -> Fetching tag: v6.11 from mirror kernel.org
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), 557 bytes | 557.00 KiB/s, done.
  -> Checking out tag: v6.11
  ->    in the work folder: /home/blu/linux-tkg//linux-src-git
Preparing worktree (detached HEAD 98f7e32f2)
Updating files: 100% (85805/85805), done.
HEAD is now at 98f7e32f2 Linux 6.11
==> WARNING: The package group has already been built, installing existing packages...
==> Installing linux611-tkg-eevdf package group with pacman -U...
[sudo] password for blu: 
loading packages...
warning: linux611-tkg-eevdf-6.11.0-273 is up to date -- reinstalling
warning: linux611-tkg-eevdf-headers-6.11.0-273 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) linux611-tkg-eevdf-6.11.0-273  linux611-tkg-eevdf-headers-6.11.0-273

Total Installed Size:  267.23 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                                     [####################################] 100%
(2/2) checking package integrity                                   [####################################] 100%
(2/2) loading package files                                        [####################################] 100%
(2/2) checking for file conflicts                                  [####################################] 100%
(2/2) checking available disk space                                [####################################] 100%
:: Processing package changes...
(1/2) reinstalling linux611-tkg-eevdf                              [####################################] 100%
(2/2) reinstalling linux611-tkg-eevdf-headers                      [####################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating module dependencies...
(3/4) Cleaning up...
(4/4) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux611-tkg-eevdf.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux611-tkg-eevdf -g /boot/initramfs-linux611-tkg-eevdf.img
==> Starting build: '6.11.0-273-tkg-eevdf'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [microcode]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux611-tkg-eevdf.img'
  -> Early uncompressed CPIO image generation successful
==> Initcpio image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux611-tkg-eevdf.preset: 'fallback'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux611-tkg-eevdf -g /boot/initramfs-linux611-tkg-eevdf-fallback.img -S autodetect
==> Starting build: '6.11.0-273-tkg-eevdf'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [microcode]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
==> WARNING: Possibly missing firmware for module: 'ast'
  -> Running build hook: [keyboard]
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
==> WARNING: consolefont: no font found in configuration
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'bfa'
==> WARNING: Possibly missing firmware for module: 'qed'
==> WARNING: Possibly missing firmware for module: 'wd719x'
==> WARNING: Possibly missing firmware for module: 'qla1280'
==> WARNING: Possibly missing firmware for module: 'qla2xxx'
==> WARNING: Possibly missing firmware for module: 'aic94xx'
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux611-tkg-eevdf-fallback.img'
  -> Early uncompressed CPIO image generation successful
==> Initcpio image generation successful
  -> exit cleanup done

**Comment by AdelKS** [comment]
Your second message shows that everything is working normally ?

**Comment by blunelsongamer** [comment]
Yeah, it was an reinstall, but it didn't take me to the install new terminal? Section. It just kicks me off for exiting clean up.

**Comment by Tk-Glitch** [comment]
First, install.sh **shouldn't** be used on Arch and other pacman distros. The makepkg path is more than recommended on those.

The installation seemed to go just fine. CPIO image generated in your `/boot` and all.
If you want to actually rebuild, you'll want to run `makepkg -sif` (the -f flag will force rebuilding packages). But nothing seems wrong here.

You might be talking about adding the entry to your bootloader maybe?
That's not automated (since you can have various bootloaders) and you'll need to do that step by hand, depending on your bootloader.
For GRUB, which is the most common, it would be `grub-mkconfig -o /boot/grub/grub.cfg`. For the others I invite you to check out the Arch wiki https://wiki.archlinux.org/title/Category:Boot_loaders.

And if your issue is none of the above, please describe it more thoroughly as it's a bit unclear right now :D

**Comment by blunelsongamer** [comment]
HI!

Should clarify that I did makepkg again, (it was on an new fresh arch install btw).

Figured the install sh script couldn't work, so I did the makepkg did, and I even updated the grub.

The grub DOES recognize the Linux tkg, but after I reboot it, nothing...unless, that's where I realized it was in the advanced options of the the Arch grub menu.

I thought the Linux tkg kernel immediately would show up at the start of the grub, but now I know I must boot it from the advanced options, and it all works well as expected.

I swore I thought it should be at the start option without needing to go to the advanced options, but thank you for trying to help with the grub update!

**Comment by Tk-Glitch** [comment]
You can change the config so grub boots on your last selection instead of going through advanced every time, but yes, we're not attempting to replace the stock kernel so you still have it at the very least as a fallback in case anything goes wrong, and the additional entries will land by default in advanced.
Glad you figured it out!
