### ISSUE TITLE
 6.11.1 failed to compile - RPM build errors Bad exit status

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#1016]
failed to compile 6.11.1 on fedora 41

![Screenshot_20240930_142104](https://github.com/user-attachments/assets/c8ac2150-9ec5-45b9-bc61-bcdd63383bd4)

[system-info.txt](https://github.com/user-attachments/files/17193936/system-info.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/17193937/shell-output.log.txt)
[customization.cfg.txt](https://github.com/user-attachments/files/17193938/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/17193939/prepare.log.txt)

6.10.12 too.

**Comment by Everest10** [comment]
$ sudo dnf install openssl-devel-engine hostname perl bison ccache dwarves elfutils-devel elfutils-libelf-devel fedora-packager fedpkg flex gcc-c++ git libXi-devel lz4 make ncurses-devel openssl openssl-devel perl-devel perl-generators pesign python3-devel qt5-qtbase-devel rpm-build rpmdevtools schedtool zstd bc rsync -y ${clang_deps} -y

Is compiling after run the command above.

**Comment by AdelKS** [comment]
Good!

**Comment by AdelKS** [comment]
Also, please do not open different issues for the same problem. Unfortunately it won't make us treat things any faster. I try to handle them whenever I have enough spare time. Thanks!
