### ISSUE TITLE
Didn't worked on New Tuxedo OS-4

### ISSUE THREAD

**Issue by blunelsongamer** [Frogging-Family/linux-tkg#1027]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on? Tuxedo OS
 - A clear and concise description of what the bug is. So i did the exact steps as told, and it was installing. It did have some erros, but mainly the ethernet. But it stop because of debian rules binary??? Idk the situation behind this. 
 - Attach the contents of your logs folder by drag & dropping each file into this message.
 
[log.txt](https://github.com/user-attachments/files/17591947/log.txt)

**Comment by ptr1337** [comment]
```
cc1: error: drivers/net/ethernet/dnet.c: Input/output error
(null):0: confused by earlier errors, bailing out
```

Seems like either that something errord before. You didnt provide the full log
