### ISSUE TITLE
dracut searches for gzip compressed modules on 6.12 debain 13 trixie/sid & Ubuntu 24.10

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/linux-tkg#1033]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?    **Debian 13 trixie/sid**
 - A clear and concise description of what the bug is.
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

wanted to try out 6.12 but got the following errors. even though it still built the kernel but about 1/2 the size

[customization.cfg.txt](https://github.com/user-attachments/files/17808057/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/17808058/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/17808059/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/17808061/system-info.txt)
[error.txt](https://github.com/user-attachments/files/17808084/error.txt)

error.txt is the missing part to the shell-output.log it seems to have not included all the information

is this just me or is someone else having the same problems? with not all of the kernel mods loading.

**Comment by Tk-Glitch** [comment]
Since you're using the default config file (which is based on Arch's), modules are compressed with zstd. It seems dracut expects gzip compressed modules here so it fails finding them.
Might be worth trying with `_configfile="running-kernel"` in your `customization.cfg` to use Debian's defconfig as base.

**Comment by cr1ogen** [comment]
> is this just me or is someone else having the same problems? with not all of the kernel mods loading.

I have the same problems, Debian Sid

**Comment by rchris494** [comment]
> > is this just me or is someone else having the same problems? with not all of the kernel mods loading.
> 
> I have the same problems, Debian Sid

i did tk's temp fix. it did build a kernel that i could use. i have only been on it a few hours so. not sure if it is 100%, but its a temporary fix until whoever in debian needs to catch up with the game.

**Comment by Tk-Glitch** [comment]
@AdelKS This is annoying. Thoughts on enforcing gz compression for deb as a bandaid for now? It seems Debian 13 should ship a new enough dracut to support zstd :thinking:

**Comment by rchris494** [comment]
well i wanted to test the fix out on 6.12.1. after not being able to boot at all. my system would hang with /scripts/init-bottom & /scripts/local-bottom. even on an older kernel 6.11.8. i did finally manage to get the system to boot up. thinking the script problem might have been related to initramfs i ran sudo update-initramfs -u -k all and ended up with the attached file error with 6.12.1

[bad.txt](https://github.com/user-attachments/files/17879046/bad.txt)

**Comment by Slaviusz** [comment]
I used the following .myfrag to fix dracut unable to find .gz modules on Ubuntu 24.10:
```
# CONFIG_MODULE_COMPRESS_GZIP is not set
CONFIG_MODULE_COMPRESS_ZSTD=y
```

**Comment by Tk-Glitch** [comment]
Okay what the hell now :D

**Comment by Tk-Glitch** [comment]
Take 2

**Comment by Slaviusz** [comment]
Just to give some context:
I used `_configfile=""` in customization.cfg.
When I was building linux-tkg I had only generic ubuntu kernel installed (24.10).

When I do `grep CONFIG_MODULE_COMPRESS /boot/config-6.11.0-9-generic`  I get:
```
# CONFIG_MODULE_COMPRESS_NONE is not set
# CONFIG_MODULE_COMPRESS_GZIP is not set
# CONFIG_MODULE_COMPRESS_XZ is not set
CONFIG_MODULE_COMPRESS_ZSTD=y
```
Indeed generic ubuntu kernel (24.10) uses `.ko.zst` zstd compressed modules by default.

**Comment by rchris494** [comment]
everything seems to be working once again. thanks for all your hard work!
