### ISSUE TITLE
6.12.2 with enabled sched_ext won't boot

### ISSUE THREAD

**Issue by hellsgod** [Frogging-Family/linux-tkg#1041]
Refer to here: https://lore.kernel.org/lkml/CAHk-=whGd0dfaJNiWSR60HH5iwxqhUZPDWgHCQd446gH2Wu0yQ@mail.gmail.com/

Revert this https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.12.y&id=09162013082267af54bb39091b523a8daaa28955

Maybe also this: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.12.y&id=acf588f9b6fb560e986365c6b175aaf589ef1f2a

Or disable sched_ext

**Comment by damachine** [comment]
hi with 6.12.2 arch did`t boot.  how do i disable sched_ext? after compile and install. i am now in a chroot and compile lts kerenel hope itt works again.

**Comment by mabod** [comment]
How do I disable sched_ext?
