### ISSUE TITLE
Is Commit bab5159 still needed for 6.12.3

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#1042]
Kernel 6.12.2 was not booting due to an issue with sched_ext.

commit https://github.com/Frogging-Family/linux-tkg/commit/bab5159471a507bfe9842149e80f4929f6be5dd4 fixed this by adding patches to `0012-misc-additions.patch` for the 6.12 kernel series. 

Is this still needed for kernel 6.12.3?

**Comment by hellsgod** [comment]
No.

**Comment by mabod** [comment]
Can someone from the linxu-tkg team please explain. What is this patch actually doing to kernel 6.12.[345]? Will it be removed soon?

**Comment by ptr1337** [comment]
> Can someone from the linxu-tkg team please explain. What is this patch actually doing to kernel 6.12.[345]? Will it be removed soon?

How about just sending a PR?

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/8c9704fc52c247bd7690ff9ea03e500a5bb8809e
Sorry for the delay.

**Comment by mabod** [comment]
> > Can someone from the linxu-tkg team please explain. What is this patch actually doing to kernel 6.12.[345]? Will it be removed soon?
> 
> How about just sending a PR?

Ok. Didnt think about it. Next time I will do that.
