### ISSUE TITLE
AUR 404 for scx-scheds

### ISSUE THREAD

**Issue by 32bitx64bit** [Frogging-Family/linux-tkg#1048]
Probably want to remove the reference to a AUR package that just 404's

In the
" Its current implementation doesn't allow for injecting additional schedulers at kernel level, and requires replacing it. Only one scheduler can be patched in at a time. However, using [Sched-ext](https://github.com/sched-ext/scx), it's possible to inject CPU schedulers at runtime. We offer support for it on ≥ 6.8 by default. Arch users can find scx schedulers on the [AUR](https://aur.archlinux.org/packages/scx-scheds) thanks to @sirlucjan (for persistence, set scheduler in "/etc/default/scx" and enable the scx service). "

**Comment by sirlucjan** [comment]
scx-scheds was moved to Arch Linux repository.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/cf4a8139f0e82595c125f173c498b51a03d517b8
