### ISSUE TITLE
AMD Ryzen 5000 and RX 6000

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#106]
Is it most likely that all of AMD's software performance optimisation will be integrated into the Linux Kernel, so you benefit from all their new technologies?

**Comment by PedroHLC** [comment]
![Here, this is for your](https://i.pinimg.com/736x/1a/1a/6c/1a1a6c08b0ce95615a10b91ff604ecb9.jpg)

**Comment by Axilot** [comment]
Is that a no?

**Comment by AdelKS** [comment]
I will actually tell you what I think I know. I may be wrong in some of what I am about to say, please correct me if so.

The linux kernel is agnostic of different kinds of CPUs as long as they have the same [architecture](https://en.wikipedia.org/wiki/List_of_CPU_architectures), in the case of regular computers and laptops, it's x86-64 + extensions to it. So no matter how physically different CPUs are, the kernel has access to/sees only the "instructions" CPUs offer, and doesn't "see" them as physically different. About the extra extensions: each CPU supports some of them. And for the kernel to use them CPU makers usually send patches to uncover them to the Linux kernel.

One thing I am not sure about is the cache architecture, I have no idea if the kernel is aware of it and has control over it.

**Comment by Axilot** [comment]
Yeah, that was my question. Because they mentioned that they have made connections between the CPU to the gddr6 memory of the graphics card possible. But this might just be the work for the app developers i guess

**Comment by AdelKS** [comment]
You mean the "direct load" thing so game can load directly game data from the hard drive to the VRAM. I have no clue how that works, but yes for sure somewhere something needs to be uncovered.

**Comment by Axilot** [comment]
But sadly they didn't showed some Vulkan Rendering optimised for RX 6000 :-C

**Comment by thotypous** [comment]
![vanilla rich chocolate cookies](https://embed.widencdn.net/img/mccormick/u8pntu7ahp/2028x1141px/Vanilla_rich_chocolate_chip_cookies_004.jpg)

**Comment by Axilot** [comment]
Why cookies? I mean i like them but why?

**Comment by SveSop** [comment]
It is a bit "unknown" when it comes to this new tech. I am not sure if it is a chipset kind of thing, or all baked into the gpu driver, or what it is - yet.

Depending on how this new "direct load" thing is implemented (chipset/gpu and/or cpu), it might take a while, but the cpu in itself will probably be very well supported from launch, although so far there is no specific "znver3" compiler optimizations, so it will probably be a good 6+ months until one can expect specific optimizations for the cpu i think. (Hardly a huge issue tho).
