### ISSUE TITLE
I found gcc-10 pathes for linux56, I have no idea if these are good for linux-tkg

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#11]
I found gcc-10 patches from https://gitlab.com/sirlucjan/kernel-patches/-/tree/master/5.6/gcc10-patches-sep and https://gitlab.com/sirlucjan/kernel-patches/-/tree/master/5.6/gcc10-patches

I have no idea if these patches are good for linux-tkg or not. Maybe have a look.

**Comment by Tk-Glitch** [comment]
Those are just warning (cosmetic) fixes/workarounds and won't actually change the resulting code (except for one of them). Since they aren't changing anything for the end-user I don't think we really need any of those 🐸 
They will most likely end up upstream in a form or another.

**Comment by Tk-Glitch** [comment]
Those were since backported upstream as expected. Closing.
