### ISSUE TITLE
Kernel not working when compiling with llvm

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#112]
If i want to compile the kernel with all of your patches applied i can't boot the kernel without any issues. However when i keep with gcc everything goes correct and its working how expected.

**Comment by kattjevfel** [comment]
What kernel version did you pick? Options? Distro? llvm/gcc version? What issues?

**Comment by Axilot** [comment]
As i mentioned it's with llvm in the configuration. My distro: Arch, Kernel version doesn't matter cause i tried both 5.9 and 5.10rc, so i guess it's working on none. And what issue? If i want to boot my arch installation with the llvm kernel installed it loads up as normal but then nothing happens. However when i compile the same kernel and change it to gcc i can normally boot.

**Comment by kattjevfel** [comment]
> it loads up as normal but then nothing happens. 

Please define "nothing happens", blank screen? does it just go completely blank after your bootloader? Not a single error?

**Comment by Tk-Glitch** [comment]
Nvidia?

**Comment by Axilot** [comment]
Having an nvidia card, yes

**Comment by Tk-Glitch** [comment]
I would assume you'll need to compile the nvidia modules with llvm, if that's even possible (I doubt it). Have you tried booting your llvm-built kernel to a TTY?

**Comment by Axilot** [comment]
not tried yet 
Thanks for your help. I guess ill then just stick with gcc until i upgraded my pc to full amd.

**Comment by Tk-Glitch** [comment]
![Screenshot_20201106_183923](https://user-images.githubusercontent.com/741977/98397307-73b29f00-205f-11eb-8f6c-03c459a43d50.png)
Tested it on my end on intel graphics (kernel driver), and can confirm it works *fine*. I have had to compile my dkms modules (`tp_smapi` and `acpi_call`, it's a thinkpad) with clang (and fixing them by hand was pretty annoying, as they are expecting gcc).
I'd say it's worthless at this point in time (also considering resulting kernels are slower than GCC-built ones on x86_64).

**Comment by Axilot** [comment]
Ok, thanks for putting your effort into this. Normally i prefer clang but gcc should be fine aswell. Wish you a nice day :-)
