### ISSUE TITLE
How did you made this fancy image in text?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#114]
In your PKGBUILD i can see that you made this beautiful image in text form. Are there tools to make it on your own or do have to put a lot of effort into this by yourself?

**Comment by Tk-Glitch** [comment]
There are various tools to convert images to ASCII such as https://github.com/uvipen/ASCII-generator or https://github.com/LazoCoder/Image-To-ASCII, among hundreds others :frog:

**Comment by Axilot** [comment]
Ah, thank you :D

**Comment by Axilot** [comment]
Am i able to reference to a source in Makefile?

**Comment by PedroHLC** [comment]
Hi @Axilot, for questions like this, please join the Frogging Family discord server, and ask maintainers (like TkG) personally:
https://discord.gg/jRy3Nxk

Otherwise everybody that "watches" this repository is notified for every issue/comment you submit :smile:

**Comment by Tk-Glitch** [comment]
Closing
