### ISSUE TITLE
Requesting clarification regarding _voluntary_preempt and VM performance

### ISSUE THREAD

**Issue by corecontingency** [Frogging-Family/linux-tkg#116]
`_voluntary_preempt` in `customization.cfg`:

`# Setting this to to "true" can improve latency on PDS (at the cost of throughput) and improve throughput on other schedulers (at the cost of latency) - Can improve VMs performance - Kernel default is "false"`

This statement regarding improved VM performance seems a little unclear to me. As stated above, PDS vs. other schedulers seem to have exactly opposite effects when `_voluntary_preempt` is set to `true`. So does the improved VM performance apply to PDS, or to the other schedulers? It doesn't make sense that it could be both, since the effects are exactly the opposite.

**Comment by Tk-Glitch** [comment]
The quirk was only true for UPDS (old, non-project C PDS) so I should update the note. The improved VM performance should apply to all schedulers, however outside of VM usage it used to lower latency on some tasks with UPDS, which never happened on CFS and MuQSS at the time. That being said there was some weird inconsistencies with it enabled on some timing critical tasks such as realtime audio work, even on UPDS.
