### ISSUE TITLE
Speed up the compiling process???

### ISSUE THREAD

**Issue by Ohio2** [Frogging-Family/linux-tkg#117]
Could you please do that? It will take less time._To compile of course!_

**Comment by AdelKS** [comment]
It's already implemented, it uses all the logical cores of your computer.

**Comment by Ohio2** [comment]
Really? I tought it does not.
Normally the linux kernel compiles ~14m

**Comment by Ohio2** [comment]
Gheez, this does not deserve a issue. Closing this

**Comment by AdelKS** [comment]
it's in the option `_force_all_threads` in `customization.cfg`. If you wanna further speed the compilation process, you can use `ccache` and `modprobed-db`. The latter can make you win a lot of time, but you need a well populated database :)
