### ISSUE TITLE
linker 'ld.lld' not found

### ISSUE THREAD

**Issue by cow-killer** [Frogging-Family/linux-tkg#118]
Configuration file is as follows:
https://pastebin.com/QsVY2S2u

Getting this when running the install script (output has been truncated):
```
 -> Copying current kernel's config and running make oldconfig...
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --oldconfig Kconfig
scripts/Kconfig.include:40: linker 'ld.lld' not found
make[1]: *** [scripts/kconfig/Makefile:71: oldconfig] Error 1
make: *** [Makefile:606: oldconfig] Error 2
 -> exit cleanup done
```

Using Pop!_OS. Defining Ubuntu in the config file won't even allow the installer to run.

**Comment by AdelKS** [comment]
`lld` is an executable program. I'd say you simply need to install it, do something like `apt search lld` to find the package, it's part of the LLVM compiler collection.

**Comment by Tk-Glitch** [comment]
You should not use llvm to begin with if you want a stable kernel, but yes you need `lld`, `clang` and `llvm` to be able to build.

**Comment by cow-killer** [comment]
Okay, installation success after installing the necessary packages, closing now.
