### ISSUE TITLE
Option to enable the kernel modules needed by Anbox

### ISSUE THREAD

**Issue by Sukid** [Frogging-Family/linux-tkg#121]
Since the dkms modules no longer work, in order to use Anbox the kernel has to be compiled with these options in the config file:
`CONFIG_ASHMEM=y` 
`CONFIG_ANDROID=y`
`CONFIG_ANDROID_BINDER_IPC=y`
`CONFIG_ANDROID_BINDERFS=y`
`CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"`

While definitely easy enough to add these to config.x86_64 ourselves, it would just be convenient to have an option for it in the .cfg file

**Comment by Sukid** [comment]
I realized it was simple enough to add this in my own PR so I did it. :p
https://github.com/Frogging-Family/linux-tkg/pull/122

**Comment by Tk-Glitch** [comment]
https://github.com/Frogging-Family/linux-tkg#anbox-usage

![Screenshot_20210311_152126](https://user-images.githubusercontent.com/741977/110801381-7b888700-827d-11eb-8f5b-b101fbb5f346.png)
