### ISSUE TITLE
Empty fs/exfat/

### ISSUE THREAD

**Issue by azapicoe** [Frogging-Family/linux-tkg#123]
Im on gentoo, and after ./install.sh config, kernel cant compile with the following error:

```
scripts/kconfig/conf  --syncconfig Kconfig
fs/Kconfig:146: can't open file "fs/exfat/Kconfig"
make[2]: *** [scripts/kconfig/Makefile:71: syncconfig] Error 1
make[1]: *** [Makefile:606: syncconfig] Error 2
make: *** [Makefile:711: include/config/auto.conf.cmd] Error 2
make: *** [include/config/auto.conf.cmd] Se borra el archivo 'include/generated/autoconf.h'
```
(Sorry for the Spanish, last line says: Removing 'include/generated/autoconf.h')

It only happen with linux-5.9

**Comment by azapicoe** [comment]
Working perfectly now. Ty for the quick fix!!

**Comment by Tk-Glitch** [comment]
Great news!

Thanks for confirming. Closing.

**Comment by AdelKS** [comment]
I think the exit cleanup inside the linux git tree, when using `install.sh`, should never be done. Since the script will reset the git code to its original state anyway at each run.
