### ISSUE TITLE
Gaming microstuttering since 5.9.6

### ISSUE THREAD

**Issue by ryester27** [Frogging-Family/linux-tkg#125]
I'm using the linux-tkg-bmq-zen packages from the Arch Linux Chaotic-AUR repo. Ever since 5.9.6, I've been getting unexplainable framerate stuttering in games when using Proton. I've mostly been testing with the games Hades and Sakuna of Rice and Ruin.

5.9.6, 5.9.8, and 5.9.9 all had the issue. When downgrading to 5.9.3, the microstuttering went away. I also tried with the Zen kernel 5.9.9, and I can't reproduce the problem. If there's any other info I can provide to help, please let me know.

**Comment by Tk-Glitch** [comment]
Project C schedulers (namely BMQ and PDS) seemingly regressed with the r1 patchset (see: http://cchalpha.blogspot.com/2020/10/project-c-v59-r1-release.html) so it could be just that. The r2 patchset was merged yesterday so you can either build 5.9.9 with it for a try or wait for 5.9.10 to get it through chaotic-aur.

The Zen kernel is using MuQSS scheduler, which isn't affected by the regression, and chaotic-aur should have builds with it available (the upds scheduler isn't affected either, but I'm not sure chaotic-aur offers builds for it).

**Comment by PedroHLC** [comment]
I've just started building the fresh 5.9.9, all variations should be ready in less than 24h...

**Comment by corecontingency** [comment]
I was getting really bad stuttering in Elite Dangerous (uses proton) using 5.9.8 with PDS. I switched over to CFS for now, but I will give PDS another look now that the patchset was updated...

**Comment by corecontingency** [comment]
Stuttering seems to be fixed in Elite Dangerous for the PDS r2 patchset and 5.9.9! Running great.

**Comment by Tk-Glitch** [comment]
Great news! Enjoy :frog:

**Comment by AdelKS** [comment]
Awesome! Hopefully UPDS will go back to the grave, I moved back to PDS too :D

**Comment by ryester27** [comment]
5.9.10 fixed all stuttering for me. I'll close the issue now
