### ISSUE TITLE
CONFIG_SCHED_DEBUG is uselessly disabled

### ISSUE THREAD

**Issue by drizzt** [Frogging-Family/linux-tkg#13]
Hi,
`CONFIG_SCHED_DEBUG` is disabled when you set _debugdisable, but `CONFIG_LATENCYTOP` is always enabled and `LATENCYTOP` enables `SCHED_DEBUG` so you can disable `LATENCYTOP` too or don't disable `SCHED_DEBUG`

**Comment by Tk-Glitch** [comment]
Well spotted. Thanks!
