### ISSUE TITLE
Anbox optional option doesn't properly install ashmem.

### ISSUE THREAD

**Issue by cryptofyre** [Frogging-Family/linux-tkg#130]
It doesn't seem to actually install ashmem but it seems to install binder just fine. I have verified the options I picked already and I didn't say no to it.

![image](https://user-images.githubusercontent.com/33162551/100037742-9d85f880-2db7-11eb-9509-129de76b48f5.png)

**Comment by Tk-Glitch** [comment]
None should load since they are both built-in, and not modules.

**Comment by PedroHLC** [comment]
:thinking: TkG, can we have this patch? I would like to have them as modules (in my system, not chaotic).
(Also, why wasn't it added as tristate by upstream? 🤷🏻‍♂️ )

**Comment by Tk-Glitch** [comment]
I'll look into it.
