### ISSUE TITLE
5.10.rc7 is failing to build

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/linux-tkg#134]
I've built every other release candidate for 5.10 perfectly fine with this PKGBUILD, and I didn't change anything in the config. No additional patches, just fsync enabled, regular cfs scheduler, etc. ACS patch is off, bcachefs is off, Anbox modules off, basically everything pretty much vanilla. 

This is the error, and it's all there is throughout the scrollback limit of my terminal (which is like 10000 lines or something crazy, I set it really high a while back). 

```
FAILED unresolved symbol __add_to_page_cache_locked
make: *** [Makefile:1170: vmlinux] Error 255
  DESCEND  objtool
  DESCEND  bpf/resolve_btfids
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.btf
  BTF     .btf.vmlinux.bin.o
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  BTFIDS  vmlinux
FAILED unresolved symbol __add_to_page_cache_locked
make: *** [Makefile:1170: vmlinux] Error 255
==> ERROR: A failure occurred in build().
    Aborting...
```

Happy to provide any more info as needed.  

Actually, I just tried running it again, with fsync set to false, just to be sure, and it still fails in the exact same spot with the exact same error. It's weird, because it's seemingly at/near the very end of the process

**Comment by ptTrR** [comment]
Got exactly the same issue.

**Comment by AdelKS** [comment]
It definitely seems like an upstream thing. Wait for the next RC I'd say.

**Comment by gardotd426** [comment]
Well there won't be another one (5.10 stable is supposed to release next
weekend), so hopefully they're aware of the issue.
