### ISSUE TITLE
Inclusion of [PATCH 00/40] Various Polaris fixes and optimizations

### ISSUE THREAD

**Issue by Faalagorn** [Frogging-Family/linux-tkg#137]
I'm waiting for the patches mentioned [here](https://www.phoronix.com/scan.php?page=news_item&px=AMD-Fixes-Up-Polaris-2020) – [[PATCH 00/40] Various Polaris fixes and optimizations
](https://lists.freedesktop.org/archives/amd-gfx/2020-October/054852.html) to come, especially for enablement of ZeroRPM on Polaris. I didn't try to apply any of the patch manually, but would it be possible to include it in any form in any of current linux-tkg kernels?

**Comment by veganvelociraptor** [comment]
I understand it's not helping your current situation as v5.11 isn't released yet. Nevertheless, there's a pull request for these changes to be included in the next kernel: https://lkml.org/lkml/2020/12/10/1753

**Comment by Tk-Glitch** [comment]
5.11 is out now
