### ISSUE TITLE
Error when building 5.10.1-102-tkg-bmq on Arch linux with makepkg

### ISSUE THREAD

**Issue by HippieMitch** [Frogging-Family/linux-tkg#138]
I am able to compile UPDS, but not BMQ with the latest linux-tkg master.  I love the work you are doing and would like to help however I can.  I can trace the errors to these lines I believe, as these do not occur when choosing UPDS as my CPU scheduler. 

BMQ:
![Screenshot-20201214200934-1156x362](https://user-images.githubusercontent.com/72957198/102154977-8da68500-3e48-11eb-9d3a-9575cb34d765.png)

UPDS:
![Screenshot-20201214202622-882x175](https://user-images.githubusercontent.com/72957198/102156054-baf43280-3e4a-11eb-8662-8880028d62e1.png)

Is this error safe to ignore?  It is only a warning with UPDS.  The kernel does compile, but with errors in BMQ.  If you need any additional information please let me know and I'll do my best to come up with it for you.

**Comment by Tk-Glitch** [comment]
The BMQ error was tracked here https://gitlab.com/alfredchen/linux-prjc/-/issues/19 and the fix will be merged in a minute.
The UPDS warning can be ignored :smiley:

**Comment by HippieMitch** [comment]
Thanks TKG!
