### ISSUE TITLE
5.10 still needs the same Bluetooth patch as 5.9 (kernel Bug 209745)

### ISSUE THREAD

**Issue by thotypous** [Frogging-Family/linux-tkg#139]
[This patch](https://github.com/Frogging-Family/linux-tkg/blob/4818f69efa1cdf0adc47f9c2e938ec973c89f2fb/linux-tkg-patches/5.9/0003-glitched-base.patch#L709-L769) which is currently applied to 5.9 (fixed by issue #99) is still needed in 5.10.

Even "vanilla" Arch kernel is applying the patch:

![image](https://user-images.githubusercontent.com/262047/102434200-0b0df900-3ff3-11eb-9e89-895a0f3c389d.png)

**Comment by corecontingency** [comment]
Looks like the patch made it into 5.10.4:

![Bluetooth connection to Logitech MX Master 2S lost after each reboot](https://user-images.githubusercontent.com/54042889/103388627-4d413b00-4ac7-11eb-9816-6c0e8909340e.png)

**Comment by thotypous** [comment]
I didn't test 5.10.4 yet, but anyway [this workaround](https://wiki.archlinux.org/index.php/Bluetooth#Problems_with_all_BLE_devices_on_kernel_5.9+) works well in case the fix does not work, so I'm closing the issue.
