### ISSUE TITLE
Add support for latest Kernel_GCC_Patch (znver3)

### ISSUE THREAD

**Issue by Devorlon** [Frogging-Family/linux-tkg#143]
I got the developer for the kernel_gcc_patch to add support for zen3 build flags. 

But when I try to replace the previous .patch file with the new [one](https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v11.0%2B_kernel_v5.10%2B.patch) it doesn't allow for user choice and instead displays some options but then skips to the SMT option. 

`Processor family`
`  1. Opteron/Athlon64/Hammer/K8 (MK8)`
`  2. Intel P4 / older Netburst based Xeon (MPSC)`
`  3. Core 2/newer Xeon (MCORE2)`
`  4. Intel Atom (MATOM)`
`> 5. Generic-x86-64 (GENERIC_CPU)`
`choice[1-5?]: 5` <- selected automaticly

The new patch does require GCC 11 so maybe support could be added in customization.cfg with something like:

> #If gcc11 is available on your system set to true for zen3 flags and other kernel options such as KCSAN (kernel 5.10+ only)
> _allowgcc11="false"

**Comment by AdelKS** [comment]
If you have the latest GCC then just pick "native" optimizations, don't change anything else. And the compiler will use `zenver3` flag automatically.

**Comment by Devorlon** [comment]
#211 Has added support for Zen 3. Though GCC11 is required. Thanks
