### ISSUE TITLE
Kernel 5.10 throws an error (gcc)

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#147]
When compiling the 5.10 Kernel i get this error:

make[1]: *** [kernel/Makefile:146: kernel/kheaders_data.tar.xz] Error 127
make: *** [Makefile:1805: kernel] Error 2
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by HippieMitch** [comment]
I had the same issue.  I solved it by installing 'cpio'.  It seems that the MAKEFILE needs it added as a dependency.

**Comment by Axilot** [comment]
Thanks, i'll try that. If that fixes the issue we gotta create a pull request to change the required packages.

**Comment by HippieMitch** [comment]
Of course, let me know how it turns out.

**Comment by Axilot** [comment]
How did you came up with that solution?

**Comment by HippieMitch** [comment]
There was a thread here yesterday with people discussing the issue, but I can't seem to find it now.

**Comment by AdelKS** [comment]
The corresponding pull request is #144

**Comment by Axilot** [comment]
I saw it, yeah. It really looks like thats missing as a make dependency. Now it compiles longer without that error, so i guess that fixed it. But i leave down a message when it successfully installed :D

**Comment by HippieMitch** [comment]
It was a pull request where I saw it lol.

**Comment by Axilot** [comment]
The pull request with the new required packages got merged into the repo, which means everything is fine now. I'll close this thread now 👍🏻

**Comment by lx0758** [comment]
Thank you very much for solving mine!
