### ISSUE TITLE
Where is the hardened arch configuration in the newer kernel versions?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#148]

**Comment by AdelKS** [comment]
For questions and issues related to your own setup, I suggest you join the Discord server to ask your questions: https://discord.gg/jRy3Nxk

**Comment by Axilot** [comment]
No, it's not for "my own" setup. It's described in the customization.cfg and could be found a few versions ago. Before 5.10

**Comment by AdelKS** [comment]
As far as I understand, this issue is a question, therefore it fits with what I suggested.

Also, at least have the decency to put more efforts to write a better title and have a description, no one here works for you.

**Comment by Axilot** [comment]
Commit 269750631bd128c12c0bca94fc0d4a445289e1ca fixed this issue. The hardened configuration file is now available for the 5.10 kernel.
