### ISSUE TITLE
BMQ have been updated to v5.7-r0

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#15]
https://gitlab.com/alfredchen/bmq/-/blob/master/5.7/bmq_v5.7-r0.patch

**Comment by Tk-Glitch** [comment]
The patch currently breaks compilation, so I'll wait for Alfred to fix it (https://gitlab.com/alfredchen/linux-bmq/-/issues/6). The rebased BMQ & PDS patches I currently offer in 5.7 have a workaround for that issue.

**Comment by HougeLangley** [comment]
Thanks
