### ISSUE TITLE
can't build 5.10

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/linux-tkg#151]
when i try to build 5.10 i get
```
  DESCEND  objtool
  DESCEND  bpf/resolve_btfids
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  LDS     scripts/module.lds
  CC      kernel/configs.o
  CHK     kernel/kheaders_data.tar.xz
  GEN     kernel/kheaders_data.tar.xz
make[1]: *** [kernel/Makefile:146: kernel/kheaders_data.tar.xz] Error 127
make: *** [Makefile:1805: kernel] Error 2
make: *** Waiting for unfinished jobs....

```
also it seems that the script is trying to run schedtool but does not offer to install it.
for the options i choose
ryzen performance
native (33)
fsync 

the rest just defaults

**Comment by SimpliFly03** [comment]
Which distribution are you running. On Arch I needed to install the package "cpio" to fix that.

**Comment by logan001** [comment]
i'm using arch
sorry i forgot to mention distro. i'm on archlinux

**Comment by SimpliFly03** [comment]
Latest PKGBUILD installs cpio automatically. You need to run git pull on linux-tkg folder to get that.

**Comment by logan001** [comment]
thank you.
