### ISSUE TITLE
Lto patch.

### ISSUE THREAD

**Issue by Sarah-Ctrl** [Frogging-Family/linux-tkg#152]
There was recently an LTO branch added that is getting the point of maturity. https://github.com/samitolvanen/linux/tree/clang-lto I made a patch file, for the branch but wasn't sure how to add it properly to tkg and am not currently about to compile the kernel, so this is untested but I wanted to at least notify you. This is the diff for my attempt. (Of course I added the patch locally, and added it to the prepare list.)  
```diff
diff --git a/customization.cfg b/customization.cfg
index edfa2e2..e08f5b0 100644
--- a/customization.cfg
+++ b/customization.cfg
@@ -164,7 +164,8 @@ _disable_acpi_cpufreq=""
 
 # You can pass a default set of kernel command line options here - example: "intel_pstate=passive nowatchdog amdgpu.ppfeaturemask=0xfffd7fff mitigations=off"
 _custom_commandline="intel_pstate=passive"
-
+#Append lto build arguments and patch to compile process. (Requires llvm)
+_lto_config="true"
```

```diff
diff --git a/linux-tkg-config/prepare b/linux-tkg-config/prepare
index 88dec12..0e3e983 100644
--- a/linux-tkg-config/prepare
+++ b/linux-tkg-config/prepare
@@ -422,7 +422,6 @@ _tkg_srcprep() {
         tkgpatch="$srcdir/0009-glitched-ondemand-bmq.patch" && _tkg_patcher
       fi
     fi
-
     msg2 "Applying Glitched PDS patch"
     tkgpatch="$srcdir/0005${doa}-glitched-pds.patch" && _tkg_patcher
 
@@ -447,7 +446,11 @@ _tkg_srcprep() {
     msg2 "Applying Glitched CFS patch"
     tkgpatch="$srcdir/0003-glitched-cfs.patch" && _tkg_patcher
   fi
-
+  if [ "$_lto_config" = "true" ]; then
+    msg2 "Applying lto kernel patch"
+    tkgpatch="$srcdir/0013-lto-linux.patch" && _tkg_patcher
+    llvm_opt = "${llvm_opt} -flto=thin -fsplit-lto-unit"
+  fi
   if [ "$_distro" = "Void" ] && [[ "$_sub" = rc* ]]; then
     cd ${wrksrc}/linux-${_rc_kern_ver}
   elif [ "$_distro" = "Void" ] && [[ "$_sub" != rc* ]]; then
```

**Comment by AdelKS** [comment]
Unfortunately the LTO patch on x86_64 arch fails on my end on an infinite linking loop. It is not ready to be broadly used, for two main reasons: not enough RAM (32GB is barely enough with modprobed-db, for full LTO at least), and the objtool errors.

**Comment by Sarah-Ctrl** [comment]
> Unfortunately the LTO patch on x86_64 arch fails on my end on an infinite linking loop. It is not ready to be broadly used, for two main reasons: not enough RAM (32GB is barely enough with modprobed-db, for full LTO at least), and the objtool errors.

My bad for submitting an issue then. I should have tried to compile with it first. Hopefully it matures a bit more. I just realized it existed recently because of the Phoronix article and wasn't sure about the state of the patch but assumed if it was mature enough for the next merge window for a pr to the mainline kernel it would have been more stable by now.

**Comment by AdelKS** [comment]
No worries! I only talked about my fiddling with LTO in the [FroggingFamily Discord](https://discord.gg/jRy3Nxk), not in here. When it will work, I will open a PR to add it here, with any extra needed tweaks/restrictions if needed.

As far as I understood, what will be mainlined in linux 5.12 is LTO for ARM only, as they are aware of the issues involving the x86 arch.

**Comment by Sarah-Ctrl** [comment]
> No worries! I only talked about my fiddling with LTO in the [FroggingFamily Discord](https://discord.gg/jRy3Nxk), not in here. When it will work, I will open a PR to add it here, with any extra needed tweaks/restrictions if needed.
> 
> As far as I understood, what will be mainlined in linux 5.12 is LTO for ARM only, as they are aware of the issues involving the x86 arch.

That's fair, before closing the issue, for future reference would this have been the proper syntactical way to add build flags and patches to linux-tkg?

**Comment by AdelKS** [comment]
Actually, the LTO patch adds new  config options that you can toggle with `make xconfig` and co, you do not need to specify the compiler options by hand. And the LLVM LTO needs some extra arguments at the `make` phase, when building the kernel. Otherwise, the toggle to enable the LTO patch in `customization.cfg` seems fitting to me.

**Comment by AdelKS** [comment]
Oh right, an easy way to try custom patches in your own machine is to append a `.mypatch` extension to your patch file and put it at the same level as the PKGBUILD file. The script will ask you if you want to apply it.

**Comment by Sarah-Ctrl** [comment]
Okay, that makes sense, I will try and use that feature in the future to test patches, thank you!

**Comment by AdelKS** [comment]
You are welcome, I will ping you here when I will implement the LTO in my fork (for an eventual PR), if you want to give it a try.

**Comment by Sarah-Ctrl** [comment]
That would be great, thank you!! Lto being integrated into major projects is always an exciting thing to see. ☺️

**Comment by ibrokemypie** [comment]
Very interested in how this effects performance, especially considering that the last I heard llvm compiled kernels are still somewhat slower than gcc ones, at least for gaming/graphics worklaods

**Comment by AdelKS** [comment]
Yea I did try a normal LLVM compiled kernel, with O3 and march=native, and it was somehow stuttery. I need to try again. But I want to try LTO + PGO kernel for the sake of it

**Comment by LifeIsStrange** [comment]
I think a GCC compiled kernel using LTO/PGO would probably be preferred given it generally outperforms clang. 
The last slide shows how to: https://www.halobates.de/kernel-lto.pdf

**Comment by AdelKS** [comment]
The latest LTO tree he seems to maintain for GCC is 5.8, whereas here it's gonna be mainlined. Which is better in terms of maintenance.

**Comment by AdelKS** [comment]
Okay 5.11 still doesn't fix the LTO issue, you can give it a try here, I only enabled it for Arch for now, since there's no need to go any further: https://github.com/AdelKS/linux-tkg/tree/LTO

If you disable the correct modules and built-in things, I think one can make it succeed.
