### ISSUE TITLE
Linux 5.11 RC3 fails to build

### ISSUE THREAD

**Issue by Orangian** [Frogging-Family/linux-tkg#155]
I was building Linux 5.11 RC3 in a Github Workflow that uses the archlinux:latest docker image and I got the following errors:

```
==> Extracting sources...

  -> Extracting linux-5.11-rc3.tar.gz with bsdtar

==> Starting prepare()...

  -> Setting version...

  -> Patching from 5.11 to 5.11.rc3

  -> Patch either not found, not available for this kernel version or not needed. Skipping...

  -> Applying graysky's cpu opts patch

  -> Applying clear linux patches

  -> Applying glitched base patch

  -> Applying misc additions patch

  -> Patch either not found, not available for this kernel version or not needed. Skipping...

  -> Applying PDS base patch

  -> Patch either not found, not available for this kernel version or not needed. Skipping...

  -> Applying prjc PDS/BMQ agressive ondemand governor patch

  -> Patch either not found, not available for this kernel version or not needed. Skipping...

  -> Applying Glitched PDS patch

  -> Patch either not found, not available for this kernel version or not needed. Skipping...

sed: can't read ./kernel/sched/alt_core.c: No such file or directory

==> ERROR: A failure occurred in prepare().

    Aborting...

  -> exit cleanup done
```

I'm not sure if it's supported by y'all yet, I was just looking at the commit history and I saw one titled Linux 5.11, so I figured that I'd try it out and see if it built. The entire log for the workflow is [here](https://gist.githubusercontent.com/Orangian/5f0a040b74107e119b75317cfa98f120/raw/71c050b7eb4d4dbb9ed3334b416c867242f69e22/workflow_log.txt). The errors start at line ~2800. [The full repository is here.](https://github.com/Osmium-Linux/linux-tkg-noninteractive) Thanks for any help you can provide!

**Comment by AdelKS** [comment]
Since the script works with barer metal Arch installs, I think it's an issue with the Archlinux Docker image image and/or script :thinking: 

Can you try to figure out where the actual Linux sources are unpacked since the tkg script doesn't seem to find it ? That would help debugging I think

**Comment by Tk-Glitch** [comment]
There is no support for any alternative cpu scheduler on 5.11 yet. Using cfs will fix this. When not setting the scheduler in .cfg you only get cfs as a choice, but when setting it in .cfg it bypasses it. I guess I should add a blacklist and a warning.

**Comment by Orangian** [comment]
Sorry, is UPDS supported on 5.11 yet? I had a build fail with message 
`sed: can't read ./kernel/sched/pds.c: No such file or directory``
and I'm not sure if it's related.

**Comment by Tk-Glitch** [comment]
No upds on 5.11 yet, but I the script will now handle unavailable cpu schedulers for a given version and offer a fallback: https://github.com/Frogging-Family/linux-tkg/commit/09c4f5b51d780b9218c934d0021239caec71424f
