### ISSUE TITLE
Compiling kernel asks lots of questions

### ISSUE THREAD

**Issue by triqster1** [Frogging-Family/linux-tkg#156]
Hey, I'm trying to compile the latest 5.10.7 kernel with the same config I previously compiled the 5.10.6 kernel, but this time I'm getting a lot of questions like:

```
Enable rseq() system call (RSEQ) [Y/n/?]
  Enabled debugging of rseq() system call (DEBUG_RSEQ) [N/y/?] (NEW)

PC/104 support (PC104) [N/y/?] (NEW)

Enable memcg SLUB sysfs support by default (SLUB_MEMCG_SYSFS_ON) [N/y/?] (NEW)

Choose SLAB allocator
  1. SLAB (SLAB)
> 2. SLUB (Unqueued Allocator) (SLUB)
  3. SLOB (Simple Allocator) (SLOB) (NEW)
choice[1-3?]:
```
I haven't had this before. Is this intended/normal? Should I just go with the defaults?

**Comment by AdelKS** [comment]
I have gotten the same thing, this was supposed to be "fixed" in the past (by accepting all the defaults). Don't worry about it, keep your "Enter" key pressed and you are good to go :D Meanwhile this will be "fixed" again
