### ISSUE TITLE
Package 'kernel-package' has no installation candidate

### ISSUE THREAD

**Issue by kevincardwell** [Frogging-Family/linux-tkg#157]
Hello,

I've tried to install this kernel 4 times now on 2 different clean and new distros, Ubuntu and POP OS but both times I get the exact same error and searching for the fix is non existent.

Here is the error:

"Package kernel-package is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'kernel-package' has no installation candidate"

Please help me.

Thank you

**Comment by AdelKS** [comment]
Hello!

Hang on tight, this will be fixed asap. You are running which version of Ubuntu, 20.10 ?

**Comment by kevincardwell** [comment]
Hello,

Yes, It is 20.10, Thank you so much!

**Comment by AdelKS** [comment]
Good!

Okay I checked now, actually I already fixed it and the PR #127 is open and will be merged soon, use my fork meanwhile: https://github.com/AdelKS/linux-tkg

**Comment by kevincardwell** [comment]
Thank you so much, that worked!

**Comment by AdelKS** [comment]
Hello! Can you close this issue ? :D
