### ISSUE TITLE
Switch from YeAH to BBR

### ISSUE THREAD

**Issue by V10lator** [Frogging-Family/linux-tkg#160]
BBR seems like the better choice, especially when you have a look at the round trip (ping) time. Here some numbers:

Algorithm | Average goodput [Mbps] | Average goodput ratio [%] | Average cwnd [#packets] | Average RTT [ms] | Average sending rate [Mbps] | Average throughput [Mbps]
----------|------------------------|---------------------------|-------------------------|------------------|-----------------------------|--------------------------
YeAH | 68.501 | 94.82 | 339.77 | 54.73 | 72.243 | 71.636
BBR | 67.442 | 95.28 | 31.22 | 4.37 | 70.779 | 70.527

**Comment by veganvelociraptor** [comment]
How many mbit is 68 Mbps? And is BBR consistently better and faster than YeAH regardless of connection type?

How about those with a faster or slower broadband connection? xDSL or mobile broadband?

Quote from https://blog.apnic.net/2020/01/10/when-to-use-and-not-use-bbr/ (the first link I got when googling) : _"...BBR can cause 100x more packet retransmissions than Cubic. This indicates that BBR provides high goodput but at the expense of high packet retransmissions in shallow buffers. Therefore, if the delivered content is sensitive to packet loss, then BBR might not be a good choice"_

**Comment by V10lator** [comment]
Mbps == Mbit/s ;)

From my own experience as well as some public benchmarks: On a good, stable xDSL connection throughput is a tiny bit lower but it fights against buffer-bloat, so this is expected.
On a weak (like mobile broadband in a bad area) connection BBR starts to shine: Throughput is much higher.
On both connections the round trip time is lower and there's less jitter.
This is also what the data above shows.

For a desktop (esp. gaming) PC a better round trip time might be more important than loosing around 1 Mbit/s on a 100 Mbit/s connection.

"...BBR can cause 100x more packet retransmissions than Cubic" - This is a feature: Instead of slowing the connection down (like Cubic would do in such a situation) it maximizes throughput. Also when you look at the Average cwnd in the table above YeAH causes ~100x more packet retransmission than BBR (32.22 vs 339.77 packets).

**Comment by veganvelociraptor** [comment]
The raw benchmark look good: https://arxiv.org/pdf/1903.03852.pdf

I am just not yet convinced it's going to lead to a better overall usage experience for general desktop users, and how relevant a server<->client streaming benchmark is compared to real life usage.

A quick sample made on my own setup, results in:
YeAH: 4.54 ms
BBR: 4.42 ms
Cubik: 4.40 ms
Vegas: 16.28 ms
Reno: 4.66 ms

**Comment by AdelKS** [comment]
Hello! This is a super interesting subject you brought up for me, do you have any reference so I can understand for example what would be the best congestion algorithm per internet connection type (DSL, 4G, Fiber) ?

**Comment by veganvelociraptor** [comment]
Did a more detailed benchmark on a computer at home:


  | Intel C2D Q9550 @ 3.4 GHz, Intel 82574L Gigabit NIC
-- | --
Algorithm | Downstream IPV4 (Mbit/s) | Upstream IPV4 (Mbit/s) | RTT IPV4 (ms) | Downstream IPV6 (Mbit/s) | Upstream IPV6 (Mbit/s) | RTT IPV6 (ms)
Reno | 506,231 | 650,435 | 9,98 | 620,994 | 633,442 | 4,377
Cubic | 447,892 | 651,362 | 8,137 | 369,412 | 631,556 | 8,584
Westwood | 598,616 | 650,969 | 3,567 | 620,005 | 634,162 | 4,248
BBR | 629,651 | 651,587 | 3,741 | 615,53 | 632,788 | 4,515
YeAH | 641,564 | 651,983 | 3,45 | 619,132 | 623,351 | 4,063

(just paste it in LibreOffice Calc please, as I've no idea how to make a fancy table here by just copy and pasting it)

Gonna do the same test on my other, newer, later on. Can't say I see much difference between BBR, YeAH and Westwood. Dunno why I did the test on IPv6, as the congestion control algorithm only should affect IPv4, and yet it does affect it...

**Comment by AdelKS** [comment]
@veganvelociraptor How do you perform such a benchmark ?

**Comment by veganvelociraptor** [comment]
https://aur.archlinux.org/packages/speedtest-cli-git/

Then I just copy and paste the results to a calc sheet and re-run the test with each congestion algorithm:
echo "cubik" > /proc/sys/net/ipv4/tcp_congestion_control
echo "westwood" > /proc/sys/net/ipv4/tcp_congestion_control
echo "bbr" > /proc/sys/net/ipv4/tcp_congestion_control
echo "yeah" > /proc/sys/net/ipv4/tcp_congestion_control

**Comment by veganvelociraptor** [comment]
I've postponed posting a benchmark made on my other computer, since I found a bug when using BBR with the igb driver used for various Intel NICs.

When using BBR, the uplink speed drops to less than 1/10th of what it should be. No other congestion algorithm exhibits this behaviour.

**Comment by SveSop** [comment]
@veganvelociraptor 
Maybe test BBR2 aswell?

Oh, and and even tho it kinda indicate only being for ipv4 `/proc/sys/net/ipv4/tcp_congestion_control` , it also works for ipv6.

> /proc/sys/net/ipv6/* Variables:
> 
> IPv6 has no global variables such as tcp_*.  tcp_* settings under ipv4/ also
> apply to IPv6 [XXX?].

[https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt)

**Comment by veganvelociraptor** [comment]
Here are the results from my second computer, now that the BBR bug appears to have been fixed (though I never managed to find any information about it other than my own results).

Instead of BBR being 90% slower on upload when using an  Intel I211 Gigabit NIC, its instead YeAH that's slower (?).


Computer #2 | Ryzen 5 2600X @ 4.2 GHz, Intel I211 Gigabit NIC
-- | --
Algorithm | Downstream IPV4 (Mbit/s) | Upstream IPV4 (Mbit/s) | RTT IPV4 (ms) | Downstream IPV6 (Mbit/s) | Upstream IPV6 (Mbit/s) | RTT IPV6 (ms)
Reno | 587,133 | 568,383 | 3,787 | 613,809 | 626,154 | 4,067
Cubic | 637,227 | 599,144 | 3,714 | 615,845 | 627,005 | 4,25
Westwood | 603,402 | 508,2 | 3,868 | 613,9 | 628,025 | 4,02
BBR | 633,027 | 622,58 | 3,867 | 599,81 | 627,545 | 3,986
YeAH | 523,768 | 444,159 | 3,717 | 537,161 | 627,822 | 4,085

> @veganvelociraptor
> Maybe test BBR2 aswell?

```
[root@zzzen PKGBUILDS]# modprobe -a tcp_bbr2
modprobe: WARNING: Module tcp_bbr2 not found
```
