### ISSUE TITLE
Misc Patching Failed

### ISSUE THREAD

**Issue by iWeaker4you** [Frogging-Family/linux-tkg#163]
When I am compiling I get that error in prepare.log.
on Ubuntu 20.10 and kernel 5.10

### Applying 0012-misc-additions.patch... ###
patching file drivers/hid/hid-quirks.c
patching file fs/btrfs/space-info.c
Hunk #2 FAILED at 554.
1 out of 2 hunks FAILED -- saving rejects to file fs/btrfs/space-info.c.rej
patching file drivers/net/wireless/intel/iwlwifi/mvm/tx.c
patching file drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c
Hunk #1 succeeded at 183 (offset -9 lines).
patching file drivers/gpu/drm/amd/amdgpu/amdgpu_ttm.c
Hunk #1 succeeded at 1965 (offset 100 lines).

**Comment by AdelKS** [comment]
For now please use #127, I think I fixed this issue there, the code is here: https://github.com/AdelKS/linux-tkg

**Comment by AdelKS** [comment]
PR #127 got merged, this issue should be fixed now.
