### ISSUE TITLE
gcc optimization  patch not applied on Debian

### ISSUE THREAD

**Issue by termac** [Frogging-Family/linux-tkg#165]
Due to the urlencode of the patch version and link the patch is not found after downloading (downloading works fine). The easiest solution would be not to url encode the version string in the first place, which works for me, see #164. If this is not a valid solution for all cases the variable `$opt_ver` needs to be fixed by replacing `%2B` with `+` right before this line and the extra `+` in this line needs to be removed: https://github.com/Frogging-Family/linux-tkg/blob/47b236a3eac48cb391112ef1ed538450e9f59af9/linux-tkg-config/prepare#L368

Looking at the lines above it is probably the same for Void linux (minus the extra `+` in the file path).

**Comment by AdelKS** [comment]
I did this replacement with my earlier PR and it either got changed back by TKG or I have been asked to revert it. It seems that on Archlinux it doesn't work the same way or something. I will have a look at it a little bit later, I am pretty sure we can fix this issue without touching the code path of archlinux 🤔

**Comment by AdelKS** [comment]
I had a look at your PR, there's one thing to change and it's all good! I have another opened PR #127 that fixes it too.

**Comment by AdelKS** [comment]
My PR #127  got merged, the issue should be fixed now :D
