### ISSUE TITLE
Keyboard input not working on 5.11rc during boot

### ISSUE THREAD

**Issue by MatthiasGrandl** [Frogging-Family/linux-tkg#167]
Seems like the 5.11 config contains more stuff as modules (e.g `CONFIG_USB_XHCI_HCD`), which might triggers this? Now I can't enter my decryption password during boot. Not sure if my diagnosis is correct though :)

**Comment by MatthiasGrandl** [comment]
Ok no that can't be the issue. With `debug` in commandline the keyboard is detected fine. I am using dracut. Maybe something is broken there...

**Comment by AdelKS** [comment]
Are you using `modprobed-db` ? Can you attach your `customization.cfg` ? Also, you may have to have the module you need available earlier, check here how to do it: https://wiki.archlinux.org/index.php/Kernel_mode_setting#Early_KMS_start

**Comment by MatthiasGrandl** [comment]
Jep I am using modprobed-db. I'll try compiling without it. My customization.cfg (with modprobed-db disabled) is: 
[customization.zip](https://github.com/Frogging-Family/linux-tkg/files/5902514/customization.zip)


I'll check early KMS. Never needed it for 5.10 though.

**Comment by MatthiasGrandl** [comment]
Newest 5.11rc worked fine without any config changes.
