### ISSUE TITLE
ccache not really effective

### ISSUE THREAD

**Issue by phush0** [Frogging-Family/linux-tkg#168]
I have noticed that since I moved to compiling 5.10.x kernel ccache is nor working correct. With 5.9.x cold cache was ~24 min and hot ~8, but with 5.10.x cold is 25m and hot is 24m which is not beneficial  at all. I am not sure if it is some config option or just some distro update passed and changed something. I am compiling with gcc and during compile I use `watch ccache --show-stats` and I am seeing only misses and files are added to cache and only some of modules are with cache hit or preprocess hit and that's it. I cleaned all cache and build it from scratch. Also tested with other projects and it it is working as expected. All cores are used.

I will appreciate some help, because every compile is too long.

**Comment by Axilot** [comment]
You gotta make sure ccache has enough space to store the compiled output. For more information on that open the man page for ccache. The command `ccache -M 20G` will increase your limit to 20 Gigabytes. Let me know if that helped you. To see if it worked out for you, you have to compile the kernel twice with ccache.

**Comment by phush0** [comment]
It is not working at all cache hit of 15 files it is just a joke. I have increased cache to 10GB

**Comment by phush0** [comment]
so it is somehow connected with ccache version 3.7.11 is working as expected 4.1 is not. At least for kernel compilation.

**Comment by AdelKS** [comment]
I suppose you should open an issue with them then: https://github.com/ccache/ccache

**Comment by openglfreak** [comment]
I had a similar issue with wine-tkg recently, putting `export SOURCE_DATE_EPOCH=0` in the config fixed that for me.

**Comment by phush0** [comment]
there is merged change in ccache which will be part from 4.2 release cycle which will fix this [#755](https://github.com/ccache/ccache/pull/755)
