### ISSUE TITLE
Feature Request: add NTFS3 as an option

### ISSUE THREAD

**Issue by kleinermob** [Frogging-Family/linux-tkg#170]
https://www.paragon-software.com/home/ntfs3-driver-faq/

**Comment by Sukid** [comment]
The DKMS driver works fine though.

**Comment by Sukid** [comment]
> The DKMS driver works fine though.

I was not considering non-arch-based distros at the time. I did manage to figure it out but it would definitely be good in that case.
This was the only repo for it I was able to find though:
https://github.com/LGA1150/ntfs3-oot

**Comment by kleinermob** [comment]
Kernel 5.15 will include this
