### ISSUE TITLE
Void Linux: make menuconfig not working

### ISSUE THREAD

**Issue by Rajalolxd** [Frogging-Family/linux-tkg#171]
make[1]: *** [scripts/kconfig/Makefile:214: scripts/kconfig/mconf-cfg] Error 1
make: *** [Makefile:602: menuconfig] Error 2
=> ERROR: linux510-tkg-bmq-5.10.12_18: do_configure: 'make menuconfig ${llvm_opt}' exited with 2
=> ERROR:   in _tkg_srcprep() at /builddir/linux-tkg/linux-tkg/linux-tkg-config/prepare:1145
=> ERROR:   in do_configure() at srcpkgs/linux510-tkg-bmq/template:491

**Comment by AdelKS** [comment]
@Hyper-KVM Can you have a look at this ?
