### ISSUE TITLE
./install.sh script fails on Fedora 33 KDE

### ISSUE THREAD

**Issue by Melorn366** [Frogging-Family/linux-tkg#173]
I am on Fedora 33 and wanted to compile your kernel. with ./install.sh install script. It looks like the script is giving me error. What did I do before running the script? I configured the customization file, set the  linux distribution part to fedora, then set config expert to true. What kind of error did I received?  
This https://privatebin.net/?dc77bec5d9341a34#FwK9LJRANaUaMiZkjQ7CYXzCwP9hNRerPrhdgs77jD4A   

 Did I try to run the script with root privileges in another try? Yes I did. Still failed.(edited)
What other files should I provide you in order to fix this?
I wanted to compile UPDS with skylake patches.
but failed on the header compile part.

**Comment by AdelKS** [comment]
Hello!

It seems that you are using `tmpfs` (RAM) as your temporary location for building. My guess is that you don't have enough RAM for that matter, or the max size of your `tmpfs` mount isn't big enough. How much RAM do you have ? But maybe it's something else.

Can you retry again with the current updates ? the code for `install.sh` got changed (including the location of the temporary build files, that is back in the `home` folder). Hopefully it's fixed, can you monitor the RAM usage during the build (including `cache`) ?

**Comment by MartB** [comment]
Does not fail for me on an nvme build so i guess @AdelKS is correct.
Also running the Fedora 33 KDE spin.

**Comment by Melorn366** [comment]
@AdelKS 
Hello AdelKS. I deleted the previous linux-tkg folder and git cloned the repository in the home folder.
End result. It failed.
What did I notice? CPU usage was 100% and RAM usage (for the entire system, was between 2-2.2 GB). How much RAM do I have ? 16 GB
What is the error code I received? 
What kernel did I use for compiling ? The first run, this kernel https://copr.fedorainfracloud.org/coprs/sentry/kernel-fsync/ the second run was with official fedora kernel. Both occasions gave me the same result.
What kind of error did i received? 

error: Bad exit status from /var/tmp/rpm-tmp.roAEC8 (%build)


RPM build errors:
    line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
    Bad exit status from /var/tmp/rpm-tmp.roAEC8 (%build)
make[1]: *** [scripts/Makefile.package:59: rpm-pkg] Error 1
make: *** [Makefile:1533: rpm-pkg] Error 2

How did I compiled the kernel ? First with root privilages, then when it failed, I deleted the entire folder, and redownloaded so that I won't run in unnecessary errors. Then the second time I run it with normal user privilages (yes the middle of the build asked my password, in order to download the necessary files)

**Comment by AdelKS** [comment]
Okay maybe the source of issue is the following: your `kernel` and `kernel-headers` do not have the same version. Can you attach the output of `dnf list --installed kernel*`, you can attach it here between \``` \```

**Comment by Melorn366** [comment]
kernel.x86_64                                         5.10.11-200.fc33                                  @updates                                           
kernel.x86_64                                         5.10.11-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel.x86_64                                         5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-core.x86_64                                    5.10.11-200.fc33                                  @updates                                           
kernel-core.x86_64                                    5.10.11-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-core.x86_64                                    5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-devel.x86_64                                   5.10.11-200.fc33                                  @updates                                           
kernel-devel.x86_64                                   5.10.11-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-devel.x86_64                                   5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-headers.x86_64                                 5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-modules.x86_64                                 5.10.11-200.fc33                                  @updates                                           
kernel-modules.x86_64                                 5.10.11-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-modules.x86_64                                 5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-modules-extra.x86_64                           5.10.11-200.fc33                                  @updates                                           
kernel-modules-extra.x86_64                           5.10.11-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-modules-extra.x86_64                           5.10.12-201.fsync.fc33                            @copr:copr.fedorainfracloud.org:sentry:kernel-fsync
kernel-srpm-macros.noarch                             1.0-3.fc33                                        @fedora 

I usually use this 5.10.11-200.fc33   for compiling stuff

**Comment by Melorn366** [comment]
And this is what I have available for the kernel.

rpm -ql kernel-devel | grep usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/Makefile
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/Makefile.build
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/Makefile.feature
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/Makefile.include
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/feature
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/feature/Makefile
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/tests
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/tests/ex
/usr/src/kernels/5.10.11-200.fc33.x86_64/tools/build/tests/ex/Makefile

**Comment by AdelKS** [comment]
Okay, I suggest to try to reinstall `kernel-headers` that is from the `updates` repository, that should have version `5.10.11` and start in the official fedora kernel `5.10.11` and try your compilation.

**Comment by Melorn366** [comment]
Allright. Doing it now.

**Comment by Melorn366** [comment]
I believe I dont heave header files installed O.o

pm -qa|grep kernel
kernel-core-5.10.11-200.fc33.x86_64
libreport-plugin-kerneloops-2.14.0-15.fc33.x86_64
abrt-addon-kerneloops-2.14.5-1.fc33.x86_64
kernel-modules-5.10.11-200.fc33.x86_64
kernel-5.10.11-200.fc33.x86_64
kernel-modules-extra-5.10.11-200.fc33.x86_64
kernel-devel-5.10.11-200.fc33.x86_64
kernel-core-5.10.11-201.fsync.fc33.x86_64
kernel-modules-5.10.11-201.fsync.fc33.x86_64
kernel-5.10.11-201.fsync.fc33.x86_64
kernel-modules-extra-5.10.11-201.fsync.fc33.x86_64
kernel-devel-5.10.11-201.fsync.fc33.x86_64
kernel-srpm-macros-1.0-3.fc33.noarch
kernel-core-5.10.12-201.fsync.fc33.x86_64
kernel-modules-5.10.12-201.fsync.fc33.x86_64
kernel-5.10.12-201.fsync.fc33.x86_64
kernel-modules-extra-5.10.12-201.fsync.fc33.x86_64
kernel-headers-5.10.12-201.fsync.fc33.x86_64
kernel-devel-5.10.12-201.fsync.fc33.x86_64

**Comment by AdelKS** [comment]
You seem to have these: `kernel-headers-5.10.12-201.fsync.fc33.x86_64`, you can either try to run your compilation on that specific copr kernel version, which is `5.10.12-fsync`. Or do a `dnf remove kernel-headers*` then reinstall the ones from `updates` repository and run the official kernel.

**Comment by Melorn366** [comment]
will try both ways. First I reinstall the fsync headers, then starting to compile, if it fails then i will go back to official fedora kernel release, and see what happens.

**Comment by AdelKS** [comment]
Yes, since you can only have one version of the headers installed, the idea is to run the kernel that corresponds to the installed headers. At least that is what is suggested [here](https://tutorialforlinux.com/2020/12/30/redhat-linux-kernel-compilation-its-not-recommended-to-have-unversioned-obsoletes-obsoletes-kernel-headers-troubleshooting-guide/)

**Comment by Melorn366** [comment]
Yes you were right ! It looks like on fedora there is only one header file active, and the moment you upgrade to the custom kernel, the official fedora released kernel gets upgraded too. Okay I clone the tkg kernel repository, and starting to compile

**Comment by Melorn366** [comment]
Do i have to set the config expert to true, if i want to add the futex 2 interface patch?

**Comment by Melorn366** [comment]
Same error.

error: Bad exit status from /var/tmp/rpm-tmp.djzDkI (%build)


RPM build errors:
    line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
    Bad exit status from /var/tmp/rpm-tmp.djzDkI (%build)
make[1]: *** [scripts/Makefile.package:59: rpm-pkg] Error 1
make: *** [Makefile:1533: rpm-pkg] Error 2
 -> exit cleanup done

**Comment by Melorn366** [comment]
kernel 5.10.11-200.fc33.x86_64
kernel-header-5.10.11-200.fc33.x86_64 were in use

**Comment by AdelKS** [comment]
I am out of ideas for now :thinking:

**Comment by Melorn366** [comment]
Meh....I give up.

**Comment by AdelKS** [comment]
The weird thing is that I have VM with Fedora 33 and it works, and another user reported in this thread that it works for him. So you have a specific change that breaks the compilation, I don't know what exactly :thinking:

**Comment by AdelKS** [comment]
Hello ! Any news on the matter ?

**Comment by MartB** [comment]
> Hello ! Any news on the matter ?

Just from me again, i built 5.10.16 and its still working on my machine.
Im using the KDE Spin and my entire setup is nowhere near vanilla, so not sure whats wrong for him.

**Comment by Melorn366** [comment]
@AdelKS Greetings. For testing purpose I installed POP OS so that I can make sure, that the problem was with my fedora config. The result is, that the install.sh script works (perfectly) was able to compile and install. On top of that I didn't needed to follow the instructions posted here https://steamcommunity.com/app/418530/discussions/0/2930112548420911027/ since the script installs everything for me. So a big kudos to you guys !.

The only annoying issue is that POP OS wants to revert to this libc version linux-libc-dev Linux Kernel Headers for development Version: 5.8.0-7642.47~1612288990~20.10~b8113e7
But probably this is not caused by the script itself, but distro specific. Do you perhaps know how to force it to use newer libc version?

**Comment by AdelKS** [comment]
Hello ! Some interesting things going on for you from what I see, good good !

About the `linux-libc-dev`, the script indeed makes a new `.deb` package for it, you mean at each update of the distro kernel it reinstalls the old version of `linux-libc-dev` ? I am not sure `libc` gets updated with the kernel sources, I think it's a lib that gets updated alone with the `glibc` package.

**Comment by Melorn366** [comment]
It wants to reinstall the old linux-libc-dev package that ships with POP_OS after just a single reboot  ! No big issue just an interesting fact  :)

**Comment by AdelKS** [comment]
Oh I see, weird behavior of this distro then :thinking:

**Comment by AdelKS** [comment]
@Melorn366 Please retry now with the newly merged PR, it should fix this error:
```shell
line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
```
