### ISSUE TITLE
5.11: patch application failed 

### ISSUE THREAD

**Issue by ninelore** [Frogging-Family/linux-tkg#177]
[prepare.log](https://github.com/Frogging-Family/linux-tkg/files/5984153/prepare.log)

also:
```
==> Starting prepare()...
  -> Setting version...
  -> Applying graysky's cpu opts patch
  -> Applying clear linux patches
  -> Applying glitched base patch
  -> Applying misc additions patch
  -> Applying PDS base patch
  -> Patch either not found, not available for this kernel version or not needed. Skipping...
  -> Applying PDS agressive ondemand governor patch
  -> Patch either not found, not available for this kernel version or not needed. Skipping...
  -> Applying Glitched PDS patch
  -> Patch either not found, not available for this kernel version or not needed. Skipping...
sed: can't read ./kernel/sched/pds.c: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

And yes this time i checked if i am on the lastest tree 😄

**Comment by Tk-Glitch** [comment]
You have set upds in your config I guess? It is not yet available on 5.11. Only PRoject C PDS and BMQ are available as alternatives to CFS right now. I'll work on finishing porting upds over in the coming days.

**Comment by ninelore** [comment]
oh ok. 
Tyvm

**Comment by Tk-Glitch** [comment]
You're welcome

**Comment by John-Gee** [comment]
Is UPDS still the recommended one or should we switch to PC?

**Comment by ninelore** [comment]
personally i got the best results with BMQ
(AMD Renoir w/ Nvidia Ampere GTX)

**Comment by John-Gee** [comment]
Alright!

I used to use BMQ and liked it better.
I think BMQ was the only one always keeping chromium usable, no matter the load.
I forgot why I had to stop using it though.

Thanks!
