### ISSUE TITLE
Alternative mirrors to kernel.org?

### ISSUE THREAD

**Issue by dustContributor** [Frogging-Family/linux-tkg#181]
This happens to me often, my internet is pretty crappy and I live in a far away land in which we speak neither english nor finish.

Thus I get blazing fast download speeds of 10 to 20 KB/s when cloning the repo. I've briefly tested with other mirrors and for instance, Google's works way better for me (600KB/s, that's a 30x improvement).

`https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable`

I tried with the GitHub mirror but it seems it's missing the X.YZ.y tags? The installer fails saying it can't find them.

`https://github.com/torvalds/linux.git`

In any case, it'd be nice if the installer script could have at least a few mirrors in its repertoire. It cuts my `git clone` from several hours to about 15min.

**Comment by AdelKS** [comment]
Hello,

This is an interesting issue, I think best is to implement `tar` downloads like Archlinux does, the only downside it has is the disk usage if it's an SSD (by decompressing hundreds of thousands of files and then deleting them after, at each update). The idea of using other mirrors is a good idea I think.

I think I will implement both, I will start with the git mirrors, let's keep this issue open till I do it.

**Comment by dustContributor** [comment]
Sweet, thanks!

**Comment by AdelKS** [comment]
Here it is:  #192 ! Give it a try and tell me if everything is alright! I didn't implement yet using `tar` files.

**Comment by dustContributor** [comment]
@AdelKS Works fine! Thanks a lot!
