### ISSUE TITLE
adding a bluetooth patch for better xbox controller support (ERTM)

### ISSUE THREAD

**Issue by fsyy** [Frogging-Family/linux-tkg#182]
hi,

i'd like to mention a patch which would be good for xbox controllers connected by bluetooth work better.

According to this thread from xpad neo driver developers:

https://github.com/atar-axis/xpadneo/issues/272

Patch:

https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git/commit/?id=98d2c3e1731007acf03addf83c863df6694beb95

Maybe it could go to community patches.

**Comment by AdelKS** [comment]
Hello, it seems that this patch is in the "community patches" repository: https://github.com/Frogging-Family/community-patches/blob/master/linux511-tkg/bluetooth-next.mypatch

Can you check if it's the same ?

**Comment by fsyy** [comment]
Hi,

seems my link is only an addition to the bluetooth next patch and already included.

Thanks for telling me. Closing :)
