### ISSUE TITLE
5.10 kernel build failure

### ISSUE THREAD

**Issue by puskapet** [Frogging-Family/linux-tkg#183]
I have the same issue as mentioned in issue #151 but I have cpio installed.
I am on the latest master branch.
I was trying to build 5.10.17 with everything default except fsync, futex2 patch and Ivy Bridge optimization.
I am building on Arch Linux linux-zen 5.10.16.zen1-1 on 30GB /tmp partition.
```
  DESCEND  objtool
  DESCEND  bpf/resolve_btfids
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/kheaders_data.tar.xz
  AR      kernel/built-in.a
  CC [M]  kernel/kheaders.o
  CC      lib/math/div64.o
  CC      lib/math/gcd.o
  CC      lib/math/lcm.o
  CC      lib/math/int_pow.o
/tmp/ccRmLktm.s: Assembler messages:
/tmp/ccRmLktm.s:9: Error: file not found: kernel/kheaders_data.tar.xz
make[1]: *** [scripts/Makefile.build:279: kernel/kheaders.o] Error 1
make: *** [Makefile:1801: kernel] Error 2
make: *** Waiting for unfinished jobs....
  CC      lib/math/int_sqrt.o
  AS      arch/x86/lib/clear_page_64.o
  CC      arch/x86/lib/cmdline.o
  CC      lib/math/reciprocal_div.o
  AS      arch/x86/lib/cmpxchg16b_emu.o
  CC      lib/crypto/chacha.o
  CC      arch/x86/lib/copy_mc.o
  CC      lib/math/rational.o
  CC [M]  lib/math/cordic.o
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done
```
I have looked at the other people having this issue but I have 0 idea why it fails since I should have all necessary programs installed.

**Comment by AdelKS** [comment]
I had the same issue and just gave up on it and compiled 5.11, I retried now (latest updates as of now) and it works again. Try to update and do it again ?

**Comment by puskapet** [comment]
I have tried compiling 5.11 and it worked, also had compiled 5.10.15 with success before and this was like my 4th try compiling 5.10.17 and it would always error out on this.

**Comment by AdelKS** [comment]
Yea I don't know, it seems like an obscure thing to me, maybe you lack `xz` compression in the `.config` or something ? Or the app related to making `.xz` archives ? Otherwise maybe someone figured out what was wrong and will answer here.

**Comment by puskapet** [comment]
Closing this, as I tried compiling with Kheaders now and it works, most likely something was broken on my system but now it works.
