### ISSUE TITLE
5.11 build refers to patch that doesn't exist at kernel.org

### ISSUE THREAD

**Issue by CosmicSavant** [Frogging-Family/linux-tkg#185]
`==> Making package: linux511-tkg-pds 5.11.0-127 (2021-02-23T16:55:16 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux-5.11.tar.xz
  -> Downloading patch-5.11.0.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   311    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://cdn.kernel.org/pub/linux/kernel/v5.x/patch-5.11.0.xz`

**Comment by AdelKS** [comment]
Sync the repository again and you should be good to go, since there's `5.11.1` now.

**Comment by CosmicSavant** [comment]
Yeah, odd that it was deleted though.

**Comment by AdelKS** [comment]
What got deleted ? There's no such thing as the 5.11.0 patch actually, it is kinda weird that you got that error since PKGBUILD didn't fail for anyone on the initial 5.11 release because the script did not try to download this unexistant patch :thinking:

**Comment by Snoop05** [comment]
It said pkgrel 127 indicating it was the 5.11.1 commit, yet somehow $_sub evaluated to 0, i guess prepare script didnt get changed for some weird reason?

**Comment by AdelKS** [comment]
Oh I understand better, weird.
