### ISSUE TITLE
5.11 option missing in customization.cfg

### ISSUE THREAD

**Issue by FGD-Garuda** [Frogging-Family/linux-tkg#186]
Maybe it's just me but shouldn't the option "5.11" be available in `customization.cfg`?

```
# Kernel Version - Options are "5.4", "5.7", "5.8", "5.9", "5.10"
_version=""
```

I was waiting for this show up but I got suspicious lately and decided to try 5.11 in the config file and it worked, I compiled `5.11.1-127`.

I do not use any menu config, only straight and raw with the customization.cfg file.

Tnx

**Comment by Tk-Glitch** [comment]
That was just an omission due to the config now being version-independent. I'll add 5.11 to the list.

**Comment by FGD-Garuda** [comment]
Pas de problème, merci Étienne! :)

No problem, thank you Etienne.
