### ISSUE TITLE
ld: BFD (GNU Binutils) 2.36.1 internal error on .tmp_vmlinux.btf

### ISSUE THREAD

**Issue by FGD-Garuda** [Frogging-Family/linux-tkg#187]
Hi there,

I was compiling 5.11 BMQ with custom options half an hour ago and during compile process I got this error msg:

```
LD [M]  drivers/gpu/drm/nouveau/nouveau.o
AR      drivers/gpu/built-in.a
AR      drivers/built-in.a
GEN     .version
CHK     include/generated/compile.h
LD      vmlinux.o
MODPOST vmlinux.symvers
MODINFO modules.builtin.modinfo
GEN     modules.builtin
LD      .tmp_vmlinux.btf
ld: BFD (GNU Binutils) 2.36.1 internal error, aborting at /build/binutils/src/binutils-gdb/bfd/merge.c:939 in _bfd_merged_section_offset

ld: Please report this bug.

BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: No debugging information found
LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
make: *** [Makefile:1165: vmlinux] Error 1
DESCEND  objtool
DESCEND  bpf/resolve_btfids
```

Not knowing the impacts of letting it complete the process, I killed it to do what the msg told me to do, which is "report this bug". It was asked so nicely. loll I have no idea if this is related to tkg kernels, some linux packages or other stuff, but I have to start somewhere.

I also have no idea what other data to provide you with for troubleshooting. Plz do let me know.
My customization.cfg file maybe?
Or maybe inxi -Fxxxza?
Anything else?

I am compiling tkg kernels for about 6 weeks only but I have compiled probably about 50 times so far and never had an error msg. Some warnings once in a while yes, but something like this one, no. I also compiled 5.11 yesterday or 2 days ago and everything went through. As far as I remember my machine was using pretty much the same package versions (plasma 5.21, etc...), but since I am on Arch and I did update once yesterday after that 1st 5.11 compile, who knows...

Thanks

**Comment by FGD-Garuda** [comment]
I could not reproduce this weird error.

I logged a bug at Sourceware and closed it.
See for details https://sourceware.org/bugzilla/show_bug.cgi?id=27467

If anyone hits that same issue and can reproduce it, plz do let know.

**Comment by AdelKS** [comment]
If you have an overclocked RAM it may be the culprit 🤔

**Comment by FGD-Garuda** [comment]
Very good point!
I am using an XP setting from the BIOS to O/C my memory.
Now that you've mentioned this, you've opened my mind about all kind of such things... a small glitch (nothing to do with tk-glitch loll) in the CPU, memory, PCIe, drives, MB... this can affect compiling in weird ways.

Should have thought about it but I didn't, tnx for the heads up.

Next times I will always try the compile process 2-3 times in a row and see if I get the error all the time. That could mean something different then.

In the meantime I did launch the compile again on my main machine and all went through perfect! So another vote for that possible hardware glitch... :)
