### ISSUE TITLE
Futex2 Proposed In Latest Effort For Linux Kernel Optimization That Can Benefit Gamers

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#19]
https://lore.kernel.org/lkml/20200612185122.327860-1-andrealmeid@collabora.com/

**Comment by Tk-Glitch** [comment]
This is not useful to us in its current form.

**Comment by Tk-Glitch** [comment]
(but you can be certain it'll be implemented when it'll make sense)
