### ISSUE TITLE
Pulling updated zstd?

### ISSUE THREAD

**Issue by John-Gee** [Frogging-Family/linux-tkg#191]
Hello,

with the release of a new userspace zstd, I realized that we're still stuck on old zstd in the kernel (https://github.com/facebook/zstd/issues/1638).

Would it be appropriate for the TKG kernel to add patch to get us at least to 1.46? (From https://github.com/terrelln/linux/branches )

Maybe this would be too risky though since zstd is used by FSs too...

Thanks!

**Comment by MCPO-Spartan-117** [comment]
I'm using 1.4.10 and it works fine, a friend of mine is using the latest zstd and he hasn't had any issues either.

**Comment by Daedalusspacegames** [comment]
I've tested this patchset on my machine as well, I've seen no issues running it. 

Obviously, if this patch set was included, consideration would have to be made for running bcachefs with it; the changes this patchset includes seems to touch APIs that bcachefs needs, resulting in a compilation error with both patchsets applied.

**Comment by John-Gee** [comment]
It's finally been pulled into linux-next, so I guess we won't need patches in TGK for it.
