### ISSUE TITLE
graysky2 gcc patches 404 url error

### ISSUE THREAD

**Issue by XyleticWasTaken** [Frogging-Family/linux-tkg#196]
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch

I think the patches were moved around to outdated_versions and the new ones were renamed.

**Comment by tuxtergames** [comment]
> curl: (22) The requested URL returned error: 404
> ==> ERROR: Failure while downloading https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch
> 
> I think the patches were moved around to outdated_versions and the new ones were renamed.

I got the same error here, even erasing installation folder for 3 times.

HEAD is now at 79a7af267 Linux 5.11.4
 -> Downloading Graysky2's CPU optimisations patch
--2021-03-09 09:28:39--  https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v10.1+_kernel_v5.8+.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-09 09:28:40 ERROR 404: Not Found.

**Comment by redgloboli** [comment]
older versions are here:

https://github.com/graysky2/kernel_gcc_patch/tree/master/outdated_versions

new versions are called differently now: more-uarches-for-gcc-v10-and-kernel-4.19-v5.4.patch for example

you could adjust your PKGBUILD and linux-tkg-config/prepare files accordingly or just wait for it.

seems kernel 5.7 didn't get an updated patch.

**Comment by bkdwt** [comment]
I compiled yesterday on Fedora and noticed that the option to choose the processor family on menuconfig remained the same as in the standard kernel.

s
![Captura de tela de 2021-03-09 10-29-44](https://user-images.githubusercontent.com/51302074/110477809-60bde300-80c2-11eb-9c37-e3e06f9db447.png)

**Comment by bkdwt** [comment]
Changed the graysky2 patch link on install.sh, but:

```
-> Applying graysky's cpu opts patch
 -> Patch either not found, not available for this kernel version or not needed. Skipping...
```

**Comment by gardotd426** [comment]
>tkg is already aware of this, see: dfd20ae

He may be aware of it, but the updated urls still 404.

**Comment by tuxtergames** [comment]
> Changed the graysky2 patch link on install.sh, but:
> 
> ```
> -> Applying graysky's cpu opts patch
>  -> Patch either not found, not available for this kernel version or not needed. Skipping...
> ```

I'll wait for a few days and wait for a fix, maybe install 5.10-xx

**Comment by bkdwt** [comment]
> > Changed the graysky2 patch link on install.sh, but:
> > ```
> > -> Applying graysky's cpu opts patch
> >  -> Patch either not found, not available for this kernel version or not needed. Skipping...
> > ```
> 
> I'll wait for a few days and wait for a fix, maybe install 5.10-xx

I trying with 5.10.x.

**Comment by tuxtergames** [comment]
> > > Changed the graysky2 patch link on install.sh, but:
> > > ```
> > > -> Applying graysky's cpu opts patch
> > >  -> Patch either not found, not available for this kernel version or not needed. Skipping...
> > > ```
> > 
> > 
> > I'll wait for a few days and wait for a fix, maybe install 5.10-xx
> 
> I trying with 5.10.x.

same error...

HEAD is now at 012f78dad Linux 5.10.21
 -> Downloading Graysky2's CPU optimisations patch
--2021-03-09 10:58:53--  https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v10.1+_kernel_v5.8+.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-09 10:58:53 ERROR 404: Not Found.

 -> exit cleanup done

**Comment by bkdwt** [comment]
> > > > Changed the graysky2 patch link on install.sh, but:
> > > > ```
> > > > -> Applying graysky's cpu opts patch
> > > >  -> Patch either not found, not available for this kernel version or not needed. Skipping...
> > > > ```
> > > 
> > > 
> > > I'll wait for a few days and wait for a fix, maybe install 5.10-xx
> > 
> > 
> > I trying with 5.10.x.
> 
> same error...
> 
> HEAD is now at 012f78dad Linux 5.10.21
> -> Downloading Graysky2's CPU optimisations patch
> --2021-03-09 10:58:53-- https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/enable_additional_cpu_optimizations_for_gcc_v10.1+_kernel_v5.8+.patch
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-03-09 10:58:53 ERROR 404: Not Found.
> 
> -> exit cleanup done

I have tested this link: https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch

I can download but the script doesn't apply.

**Comment by gardotd426** [comment]
Yeah none of them are going to work, guys. All the urls in the TKG repo are broken. Until Etienne fixes it, there's nothing that can be done.

**Comment by ptr1337** [comment]
tested with wget the download, seems to work. But dont know how to implement this into the script.

`ptr1337@MacBook-Air-von-Peter ~ % wget https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch
--2021-03-09 15:05:29--  https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 22088 (22K) [text/plain]
Wird in »more-uarches-for-gcc-v10-and-kernel-5.8+.patch« gespeichert.

more-uarches-for-gc 100%[===================>]  21,57K  --.-KB/s    in 0,003s

2021-03-09 15:05:29 (6,62 MB/s) - »more-uarches-for-gcc-v10-and-kernel-5.8+.patch« gespeichert [22088/22088]`

**Comment by bkdwt** [comment]
> tested with wget the download, seems to work. But dont know how to implement this into the script.
> 
> `ptr1337@MacBook-Air-von-Peter ~ % wget https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch
> --2021-03-09 15:05:29-- https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch
> Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
> Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
> Länge: 22088 (22K) [text/plain]
> Wird in »more-uarches-for-gcc-v10-and-kernel-5.8+.patch« gespeichert.
> 
> more-uarches-for-gc 100%[===================>] 21,57K --.-KB/s in 0,003s
> 
> 2021-03-09 15:05:29 (6,62 MB/s) - »more-uarches-for-gcc-v10-and-kernel-5.8+.patch« gespeichert [22088/22088]`

Yeah, the same for me.

**Comment by gardotd426** [comment]
I just changed downloaded the new patch but saved it under the same name as the old patch, and removed the https://....... from the source array in the PKGBUILD, so that way it looks in the current directory for the file. Idk if it'll actually build but I'm trying now. 

If you want to try and use the old patch, you can do the same thing just with the old instead of the new. Idk about non-Arch users.

**Comment by gardotd426** [comment]
Like, I ran `wget https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch -O enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch` and then removed the url from the source stuff in the PKGBUILD, so it just shows the filename. Who knows if it'll build, but I'd hope it would, since I'm on Arch and everything should be about as up to date as possible

**Comment by redgloboli** [comment]
if you edited PKGBUILD, you would also need to edit linux-tkg-config/prepare file

for example:

- tkgpatch="$srcdir/enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v${opt_ver}.patch" && _tkg_patcher
+ tkgpatch="$srcdir/more-uarches-for-gcc-v10-and-kernel-${opt_ver}.patch" && _tkg_patcher

to have the scripts use the patches.

you could also just replace 

https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/

with

https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/outdated_versions/

in the PKGBGUILD to use the old files.

**Comment by gardotd426** [comment]
Um, no. 

If you name the new file the same exact name as the old original file, nothing else needs to be changed.

**Comment by gardotd426** [comment]
like I said, `wget https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch -O enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch` gives me the new patch under the old patch's name. So nothing else needs changing.

**Comment by gardotd426** [comment]
I don't imagine TKG is just going to leave this broken, so I see no point in that. I just copied the original PKGBUILD to PKGBUILD.bak, and when he fixes it, I'll return it to it's original state and do a git pull.

**Comment by redgloboli** [comment]
i'm sure he'll fix it. no worries from my side. just wanted to point out what could be done besides manually downloading and renaming. ;)

was thinking about a pull request but i didn't know how to handle the 5.7 patch which seems didn't get a new version and you need to handle the different download URL for this version separateley in the script.

**Comment by redgloboli** [comment]
no worries and no pressure meant.

**Comment by Tk-Glitch** [comment]
Ok I see a typo :frog:

**Comment by Tk-Glitch** [comment]
Please try again with https://github.com/Frogging-Family/linux-tkg/commit/01f9622fbf00c96dd04e71862a7ebfc024cde370

**Comment by bkdwt** [comment]
@Tk-Glitch 

```
origin	https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (fetch)
origin	https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (push)
 -> Current branch: * (HEAD detached at v5.10.21)
 -> Reseting files to their original state
HEAD is now at 012f78dad Linux 5.10.21
 -> Switching to linux-5.10.y
  linux-5.10.y
 -> 5.10.y branch exists locally, updating...
Previous HEAD position was 012f78dad Linux 5.10.21
Switched to branch 'linux-5.10.y'
Your branch is up to date with 'origin/linux-5.10.y'.
fatal: 'kernel.org' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 -> exit cleanup done

```

**Comment by AdelKS** [comment]
@bkdwt can you go in `linux-src-git` and do `git remote -v`

**Comment by bkdwt** [comment]
> @bkdwt can you go in `linux-src-git` and do `git remote -v`

Problem persists. I'll try to delete all and git clone again.

**Comment by AdelKS** [comment]
Oh I mean show me the output xD

**Comment by bkdwt** [comment]
> Oh I mean show me the output xD

Cloned the repo again and now works! ;)
