### ISSUE TITLE
UPDS not avaliable for kernel 5.10+

### ISSUE THREAD

**Issue by bkdwt** [Frogging-Family/linux-tkg#197]
Hi! I got this error when I try to compile the 5.10 kernel with upds:

```
[bkdwt@fedora linux-tkg]$ ./install.sh install
 -> Ryzen Desktop (Performance) profile will be used.
 -> 
 ==> WARNING: Your cpusched selection ( upds ) is not available for the selected kernel version. Please select another:
 -> Which CPU sched variant do you want to build/install? Select "1" if unsure.
1) Undead PDS (TkG)  3) Project C / BMQ	  5) CFS
2) Project C / PDS   4) MuQSS
#? 
```
But readme has this:

`5.10.y (Undead PDS, Project C / PDS & BMQ, MuQSS)`

Can I choose option 1 anyway?

**Comment by ptr1337** [comment]
Just dont write anything into the custom.cfg  and select ( 1) Undead PDS (TkG); that is upds. 
Give it a try with that.

**Comment by bkdwt** [comment]
Many thanks @Tk-Glitch 😊
