### ISSUE TITLE
linux-tkg-{bmq,muqss,pds}-haswell fails to boot on Pentium G3250

### ISSUE THREAD

**Issue by ahmubashshir** [Frogging-Family/linux-tkg#201]
PREEMPT tkg kernels fails to boot on my machine with Pentium G3250, tried with both grub and systemd-boot.

**Comment by Tk-Glitch** [comment]
Make sure to use dkms modules for Nvidia if you're using that. Otherwise, logs? :frog:

**Comment by ahmubashshir** [comment]
I don't have a gpu :P, no logs comes up... in sd-boot, keyboard leds blinks once and then it reboots to boot menu. In grub, it shows
```
Loading /vmlinuz-linux-tkg-bmq-haswell...
Loading /initramfs-linux-tkg-bmq-haswell.img...
```
then leds blinks and reboot to loader :/ even without `quiet`.

**Comment by ahmubashshir** [comment]
Non PREEMPT kernels boots fine though, I'm using `linux-lts-tkg-bmq` right now.

**Comment by Tk-Glitch** [comment]
Chaotic-aur naming.. Have you tried a self built? That's the first time such an issue is reported, and I have never faced an issue with westmere, sandy bridge, broadwell, skylake, coffee lake and comet lake. It would be weird that only haswell suddenly broke.

**Comment by kostadin04** [comment]
It will not work with `-march=haswell`, since it has cut down instructions from the other Haswell cpu's, I think for those pentiums `-march=nehalem`works the best.

**Comment by Tk-Glitch** [comment]
That would explain partially at least. If that specific CPU has limitations versus usual haswell chips, we can't use the -march flag safely. Building with -mnative instead should work though, but that obviously won't be an option for chaotic-aur :frog:

@ahmubashshir could you please try the -generic version then?

**Comment by ahmubashshir** [comment]
I'll try

**Comment by ahmubashshir** [comment]
Both generic and nehalem worked, thank for the suggestion @Tk-Glitch, @kostadin04.
