### ISSUE TITLE
CCache breaks install on OpenSUSE

### ISSUE THREAD

**Issue by wolfw3** [Frogging-Family/linux-tkg#204]
Hi, I think I found an issue in the linux-tkg build. Whenever ccache is enabled on OpenSUSE Leap, the build fails with this error: https://pastebin.com/5BMbPRVD
This is on a fresh install of the OpenSUSE server edition

Disabling ccache in customization.cfg fixes this.

**Comment by fosspill** [comment]
Thank you! After doing this though I'm left with:
RPM build errors:
    line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
    Bad exit status from /var/tmp/rpm-tmp.7H2Dgn (%build)
make[1]: *** [scripts/Makefile.package:59: rpm-pkg] Error 1
make: *** [Makefile:1534: rpm-pkg] Error 2
 -> exit cleanup done

**Comment by AdelKS** [comment]
This definitely looks like an "old" version of `ccache` that doesn't support latest arguments, in this case `locale` for `CCACHE_SLOPPINESS`, which is in the [current latest version of ccache](https://ccache.dev/manual/latest.html).

About the `Obsoletes: Obsoletes: kernel-headers` this error appeared in previous issues and I couldn't pinpoint the issue with it.

**Comment by AdelKS** [comment]
Hello, please retry with ccache disabled and see if this error message gets fixed:
```
line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
```

**Comment by fosspill** [comment]
I just retried after a git pull and I'm getting the exact same error

**Comment by AdelKS** [comment]
@fosspill can you try again with this change in `customization.cfg`
```
_configfile="linux-tkg-config/5.11/config.x86_64"
```

**Comment by fosspill** [comment]
Did the exact change and still get the same error sadly

**Comment by AdelKS** [comment]
Thank you for your feedback @fosspill. Unfortunately, my intuition on the source of the issue wasn't correct. I will keep it in mind and I may work it out in the near future.

Can you open another bug report about the title "RPM compile fail: unversioned obsoletes to kernel-headers" ? Because the issue with CCache is that it was old on OpenSuse Leap.
