### ISSUE TITLE
5.11.x install fails

### ISSUE THREAD

**Issue by jollycar** [Frogging-Family/linux-tkg#212]
==> Retrieving sources...
  -> Downloading linux-5.11.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  112M  100  112M    0     0  9211k      0  0:00:12  0:00:12 --:--:-- 8449k
  -> Downloading patch-5.11.10.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  416k  100  416k    0     0  1787k      0 --:--:-- --:--:-- --:--:-- 1787k
  -> Downloading more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-gcc-v10-and-kernel-5.8%2B.patch
    Aborting...
  -> exit cleanup done

**Comment by jollycar** [comment]
see this commit:
https://github.com/graysky2/kernel_gcc_patch/commit/5fa7fc7802c929eb239198adabcfc42ee852065b

**Comment by AdelKS** [comment]
A PR fixed that minutes ago, git pull and you are good to go! Don't forget to close the issue :P

**Comment by jollycar** [comment]
yes confirmed fixed. Kudos!
