### ISSUE TITLE
0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch patch failed

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#215]
### Applying 0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch... ###
patching file fs/proc/task_mmu.c
Hunk #4 FAILED at 1212.
Hunk #5 succeeded at 1225 (offset 1 line).
Hunk #6 FAILED at 1263.
Hunk #7 succeeded at 1328 (offset -1 lines).
Hunk #8 succeeded at 1401 (offset -1 lines).
Hunk #9 succeeded at 1452 (offset -1 lines).
Hunk #10 succeeded at 1470 (offset -1 lines).
2 out of 10 hunks FAILED -- saving rejects to file fs/proc/task_mmu.c.rej

![2021-04-01_19-13](https://user-images.githubusercontent.com/1161594/113286174-6b187900-931e-11eb-98ba-bb8984b0b65d.png)

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue. Could you please attach your config file if you modified it?

**Comment by Tk-Glitch** [comment]
You seem to have a broken tree, actually. 5.11.11 patch is missing in your log, which is not supposed to happen.

**Comment by HougeLangley** [comment]
Thanks, I will try

**Comment by AdelKS** [comment]
How can one have a broken tree ? Have you downloaded the zip instead of git cloning @HougeLangley ? I think we should add a line stating to `git clone` in the README.

**Comment by Tk-Glitch** [comment]
This is a makepkg build, so this doesn't apply. Also, if the patch is either missing or corrupted it wouldn't pass the checksum. For some reason here it passed but the patch isn't extracted nor applied.

**Comment by Tk-Glitch** [comment]
Actually it might be a dependency issue. @HougeLangley could you please check if you have the `xz` package installed?

This is what should happen:
```
==> Extracting sources...
  -> Extracting linux-5.11.tar.xz with bsdtar
  -> Extracting patch-5.11.11.xz with xz
==> Starting prepare()...
  -> Setting version...
  -> Patching from 5.11 to 5.11.11
  -> Applying graysky's cpu opts patch
```

**Comment by Tk-Glitch** [comment]
> I meant to git clone linux-tkg instead of downloading its zip from Github. The patch is inside the repository and is not fetched from a remote location thinking

The 5.11.y patches are fetched from kernel.org :thinking:

**Comment by AdelKS** [comment]
Absolutely! I was talking about the patch written in the headline of this issue x)

You are most probably right about him not having `xz` installed !

**Comment by Tk-Glitch** [comment]
> Absolutely! I was talking about the patch written in the headline of this issue x) But as you pointed out, it wouldn't pass the checksum.

Oh, right. I don't think that patch is at fault here. It's just trying to apply against plain 5.11 while it's not compatible and should be applied against 5.11.11 (actually it was rebased against some other 5.11.y update but that's not the point :frog: ).

`xz` is in the make dependencies array so running `makepkg -si` as recommended should cover both the dependencies and installation steps.

**Comment by HougeLangley** [comment]
[prepare.log](https://github.com/Frogging-Family/linux-tkg/files/6243787/prepare.log)

**Comment by HougeLangley** [comment]
> Actually it might be a dependency issue. @HougeLangley could you please check if you have the `xz` package installed?
> 
> This is what should happen:
> 
> ```
> ==> Extracting sources...
>   -> Extracting linux-5.11.tar.xz with bsdtar
>   -> Extracting patch-5.11.11.xz with xz
> ==> Starting prepare()...
>   -> Setting version...
>   -> Patching from 5.11 to 5.11.11
>   -> Applying graysky's cpu opts patch
> ```

yes, I have been installed

![xz](https://user-images.githubusercontent.com/1161594/113300327-5e9d1c00-9330-11eb-861e-e5ee5189f7b2.png)

**Comment by AdelKS** [comment]
Can you please attach the entirety of what is displayed in your command line starting from `makepkg -si` ? @HougeLangley

**Comment by HougeLangley** [comment]
> Can you please attach the entirety of what is displayed in your command line starting from `makepkg -si` ? @HougeLangley
> 
> Edit: also, the file `customization.cfg`

OK, wait for a moment. I will finish gentoo ebuild and will test again.

**Comment by tuantran1632001** [comment]
I think I have the same problem with the same report in prepare.log. I do use modprobed-db but I doubt that's the issue.

There are also two new options that I don't recognize though: PCI Express Bandwidth Change No
tification (PCIE_BW), Analog Devices Generic AXI ADC IP core driver (ADI_AXI_ADC). Build still failed with both of them disable or enable.

[makepkg.txt](https://github.com/Frogging-Family/linux-tkg/files/6244551/makepkg.txt)
[linux-tkg.txt](https://github.com/Frogging-Family/linux-tkg/files/6244555/linux-tkg.txt) - custom config file

**Comment by AdelKS** [comment]
Okay found the issue, that I can reproduce on my machine, this:
```shell
  -> Patching from 5.11 to 5.11.11
  -> Patch either not found, not available for this kernel version or not needed. Skipping...
```

**Comment by Tk-Glitch** [comment]
So we have been able to find the root cause, which is the 5.40 update to `file`. 5.39 works fine, while 5.40 leads to this issue. I'll try to make some kind of workaround.
