### ISSUE TITLE
Not seeing bcachefs related kernel config options/files on 5.11

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/linux-tkg#223]
Hello, @Tk-Glitch! I've recently been trying to build a 5.11 tkg kernel with bcachefs support, but even after enabling in customization.cfg, the files and kernel config options don't show up. Elsewhere, I've really only seen 5.10 kernels with it, so I'm not sure if it's supposed to be 5.10-only or something else (maybe I'm doing something wrong?). I've installed bcachefs-tools, so I don't think that's an issue...

Thanks as always!

**Comment by Tk-Glitch** [comment]
The patchset hasn't been rebased against 5.11 at this point in time. Here's the author's repo: https://github.com/koverstreet/bcachefs

**Comment by CartoonFan** [comment]
Ah, thanks. I did a little experimenting of my own after I made this issue, and I realized the same thing. If I had known it was 5.10 only, I wouldn't have made this issue, so sorry about that. I just wish that it was publicly mentioned somewhere, you know? That way, I wouldn't have had to go digging around PKGBUILDs and such.

Hmm...since someone recently made a rebase issue over there (https://github.com/koverstreet/bcachefs/issues/209), should I close this? I mean, it **is** an actual issue, but...

**Comment by PedroHLC** [comment]
Actually that GitHub repository is a mirror, the active one is here: https://evilpiepirate.org/git/bcachefs.git

**Comment by CartoonFan** [comment]
Ah, good to know, @PedroHLC. I wasn't sure if that one was still active or not.

**Comment by CartoonFan** [comment]
So, it seems like the bcachefs kernel recently had a rebase to 5.11. I don't know of any patch changes or anything, but at least the zen-bcachefs kernel seems to compile and run fine.

**Comment by Sukid** [comment]
Yep, linux-bcachefs-git is at 5.11 as well as of a couple days ago.

**Comment by YellowOnion** [comment]
you can use `https://evilpiepirate.org/git/bcachefs.git/rawdiff/?id=${kernel.commit}&id2=${kernel.base}` to download a diff file to patch any kernel version you want.

**Comment by CartoonFan** [comment]
Thanks for the info, @YellowOnion!

**Comment by Sukid** [comment]
@YellowOnion Ooooh, cool! What do we do with that url though? Is latestcommit the bcachefs commit and basecommit the linux kernel commit?

**Comment by YellowOnion** [comment]
> @YellowOnion Ooooh, cool! What do we do with that url though? Is latestcommit the bcachefs commit and basecommit the linux kernel commit?

so Kents master is based on v5.11, so if you find Torvalds tag for v5.11 commit id, and then put it in the "basecommit", then find the commit on master that you want to create a patch for and use latest commit.

this patch file should apply to any v5.11.x, and MIGHT apply to 5.12, last night I did some testing and there was some changes to the linux API, so back porting to v5.10 is not easy.

you can also do this on a local copy from git.

```
$ git diff v5.10 origin/bcachefs-v5.10 > ../bcachefs-5.9.patch
$ git diff v5.9 origin/bcachefs-v5.9 > ../bcachefs-5.9.patch
$ git diff v5.10 origin/bcachefs-v5.10 > ../bcachefs-5.10.patch
$ git diff v5.11 origin/master > ../bcachefs-5.11.patch
```

**Comment by YellowOnion** [comment]
You can attempt to use these: https://github.com/YellowOnion/bcachefs-patches

**Comment by CartoonFan** [comment]
Thanks, @Tk-Glitch!
