### ISSUE TITLE
Strange values in src/customization-all.cfg

### ISSUE THREAD

**Issue by MrDrMcCoy** [Frogging-Family/linux-tkg#225]
While running `makepkg` I decided to look in the `src/` directory to see what it was up to, and what differences there were between the main `customization.cfg` and `customization-all.cfg`. To my surprise, there were several things in there that just seem wrong. For example, these appear to be invalid shell array definitions, assuming that's what they are:

```
_CPUSCHEDARRAY=([0]="Undead
_CPUSCHEDVARARRAY=([0]="upds"
_cpu_marchs=([0]="k8"
```

Additionally, these values seem to be ignoring my preferences:

```
_march="native_intel"
_march_upper="NATIVE_INTEL"
```

As opposed to the values set in [my customization.cfg](https://pastebin.com/gcn0jm3W):

```
_OPTIPROFILE="2"
_processor_opt="zen2"
```

Despite all this, the kernel does compile and I am able to boot with it. Is this a misunderstanding on my part, or is there an issue here?

**Comment by AdelKS** [comment]
Hello, 

Don't worry about this, this file is created by pulling all the variables that have been defined during the script:

` PKGBUILD, line 495`
```shell
declare -p | cut -d ' ' -f 3 | grep -P '^_(?!=|EXT_CONFIG_PATH|where|path)' > "${srcdir}/customization-full.cfg"
```
And the thing is, the variables keep their last defined value, which is not necessarily the one used to actually make the kernel. For example the variable `_march` actually runs in a loop and explores all possibilities, and only when it is equal to the user defined value that it's used to actually configure the kernel.

**Comment by MrDrMcCoy** [comment]
Thanks for the clarification, @AdelKS. Is there any way to see/store the variables that were used in the final build?

Also, if I were to come up with another means of writing out those variables that does a better job of parsing arrays, etc, would that be a worthy PR?

**Comment by AdelKS** [comment]
Basically temporary variables that have no particular interest are getting stored in `customization-full.cfg`. What one can do is to do exceptions and not store them. 

I think one should just trust that `customization.cfg` is followed by the letter, along with the user input during the script so one doesn't need to check `customizatio-full.cfg` in my opinion. I think a filled out `customization.cfg` should be the one to be saved.

**Comment by MrDrMcCoy** [comment]
@AdelKS All right, thanks for clearing that up.
