### ISSUE TITLE
Disabling stripping of debug symbols

### ISSUE THREAD

**Issue by lordkitsuna** [Frogging-Family/linux-tkg#226]
hello! it seems that even with the various debug options enabled the symbols get stripped out of the vmlinux file. was hoping an option could be added to remove the stripping so the kernel built can be used for debugging with things like faddr2line

**Comment by lordkitsuna** [comment]
Was curious if anyone knew how this could be done. Maybe a change i can make locally to the pkg configs or something. I've been in need of faddr2line of late so I've had no choice but to have a separate debug kernel build without any patches but ideally i wouldn't have to keep rebooting for that. 

I'm not sure where the stripping takes place so I'm not sure where to look into disabling it

**Comment by AdelKS** [comment]
How do you get your separate debug kernel build ? How is it not stripped ? Or is it some binary release from upstream ?

**Comment by lordkitsuna** [comment]
Honestly I'm not 100% sure anymore it's such a mix of me tryingto manually build using https://wiki.archlinux.org/title/Kernel/Traditional_compilation and taking random aur scripts. I will compile everything i have and share the configs here once i have them all sorted so hopefully someone can figureoout which part of my mess is avoiding the stripping

**Comment by lordkitsuna** [comment]
I managed to figure out what was doing the stripping and created a PR to make it optional https://github.com/Frogging-Family/linux-tkg/pull/265

**Comment by lordkitsuna** [comment]
solved by #265
