### ISSUE TITLE
kernel-devel actually is needed on Fedora for DKMS

### ISSUE THREAD

**Issue by trgeiger** [Frogging-Family/linux-tkg#229]
The recent change to no longer build kernel-devel for Fedora has broken DKMS. Seems that Fedora requires the corresponding -devel package for the current kernel to install DKMS modules.
```bash
❯ sudo dkms autoinstall          
Error! echo
Your kernel headers for kernel 5.11.15_tkg_pds cannot be found at
/lib/modules/5.11.15_tkg_pds/build or /lib/modules/5.11.15_tkg_pds/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.
```

**Comment by trgeiger** [comment]
I opened this PR to address this https://github.com/Frogging-Family/linux-tkg/pull/230

**Comment by AdelKS** [comment]
I expected the headers to be installed by the... `kernel-headers` RPM package x)

The folder `/lib/modules/5.11.15_tkg_pds/build` seems to be pointing to `/usr/src/kernels/5.11.15_tkg_pds` which for sure is installed by the `kernel-devel` package. `kernel-headers` seems to install stuff in `/usr/include` and actually this is he useless package that can be omitted :thinking:

**Comment by AdelKS** [comment]
Okay, I just checked what's inside the DEB packages and they got their naming right : `linux-headers` actually installs the headers that DKMS uses. `linux-libc-dev` DEB package is the equivalent of `kernel-headers` in Fedora, confusing stuff. It really seems like Fedora packaging script on the kernel side has an issue...
