### ISSUE TITLE
EFISTUB

### ISSUE THREAD

**Issue by rejedai** [Frogging-Family/linux-tkg#232]
I can't figure it out, does this core support **EFISTUB**? I didn't find the `CONFIG_EFI_STUB=y` option in the config files. When trying to start the kernel directly through UEFI, the system does not boot with the error "`failed to mount /sysroot`". Or does loading the kernel indicate that this option is present?

**Comment by rejedai** [comment]
I found it [here](https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/5.11/config.x86_64), so the problem is in my settings.

**Comment by rejedai** [comment]
I was able to find a solution.

main sctipt:
```
#!/bin/bash

rm /home/murr/Downloads/efi_creater/linux.efi
echo "cp old EFI removed"
objcopy \
    --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="/efi_creater/kernelparameter" --change-section-vma .cmdline=0x30000 \
    --add-section .splash="/usr/share/systemd/bootctl/splash-arch.bmp" --change-section-vma .splash=0x40000 \
    --add-section .linux="/boot/vmlinuz-linux-tkg-muqss-skylake" --change-section-vma .linux=0x2000000 \
    --add-section .initrd="/boot/initramfs-linux-tkg-muqss-skylake.img" --change-section-vma .initrd=0x3000000 \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/efi_creater/linux.efi"

echo "cp EFI created"

rm /boot/EFI/arch/linux-tkg-muqss-skylake.efi
echo "old EFI removed"
cp /home/murr/Downloads/efi_creater/linux.efi /boot/EFI/arch/linux-tkg-muqss-skylake.efi
echo "EFI created"
```

/efi_creater/kernelparameter:
```
root=UUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX rw initrd=\intel-ucode.img quiet splash 
```

**UUID** must be **ROOT** of the partition, not **BOOT** !!!
Then place created file to `/esp/EFI/arch/` and create boot entry.

**Comment by AdelKS** [comment]
> I found it here, so the problem is in my settings.

You probably used `modprobed-db`: it does not catch EFI modules and they need to be added by hand afaik.
