### ISSUE TITLE
Can't compile linux-tkg 5.12 with 2994601

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/linux-tkg#235]
Can't compile linux-tkg 5.12 with 2994601740537250f841089b3642e055b529d930
[prepare.log](https://github.com/Frogging-Family/linux-tkg/files/6397530/prepare.log)
![Screenshot from 2021-04-29 14-23-59](https://user-images.githubusercontent.com/36989404/116530042-03425780-a8f7-11eb-8455-c4672a117364.png)
![Screenshot from 2021-04-29 14-23-18](https://user-images.githubusercontent.com/36989404/116530046-04738480-a8f7-11eb-9ae3-ea41e2b47a96.png)

**Comment by Tk-Glitch** [comment]
![Screenshot_20210429_122020](https://user-images.githubusercontent.com/741977/116536548-5dd2b800-a8e5-11eb-8800-272e87abf8e7.png)
I cannot reproduce the issue on my end. Have you modified the kernel config or used external patches?

**Comment by AdelKS** [comment]
Maybe it's one of those specific MuQSS options, can you attach your `customization.cfg` along with your terminal output before the start of the compile stage ?

**Comment by Kerrung** [comment]
Now everything compiles fine for me, and the problem appears when I use the -flto flag in /etc/makepkg.conf, when I use GCC 11.1, which I myself compiled from source.
By the way, can you tell me if GCC supports LTO compilation? Is Clang strictly required for this?

**Comment by Tk-Glitch** [comment]
GCC supports LTO, but compiling the kernel with it is unique to Clang for now.
