### ISSUE TITLE
_timer_freq in the config file doesn't seem to do anything

### ISSUE THREAD

**Issue by Apig-Sharbo** [Frogging-Family/linux-tkg#238]
So i was at trying to change the **Timer frequency**, trying different values. When using menuconfig, xconfig, etc... and setting the value of 1000hz for example there, i would verify after finishing and rebooting into the new kernel by running:
```bash
zcat /proc/config.gz | grep CONFIG_HZ
```
it would output this after everything was successful:
```bash
➜  zcat /proc/config.gz | grep CONFIG_HZ
# CONFIG_HZ_PERIODIC is not set
# CONFIG_HZ_100 is not set
# CONFIG_HZ_250 is not set
# CONFIG_HZ_300 is not set
# CONFIG_HZ_500 is not set
# CONFIG_HZ_750 is not set
CONFIG_HZ_1000=y
CONFIG_HZ=1000
```
But when by changing **_timer_freq** value in the either **"customization.cfg"** or **"linux-tkg.cfg"** to any of the suggested values, it always applied 500hz at the end after verifying.
I tried with kernels **5.11**, **5.10** and  **5.9** and also with cpu schedulars **cfs** and **upds**, all of them had the same outcome (still 500hz ignoring the value i set). 

**NOTE**: I had **_modprobeddb** set to **true** to make testing/compiling faster, but the problem **persisted** with it set to **false** as well. Just wanted to give more info.

In **kernelconfig.new** i get this when timer frequency is set to **1000hz** through the config file:
```
# CONFIG_HZ_100 is not set
# CONFIG_HZ_250 is not set
# CONFIG_HZ_300 is not set
CONFIG_HZ_500=y
# CONFIG_HZ_750 is not set
# CONFIG_HZ_1000 is not set
CONFIG_HZ=500
``` 
as opposed to this, when set to **1000hz** through **menuconfig** for example:
```
# CONFIG_HZ_100 is not set
# CONFIG_HZ_250 is not set
# CONFIG_HZ_300 is not set
# CONFIG_HZ_500 is not set
# CONFIG_HZ_750 is not set
CONFIG_HZ_1000=y
CONFIG_HZ=1000
```

System info, if needed:
- Linux Distro: Manjaro + dwm
- CPU: Intel i7 6700HQ
- GPU:
  + NVIDIA GeForce GTX 950M
  + Intel HD Graphics 530
- RAM: 16GB

**Comment by AdelKS** [comment]
Oh! Weird stuff is going on, that means `kernelconfig.new` is copied back to user directory too early ? 🤔

**Comment by Tk-Glitch** [comment]
Seems to be enough : https://github.com/Frogging-Family/linux-tkg/commit/63f0a1ea79e63ea622bb19feedba6911c40aa0d5

I also checked `/proc/config.gz` post boot and values were fine.

**Comment by Tk-Glitch** [comment]
Ok, I think your issue is that you're using a preset with `_OPTIPROFILE="3"`, which is setting a 500Hz tickrate. The profile overwrites customization.cfg values.

See:
```
# Prompt about optimized configurations. Available variable values will overwrite customization.cfg/external config ones.
    plain "Do you want to use a predefined optimized profile?"
    read -rp "`echo $'  > 1.Custom\n    2.Ryzen Desktop (Performance)\n    3.Other Desktop (Performance)\nchoice[1-3?]: '`" _OPTIPROFILE;
```

The issue here is that the comment in the .cfg doesn't say profiles are overriding .cfg options.
