### ISSUE TITLE
Suspend and hibernate not working on 5.7.5

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#24]
Anyone have same problem like me, suspend and hibernate not working on kernel 5.7.5. At first I think is BMQ's problem. Because this issue.

https://gitlab.com/alfredchen/projectc/-/issues/17

But, I found the PDS and MuQSS have same problems

**Comment by Snoop05** [comment]
I can confirm, on 5.7.2-5 suspend worked, after upgrading to 5.7.5-11 with same settings i doesnt anymore. I will try arch kernel (5.7.5-1 in testing) to see if its affected too

**Comment by Tk-Glitch** [comment]
It seems to be an upstream regression. Quite a few reports regarding hibernate and/or suspend right now. I'll investigate.

**Comment by HougeLangley** [comment]
Update to 5.7.6, still could not suspend and hibernate.

Anyone no luck like me.

**Comment by Tk-Glitch** [comment]
https://bugzilla.kernel.org/buglist.cgi?quicksearch=suspend

**Comment by AdelKS** [comment]
I don't know if this information is of any help, but I am running 5.7 PDS on Ubuntu and the computer can suspend.
