### ISSUE TITLE
i2c_hid module is not found

### ISSUE THREAD

**Issue by trgeiger** [Frogging-Family/linux-tkg#240]
On new installations of either 5.12 or 5.11 on Fedora, i2c_hid module is nowhere to be found which breaks my touchpad. I've tried removing all custom kernels and compiling while booted into the stock kernel, but nothing seems to be helping.

This also only started happening recently so I'm not sure if it has to do with the recent DKMS Fedora changes--I've manually installed the generated kernel, kernel-devel, and kernel-headers packages though so I don't think it should have anything to do with that.

**Comment by Tk-Glitch** [comment]
After a quick search I can find quite a few users with i2c_hid related issues. But usually it's just that it doesn't get loaded and loading it manually fixes the issue. If it's actually missing, we're probably dealing with a .config issue. Would you have your .config at hand maybe?

**Comment by trgeiger** [comment]
Yeah I've seen the same issues, but the actual module is missing. So I also came to the conclusion that it's a .config issue, but I thought/hoped that booting into a default kernel and then compiling would fix the issue. Would the kernelconfig.new that's generated by the script be an accurate copy of what my .config has? (I'm not well versed on fetching and manipulating kernel configs).

**Comment by trgeiger** [comment]
OH I see them in /boot, I'll upload the stock and the 5.12.1 that was generated

**Comment by trgeiger** [comment]
[config-5.11.17-300.fc34.x86_64.txt](https://github.com/Frogging-Family/linux-tkg/files/6416759/config-5.11.17-300.fc34.x86_64.txt)
[config-5.12.1_tkg_pds.txt](https://github.com/Frogging-Family/linux-tkg/files/6416760/config-5.12.1_tkg_pds.txt)

**Comment by trgeiger** [comment]
Weird, I was booted into 5.11.17 but the 5.11.17 config and the kernelconfig.new are much different it seems. I'm going to try making a local copy of the 5.11.17 config file and pass that directly via the customization.cfg file to see if that works any better.

**Comment by Tk-Glitch** [comment]
The problem here is using a 5.11 kernel config as base for 5.12. The option name was changed from `CONFIG_I2C_HID` to `CONFIG_I2C_HID_ACPI` between 5.11 and 5.12. So yeah, you'd have to manually enable it.

**Comment by trgeiger** [comment]
Ohh, well that makes sense. So basically to have this work automatically I would have to wait until Fedora is shipping their own stock 5.12 config file. Awesome, thanks for your help!

**Comment by Tk-Glitch** [comment]
It *can* work as is sometimes, but yeah the safest way is indeed to wait until your distro ships a 5.12.y kernel.
Alternatively, you can also try using the Arch config offered here : https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/5.12/config.x86_64
Fedora is usually fine with Arch kernels.
