### ISSUE TITLE
I see an error message message during system startup: "psi: task underflow!"

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/linux-tkg#244]
[prepare.log](https://github.com/Frogging-Family/linux-tkg/files/6510546/prepare.log)
[customization.zip](https://github.com/Frogging-Family/linux-tkg/files/6510550/customization.zip)
But I don't see it with "linux" package from official Arch Linux repositories.

**Comment by AdelKS** [comment]
Hello, this is probably a `modprobed-db` thing, can you try without it ?

**Comment by Tk-Glitch** [comment]
Not an issue. MuQSS has very limited support for psi so that's expected. If it's annoying you, either disabled psi with `psi=0` kernel boot parameter or use CFS :frog:

**Comment by Kerrung** [comment]
> Hello, this is probably a `modprobed-db` thing, can you try without it ?

Unfortunately, _modprobeddb="true" causes compilation to not even start for me. Therefore, I have to not use this anyway, unfortunately. I even opened a bug report here on this topic: #224
