### ISSUE TITLE
undefined reference to `cpufreq_default_governor'

### ISSUE THREAD

**Issue by Darklink999999** [Frogging-Family/linux-tkg#246]
Hello, trying to compile the 5.12 kernel gives this error:

```
ld: drivers/cpufreq/cpufreq.o: in function `cpufreq_init_policy':
/home/qushy/linux-tkg/src/linux-5.12/drivers/cpufreq/cpufreq.c:1080: undefined reference to `cpufreq_default_governor'
ld: drivers/cpufreq/cpufreq.o: in function `cpufreq_core_init':
/home/qushy/linux-tkg/src/linux-5.12/drivers/cpufreq/cpufreq.c:2884: undefined reference to `cpufreq_default_governor'
```

I'm on Garuda Linux. Am i missing some dependencies possibly?

**Comment by jollycar** [comment]
Same here
```
  LD      .tmp_vmlinux.btf
ld: drivers/cpufreq/cpufreq.o: in function `cpufreq_init_policy':
/home/x/opt/linux-tkg/src/linux-5.12/drivers/cpufreq/cpufreq.c:1080: undefined reference to `cpufreq_default_governor'
ld: drivers/cpufreq/cpufreq.o: in function `cpufreq_core_init':
/home/x/opt/linux-tkg/src/linux-5.12/drivers/cpufreq/cpufreq.c:2884: undefined reference to `cpufreq_default_governor'
  BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: No such file or directory
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
make: *** [Makefile:1202: vmlinux] Error 1
```
I'm running 5.11 tkg on manjaro

**Comment by jollycar** [comment]
Followup: I only get this error when building using ```_cpusched="muqss"```. When using ```pds```, the build compiles.

**Comment by AdelKS** [comment]
Please attach your entire bash output from the beginning the script and `cusromization.cfg`

**Comment by jollycar** [comment]
I have uploaded the bash output and customization.cfg:
[log_and_customization.zip](https://github.com/Frogging-Family/linux-tkg/files/6637737/log_and_customization.zip)

**Comment by AdelKS** [comment]
Thanks!

Can you try again with the `customization.cfg` option `_default_cpu_gov` empty ? (So it' `schedutil` instead of `ondemand`). I get the feeling this may enable the compile process to finish. It is interesting that it's only failing at linking.

**Comment by MCPO-Spartan-117** [comment]
The commit that was supposed to fix this seems rather extreme since this seems to only happen to one person as i'm able to build it just fine with the latest 5.12.15 kernel, i'll upload my frogminer and kernel configs just in case this is an issue with those but i believe this might be a issue with manjaro's gcc or something.
[5.12.tar.gz](https://github.com/Frogging-Family/linux-tkg/files/6778980/5.12.tar.gz)
Using Artix-x86_64 with GCC 11.1.0-1 and glibc 2.33-5.
