### ISSUE TITLE
Tell which timer to use depending on (maybe) parameters and scheduler

### ISSUE THREAD

**Issue by binarydepth** [Frogging-Family/linux-tkg#247]
I was prompted and it pointed to 750Hz timer but I don't know why or what it is.  I have Ryzen 5 1600 non-AF. I'm trying PDS first, hope it does better than BMQ.

**Comment by Tk-Glitch** [comment]
Default choice (just hitting enter) is a good balance overall. Default is 1000Hz for CacULE, 100Hz for MuQSS and 500Hz for other schedulers.

**Comment by ptr1337** [comment]
nvm

**Comment by pkejval** [comment]
Just wondering why is CacULE allowed to use 2000Hz? Does it have any advantages over 1000Hz?

**Comment by Tk-Glitch** [comment]
Well, higher Hz means lower latency (but higher overhead / less throughput). So it's a double edged sword. Higher responsiveness for lower performance, basically.
As to why it's allowed to use 2000Hz, that frequency is simply added by the patchset. Instead of just ignoring the option altogether, I preferred respecting its developer's choice and allowing it to be selected with the existing variable if the user wants it.

**Comment by binarydepth** [comment]
> Well, higher Hz means lower latency (but higher overhead / less throughput). So it's a double edged sword. Higher responsiveness for lower performance, basically.

Hey XD. So, the default timer just gets an ">" to the left, right? Then just add quoted text if you want, because maybe there are articles getting technical about it. It's a bit confusing at first glance but I think you mean less fps with more responsiveness? haven't actually researched this. So, I was asking from the point of view of someone who doesn't have the technical knowledge like me.

**Comment by ptr1337** [comment]
> Well, higher Hz means lower latency (but higher overhead / less throughput). So it's a double edged sword. Higher responsiveness for lower performance, basically.
> As to why it's allowed to use 2000Hz, that frequency is simply added by the patchset. Instead of just ignoring the option altogether, I preferred respecting its developer's choice and allowing it to be selected with the existing variable if the user wants it.

Seems like youre right ? Mhm.

**Comment by Tk-Glitch** [comment]
> So, the default timer just gets an ">" to the left, right?

Absolutely.

> It's a bit confusing at first glance but I think you mean less fps with more responsiveness?

Reality is a bit more complex, but that's pretty much it, yes.

I'll add some fluffy text to explain it in the comment, thanks for feedback :slightly_smiling_face:
