### ISSUE TITLE
5.13.rc3 compilation error

### ISSUE THREAD

**Issue by jhu54** [Frogging-Family/linux-tkg#249]
Pretty new to this, thought I would try to compile the rc3 kernel and get this error (ubuntu, rc3, custom and cfs options selected):

Branch 'master-kernel.org' set up to track remote branch 'master' from 'kernel.org'.
Switched to a new branch 'master-kernel.org'
 -> Checking out latest RC tag: v5.13-rc3
Note: switching to 'v5.13-rc3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c4681547b Linux 5.13-rc3
 -> Downloading Graysky2's CPU optimisations patch
--2021-05-25 12:01:50--  https://raw.githubusercontent.com/graysky2/kernel_gcc_patch/master/more-uarches-for-kernel-.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-25 12:01:50 ERROR 404: Not Found.

Should I add:

    "513")
    opt_ver="5.8+"
    ;;

to the basever case statement in the install.sh script? It does produce a compiled kernel but am not sure if this is the correct approach.

**Comment by AdelKS** [comment]
Hello, thanks for pointing it out. What you did is absolutely correct. @Tk-Glitch please add that line, I will have a look at it and do something about it in my PR, best would be to make it happen for anything above 5.8 instead of case-wise approach.

**Comment by jhu54** [comment]
Thanks. Just to clarify the rc3 - are fsync, winesync and futex2 options available?

**Comment by Tk-Glitch** [comment]
I'll make the adequate changes, thanks for reporting.

5.13 RCs are only offering optional winesync support currently. Fsync and Futex2 support is planned and I'll make it happen asap.

**Comment by jhu54** [comment]
Absolutely wonderful thanks for the update and making this and the WINE builds. Now if only I could get gcc 11 to compile on Mint 20.1 to experiment with the 11th gen compiler improvements.
