### ISSUE TITLE
Is there any way I can compile 5.4 instead of 5.4.123?

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#250]
Title.

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/linux-tkg/blob/dd1a0f0d9169ed64861dd4d2a86eadaa9c594d03/linux-tkg-config/prepare#L3

Change this to your version you want and create a sha256 of it and change it also

**Comment by AdelKS** [comment]
Yes.

Instead of being short on your description, you can give more information on the distro you use, your hardware, and why you would like to do such a thing so maybe we can help you better.

**Comment by rizzini** [comment]
> https://github.com/Frogging-Family/linux-tkg/blob/dd1a0f0d9169ed64861dd4d2a86eadaa9c594d03/linux-tkg-config/prepare#L3
> 
> Change this to your version you want and create a sha256 of it and change it also

Thank you so much! It worked.

> Yes.
> 
> Instead of being short on your description, you can give more information on the distro you use, your hardware, and why you would like to do such a thing so maybe we can help you better.

I objectively know what I want. I'm testing some patches of my own and I want to keep using TKG's too, but for 99% of the cases, you're right.
