### ISSUE TITLE
_OPTIPROFILE setting not respected.

### ISSUE THREAD

**Issue by Daedalusspacegames** [Frogging-Family/linux-tkg#253]
Pretty much what the title says. If the _OPTIPROFILE is any value, then irrespective of that value the prepare script seems to select "Ryzen desktop (performance)", If left empty _OPTIPROFILE is prompted as expected, and does seem to respect the setting in that case.

Edit: For clarity, this issue only started after the refactor.

**Comment by AdelKS** [comment]
Thanks for the feedback, #254 fixes it
