### ISSUE TITLE
Feature request: Kernel local version not working as expected

### ISSUE THREAD

**Issue by binarydepth** [Frogging-Family/linux-tkg#255]
I am trying to get `uname -a` to output Zen1 in the kernel name. Maybe this should be done by default to know the kernel is optimized for your CPU.

**Comment by AdelKS** [comment]
Are you thinking of something different than #133 ?

**Comment by binarydepth** [comment]
Yes, sorry I forgot about that issue. mb

**Comment by AdelKS** [comment]
What distro are you using? What is your issue with local version? Can you write what your package manager shows when it tries to install the kernel.

**Comment by binarydepth** [comment]
I'm using Garuda. It just Says Linux512 and followed by the scheduler. I expect the config to work as documented in the customization file. Linux512-LOCAL-PDS

**Comment by AdelKS** [comment]
Oh that feature is `non-arch specific`, `Garuda` being `Arch` based, that config option does nothing. You can use `custom_pkgbase` instead: for that you need to write the entirety of the package name: `linux512-local-pds`

**Comment by binarydepth** [comment]
I'm using Garuda. It just Says Linux512 and followed by the scheduler. I expect the config to work as documented in the customization file. Linux512-LOCALNAME-PDS

**Comment by ErdeFB** [comment]
It's working as documented. Use custom_pkgbase instead.

**Comment by binarydepth** [comment]
> It's working as documented. Use custom_pkgbase instead.

It Works! Sorry, didn't read properly.
