### ISSUE TITLE
CacULE for LTS kernels

### ISSUE THREAD

**Issue by ranplayer** [Frogging-Family/linux-tkg#263]
Hi,

Would it be possible to add the CacULE scheduler for the LTS kernels (5.4/5.10) ?

**Comment by ptr1337** [comment]
https://aur.archlinux.org/packages/linux-cacule-lts/
or at my GitHub repo. 

5.4 will be pushed soon, 5.10-RT-(RDB) already pushed.

**Comment by ranplayer** [comment]
Great, thanks @ptr1337
