### ISSUE TITLE
Realtime patch?

### ISSUE THREAD

**Issue by SM9CC** [Frogging-Family/linux-tkg#264]
It would be interesting to see an tkg-rt kernel, I am not sure how well it would work with the other patches.

Is this possible?

Thanks.

**Comment by ptr1337** [comment]
If non TKG allowed, https://aur.archlinux.org/packages/linux-cacule-rdb-rt/
non RDB-Version also possible, needs to be polished a bit more.

**Comment by Tk-Glitch** [comment]
It wouldn't play well with the goal of our patchsets, which is gaming oriented (and RT kernels are simply bad for gaming).

**Comment by ptr1337** [comment]
> It would be interesting to see an tkg-rt kernel, I am not sure how well it would work with the other patches.
> 
> Is this possible?
> 
> Thanks.

@SM9CC 

https://aur.archlinux.org/packages/linux-cacule-rt/

https://aur.archlinux.org/packages/linux-cacule-rdb-rt/

Update to the newest kernel version, also several other patches. Gaming expierence so far good. Desktop usage also.

Prebuilt Kernels also Gneric3 youll find here,

https://aur.cachyos.org/?dir=cachyos-aur

**Comment by SM9CC** [comment]
> > It would be interesting to see an tkg-rt kernel, I am not sure how well it would work with the other patches.
> > Is this possible?
> > Thanks.
> 
> @SM9CC
> 
> https://aur.archlinux.org/packages/linux-cacule-rt/
> 
> https://aur.archlinux.org/packages/linux-cacule-rdb-rt/
> 
> Update to the newest kernel version, also several other patches. Gaming expierence so far good. Desktop usage also.
> 
> Prebuilt Kernels also Gneric3 youll find here,
> 
> https://aur.cachyos.org/?dir=cachyos-aur

Thanks, I will try them! :)

**Comment by X9VoiD** [comment]
Made a pr to add rt patches :bread: I think it will still be beneficial to some extent. A case would be osu! players that requires really low latency and/or consistent frame pacing even if it reduces average fps by a small margin.

**Comment by alphabitserial** [comment]
I know this is an old issue but I just wanted to say _thank you_ for including this patchset, it's solved an issue with running Linux on my Macbook where the audio on the headphones wouldn't work in apps like Discord but would basically just stutter forever.
