### ISSUE TITLE
Please rebase bcachefs patch against 5.12 kernel

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/linux-tkg#266]
Hello, @Tk-Glitch! I just wanted to let you know that bcachefs recently became compatible with the 5.12 kernel, and I was wondering if you could update the patch to work with the new kernel. Hopefully that's not too much trouble :grin: . Thanks as always!

**Comment by PedroHLC** [comment]
@Tk-Glitch, suggestion, source `https://evilpiepirate.org/git/bcachefs.git/rawdiff/?id=master&id2=v5.12` instead.

The same can be done with older versions:
* `https://evilpiepirate.org/git/bcachefs.git/rawdiff/?id=bcachefs-v5.11&id2=v5.11`
* `https://evilpiepirate.org/git/bcachefs.git/rawdiff/?id=bcachefs-v5.10&id2=v5.10`

Probably better as Kent is active in them all...

**Comment by AdelKS** [comment]
that's a good idea, although changes in those patches won't be reflected in a bump in `pkgrel` :thinking:

**Comment by Tk-Glitch** [comment]
Also it tends to break at times, needing local edits, which has been the only reason for me to use local patchsets for it (and I'm stuck with it).

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/d4a42125518b9b84131d75b81ecd8aeade5af932

**Comment by CartoonFan** [comment]
Thanks, @Tk-Glitch!
