### ISSUE TITLE
Can't compile linux-tkg 5.12.10.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/linux-tkg#267]
Arch Linux
[prepare.log](https://github.com/Frogging-Family/linux-tkg/files/6662205/prepare.log)
I managed to compile successfully when the 5.12.9 kernel was the newest and then, of course, I used the linux-tkg commit that was older than now (I don't remember which one), because it was the newest at that time. But now, when I try to compile on 5.12.10 using 8126726847252a5b14e8e08553ac727c7cd37bfe, the compilation crashes and I see this: 
![Screenshot from 2021-06-16 14-45-51](https://user-images.githubusercontent.com/36989404/122203938-fd5d0180-ceb7-11eb-8e86-d777f0e7d1b8.png)

**Comment by Tk-Glitch** [comment]
You're out of memory.

Random google search result :frog: : https://www.programmersought.com/article/68464560932/
