### ISSUE TITLE
Can't compile 5.12.11

### ISSUE THREAD

**Issue by pkejval** [Frogging-Family/linux-tkg#270]
Can't compile yesterdays 5.12.11 with no errors. Tried on two computers with stable Manjaro:

` LD [M]  crypto/sm2_generic.o
==> CHYBA: Došlo k chybě v build().
    Rušení...
  -> exit cleanup done

  -> compilation time : 

real	0m39,265s
user	3m20,535s
sys	0m22,561s
`
Attached my config.
[linux-tkg.txt](https://github.com/Frogging-Family/linux-tkg/files/6667762/linux-tkg.txt)

**Comment by AdelKS** [comment]
Hello, the latest kernel update changed a small thing which prevents at least project C schedulers from compiling (PDS, BMQ): https://gitlab.com/alfredchen/linux-prjc/-/issues/27

As soon as it's fixed upstream, we'll mirror it here

**Comment by robson-66** [comment]
I have the same problem when building `linux-tkg-bmq`
