### ISSUE TITLE
Arch instructions do not work

### ISSUE THREAD

**Issue by fatalis** [Frogging-Family/linux-tkg#272]
https://github.com/Frogging-Family/linux-tkg#arch--derivatives

`PKGBUILD: line 8: plain: command not found`

PKGBUILD uses things declared in install.sh? docs not updated for Arch or something?

**Comment by AdelKS** [comment]
Hello,

Which distro are you using ? `makepkg -si` works perfectly on Arch. You would get that error if you run the `PKGBUILD` file directly, someting like `sh PKGBUILD` or `./PKGBUILD` :thinking: Have you installed `base-devel` : `pacman -S --needed base-devel` ?

**Comment by fatalis** [comment]
woops, forgot I'm using a custom `makepkg` which seems to break this PKGBUILD. closing
