### ISSUE TITLE
Futex2 Patches - Compiling error on Kernel 5.13.0

### ISSUE THREAD

**Issue by EduFrazao** [Frogging-Family/linux-tkg#273]
Hi. Futex2 patches apply succeful on 5.13.0, but fails to compile with this error:

`
beast /usr/src/linux # make
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND objtool
  CHK     include/generated/compile.h
  CC      kernel/futex2.o
kernel/futex2.c: In function ‘futex_get_shared_key’:
kernel/futex2.c:314:31: error: implicit declaration of function ‘basepage_index’; did you mean ‘page_index’? [-Werror=implicit-function-declaration]
  314 |   key->index = (unsigned long)basepage_index(tail);
      |                               ^~~~~~~~~~~~~~
      |                               page_index
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:272: kernel/futex2.o] Error 1
make: *** [Makefile:1847: kernel] Error 2

`
GCC Info:

`
beast /usr/src/linux # gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/10.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-10.3.0/work/gcc-10.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/10.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/10.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 10.3.0 p1' --disable-esp --enable-libstdcxx-time --with-build-config=bootstrap-lto --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libssp --disable-libada --disable-systemtap --disable-vtable-verify --disable-libvtv --without-zstd --enable-lto --with-isl --disable-isl-version-check --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.3.0 (Gentoo 10.3.0 p1)
`

**Comment by Tk-Glitch** [comment]
I have updated the patch for 5.13 release: https://github.com/Frogging-Family/linux-tkg/commit/6d796bf233f7f4c4840f4bf89e23d11d791b4409

**Comment by EduFrazao** [comment]
Thank you! Its working now.
