### ISSUE TITLE
Ubuntu kernel target 5.12.14 fails to compile

### ISSUE THREAD

**Issue by jhu54** [Frogging-Family/linux-tkg#276]
Attempted to compile Ubuntu target for pds and cfs options and both give this error and exit:

make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1587: deb-pkg] Error 2

**Comment by AdelKS** [comment]
Try again now, this issue may have been fixed. Otherwise please attach as a file here (by drag and drop) the complete output of the script and your customization.cfg. which version of Ubuntu is it?

**Comment by jhu54** [comment]
fixed - thx
