### ISSUE TITLE
Problems during Module Installation for linux 5.12.14

### ISSUE THREAD

**Issue by wildanazman** [Frogging-Family/linux-tkg#277]
Anyone knows how to fix this? 
![image](https://user-images.githubusercontent.com/85623687/124296377-792f9d00-db8c-11eb-8982-1ae306ad8b0f.png)

**Comment by AdelKS** [comment]
I assume this  is Ubuntu, it looks like you are not using `install.sh` nor the produced `.deb` packages in the `DEBS` folder ?

**Comment by wildanazman** [comment]
yes, this is ubuntu. I just follow the steps to upgrade and compile kernel in the internet but still none of thems are working.

**Comment by AdelKS** [comment]
Have you had a read at linux-tkg's [README](https://github.com/Frogging-Family/linux-tkg) on how to use it ?
```shell
git clone https://github.com/Frogging-Family/linux-tkg.git
cd linux-tkg
# Optional: edit the "customization.cfg" file
./install.sh install
```
