### ISSUE TITLE
kernel-headers package conflicts with linux-glibc-devel (opensuse TW)

### ISSUE THREAD

**Issue by whew-inc** [Frogging-Family/linux-tkg#278]
Hi

I can't install kernel-headers RPM without either overwriting files that belong to `linux-glibc-devel` or removing it. Removing it gets rid of a ton of other devel packages and even Steam.

**Comment by AdelKS** [comment]
Hello,

Overwriting files from `linux-glibc-devel` should be relatively safe as you can resinstall it after and ask it to overwrite stuff, too. If I remember well, this package is only needed for `winesync/fastsync` support. So if  you don't need that, you can safely not install that package. The `install.sh` script doesn't offer to not install that package specifically, but you can answer "no" when it prompts for installing, then you install the `rpm` files in the `RPMS` manually, where you omit the that corresponds to `linux-glibc-devel`.
