### ISSUE TITLE
Checksum Linux Kernel

### ISSUE THREAD

**Issue by wildanazman** [Frogging-Family/linux-tkg#280]
Does anyone know how to do the security checksum verification of the Linux kernel source code for Linux 5.12.14? Is there any source that I can refer to.

**Comment by ptr1337** [comment]
which souce is failing ? 

output please

**Comment by wildanazman** [comment]
Nothing is failing. I just need to get security checksum verification for the linux kernel source code for my assignment. but I didnt find a way.

**Comment by wildanazman** [comment]
![image](https://user-images.githubusercontent.com/85623687/124738673-c07eaa80-df4b-11eb-986d-5a92c32962e5.png)

**Comment by AdelKS** [comment]
`install.sh` performs a `git clone` and downloads the kernel source code to `linux-src-git`, using the tool `git`. `git` checksums automatically every file within that folder.

**Comment by AdelKS** [comment]
Your assignment probably expects the other way get the source code: through tarballs. Those can be downloaded from here https://cdn.kernel.org/pub/linux/kernel/v5.x/ , along with signature files with the `.sign` extension that you can verify with `gpg` (you can Google that).

**Comment by wildanazman** [comment]
Yes, i already managed to upgrade and compile to the latest version which is 5.12.14. But I dont know how to do the security checksum for the linux kernel source code. Any tips?

**Comment by AdelKS** [comment]
The "security checksum" is to verify the downloaded tarball with its corresponding `.sign` file with `gpg`: https://wiki.archlinux.org/title/GnuPG#Verify_a_signature

**Comment by wildanazman** [comment]
Owh, i see. I have done that prt but i didnt know that is security checksum. Thanks man.
