### ISSUE TITLE
im having this after doing those commands

### ISSUE THREAD

**Issue by Solid-Freeman** [Frogging-Family/linux-tkg#284]
[solidfreeman@SolidFreeeman linux-tkg]$ makepkg -si
           .---.`               `.---.
        `/syhhhyso-           -osyhhhys/`
       .syNMdhNNhss/``.---.``/sshNNhdMNys.
       +sdMh.`+MNsssssssssssssssNM+`.hMds+
       :syNNdhNNhssssssssssssssshNNhdNNys:
        /ssyhhhysssssssssssssssssyhhhyss/
        .ossssssssssssssssssssssssssssso.
       :sssssssssssssssssssssssssssssssss:
      /sssssssssssssssssssssssssssssssssss/   Linux-tkg
     :sssssssssssssoosssssssoosssssssssssss:        kernels
     osssssssssssssoosssssssoossssssssssssso
     osssssssssssyyyyhhhhhhhyyyyssssssssssso
     /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
      smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
       /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
        `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
           `-+shdNNNNNNNNNNNNNNNdhs+-`
                 `.-:///////:-.`
  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
        0) 5.14.rc2
      > 1) 5.13.4
        2) 5.12.19
        3) 5.11.22
        4) 5.10.52
        5) 5.9.16
        6) 5.8.18
        7) 5.7.19
        8) 5.4.134
[0-8]: 1
    Selected: 5.13.4
  -> Which CPU sched variant do you want to build/install?
  -> Project C (pds) / BMQ (bmq) is usually a good balance for gaming.
  -> Select "cfs" (linux kernel's default) if unsure.
      > 0) Project C / PDS
        1) Project C / BMQ
        2) CacULE
        3) CFS (Completely Fair Scheduler) Linux kernel's default
[0-3]: 0
    Selected: Project C / PDS
    Do you want to use a predefined optimized profile?
      > 0) Custom
        1) Ryzen Desktop (Performance)
        2) Other Desktop (Performance)
[0-2]: 2
    Selected: Other Desktop (Performance)
  -> Generic Desktop (Performance) profile will be used.
  -> 
    Which compiler do you want to use?
      > 0) GCC (recommended)
        1) Clang/LLVM
[0-1]: 0
    Selected: GCC (recommended)
==> WARNING: The package group has already been built, installing existing packages...
==> Installing linux513-tkg-pds package group with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (2) linux513-tkg-pds-5.13.4-182  linux513-tkg-pds-headers-5.13.4-182

Total Installed Size:  254.23 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                     [######################] 100%
(2/2) checking package integrity                   [######################] 100%
(2/2) loading package files                        [######################] 100%
(2/2) checking for file conflicts                  [######################] 100%
error: failed to commit transaction (conflicting files)
linux513-tkg-pds: /etc/modules-load.d/winesync.conf exists in filesystem (owned by linux513-tkg-cfs)
linux513-tkg-pds: /etc/udev/rules.d/winesync.rules exists in filesystem (owned by linux513-tkg-cfs)
linux513-tkg-pds: /usr/include/linux/winesync.h exists in filesystem (owned by linux513-tkg-cfs)
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
  -> exit cleanup done

**Comment by AdelKS** [comment]
Hello, you need to disable `winesync` in `customization.cfg` as only one kernel at a time can be installed with it. You probably aren't using winesync anyway.

Cheers

**Comment by JohnyPeaN** [comment]
You can install it this (horrible) way:
sudo pacman -U *tkg-pds*182*.pkg.tar.zst --overwrite='*'

But removing any kernel (which includes these) will remove them for others.
I think these configuration files should not be included in kernel package, but instead have its own.

**Comment by Tk-Glitch** [comment]
Yeah, you can't have two kernels installed side by side with built-in winesync support enabled. Using the dkms driver instead is the recommended way (as detailed in the prompt at build time).

**Comment by Solid-Freeman** [comment]
sorry guys im new here about kernel 
i need more details using linux manjaro

**Comment by AdelKS** [comment]
You edit [this line](https://github.com/Frogging-Family/linux-tkg/blob/c50061015feb38e0a098e3b7c58d71e225fe7498/customization.cfg#L142) and change it to `_winesync="false"` in the file `customization.cfg` that is in the same folder where you ran `makepkg -si` in your first message.

**Comment by Solid-Freeman** [comment]
> You edit [this line](https://github.com/Frogging-Family/linux-tkg/blob/c50061015feb38e0a098e3b7c58d71e225fe7498/customization.cfg#L142) and change it to `_winesync="false"` in the file `customization.cfg` that is in the same folder where you ran `makepkg -si` in your first message. And this time you run `makepkg -fsi`

still getting same error

**Comment by AdelKS** [comment]
Please attach your customization.cfg file and the entire output on your terminal here, by saving it in a text file then drag & dropping it where you write your answer.

**Comment by Solid-Freeman** [comment]
> Please attach your customization.cfg file and the entire output on your terminal here, by saving it in a text file then drag & dropping it where you write your answer.

i think i edit the wrong file ! did this now that's the result :) anyway thanks i should reboot with the new kernel
 
![Screenshot_2021-07-24_11-21-43](https://user-images.githubusercontent.com/87747082/126864107-c611f6c8-5bad-44be-83ab-a0233ee392d3.png)

**Comment by AdelKS** [comment]
Awesome! Enjoy your new kernel. If you don't have any more questions, don't forget to close the issue :)

**Comment by Solid-Freeman** [comment]
> Awesome! Enjoy your new kernel. If you don't have any more questions, don't forget to close the issue :)

One thing how can I boot with new kernel in advanced tab 

Only showin those two 
![Uploading 16271191170673776760966461247114.jpg…]()

**Comment by AdelKS** [comment]
Oh, you need to update your [GRUB boot entries](https://wiki.archlinux.org/title/GRUB#Generated_grub.cfg): `sudo grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by Solid-Freeman** [comment]
> Oh, you need to update your [GRUB boot entries](https://wiki.archlinux.org/title/GRUB#Generated_grub.cfg): `sudo grub-mkconfig -o /boot/grub/grub.cfg`

Did this command on terminal nothing happened grub is empty :/  in manjaro

**Comment by AdelKS** [comment]
Must be some Manjaro shenanigans, can you give me the output of your terminal, always do that when you get issues. And give me the output of `ls /boot`

**Comment by Solid-Freeman** [comment]
![Screenshot_2021-07-24_14-09-45](https://user-images.githubusercontent.com/87747082/126868005-0cb3ead7-f7d8-4cba-918c-8cd82bfc23b1.png)
this one ?

**Comment by AdelKS** [comment]
Yes! You can just copy the output text and attach it between \``` ``` 

Now, what's the error you get with the `grub-mkconfig` command ?

**Comment by Solid-Freeman** [comment]
i dont know what to copy but here xD 
```[solidfreeman@SolidFreeeman ~]$ ls /boot
efi                                      initramfs-linux514-tkg-cfs.img
grub                                     intel-ucode.img
initramfs-5.10-x86_64-fallback.img       linux510-x86_64.kver
initramfs-5.10-x86_64.img                memtest86+
initramfs-linux513-tkg-cfs-fallback.img  vmlinuz-5.10-x86_64
initramfs-linux513-tkg-cfs.img           vmlinuz-linux513-tkg-cfs
initramfs-linux513-tkg-pds-fallback.img  vmlinuz-linux513-tkg-pds
initramfs-linux513-tkg-pds.img           vmlinuz-linux514-tkg-cfs
initramfs-linux514-tkg-cfs-fallback.img
[solidfreeman@SolidFreeeman ~]$  ```


[SolidFreeeman solidfreeman]# grub-mkconfig
/etc/default/grub: line 60: ^T: command not found
[SolidFreeeman solidfreeman]# sudo grub-mkconfig -o /boot/grub/grub.cfg
/etc/default/grub: line 60: ^T: command not found
[SolidFreeeman solidfreeman]#

**Comment by AdelKS** [comment]
Thanks !

Here's your issue:
```
[SolidFreeeman solidfreeman]# sudo grub-mkconfig -o /boot/grub/grub.cfg
/etc/default/grub: line 60: ^T: command not found
```
Have you edited by hand the file `/etc/default/grub` ?

**Comment by Solid-Freeman** [comment]
yeah i guess so i add some command 
for TSX

**Comment by AdelKS** [comment]
You made a syntax mistake while doing so, probably. Can you attach that file ?

**Comment by Solid-Freeman** [comment]
the /etc/default/grub ?

**Comment by AdelKS** [comment]
Yes, I can help you fix the syntax error there so `grub-mkconfig` successfully completes

**Comment by Solid-Freeman** [comment]
> Yes, I can help you fix the syntax error there so `grub-mkconfig` successfully completes

is there any way to send this Grub file here ?

**Comment by AdelKS** [comment]
You can attach it here by first copying it to your home folder, `sudo cp /etc/default/grub ~/` then drag and drop it in your text reply here in GitHub.

**Comment by Solid-Freeman** [comment]
``````GRUB_DEFAULT=saved
GRUB_DISTRIBUTOR="Manjaro"
GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 tsx=on tsx_async_abort=off  mitigations=off security=apparmor udev.log_priority=3"
GRUB_CMDLINE_LINUX=""

# If you want to enable the save default function, uncomment the following
# line, and set GRUB_DEFAULT to saved.
GRUB_SAVEDEFAULT=true

# Preload both GPT and MBR modules so that they are not missed
GRUB_PRELOAD_MODULES="part_gpt part_msdos"

# Uncomment to enable booting from LUKS encrypted devices
#GRUB_ENABLE_CRYPTODISK=y

# Uncomment to use basic console
GRUB_TERMINAL_INPUT=console

# Uncomment to disable graphical terminal
#GRUB_TERMINAL_OUTPUT=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command 'videoinfo'
GRUB_GFXMODE=auto

# Uncomment to allow the kernel use the same resolution used by grub
GRUB_GFXPAYLOAD_LINUX=keep

# Uncomment if you want GRUB to pass to the Linux kernel the old parameter
# format "root=/dev/xxx" instead of "root=/dev/disk/by-uuid/xxx"
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
GRUB_DISABLE_RECOVERY=true

# Uncomment this option to enable os-prober execution in the grub-mkconfig command
GRUB_DISABLE_OS_PROBER=false

# Uncomment and set to the desired menu colors.  Used by normal and wallpaper
# modes only.  Entries specified as foreground/background.
GRUB_COLOR_NORMAL="light-gray/black"
GRUB_COLOR_HIGHLIGHT="green/black"

# Uncomment one of them for the gfx desired, a image background or a gfxtheme
#GRUB_BACKGROUND="/usr/share/grub/background.png"

# Uncomment to get a beep at GRUB start
#GRUB_INIT_TUNE="480 440 1"

# Uncomment to ensure that the root filesystem is mounted read-only so that
# systemd-fsck can run the check automatically. We use 'fsck' by default, which
# needs 'rw' as boot parameter, to avoid delay in boot-time. 'fsck' needs to be
# removed from 'mkinitcpio.conf' to make 'systemd-fsck' work.
# See also Arch-Wiki: https://wiki.archlinux.org/index.php/Fsck#Boot_time_checking
#GRUB_ROOT_FS_RO=true
GRUB_TIMEOUT_STYLE="menu"
GRUB_TIMEOUT="10"
GRUB_THEME="/usr/share/grub/themes/Vimix/theme.txt"
^T
T
^t

**Comment by AdelKS** [comment]
Okay remove those `^T`, `T` and `^t` are the end of the file and retry the `grub-mkconfig -o ...` command

**Comment by Solid-Freeman** [comment]
tried those two 
``` [solidfreeman@SolidFreeeman ~]$ sudo grub-mkconfig -o /boot/grub/grub.cfg
[sudo] password for solidfreeman: 
/etc/default/grub: line 60: ^T: command not found
[solidfreeman@SolidFreeeman ~]$ grub-mkconfig -o 
grub-mkconfig: option requires an argument -- `-o'
[solidfreeman@SolidFreeeman ~]$ ```

**Comment by AdelKS** [comment]
Okay, you didn't save your changes after removing those characters are the end of `/etc/default/grub`. Do `sudo nano /etc/default/grub` to open `nano` on that file, remove those weird lines at the end. Then save with `ctrl+x`. The `grub-mkconfig` command is only this one `sudo grub-mkconfig -o /boot/grub/grub.cfg`. I was writing the other commands just as a shorthand for.

**Comment by AdelKS** [comment]
Oh okay you are good now ! You can restart 👯‍♂️

**Comment by Solid-Freeman** [comment]
> Oh okay you are good now ! You can restart 👯‍♂️

Now I can see the kenerls but when I hit one of them I get this 
![16271306071085711406493466995790](https://user-images.githubusercontent.com/87747082/126868813-c10a3bb7-db41-42a1-83f3-239e6dff449c.jpg)

**Comment by AdelKS** [comment]
That's normal, just filesystem check. You get to the login screen after right ?

**Comment by Solid-Freeman** [comment]
> That's normal, just filesystem check. You get to the login screen after right ?

I can't get a in login screen or it will take sometime ?

**Comment by AdelKS** [comment]
You have and Nvidia GPU ?

**Comment by Solid-Freeman** [comment]
> You have and Nvidia GPU ?

Yeah gtx 1660 ti

**Comment by AdelKS** [comment]
Okay you need to make sure the driver package that you have installed for it is called `nvidia-dkms`. If not replace your current one with `nvidia-dkms`

**Comment by Solid-Freeman** [comment]
> Okay you need to make sure the driver package that you have installed for it is called `nvidia-dkms`. If not replace your current one with `nvidia-dkms`

Where should I put that ?

**Comment by AdelKS** [comment]
Restart in the kernel that works, open your software center and look for Nvidia packages. See if you can find a dkms version ?

**Comment by Solid-Freeman** [comment]
> Restart in the kernel that works, open your software center and look for Nvidia packages. See if you can find a dkms version ?

adel thank you very much u saved me :)

**Comment by AdelKS** [comment]
Happy to help ! So everything is working, each kernel version ?

**Comment by Solid-Freeman** [comment]
> Happy to help ! ☺️ So everything is working, each kernel version ?

Like a charm😍😍❤️❤️❤️ thank you again

**Comment by AdelKS** [comment]
Amazing ! Enjoy your shiny new linux-tkg kernels ! Have you joined the Frogging-Family Discord ? You can her help for your future problems more easily : https://discord.gg/jRy3Nxk

**Comment by Solid-Freeman** [comment]
> Happy to help ! ☺️ So everything is working, each kernel version ?

Everything is working except the last one 5.14 same thing Nvidia driver need to be installed on it :)
