### ISSUE TITLE
Anbox option doesn't properly install ashmem nor binder

### ISSUE THREAD

**Issue by devheitor** [Frogging-Family/linux-tkg#285]
I'm using Ubuntu 20.04

I set _anbox="true" in customization.cfg file and installed the Linux 5.4.134-tkg-cfs kernel. It took a lot to finish the process from start to end, and when I rebooted into the new kernel:
ls -l /dev/{ashmem,binder}
ls: cannot access '/dev/ashmem': No such file or directory
ls: cannot access '/dev/binder': No such file or directory

Any idea? What could have gone wrong?

**Comment by Tk-Glitch** [comment]
That feature doesn't work with 5.4. You'll need to use a newer kernel version.

**Comment by Tk-Glitch** [comment]
The prompt is skipped on 5.4 specifically (https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/prepare#L1181), but it's not documented in the .cfg. I'll add a note.

**Comment by devheitor** [comment]
Thanks @Tk-Glitch ! Any other kernel will work? any recomentation?

**Comment by Tk-Glitch** [comment]
If you want LTS, 5.10. If you're not against using the current stable release, then 5.13 :)
