### ISSUE TITLE
Multimedia audio controller: Intel Corporation Comet Lake PCH cAVS microphone not working 

### ISSUE THREAD

**Issue by fiercebrake** [Frogging-Family/linux-tkg#286]
Greetings everyone!

I am currently using archlinux + linux-tkg 5.13 on an HP omen laptop.

Problem is:

when i compile the kernel without modprobed-db, the mic works, and the sound card profile (in pulseaudio) is labeled as "Play HIFI quality music"

But when i compile the kernel using modprobed-db, the sound card profile is a generic one, and the mic is not recognized.

I already made sure that the very same modules/drivers compiled/loaded without modprobed-db, are present when compiling with modprobed-db. SO all modules/drivers are present, but teh mic will not work and the profile on pulseaudio is completely different.

has any of you guys faced this problem before ? any advise will be appreciated.

**Comment by AdelKS** [comment]
Unfortunately `modprobed-db` doesn't catch everything and you need to find the module to add by other means and  add it by hand. Whenever you find it, consider updating archlinux's wiki in the "suggested modules"

**Comment by AdelKS** [comment]
a way to find the config option is to diff between a mdoprobed-db config and the full one and look for sound related diffrences. It is a good first lead I think.

**Comment by fiercebrake** [comment]
Hey @AdelKS 

I agree with your idea about diff, which is what i did to make sure the very same modules are included for compilation.

So, according to modprobed-db, the very same modules are available and loaded on both instances, but teh sound card will not work as expected.

**Comment by AdelKS** [comment]
I understood that, modprobed-db is not a fool-proof tool: the kernel's `.config` file is only made of `CONFIG_XXXX` entries, and modprobed-db lists modules by their simple name. My theory is that that there isn't a 1to1 correspondance between module names and the kernel CONFIG toggles. So there's a toggle that is getting changed. This won't show through `modprobed-db list` calls but will only show if you diff between the files `kernelconfig.new`, created at the same level as the PKGBUILD file, on a full kernel and on a stripped kernel.

**Comment by fiercebrake** [comment]
Ah! gotcha, so i need to check diff among the kernelconfig files.

Thanks for the pointer! i will get to it now!

**Comment by AdelKS** [comment]
Great! Keep me updated!

**Comment by fiercebrake** [comment]
@AdelKS 
I tried copying over the sound block from the kernelconfig that works, and compiling with that. Did not work

I tried using the whole kernelconfig that works. Did not work.

Any other advise you may have in mind ?

**Comment by AdelKS** [comment]
The kernel config that works does not work ? That's quite weird... Okay boot on the kernel that works you can get its `.config` file with `zcat --verbose /proc/config.gz > .config` and compare it with "whole kernelconfig that works". :thinking:

**Comment by fiercebrake** [comment]
@AdelKS 
I booted from the kernel that works as required

I pulled the config file as per your instructions

I compared (using diff) the config file pulled as per your instructions against the "whole kernelconfig that works; they are the same, no differences

**Comment by AdelKS** [comment]
That's very weird, that means... the issue is somewhere else ? But what else can it be, everything else is the same... I am lost. So you have basically two kernels, built with the same config file, one gives you mic audio and the other doesn't ? Same `customization.cfg` file ?

**Comment by fiercebrake** [comment]
@AdelKS 

Yes;

I have 2 kernels

Both built with the same kernelconfig file, one gives me mic (the one where modprobed-db is disabled), but the other not.

Same customization file on both (except for modprobed-db being enabled/disabled)

**Comment by AdelKS** [comment]
Wait, you know that `modprobed-db` only modifies the kernel config file right ? So a kernel config where you enable modprobed-db should have different config toggles

**Comment by AdelKS** [comment]
So, to make sure we understand each other: you run the `makepkg` script
1- without modprobed-db, it gives you a `kernelconfig.new` file, you rename it to `kernelconfig.full`
2- with modrpobed-db, it gives you a `kernelconfig.new` file, your rename it to `kernelconfig.mdb`
you compared `kernelconfig.mdb` with `kernelconfig.full` and made a `kernelconfig.mixed`, you tried to compile a kernel with `kernelconfig.mixed` by feeding it to the script with `_configfile` in `customization.cfg`. It didn't work. You gave `kernelconfig.full` to the script too and it still didn't work ?

**Comment by fiercebrake** [comment]
@AdelKS 

Correct on all accounts.

**Comment by AdelKS** [comment]
One last thing, when you tried `kernelconfig.mixed` or `kernelconfig.mixed` you did not activate `modprobed-db` right ? if you didn't, something is definitely off

**Comment by fiercebrake** [comment]
@AdelKS 

if i use kernelconfig.mixed or kernelconfig.mixed having modprobed-db disabled, the mic works fine.

problem comes when enabling modprobed-db. As mentioned before, i have double checked to make sure all the mods/drivers are present/loaded.

**Comment by AdelKS** [comment]
Oh! Now I understand! You need to know that `modprobed-db` is not useful anymore as it only affects the `kernelconfig.new`. So when you use `kernelconfig.mixed` you already have the unneeded modules stripped out and you do not need to use modprobed-db anymore. And if you do, it will deactivate again that module you are looking for.

**Comment by AdelKS** [comment]
So now, since you have `kernelconfig.mixed`, you can either start using only that, and not use `modprobed-db` anymore, or try to pinpoint exactly with CONFIG option is important, then try to find the associated module name, to add in modprobed-db's database manually. I don't know how one can find the module name associated to a specific CONFIG toggle in the `.config` file. Maybe its name directly ? One needs to read the code behind `make localmodconfig LSMOD=...`

**Comment by fiercebrake** [comment]
Ah!

man, sorry to waste your time on such a petty problem!, lol, i truly didn't get it was either one or the other until you mentioned it. Such a noob mistake from my part!

Yep, it works as expected using kernelconfig.mixed and having modprobed-db disabled.

Thanks for clarifying that @AdelKS, your help and patience is MUCH appreciated!

**Comment by AdelKS** [comment]
It's alright! It takes us time to understand things.

Happy to help ! Now I do not know if there's a way to get some "fake" module name to account for your mic thing. If you can pinpoint the exact CONFIG toggles you need, I'll check the code of `make localmodconfig LSMOD=` and see if I can figure out how to get a related "module name" even if no module is loaded for that matter.

**Comment by eclass4learning** [comment]
Cool!

I will see if i can get it done today, otherwise will be done at some point throughout the week.

I will inform once done,

Thanks!

**Comment by eclass4learning** [comment]
I tried isolating teh specific module that loads teh dirvers, but to no avail.

ultimately waht i did is fall back to v5.10

In kernel 5.10 the sound card is recognized by only using modprobed-db

Thanks for teh help, highly appreciated! and sorry for the long delay on this one.

**Comment by fiercebrake** [comment]
tried isolating teh specific module that loads teh dirvers, but to no avail.

ultimately waht i did is fall back to v5.10

In kernel 5.10 the sound card is recognized by only using modprobed-db

Thanks for teh help, highly appreciated! and sorry for the long delay on this one.
