### ISSUE TITLE
Discussion: PDS is coming back with Project C ?

### ISSUE THREAD

**Issue by AdelKS** [Frogging-Family/linux-tkg#29]
Heylo!

I went to check Alfred Chen's blog and it seems he will be picking back PDS under what he named Project C, it seems that PDS will also get updated if I understood well, what are you thoughts ?

Adel

**Comment by Tk-Glitch** [comment]
Ola!

PDS will be back indeed. Well my thoughts are: "FINALLY".
Having a somewhat forced stepdad role wasn't terribly exciting, and Alfred will do a better job being both more familiar than myself with his own code and a better developer in general.

I can't wait :smile:

**Comment by AdelKS** [comment]
Haha you are getting rid of the child that has been forced on you for adoption xD

I love news like these ! I have only tried his PDS scheduler per your recommendations in the repo :P Let's see what he'll come up with, I will follow his blog more closely. Actually maybe even spend more time understanding what he's doing, maybe I can suggest some wild ideas to him (probably not though).
