### ISSUE TITLE
Changing _custom_pkgbase result in unmountable root.

### ISSUE THREAD

**Issue by patlefort** [Frogging-Family/linux-tkg#292]
If I set that variable, boot will hang trying to mount the root of my system until it times out. My system is mounted on a btrfs sub-volume. However, it boot fine if I let that variable alone. My boot options are: `root=LABEL=Roots rootflags=subvol=/roots/arch rw quiet splash selinux=0 amdgpu.runpm=0 nowatchdog mitigations=off`. This is on Arch Linux.

**Comment by AdelKS** [comment]
Please show what's on your `/boot` folder and provide what you set in the `_custom_pkgbase` variable.

**Comment by patlefort** [comment]
My boot folder:
```
total 110M
drwxr-xr-x 4 root root 4.0K Aug  9 03:56 .
drwxr-xr-x 1 root root  158 Jun  1 14:39 ..
-rwxr-xr-x 1 root root  40K Jul 18 09:45 amd-ucode.img
-rwxr-xr-x 1 root root  114 Jul 29 03:13 cmdline.txt
drwxr-xr-x 8 root root 4.0K Aug  9 03:58 EFI
-rwxr-xr-x 1 root root  13M Aug  9 03:56 initramfs-linux513-tkg-pds.img
-rwxr-xr-x 1 root root  13M Aug  8 11:48 initramfs-linux-amd-znver2.img
-rwxr-xr-x 1 root root  12M Aug  8 17:18 initramfs-linux.img
-rwxr-xr-x 1 root root  13M Aug  9 03:45 initramfs-linux-tkg.img
-rwxr-xr-x 1 root root  12M Aug  9 03:11 initramfs-linux-xanmod-cacule.img
-rwxr-xr-x 1 root root  346 Jul 29 03:13 refind_linux.conf
drwxr-xr-x 2 root root 4.0K Apr 28 18:44 syslinux
-rwxr-xr-x 1 root root 4.2M Aug  8 03:59 System.map-5.13.9-AMD-znver2
-rwxr-xr-x 1 root root 9.2M Aug  8 17:18 vmlinuz-linux
-rwxr-xr-x 1 root root 9.6M Aug  9 03:56 vmlinuz-linux513-tkg-pds
-rwxr-xr-x 1 root root 9.1M Aug  8 11:47 vmlinuz-linux-amd-znver2
-rwxr-xr-x 1 root root 9.6M Aug  9 03:45 vmlinuz-linux-tkg
-rwxr-xr-x 1 root root 8.7M Aug  9 03:11 vmlinuz-linux-xanmod-cacule
```
`_custom_pkgbase` is `linux-tkg`.
`xanmod-cacule` has the same problem and I didn't touch their pkgbuild. Other kernels boot fine. They are booted from rEFInd. My `/boot` is a bind mount into my arch EFI folder `/efi/EFI/arch`. So my kernels are booted directly from rEFInd without grub.

**Comment by Snoop05** [comment]
maybe something is messed up with mkinitcpio config

**Comment by patlefort** [comment]
So I tracked it down to rEFInd not choosing the right initrd. It select `initramfs-linux.img` instead for this one but somehow it work fine for `linux-amd-znver2` and `linux513-tkg-pds`. Very strange.

**Comment by AdelKS** [comment]
Yea I had in mind an initramfs issue, glad you got in the right path to fixing it!
