### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/linux-tkg#293]
trying to compile 5.13.10 and also the previous 5.13.9 i get the same amdgpu line error
```
  CHK     kernel/kheaders_data.tar.xz
  TEST    posttest
  MODPOST modules-only.symvers
ERROR: modpost: "pm_suspend_target_state" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:150: modules-only.symvers] Error 1
make[1]: *** Deleting file 'modules-only.symvers'
make: *** [Makefile:1777: modules] Error 2
make: *** Waiting for unfinished jobs....
arch/x86/tools/insn_decoder_test: success: Decoded and checked 6401779 instructions
  TEST    posttest
arch/x86/tools/insn_sanity: Success: decoded and checked 1000000 random instructions with 0 errors (seed:0xee9ecc52)
Kernel: arch/x86/boot/bzImage is ready  (#1)
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

```

the settings are amd performance -> 0 amd (for cpu) rest default except i go with menuconfig and disable hibernate and set cpu to powersave. 
i get this error on both laptop (with APU only) and workstation (that has nvidia gpu only)

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue with the default provided config.

> and disable hibernate

Considering the error is related to power management/suspend, this is an ideal suspect here. Try without disabling hibernate. This should be managed in userspace imho.

**Comment by logan001** [comment]
yeap it seems to work without disabling hibernate and suspend to ram.
if this is not a bug related to frogging family :) please close it
