### ISSUE TITLE
Building with CacULE in a clean chroot fails because of missing wget dependency

### ISSUE THREAD

**Issue by Nocifer** [Frogging-Family/linux-tkg#299]
This happens when the install script tries to download the CacULE source file, with the following error:

```
/startdir/linux-tkg-config/prepare: line 505: wget: command not found
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done
```

So wget should be added to the makedepends array.

**Comment by ptr1337** [comment]
Fork it, add wget here : 
https://github.com/Frogging-Family/linux-tkg/blob/master/PKGBUILD#L67
