### ISSUE TITLE
PKGBUILD Error - Line 670: Argument List Too Long

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#300]
When I try to run the PKGBUILD to compile, it fails partway through claiming this error:
```
/mnt/bigStorage/linux-tkg/PKGBUILD: line 670: /usr//bin/install: Argument list too long
==> ERROR: A failure occurred in package_linux510-tkg-upds().
    Aborting...
  -> exit cleanup done
```

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue.

**Comment by ThisNekoGuy** [comment]
It might've been before the last commit; I had this issue twice in the last few days

This morning I set it to compile again and it hasn't failed yet after I git-pulled, so I'll report what happened when it's done

**Comment by ThisNekoGuy** [comment]
Strange; it happened to me again :thinking:

**Comment by ThisNekoGuy** [comment]
Must've been something wrong with my `makepkg.conf`

I had:
```
MAKEFLAGS="-j$(nproc) --platform linux-clang"
```

or something like that and removing the last part fixed the issue
