### ISSUE TITLE
Mouse is locked inside the game(Diablo 3) window(windowed mode).

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#316]
This game has this option, but I keep it disabled. This doesn't happen using Arch's repository wine. 

Is there any way to avoid that?

![Screenshot_20210921_153315](https://user-images.githubusercontent.com/1186150/134227947-e50a24b1-c3f2-4a50-bdad-edc1f5d46aa8.png)

**Comment by AdelKS** [comment]
I think you opened the issue in the wrong repository xD 

Here you go: https://github.com/Frogging-Family/wine-tkg-git

**Comment by rizzini** [comment]
Oh my... Closing it. Thank you.
