### ISSUE TITLE
Launching 5.14.8 goes straight to intramfs screen with no USB keyboard

### ISSUE THREAD

**Issue by jhu54** [Frogging-Family/linux-tkg#322]
Had the same problem with 5.14.7 - compile using either bmq or pds, select stock options. rocketlake optimisations and 0 for config. Compile occurs as per normal, but when I select installation, I note that usual error about missing amd firmware does not appear and attempting to load the kernel (5.14.7 or 8) drop into the intramfs command prompt with no USB keyboard. This did not occur with 5.14.6.

Ubuntu target and full tickless were other options, GCC compiler...

**Comment by netbospl** [comment]
To be honest my PC was unstable under kernel 5.14.
It was hanging ofter (every few hours, sometimes less).
I've decided to fallback to 5.13, no hangs for past 72 on 5.13.
I'm happy with 5.13 myself.

**Comment by chipshopness** [comment]
Same here on Ubuntu with both 5.14.7 and 5.14.8.

**Comment by AdelKS** [comment]
Please re-compile from an official ubuntu kernel and use `_configfile="current-kernel"` in `customization.cfg`

**Comment by jhu54** [comment]
Assume you mean _configfile="running-kernel" ...

**Comment by AdelKS** [comment]
Hello @jhu54 ,

I think it is an `initramfs` compression algorithm issue where the kernel is not set to decompress the algorithm used by Ubuntu by default. Can you attach your `/etc/initramfs-tools/initramfs.conf

Can you also please attach the config file of the "5.14.8" kernel that works here ? You can obtain it by running the kernel then doing
```
cp /boot/config-`uname -r` config-works
```

> Strange it did not work with the stock Ubuntu kernel from focal...

It is normal as the kernel is "old" and its config file leads to issues when "upgrading" it to 5.14

**Comment by ptr1337** [comment]
@AdelKS 

I got also one report that my kernel does not work. 

`Hi i found bug in your latest kernel 5.14.8-1-cacule-rdb-llvm

Usb not working propely usb mouse after connect to usb doesn't work and booting show repeating warning about xhci_hcd`

He wrote me. But stock does work. Maybe a patch ? Cant debug it atm.

**Comment by AdelKS** [comment]
Thanks @jhu54 

Unfortunately my initramfs hypothesis is wrong: it is compressed with lz4 and both the default config (that doesn't work for you) and the config that works enable decompressing lz4 initramfs. Is there any error message when the computer drops in initramfs ? That would be helpful. What's your filesystem type, BTRFS ?

@ptr1337 which patch is it ?

**Comment by jhu54** [comment]
Unfortunately there was no error message just straight to the command prompt. Partition is a Ext4 - I don't use BTRFS on this system.

**Comment by AdelKS** [comment]
Do you have anything in `/etc/initramfs-tools/conf.d` ? 

I have an idea, can you try rebuilding the kernel with an empty `_configfile` (so, to have defaults), but you open `xconfig` when prompted at the end, and chose `lz4` in `General setup > kernel compression mode`. And tell me if it works. I hope this it :D

**Comment by ptr1337** [comment]
@AdelKS 

Acutally i dont know which it was correctly. I completly cleared up my PKGBUILD. 
And also changed the config variable from the latest arch commit. 

https://github.com/ptr1337/linux-cacule/commit/95c87db8677da6228b3942c5618f580ca5b644e2#diff-9e8168f6f1a00a4a5026f968abac40315be124bd231ccc66461c71ac1444ae68

But i think it was one of those: 
```
	source = https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.14/misc/amd/0011-amd-ptdma.patch
	source = https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.14/misc/0007-string.patch
	source = https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.14/misc/0004-folio-mm.patch
	source = https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.14/0001-Allow-polling-rate-to-be-set-for-all-usb-devices.patch
```

I dont know which patches yourre actually using.

**Comment by jhu54** [comment]
There is nothing in /etc/initramfs-tools/conf.d - I have rolled back to 5.14.6 - something in the new 5.14.8 causing some instability with my 6700xt. Once I can see whether it is a Mesa/RADV issue or kernel I will try a recompile as suggested.

**Comment by AdelKS** [comment]
> Same issue - no warnings about amdgpu firmware being missing and boot straight into initramfs when kernel selected at boot. Using the configfile option rather than the default does generate a working kernel...

So you tried to make the kernel lz4 compressed and that changes nothing right ? I am out of ideas for now... x)

**Comment by ptr1337** [comment]
@AdelKS 

Seems to be fixed with 5.14.9

**Comment by AdelKS** [comment]
Thanks @ptr1337 let's see if it makes any difference for the people having issues here! Please report back!

**Comment by chipshopness** [comment]
Same problem for me with 5.14.9.

I've just noticed that the kernel and initrd are much smaller than they should be.

38734255 Oct  2 19:49 initrd.img-5.14.6-tkg-cacule-llvm
11419452 Oct  2 19:46 initrd.img-5.14.9-tkg-cacule-llvm

18106400 Sep 18 15:03 vmlinuz-5.14.6-tkg-cacule-llvm
10772160 Oct  2 18:52 vmlinuz-5.14.9-tkg-cacule-llvm

[config-5.14.6-tkg-cacule-llvm.zip](https://github.com/Frogging-Family/linux-tkg/files/7272042/config-5.14.6-tkg-cacule-llvm.zip)
[config-5.14.9-tkg-cacule-llvm.zip](https://github.com/Frogging-Family/linux-tkg/files/7272043/config-5.14.9-tkg-cacule-llvm.zip)

**Comment by ptr1337** [comment]
just checked the config, at 5.14.6 youre using lz4 compression and at the .9 kernel youre using zstd compression. 

There is the differnce from. 

Did you tried xanmods prebuilt kernel for example? 
Also did you tried to compile with gcc ?

**Comment by chipshopness** [comment]
I changed the compression method yesterday just to check it wasn't that. I've redone the initrd for 5.14.6 as zstd and it works fine.
Just tried with gcc and the problem still occurs.

**Comment by cpw** [comment]
Hi, so I'm just chiming in here that kernel debs built since .1 are not working properly. I've now tried a 5.14.7 and 5.14.9 kernel and both are weirdly broken - they boot to an empty initramfs.

Things I've noticed:
1. The deb size has doubled.
```
-rw-r--r-- 1 cpw cpw  52316760 Sep  7 08:40 linux-image-5.14.1-tkg-pds_5.14.1-tkg-pds-1_amd64.deb
-rw-r--r-- 1 cpw cpw 102709048 Sep 23 10:11 linux-image-5.14.7-tkg-pds_5.14.7-tkg-pds-1_amd64.deb
-rw-r--r-- 1 cpw cpw 102708944 Oct  4 11:14 linux-image-5.14.9-tkg-pds_5.14.9-tkg-pds-1_amd64.deb
```
2. The initramfs creation is throwing an error:
```
sudo update-initramfs -u -k 5.14.9-tkg-pds
update-initramfs: Generating /boot/initrd.img-5.14.9-tkg-pds
find: ‘/var/tmp/mkinitramfs_lhogKM/lib/modules/5.14.9-tkg-pds/kernel’: No such file or directory
```
3. The initram file size is significantly smaller for the newer kernels:
```
-rw-r--r-- 1 root root 76401646 Oct  4 12:58 initrd.img-5.14.1-tkg-pds
-rw-r--r-- 1 root root 76383778 Oct  4 12:57 initrd.img-5.14.1-tkg-pds.saved
-rw-r--r-- 1 root root 21122915 Oct  4 12:58 initrd.img-5.14.9-tkg-pds
```

I'm also attaching the verbose output from creating initramfs for both 5.14.1 (which works) and 5.14.9 (which doesn't).

[initram5141.log](https://github.com/Frogging-Family/linux-tkg/files/7279894/initram5141.log)
[initram5149.log](https://github.com/Frogging-Family/linux-tkg/files/7279895/initram5149.log)

**Comment by AdelKS** [comment]
Oh thanks for the extra information! You just explained what's wrong: the initramfs creation is failing.

I think we are going to fix this actually. Can you attach the output of `ls -al /lib/modules/[kernel that works]/` and `ls -al /lib/modules/[kernel that doesn't]/`. And have you checked what's in `ls -al /lib/modules/[kernel that doesn't]/kernel` ?

**Comment by cpw** [comment]
Attaching both 14.1 and 14.9. What is .zst? I think that might be the problem...
[flist5.14.9.log](https://github.com/Frogging-Family/linux-tkg/files/7280534/flist5.14.9.log)
[flist5.14.1.log](https://github.com/Frogging-Family/linux-tkg/files/7280535/flist5.14.1.log)

**Comment by AdelKS** [comment]
The kernel modules are `zstd` compressed, it should not be a problem as there is a config option to make the kernel properly read them. Aaaaaaaaaaaaaaaaaaaah! The initramfs creation tool in Ubuntu does not understand ZSTD !!! Gosh! Thanks! You just figured out the issue. Awesome.

Now, to confirm, please simply perform a compilation, use `xconfig` when prompted, search for `ZSTD` and replace the option that says "ZSTD compress kernel modules` with `LZ4` and give it a try. I am pretty sure that will solve it.

Thanks!

**Comment by AdelKS** [comment]
Okay, the config option is `MODULE_COMPRESS_ZSTD`, replace it first `NONE` (in `xconfig`) and try.

**Comment by AdelKS** [comment]
Easier option, use this frag file: de-compress it at the same level as `install.sh`

[zstd-remove.zip](https://github.com/Frogging-Family/linux-tkg/files/7280590/zstd-remove.zip)

**Comment by cpw** [comment]
Already recompiling the kernel LUL...

**Comment by cpw** [comment]
Confirming that fixed the problem: 
```
uname -a
Linux cheesypuffs 5.14.9-tkg-pds #1 TKG SMP PREEMPT Mon Oct 4 14:56:23 EDT 2021 x86_64 GNU/Linux
```

**Comment by AdelKS** [comment]
Amazing, thanks for your help! <3

I will PR the fix.
