### ISSUE TITLE
Unable to use Virtualbox (missing kernel module)

### ISSUE THREAD

**Issue by xk0niR** [Frogging-Family/linux-tkg#326]
Hello,

some system Info:
**uname -a**
5.14.8-203-tkg-pds-llvm

**zcat /proc/config.gz | grep VBOX**
CONFIG_DRM_VBOXVIDEO=m
CONFIG_VBOXGUEST=m
CONFIG_VBOXSF_FS=m

I´ll get the following error when trying to start a VM
"The VirtualBox Linux kernel driver is either not loaded or not set up correctly."
"VERR_VM_DRIVER_NOT_INSTALLED"

**sudo modprobe vboxdrv**
modprobe: FATAL: Module vboxdrv not found in directory /lib/modules/5.14.8-203-tkg-pds-llvm

Then tried to install virtualbox drivers (I thought they are already included in the kernel, see config.gz):
**sudo pacman -S virtualbox-host-dkms**
"Warning, `dkms install --no-depmod -m vboxhost -v 6.1.26_OSE -k 5.14.8-203-tkg-pds-llvm' returned 10"

Anyone has an idea?
Thanks a lot!

**Comment by Tk-Glitch** [comment]
Did you set dkms to use llvm? Else and since your kernel was built with llvm/clang, it will fail.
You can force dkms to use llvm/clang by adding the following to your `/etc/dkms/framework.conf`:
```
export LLVM=1
export CC=clang
```
Keep in mind that it will break compiling dkms drivers on kernels built with GCC (such as stock kernel).

All of this aside, vbox module also might fail to build with clang (no idea, I haven't tried).

**Comment by xk0niR** [comment]
This worked! I can now use Virtualbox with TKG kernel.
As you mentioned it will fail with stock kernel now.
I might try to find a setting to disable dkms this module for stock kernel to hide the error message.

You could use **virtualbox-host-modules-arch** package for stock kernel but it´s conflicting with **virtualbox-host-dkms**.
Anyway I don´t use stock kernel usually so it´s fine for me.

**Comment by Tk-Glitch** [comment]
Great!

Alternatively, building your -tkg kernel with GCC (without the dkms modification) would also work.

**Comment by Tk-Glitch** [comment]
Great!

Alternatively, building your -tkg kernel with GCC (without the dkms modification) would also work.
