### ISSUE TITLE
Failing to boot on Ubuntu 20.04

### ISSUE THREAD

**Issue by Salekin-1169** [Frogging-Family/linux-tkg#327]
I've been using this repo to build kernel for my system (thanks for the great work, really appreciate it)
But it's been failing for me since `5.14` was added (don't remember the exact date, but at the time of fail [this pr](https://github.com/Frogging-Family/linux-tkg/pull/304) wasn't merged yet)

I keep getting `Target filesystem doesn't have requested /sbin/init` error on boot
![err](https://user-images.githubusercontent.com/49670756/135666623-0ce56a40-70a7-4073-9702-6e39456c2314.jpg)
But my pc runs flawlessly when I revert back to the default kernel (from boot menu)

Here's the attached config file. The only changes I made is 1000hz, no hz and runqueue mc
[customization.zip](https://github.com/Frogging-Family/linux-tkg/files/7269157/customization.zip)

I've tried these so far:

`gcc-9, gcc-10, gcc-11` = `Target filesystem doesn't have requested /sbin/init` 

`kernel 5.13, 5.14` = `Target filesystem doesn't have requested /sbin/init` 

`_configfile="running-kernel"` = compilation fails with dpkg error
`_configfile="linux-tkg-config/5.14/config.x86_64"` = compilation finishes, but same error on boot 

Please help me figure out what am I doing wrong here

Spec:
Ubuntu 20.04.3
default kernel (5.11)
everything is on default out of the box

**Comment by AdelKS** [comment]
Can you try compiling with `config-works` from [this issue reply](https://github.com/Frogging-Family/linux-tkg/issues/322#issuecomment-928614736) and see if the resulting kernel boots ? You need to unzip at the same level as `install.sh` and set `_configfile` to that name.
