### ISSUE TITLE
[REQUEST] Put `CONFIG_BLK_DEV_LOOP` to `y`

### ISSUE THREAD

**Issue by Fox2Code** [Frogging-Family/linux-tkg#329]
The current config is `CONFIG_BLK_DEV_LOOP=m` meaning it is not loaded by default

Putting this to `CONFIG_BLK_DEV_LOOP=y` would make android development easier as this modules is required for a lot of Android development tools touching systems images.

This is because this module is required to use the `-o loop` parameter on the `mount` command I need it enabled.  
So without this module it's **impossible** to mount `.img` files. (Also breaking a lot of other tools relying of this command)

Can this be changed please, if you deny because it's arch default I would completely understand, but for me this is life changing.

Also I know it possible to enable it manually with `insmod` but I wasn't able to find the full command again anywhere on the internet, and trying to guess the command from memory didn't work also, so I am just stuck at asking help here.

**Comment by AdelKS** [comment]
Hello,

Do you also put `_anbox="true"`, in `customization.cfg` in your custom kernels ? I can imagine at least the option you are asking for being set to `y` in such case.

Otherwise, if this is a niche request that is mainly of interest to you, you are in luck! `linux-tkg` is about customization and it enables you to have it set to `y` in all your custom kernels without asking us to change anything: when you run the install script, ask it to run `xconfig`. This will show you a window with all the kernel options, you can search for `BLK_DEV_LOOP` in that window, set it to `y`, then save. The script will ask you to generate a so-called `fragment`, call it `dev-loop.myfrag`. And from then on the script will always ask you if you want to use that "frag" file to apply its change at each kernel build.

**Comment by Fox2Code** [comment]
I'm using the `chaotic-aur` version, I ask this because I don't want to have to build an entire kernel each time I want to mount a`.img`.
And `CONFIG_BLK_DEV_LOOP=y` is the default in debian/ubuntu, so most linux tools assume this module is enabled.

**Comment by ReperakDev** [comment]
If you can't be bothered to compile the kernel yourself then you shouldn't use it. Like AdelKS said linux-tkg is meant to be customized to your individual needs and that involves compiling it from source.

If you have any modern CPU compiling the kernel won't take that long (30 minutes on my mid-range Ryzen laptop)

**Comment by Fox2Code** [comment]
I think I maybe found a workaround for this issue, with config files there is a way to fore load the module on boot.

But I will still keep this issue open because I think it could really be beneficial for software that depend of this.

Like I said in my first post I don't mind it being closed and denied, I found a workaround, and I'm happy.

**Comment by Fox2Code** [comment]
@ReperakDev  not everyone will, and not everyone using linux is willing to spend 30 minutes not using it's computer to build a kernel.  

Imagine I tell you the same thing for every component of your computer, for me compiling my custom wine is already a pain because of the time to wait, I don't have time and the resource (Physically end mentally) to also build the kernel to fits all my needs.

I do not have any build server I can ask to do all the boring work for me, so every build I need to do I need it to be on my main computer, and my computer is in my bedroom and I cannot move it, so I must turn it off at night.

**Comment by AdelKS** [comment]
@Fox2Code you are not requesting a big change and it is understandable. I thought of telling you about auto-loading the module on boot and entirely forgot: I think it is the best solution and nothing else needs to be done. This solution fixes the issue.

About the 30mins building the kernel, if you like to toy around: if you use `ccache` and `modprobed-db` you can probably reduce the compilation time to around 10 minutes or less. You can use your main computer to build for your small one just by ssh'ing to it, but you probably have some other constraints.

**Comment by karx1** [comment]
For me it takes about 20 minutes with modprobed-db on an Intel i5, and I only recompile about once a month. I can pretty much just start the compile, go make tea, and then come back and it'll be done.
