### ISSUE TITLE
key unknown (arch linux, yay used)

### ISSUE THREAD

**Issue by simona70** [Frogging-Family/linux-tkg#34]
error: linux-tkg-bmq: key "6025FD838D82C3041F4C71CA8A9E14A07010F7E3" unknown
error: can't find key "6025FD838D82C3041F4C71CA8A9E14A07010F7E3" on remote server

**Comment by Tk-Glitch** [comment]
There is no key required to build linux-tkg. As you're using `yay` I assume you're using an external repo, for which this key might be needed. If it's chaotic-aur, the keys can be found on their main page: https://lonewolf.pedrohlc.com/chaotic-aur/ .

**Comment by PedroHLC** [comment]
TkG, feel free to close this issue. I've announced this in chaotic-aur's channel twice. :joy: 
Anyway, for security reasons, builds done in the secondary cluster (Donated by LordKitsuna), have a different sub-key that need to  be added with:
```
sudo pacman-key --keyserver keys.mozilla.org -r 8A9E14A07010F7E3
sudo pacman-key --lsign-key 8A9E14A07010F7E3
```
In the chaotic-aur's homepage, there is an AIO command for both keys.
