### ISSUE TITLE
What is the Performance Difference Between tkg and Xanmod?

### ISSUE THREAD

**Issue by Amarakon55** [Frogging-Family/linux-tkg#344]
Are there any benchmarks on Xanmod vs linux-tkg? I use xanmod, but I want to know what would be the benefits of linux-tkg. For example, I know xanmod decreases my render times in Blender and increases my fps in games. Would tkg give a performance increase from xanmod?

**Comment by Amarakon55** [comment]
I would assume that tkg with bmq has slightly better performance than xanmod. But I couldn't find any benchmarks for that.

**Comment by ReperakDev** [comment]
Generally the best gaming performance comes with the PDS scheduler. You might want to tinker with the configuration to see what you like.

**Comment by HougeLangley** [comment]
You guys could check my game benchmark

https://youtu.be/mNKXumLlxII
https://youtu.be/-qFXu_5T9Dg

**Comment by HougeLangley** [comment]
![Screenshot_20211103-085206_YouTube.png](https://user-images.githubusercontent.com/1161594/139971310-afc3f0db-35e6-47bb-b089-4aa214c1522b.png)
This Xanmod

![Screenshot_20211103-085354_YouTube.png](https://user-images.githubusercontent.com/1161594/139971322-2bc482c4-68ef-4bb1-a732-d4435c965db3.png)

**Comment by HougeLangley** [comment]
Xanmod is the best one

**Comment by Amarakon55** [comment]
I did my own tests and tkg is slightly faster.

**Comment by HougeLangley** [comment]
> I did my own tests and tkg is slightly faster.

Could you post something prove it? Video and images?

**Comment by Amarakon55** [comment]
> > I did my own tests and tkg is slightly faster.
> 
> Could you post anything prove it? Video and images?

![IMG_20211102_220825_274](https://user-images.githubusercontent.com/92645199/140673662-031cb76c-40fa-4c8c-8f23-9a60792ca248.jpg)
![IMG_20211102_222207_575](https://user-images.githubusercontent.com/92645199/140673666-f2bf7375-b39a-4f19-bfe2-964338e6f1d8.jpg)

**Comment by Amarakon55** [comment]
Linux-tkg is about 10 seconds faster in the blender classroom render.

**Comment by Amarakon55** [comment]
I haven't done testing in games though.
