### ISSUE TITLE
5.15.1 is unable to boot

### ISSUE THREAD

**Issue by NovaMoon** [Frogging-Family/linux-tkg#349]
This is all i can manage to get. system fully locks up right after selecting the kernel in grub. 5.14 and vanilla works as expected

![IMG_20211107_202347439](https://user-images.githubusercontent.com/16277013/140661142-9ba2f05e-2d2b-41c4-8ce3-9e34f81d21b4.jpg)

**Comment by Tk-Glitch** [comment]
Did you build it or is that from chaotic?

**Comment by NovaMoon** [comment]
> Did you build it or is that from chaotic?

i build it myself

**Comment by NovaMoon** [comment]
i updated the repo today and now after rebuilding it boots :+1:

**Comment by Tk-Glitch** [comment]
Ok, so you have hit the issue I fixes with https://github.com/Frogging-Family/linux-tkg/commit/b9e7299e3029630ddb8a26b3ad647bc4d15fcc54
Good.
