### ISSUE TITLE
Ubuntu/Debian Install Script Error (unary operator expected)

### ISSUE THREAD

**Issue by Hexcede** [Frogging-Family/linux-tkg#352]
On line 348 of the `install.sh` script (head is at commit db405096bd7fb52656fc53f7c5ee87e7fe2f99c9 for future reference) there is an error during the install prompt on my system. Even though its just a single line, I don't full well understand what the issue is because I only recently started using linux & bash and haven't familiarized myself with the syntax here yet.

Contents of lines 347-349:
```bash
read -p "Do you want to install the new Kernel ? Y/[n]: " _install
if [[ $_install =~ [yY] ]] || [ $_install = "yes" ] || [ $_install = "Yes" ]; then
  cd "$_where"
```

I'm not confident but I'm fairly sure it has to do with the `yY` selection.

**Comment by AdelKS** [comment]
Hello!

Change it to this:
```shell
if [[ $_install =~ ^(y|Y|yes|Yes)$ ]]; then
```

Does it fix the issue you are facing ?

**Comment by Hexcede** [comment]
> Hello!
> 
> If you change it to this:
> 
> ```shell
> if [[ $_install =~ ^(y|Y|yes|Yes)$ ]]; then
> ```
> 
> Does it fix the issue you are facing ?

It seems so, yes. I am unsure if the command executed as there wasn't any output, but, no script errors.
![image](https://user-images.githubusercontent.com/8394472/141035110-d247e8e8-88d3-473b-b18f-303603a51a26.png)

**Comment by AdelKS** [comment]
Run `./install.sh uninstall-help` to see if the new kernel you installed is listed.

**Comment by Hexcede** [comment]
> Run `./install.sh uninstall-help` to see if the new kernel you installed is listed.

It looks that way, but, I had manually installed the kernel before, based on the script. The build I just produced is the same as the one I already had installed.

I'll do another build later for something I don't have installed and see.

**Comment by AdelKS** [comment]
You mean you installed it from the `DEBS` folder. That's good enough.

**Comment by Hexcede** [comment]
> Hello!
> 
> If you change it to this:
> 
> ```shell
> if [[ $_install =~ ^(y|Y|yes|Yes)$ ]]; then
> ```
> 
> Does it fix the issue you are facing ?

Hey I apologize for the late response, I just wanted to mention that this does indeed fix the issue, however this does have one problem.

The option will select yes by default normally, but the statement you provided doesn't do that (it explicitly checks for yes, whereas it should actually explicitly check for no I believe)

I also think that it would actually be a lot nicer from a production point of view to be able to run the install script to _just_ build and then run the install script to _just_ install. I don't think the functionality between the two really needs to be intertwined the way it is and its inconvenient to test for issues with the way its built.

**Comment by AdelKS** [comment]
> I also think that it would actually be a lot nicer from a production point of view to be able to run the install script to just build and then run the install script to just install. I don't think the functionality between the two really needs to be intertwined the way it is and its inconvenient to test for issues with the way its built.

I did it this way because some knowledge of the "prepare" phase is needed for the compile phase, and the variables are lost when the script is done. One could save the relevant data in a file within `linux-src-git` or something similar though, but there are more room for issues if both phases are separated unfortunately.

I just realized, the initial issue happens because the variables are not quoted:

```shell
if [[ $_install =~ [yY] ]] || [ $_install = "yes" ] || [ $_install = "Yes" ]; then
```

should be

```shell
if [[ "$_install" =~ [yY] ]] || [ "$_install" = "yes" ] || [ "$_install" = "Yes" ]; then
```

because `$_install` can be empty. Will fix that in a PR now.
