### ISSUE TITLE
Void package has wrong checksums

### ISSUE THREAD

**Issue by Meister1593** [Frogging-Family/linux-tkg#357]
Basically, for every kernel in void template (hyper-kvm's) checksum has wrong signature and it halts build after downloading kernel + patch

**Comment by AdelKS** [comment]
@Ann1kaB hope that VM of yours is still there haha

**Comment by NotCreative21** [comment]
I'm also having this problem, it'd be nice if someone could provide the updated checksums or make a pull request
this pull request may fix it: [https://github.com/Frogging-Family/linux-tkg/pull/363/commits/d10f2074d3fb71c0d52e4e60e1964cd0c2a14e5c](https://github.com/Frogging-Family/linux-tkg/pull/363/commits/d10f2074d3fb71c0d52e4e60e1964cd0c2a14e5c )
if someone could check it out that would be nice

**Comment by MTTbrandUser** [comment]
I'm also having this issue

**Comment by AdelKS** [comment]
It should be good now per #421
