### ISSUE TITLE
Bcachefs is on 5.15 now!

### ISSUE THREAD

**Issue by Sukid** [Frogging-Family/linux-tkg#366]
Sorry for yet another pester about this, but bcachefs is on 5.15.* now, could ya add that? :point_right: :point_left: 

(really looking forward to it being mainlined. it's made my own storage system so much more convenient..)

**Comment by Sukid** [comment]
I'm afraid I don't. I definitely will take the time to learn at some point though.

**Comment by gardotd426** [comment]
I've got you covered. I got the patch and am building now (the patch applied cleanly, just want to make sure there are no build errors). I'll push the PR when the build is done.

**Comment by Sukid** [comment]
Thank you!!
