### ISSUE TITLE
LTO is not being used when specified in customization.cfg

### ISSUE THREAD

**Issue by itspngu** [Frogging-Family/linux-tkg#371]
It seems the Kconfig setting `LTO_NONE` prevents LTO from being used when specified (`_lto_mode="full"` or `_lto_mode="thin"`) in customization.cfg:

```
 -> Setting config
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
.config:3382:warning: override: LTO_NONE changes choice state
#
# configuration written to .config
#
 -> Configuration done.
```

This is also evident from the build output not containing `LTO` lines, which do appear when building with `LTO_NONE=n` on top of making the above warning disappear.

**Comment by AdelKS** [comment]
What is the version of your Clang ? Out of memory you need at least Clang 11. Also, are you using .config overrides ? (like frags, use make xconfig, or your own custom config file). Because it works in many machines

**Comment by itspngu** [comment]
No fragments, but I based everything on the default config for fedora found here: https://src.fedoraproject.org/rpms/kernel/raw/f35/f/kernel-x86_64-fedora.config

```
clang --version
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

After removing the aforementioned config and commenting out the `_configfile` setting in customization.cfg it does indeed work(-ish):

```
 -> Setting config
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
.config:10692:warning: override: LTO_CLANG_FULL changes choice state
.config:10695:warning: override: INIT_STACK_ALL_ZERO changes choice state
#
# configuration written to .config
#
```

I'm confused now: https://github.com/Frogging-Family/linux-tkg/blob/master/customization.cfg#L67

```
$ cat linux-tkg-config/5.15/config.x86_64 | grep LTO
CONFIG_ARCH_SUPPORTS_LTO_CLANG=y
CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN=y
CONFIG_LTO_NONE=y
CONFIG_HID_WALTOP=m
```

```
cat fedora-x86_64.config | grep LTO
CONFIG_HID_WALTOP=m
# CONFIG_LTO_CLANG_FULL is not set
# CONFIG_LTO_CLANG_THIN is not set
CONFIG_LTO_NONE=y
```

Adding the 2 `CONFIG_ARCH_SUPPORTS_LTO_CLANG` lines to the fedora config doesn't change anything:

```
-> Setting config
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
.config:3382:warning: override: LTO_NONE changes choice state
#
# configuration written to .config
#
```

Is the `_configfile` setting not being used as a base config but instead as an overlay of sorts?

**Comment by AdelKS** [comment]
> Is the _configfile setting not being used as a base config but instead as an overlay of sorts?

No it uses [only the provided one](https://github.com/Frogging-Family/linux-tkg/blob/c98ffc24b15f877e9a3d794bdffeef9d81c3c3de/linux-tkg-config/prepare#L531)

The config check script from the kernel is kinda hard to please, probably some other config difference is making it chose to do what it's doing.

Your clang is new and shouldn't affect the outcome, so probably it's a config difference.

**Comment by AdelKS** [comment]
> the question is should I close #372 ?

Absolutely not, custom config files are supported and if we can help properly overwrite what's needed when using one is good!
