### ISSUE TITLE
_custom_pkgbase not applying.

### ISSUE THREAD

**Issue by gentuwu** [Frogging-Family/linux-tkg#374]
So, my issue exactly basically is that regardless of what i input into `_custom_pkgbase`; It never actually changes from the default name whatsoever; I'd appreciate your help greatly as i've recompiled this like 5+ times (probably more) just to name my kernel something cool, lol.

**Comment by robson-66** [comment]
This only works for renaming a package 
![ScreenShot](https://i.postimg.cc/BZccGFvg/screen2.png)

![ScreenShot](https://i.postimg.cc/7L20tGcS/screen.png)

**Comment by gentuwu** [comment]
> This only works for renaming a package ![ScreenShot](https://camo.githubusercontent.com/cf4a6ead9481548538e0a671afa0f2a6282015ae76f50d997c06e0d73849b569/68747470733a2f2f692e706f7374696d672e63632f425a6363474676672f73637265656e322e706e67)
> 
> ![ScreenShot](https://camo.githubusercontent.com/ea4dac798cbf76a7edd3bc88e8a807ea1fca7ce6ecda01bb8d976989b5d0bd29/68747470733a2f2f692e706f7374696d672e63632f374c3230744763532f73637265656e2e706e67)

Well, when I use menuconfig to change it, it gives me an error.

`rm: cannot remove '/home/aura/linux-tkg/pkg/linux515-tkg-bmq/usr/lib/modules/5.15.5-224-tkg-bmq/build': No such file or directory
==> ERROR: A failure occurred in package_linux515-tkg-bmq().`

**Comment by AdelKS** [comment]
The Arch equivalent to `_kernel_localversion` hasn't yet been implemented, see #133
