### ISSUE TITLE
akmods fails on Fedora with Nvidia drivers (Package has no %description)

### ISSUE THREAD

**Issue by Puncia** [Frogging-Family/linux-tkg#375]
Hi, I've been trying to install 5.15.5 but akmods is unable to build the rpms for my Nvidia drivers.

```
> cat /var/cache/akmods/nvidia-470xx/470.86-1-for-5.15.5_tkg_mara_venier.failed.log
2021/12/01 21:50:23 akmods: Building RPM using the command '/sbin/akmodsbuild --kernels 5.15.5_tkg_mara_venier /usr/src/akmods/nvidia-470xx-kmod.latest'
warning: user mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
error: Package has no %description: kmod-nvidia-470xx-5.15.5_tkg_mara_venier
Installing /usr/src/akmods/nvidia-470xx-kmod.latest
Building target platforms: x86_64
Building for target x86_64
2021/12/01 21:50:23 akmodsbuild: * Rebuilding /usr/src/akmods/nvidia-470xx-kmod.latest for kernel(s) 5.15.5_tkg_mara_venier: warning: user mockbuild does not exist - using root
2021/12/01 21:50:23 akmodsbuild: warning: user mockbuild does not exist - using root
2021/12/01 21:50:23 akmodsbuild: error: Package has no %description: kmod-nvidia-470xx-5.15.5_tkg_mara_venier
2021/12/01 21:50:23 akmodsbuild: Installing /usr/src/akmods/nvidia-470xx-kmod.latest
2021/12/01 21:50:23 akmodsbuild: Building target platforms: x86_64
2021/12/01 21:50:23 akmodsbuild: Building for target x86_64
2021/12/01 21:50:23 akmodsbuild:
2021/12/01 21:50:23 akmods: Building rpms failed; see /var/cache/akmods/nvidia-470xx/470.86-1-for-5.15.5_tkg_mara_venier.failed.log for details
```

Looking around previous issues here I found this problem mentioned a bunch of times alongside others, but no real solution has been provided as far as I am aware.
I used `linux-tkg` in the past on the same system/installation without any issue and akmods run flawlessly.

[customization.cfg.zip](https://github.com/Frogging-Family/linux-tkg/files/7637348/customization.cfg.zip)

(I also tried to install using the `Generic` option but run into other issues, like having to use `grub2-mkconfig` manually instead of `grub-mkconfig` like the script does, but that's beyond the scope of this issue - also I know `Generic` is not meant to be used with Fedora because of that)

I am using Fedora 35

**Comment by Puncia** [comment]
https://discussion.fedoraproject.org/t/rmnscnce-kernel-xanmod/27945/22
https://pagure.io/kernel-xanmod/issue/2#comment-737270

Apparently the issue is related to the `CacULE` scheduler, which is what I've been trying to use

**Comment by ptr1337** [comment]
Probally not a issue related to the scheduler, more to fedoras way to use dkms.

**Comment by AdelKS** [comment]
Given #69 the solution found was to install the official Nvidia driver that uses DKMS instead.

**Comment by Sid127** [comment]
This happens on PDS scheduler using kernel 5.17.5 and nvidia driver version 510.62.02 as well

**Comment by AdelKS** [comment]
Hello! Please try PR https://github.com/Frogging-Family/linux-tkg/pull/610 to confirm that it fixes this issue. It worked like a charm in my VM.

Adel

**Comment by Tk-Glitch** [comment]
Should be fixed with https://github.com/Frogging-Family/linux-tkg/commit/1d063ca32634997616d9cb1da81253bdedc67054
