### ISSUE TITLE
A failure occurred in prepare

### ISSUE THREAD

**Issue by Doctorwho1909** [Frogging-Family/linux-tkg#39]
sed: can't read ./kernel/sched/alt_core.c: No such file or directory 

when compiling 5.8 kernel 

``[matt@archlinux linux58-tkg]$ makepkg -si
           .---.`               `.---.
        `/syhhhyso-           -osyhhhys/`
       .syNMdhNNhss/``.---.``/sshNNhdMNys.
       +sdMh.`+MNsssssssssssssssNM+`.hMds+
       :syNNdhNNhssssssssssssssshNNhdNNys:
        /ssyhhhysssssssssssssssssyhhhyss/
        .ossssssssssssssssssssssssssssso.
       :sssssssssssssssssssssssssssssssss:
      /sssssssssssssssssssssssssssssssssss/
     :sssssssssssssoosssssssoosssssssssssss:
     osssssssssssssoosssssssoossssssssssssso
     osssssssssssyyyyhhhhhhhyyyyssssssssssso
     /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
      smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
       /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
        `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
           `-+shdNNNNNNNNNNNNNNNdhs+-`
                 `.-:///////:-.`
    Do you want to use a predefined optimized profile?
  > 1.Custom
    2.Ryzen Desktop (Performance)
    3.Other Desktop (Performance)
choice[1-3?]: 1
    What CPU sched variant do you want to build/install?
  > 1.PDS
    2.Project C / BMQ
    3.CFS
choice[1-2?]: 1
==> Making package: linux58-tkg-pds 5.8.0-1 (Wed 05 Aug 2020 12:17:29 PM ADT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux-5.8.tar.xz
  -> Downloading enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26616  100 26616    0     0   131k      0 --:--:-- --:--:-- --:--:--  131k
  -> Found config.x86_64
  -> Found 90-cleanup.hook
  -> Found cleanup
  -> Found 0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch
  -> Found 0002-clear-patches.patch
  -> Found 0003-glitched-base.patch
  -> Found 0003-glitched-cfs.patch
  -> Found 0005-glitched-ondemand-pds.patch
  -> Found 0005-glitched-pds.patch
  -> Found 0005-v5.8_undead-pds099o.patch
  -> Found 0006-add-acs-overrides_iommu.patch
  -> Found 0007-v5.8-fsync.patch
  -> Found 0009-glitched-ondemand-bmq.patch
  -> Found 0009-glitched-bmq.patch
  -> Found 0009-prjc_v5.7-r3.patch
  -> Found 0011-ZFS-fix.patch
  -> Found 0012-misc-additions.patch
==> Validating source files with sha256sums...
    linux-5.8.tar.xz ... Passed
    enable_additional_cpu_optimizations_for_gcc_v10.1%2B_kernel_v5.8%2B.patch ... Passed
    config.x86_64 ... Passed
    90-cleanup.hook ... Passed
    cleanup ... Passed
    0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch ... Passed
    0002-clear-patches.patch ... Passed
    0003-glitched-base.patch ... Passed
    0003-glitched-cfs.patch ... Passed
    0005-glitched-ondemand-pds.patch ... Passed
    0005-glitched-pds.patch ... Passed
    0005-v5.8_undead-pds099o.patch ... Passed
    0006-add-acs-overrides_iommu.patch ... Passed
    0007-v5.8-fsync.patch ... Passed
    0009-glitched-ondemand-bmq.patch ... Passed
    0009-glitched-bmq.patch ... Passed
    0009-prjc_v5.7-r3.patch ... Passed
    0011-ZFS-fix.patch ... Passed
    0012-misc-additions.patch ... Passed
==> Extracting sources...
  -> Extracting linux-5.8.tar.xz with bsdtar
==> Starting prepare()...
  -> Setting version...
patching file kernel/fork.c
Hunk #1 succeeded at 106 (offset 4 lines).
Hunk #2 succeeded at 1866 (offset 306 lines).
Hunk #3 succeeded at 2970 (offset 613 lines).
patching file kernel/sysctl.c
Hunk #1 succeeded at 106 (offset 1 line).
Hunk #2 succeeded at 1885 (offset 1369 lines).
patching file kernel/user_namespace.c
Hunk #1 succeeded at 21 with fuzz 2 (offset -3 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1140 (offset 136 lines).
patching file kernel/user_namespace.c
Hunk #1 succeeded at 22 (offset -5 lines).
  -> Applying graysky's cpu opts patch
patching file arch/x86/include/asm/vermagic.h
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
patching file arch/x86/Makefile_32.cpu
  -> Applying clear linux patches
patching file drivers/pci/pci.c
Hunk #1 succeeded at 62 (offset 1 line).
patching file drivers/idle/intel_idle.c
Hunk #1 succeeded at 531 with fuzz 2 (offset 65 lines).
Hunk #2 succeeded at 539 (offset 65 lines).
Hunk #3 succeeded at 547 (offset 65 lines).
Hunk #4 succeeded at 555 (offset 65 lines).
Hunk #5 succeeded at 563 (offset 65 lines).
Hunk #6 succeeded at 571 (offset 65 lines).
Hunk #7 succeeded at 579 (offset 65 lines).
Hunk #8 succeeded at 599 with fuzz 2 (offset 65 lines).
Hunk #9 succeeded at 607 (offset 65 lines).
Hunk #10 succeeded at 615 (offset 65 lines).
Hunk #11 succeeded at 623 (offset 65 lines).
Hunk #12 succeeded at 631 (offset 65 lines).
Hunk #13 succeeded at 639 (offset 65 lines).
Hunk #14 succeeded at 647 (offset 65 lines).
Hunk #15 succeeded at 668 with fuzz 2 (offset 65 lines).
Hunk #16 succeeded at 676 (offset 65 lines).
Hunk #17 succeeded at 684 (offset 65 lines).
Hunk #18 succeeded at 692 (offset 65 lines).
Hunk #19 succeeded at 700 (offset 65 lines).
Hunk #20 succeeded at 708 (offset 65 lines).
Hunk #21 succeeded at 716 (offset 65 lines).
Hunk #22 succeeded at 737 with fuzz 2 (offset 65 lines).
patching file net/ipv4/tcp.c
Hunk #1 succeeded at 4209 (offset 312 lines).
patching file kernel/locking/rwsem.c
Hunk #1 succeeded at 717 (offset -3 lines).
Hunk #2 succeeded at 751 (offset -3 lines).
patching file drivers/Makefile
Hunk #1 succeeded at 59 (offset 1 line).
Hunk #2 succeeded at 73 (offset 1 line).
  -> Applying glitched base patch
patching file scripts/mkcompile_h
Hunk #1 succeeded at 41 with fuzz 2 (offset -9 lines).
patching file fs/dcache.c
Hunk #1 succeeded at 71 (offset 2 lines).
patching file kernel/sched/core.c
Hunk #1 succeeded at 59 with fuzz 1 (offset 18 lines).
Hunk #2 succeeded at 71 (offset 10 lines).
patching file scripts/setlocalversion
patching file init/Kconfig
Hunk #1 succeeded at 1294 (offset 50 lines).
patching file drivers/infiniband/core/addr.c
Hunk #1 succeeded at 820 with fuzz 1 (offset 99 lines).
patching file include/linux/blkdev.h
Hunk #1 succeeded at 46 with fuzz 1 (offset -1 lines).
patching file init/Kconfig
Hunk #1 succeeded at 92 (offset 47 lines).
patching file kernel/sched/fair.c
Hunk #3 succeeded at 95 with fuzz 2.
Hunk #4 succeeded at 149 with fuzz 2 (offset 21 lines).
patching file mm/page-writeback.c
patching file net/ipv4/Kconfig
Hunk #1 succeeded at 691 (offset -11 lines).
Hunk #2 succeeded at 727 (offset -11 lines).
patching file include/linux/compiler_types.h
Hunk #1 succeeded at 245 with fuzz 1 (offset 57 lines).
patching file mm/huge_memory.c
patching file net/sched/Kconfig
Hunk #1 succeeded at 459 (offset 30 lines).
Hunk #2 succeeded at 481 (offset 30 lines).
patching file mm/page_alloc.c
Hunk #1 succeeded at 330 (offset 67 lines).
patching file include/linux/mm.h
Hunk #1 succeeded at 190 (offset 44 lines).
patching file block/elevator.c
patching file include/linux/blkdev.h
Hunk #1 succeeded at 624 (offset 3 lines).
patching file include/linux/pagemap.h
Hunk #1 succeeded at 655 (offset 1 line).
patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #1 succeeded at 1857 (offset 92 lines).
patching file drivers/cpufreq/intel_pstate.c
Hunk #1 succeeded at 2832 (offset 6 lines).
  -> Applying misc additions patch
patching file drivers/tty/Kconfig
Hunk #1 succeeded at 76 (offset 1 line).
patching file include/uapi/linux/vt.h
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 3 with fuzz 2.
patching file Documentation/scheduler/sched-PDS-mq.txt
patching file arch/powerpc/platforms/cell/spufs/sched.c
patching file arch/x86/Kconfig
Hunk #1 succeeded at 1001 (offset -5 lines).
patching file drivers/cpufreq/cpufreq_conservative.c
patching file drivers/cpufreq/cpufreq_ondemand.c
patching file fs/proc/base.c
patching file include/linux/init_task.h
patching file include/linux/jiffies.h
patching file kernel/smp.c
patching file include/linux/sched.h
Hunk #1 succeeded at 32 (offset 1 line).
Hunk #2 succeeded at 650 (offset -3 lines).
Hunk #3 succeeded at 665 (offset -3 lines).
Hunk #4 succeeded at 674 (offset -3 lines).
Hunk #5 succeeded at 684 (offset -3 lines).
Hunk #6 succeeded at 1347 (offset 20 lines).
patching file include/linux/sched/deadline.h
patching file include/linux/sched/prio.h
patching file include/linux/sched/rt.h
patching file include/linux/sched/task.h
patching file include/linux/skip_list.h
patching file include/uapi/linux/sched.h
patching file init/Kconfig
Hunk #1 succeeded at 124 with fuzz 2 (offset 63 lines).
Hunk #2 succeeded at 877 (offset 85 lines).
Hunk #3 succeeded at 964 (offset 70 lines).
Hunk #4 succeeded at 1093 (offset 70 lines).
Hunk #5 succeeded at 1237 (offset 86 lines).
patching file init/init_task.c
Hunk #1 succeeded at 66 (offset 7 lines).
Hunk #2 succeeded at 324 (offset 22 lines).
patching file kernel/cgroup/cpuset.c
patching file kernel/delayacct.c
patching file kernel/exit.c
Hunk #1 succeeded at 121 (offset -1 lines).
Hunk #2 succeeded at 142 (offset -1 lines).
patching file kernel/livepatch/transition.c
patching file kernel/locking/rtmutex.c
Hunk #1 succeeded at 227 (offset -2 lines).
Hunk #2 succeeded at 678 (offset -2 lines).
Hunk #3 succeeded at 951 (offset -2 lines).
patching file kernel/sched/Makefile
Hunk #1 succeeded at 22 (offset 6 lines).
patching file kernel/sched/cpufreq_schedutil.c
patching file kernel/sched/cputime.c
patching file kernel/sched/idle.c
Hunk #1 succeeded at 372 (offset 11 lines).
Hunk #2 succeeded at 493 (offset 11 lines).
patching file kernel/sched/pds.c
patching file kernel/sched/pds_sched.h
patching file kernel/sched/pelt.c
Hunk #1 succeeded at 274 (offset 24 lines).
Hunk #2 succeeded at 392 (offset 24 lines).
patching file kernel/sched/pelt.h
patching file kernel/sched/sched.h
Hunk #2 succeeded at 2546 (offset -4 lines).
patching file kernel/sched/stats.c
patching file kernel/sysctl.c
Hunk #1 succeeded at 120 (offset -10 lines).
Hunk #2 succeeded at 191 with fuzz 2 (offset -101 lines).
Hunk #3 succeeded at 1660 with fuzz 1 (offset 1351 lines).
Hunk #4 succeeded at 1842 (offset 1351 lines).
Hunk #5 succeeded at 2428 (offset 1373 lines).
patching file kernel/time/posix-cpu-timers.c
Hunk #1 succeeded at 216 (offset -20 lines).
Hunk #2 succeeded at 789 (offset -17 lines).
Hunk #3 succeeded at 797 (offset -17 lines).
Hunk #4 succeeded at 825 (offset -17 lines).
Hunk #5 succeeded at 842 (offset -17 lines).
Hunk #6 succeeded at 1078 (offset -17 lines).
patching file kernel/trace/trace_selftest.c
patching file drivers/cpufreq/cpufreq_ondemand.c
Hunk #1 succeeded at 18 with fuzz 1 (offset -3 lines).
patching file kernel/Kconfig.hz
Hunk #1 succeeded at 5 (offset 1 line).
Hunk #2 succeeded at 40 (offset 1 line).
Hunk #3 succeeded at 60 (offset 1 line).
patching file kernel/Kconfig.hz
Hunk #1 succeeded at 5 (offset 1 line).
Hunk #2 succeeded at 47 (offset 1 line).
Hunk #3 succeeded at 68 (offset 1 line).
patching file mm/vmscan.c
Hunk #1 succeeded at 169 with fuzz 2 (offset 10 lines).
patching file init/Kconfig
Hunk #1 succeeded at 792 (offset 77 lines).
Hunk #2 succeeded at 1094 (offset 145 lines).
patching file kernel/sched/Makefile
Hunk #1 succeeded at 30 (offset 6 lines).
patching file kernel/sched/pds.c
Hunk #1 succeeded at 83 with fuzz 1 (offset 2 lines).
Hunk #2 succeeded at 6489 (offset 124 lines).
sed: can't read ./kernel/sched/alt_core.c: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done
```

**Comment by Doctorwho1909** [comment]
seems the file alt_core.c is removed from final 5.89 kernel source code

**Comment by Tk-Glitch** [comment]
Looks like an error introduced by https://github.com/Frogging-Family/linux-tkg/pull/38
Fix incoming.

**Comment by Tk-Glitch** [comment]
That PR is actually completely broken. I'll nuke.

**Comment by openglfreak** [comment]
Huh, weird, I swear it compiled for me

**Comment by openglfreak** [comment]
@Tk-Glitch You seem to be offline in Discord. Can I get some feedback about what was wrong with the PR? Maybe I can fix it?

**Comment by Tk-Glitch** [comment]
Answered on Discord. I'll review the breakage asap, but at least the revert will allow for functional builds with cfs and pds.
