### ISSUE TITLE
Does the futex_waitv working at the moment?

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#394]
I can't seem to get it working with the latest TKG kernel and wine. I'm checking as it's said [here](https://github.com/andrealmeid/futex_waitv_patches).

**Comment by AdelKS** [comment]
Have you activated it in the customization file ? Also, on wine's side it is reported and activated as being fsync

**Comment by rizzini** [comment]
> Have you activated it in the customization file ? Also, on wine's side it is reported and activated as being fsync

I did. On both, Wine and Kernel. 

> Also, on wine's side it is reported and activated as being fsync
No log about fsync is shown.

**Comment by Kron4ek** [comment]
Have you enabled the `WINEFSYNC` env variable?

**Comment by rizzini** [comment]
> Have you enabled the WINEFSYNC env variable?

I messed up. I'll check my variables declaration again.
