### ISSUE TITLE
Schedtool was not installed during dependency installation

### ISSUE THREAD

**Issue by fiordiconio** [Frogging-Family/linux-tkg#398]
I got an error which said: "Schedtool command not found"

I thought that schedtool would be installed in that dependencies installation that happened at first
Such as like this:
https://github.com/Frogging-Family/linux-tkg/pull/399

This is the line where it says the message
https://github.com/Frogging-Family/linux-tkg/blob/2c0540c869775f5740e286f6099f4444123adbaa/PKGBUILD#L766

The building process continues nevertheless

**Comment by AdelKS** [comment]
This is a desired behavior as `schedtool` is an optional dependency. Although it doesn't hurt to simply add it to the dependencies and just simplify the line you refer to.

**Comment by fiordiconio** [comment]
@AdelKS Yeah, that is what I was talking about

**Comment by Tk-Glitch** [comment]
We don't want to enforce schedtool installation. We used to do it and there were complaints from people who didn't want to install/use it, so we made it optional.

**Comment by fiordiconio** [comment]
Okay, thank you for the clarification
