### ISSUE TITLE
How to install the built package?

### ISSUE THREAD

**Issue by mrshroomy** [Frogging-Family/linux-tkg#402]
error: failed to commit transaction (conflicting files)
linux516-tkg-pds: /etc/modules-load.d/winesync.conf exists in filesystem (owned by linux515-tkg-pds)
linux516-tkg-pds: /etc/udev/rules.d/winesync.rules exists in filesystem (owned by linux515-tkg-pds)
linux516-tkg-pds: /usr/include/linux/winesync.h exists in filesystem (owned by linux515-tkg-pds)
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
  -> exit cleanup done

  -> compilation time : 

real    36m35,493s
user    221m56,217s
sys     22m9,093s

How do i install the package without compiling again?

**Comment by JohnyPeaN** [comment]
pacman -U linux516-tkg-pds*.pkg.tar.zst --overwrite='*' in directory where the packages were created. Be carefull with this command. Uninstalling linux515-tkg-pds will remove those files from system even for linux516-tkg-pds and vice versa.
