### ISSUE TITLE
Missing option in kernel config causes Chaotic-AUR builds to stall

### ISSUE THREAD

**Issue by dr460nf1r3** [Frogging-Family/linux-tkg#403]
Hey! Most of our Chaotic-AUR builds are locked due to a new kernel config which doesn't seem to be available. Since we can't process input in our toolbox, adding this to the config would be very helpful. Thanks :) 
`Disable unprivileged BPF by default (BPF_UNPRIV_DEFAULT_OFF) [N/y/?] (NEW)`

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/linux-tkg/commit/5b68122f5191f5e66aa072bc98516253582bcd66
