### ISSUE TITLE
Adding Comet Lake To TKG

### ISSUE THREAD

**Issue by S29GamerRNX** [Frogging-Family/linux-tkg#406]
I'm Having a laptop which has base arch,So I want to get tkg kernel because I'm not getting good performance on stock one, I can't find  my cpu architecture name on the list which is Comet Lake,I'm having intel i5 10210U chip.Its a kind request to add Comet lake to tkg kernel cpu list.Thank you in advance

**Comment by Tk-Glitch** [comment]
Comet Lake happens to be based on Skylake 14nm, like Coffee Lake. So it's technically supported through the Skylake optimization :slightly_smiling_face:

**Comment by AdelKS** [comment]
Here's the list of supported architectures by the compiler: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

If the lineup of your CPU isn't listed: it is either too new or it is part of and older naming scheme since the technology behind didn't change.

**Comment by S29GamerRNX** [comment]
> Comet Lake happens to be based on Skylake 14nm, like Coffee Lake. So it's technically supported through the Skylake optimization :slightly_smiling_face: 

But isn't it as effective as the original just asking because I don't know what performance boost it does but surely I'll give it a try thanks 😉

**Comment by S29GamerRNX** [comment]
> Here's the list of supported architectures by the compiler: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
> 
> If the lineup of your CPU isn't listed: it is either too new or it is part of an older naming scheme since the technology behind didn't change.
> 
> P.S: your kernel performance won't noticeably change with this. `mitigations=off` kernel command line gets you better improvements for example (although there's a security tradeoff)

Hey,thanks for the list but tkg do support alder Lake(12th gen) and mine is Comet Lake(10th gen) which is not too old they should support it just saying I tried mitigations=off too it still didn't give me performance boost.

**Comment by AdelKS** [comment]
> mine is Comet Lake(10th gen) which is not too old they should support it

So the second part of my sentence applies: it is part of an older naming scheme, and there's no extra optimisation to be done than the one made for the older generations under that same naming.

> I tried mitigations=off too it still didn't give me performance boost.

All of this won't give you a performance "boost", just a slight improvement. Given you are on a laptop, maybe it's thermal throttling, maybe you have a BIOS option to unlock higher power draw.

**Comment by Tk-Glitch** [comment]
> > Comet Lake happens to be based on Skylake 14nm, like Coffee Lake. So it's technically supported through the Skylake optimization slightly_smiling_face
> 
> But isn't it as effective as the original just asking because I don't know what performance boost it does but surely I'll give it a try thanks wink

Nope, nothing extra. Skylake, Kaby Lake, Coffee Lake, Whiskey Lake and Comet Lake are sharing the same Skylake 14nm arch. Cannon Lake is the one that's different in the Skylake family as it's based on Skylake 10nm, that's why it has its own optimization option. Alder Lake is a pretty different arch.

**Comment by S29GamerRNX** [comment]
> > mine is Comet Lake(10th gen) which is not too old they should support it
> 
> So the second part of my sentence applies: it is part of an older naming scheme, and there's no extra optimisation to be done than the one made for the older generations under that same naming.
> 
> > I tried mitigations=off too it still didn't give me performance boost.
> 
> All of this won't give you a performance "boost", just a slight improvement. Given you are on a laptop, maybe it's thermal throttling, maybe you have a BIOS option to unlock higher power draw.

Ok I'll check with my bios if thermal throttling is available.Thanks 😊

**Comment by S29GamerRNX** [comment]
> > > Comet Lake happens to be based on Skylake 14nm, like Coffee Lake. So it's technically supported through the Skylake optimization slightly_smiling_face
> > 
> > But isn't it as effective as the original just asking because I don't know what performance boost it does but surely I'll give it a try thanks wink
> 
> Nope, nothing extra. Skylake, Kaby Lake, Coffee Lake, Whiskey Lake and Comet Lake are sharing the same Skylake 14nm arch. Cannon Lake is the one that's different in the Skylake family as it's based on Skylake 10nm, that's why it has its own optimization option. Alder Lake is a pretty different arch.

Oh then I'll give it a spin and I also got 14nm architecture like that I try it and tell. Thanks for clearing my doubt tysm 😊

**Comment by S29GamerRNX** [comment]
> > Ok I'll check with my bios if thermal throttling is available.Thanks 😊
> 
> Thermal throttling is an effect where the CPU starts running slowly when it gets too hot. Actually I think it's better to leave your BIOS alone, there are so many things that can go wrong by "experimenting" x)

Ok lol
