### ISSUE TITLE
Void Linux Templates fails or is old

### ISSUE THREAD

**Issue by wael444** [Frogging-Family/linux-tkg#421]
by using [the void linux linux tkg templates](https://github.com/Ann1kaB/void-packages/tree/tkg), package pcre has an old distfile:
```
https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.bz2: No address record
=> ERROR: pcre-8.45_1: failed to fetch pcre-8.45.tar.bz2.
```
by trying to use void-packages from master and adding the tkg templates manually (attempted 5.17 linux):
```
=> linux-tkg-5.17.0_21: installing target dependencies: xz-5.2.5_2 modprobed-db-2.44_2 wget-1.21.2_1 ...
=> ERROR: xbps-src: unexistent file: /void-packages/srcpkgs/linux517-tkg-pds/template
```
it seems the templates only go until linux 5.15?? 

so i tried to instead get only the updated PCRE+PCRE2 template and add it to the tkg repo manually:
```
=> linux-tkg-5.17.0_21: installing target dependencies: xz-5.2.5_2 wget-1.21.2_1 modprobed-db-2.44_2 ...
=> ERROR: xbps-src: unexistent file: /void-packages/srcpkgs/linux517-tkg-pds/template
``` 
same error. i don't think there should be a template for each version Linux TKG. it should be automatic, makes the directory structure a mess or if there is a reason behind it and i'm just the having brain damage

but all the templates are symlinked to linux-tkg anyway. its just the templates aren't being updated.

**Comment by AdelKS** [comment]
Hello!

Is it possible to have everything in the `linux-tkg` and not a third party repo ? Your help would be very welcome if you are up for the task in making things better for void.

**Comment by wael444** [comment]
> Is it possible to have everything in the linux-tkg and not a third party repo?

i'm not sure what you mean, but from my understanding the templates are used to make void linux package installation much easier to handle. using something else like a script would make XBPS not be able to manage or reconfigure it.
the templates can't be included in the linux-tkg repository either because of `xbps-src`, it all has to be manually updated.
i don't understand why each kernel build has its own symlink. as the way TKG works absolutely does not go with void linux's templates. the only solutions now is to wait for @Ann1kaB, or to compile and install your own. or if there is a solution and i just have brain damage

**Comment by Ann1kaB** [comment]
Hi! sorry for the long wait, but i've updated the repo, and made a few changes that make it easier to maintain, and won't get as broken for long, now i just need to automate merging to void-packages master...

**Comment by Ann1kaB** [comment]
> i don't understand why each kernel build has its own symlink.
actually, I *sort of* fixed that, instead now it just creates the symlink if it doesn't exist.

**Comment by wael444** [comment]
i know this is an off-topic issue, but i am currently suffering with a Nvidia DKMS problem:
```
Building DKMS module 'nvidia-510.47.03' for kernel-5.17.0-tkg-pds_22... FAILED!
DKMS module 'nvidia-510.47.03' failed to build, please check /var/lib/dkms
```
the only thing different in the TKG kernel logs vs normal kernel is that vmlinuz doesn't exist for the normal kernel.
another user reported that the Nvidia kernel module does not get built successfully and X does not start.
