### ISSUE TITLE
Git updates

### ISSUE THREAD

**Issue by ryanmusante** [Frogging-Family/linux-tkg#427]
Are the following recommended for a directory before each new pull?
```
git reset --hard HEAD
git clean -xdf
```
Or would a pull [alone] from origin overwrite and remove junk by default? 
```
git pull origin master
```

**Comment by AdelKS** [comment]
Hello!

A pull alone does not overwrite any file that did not get modified through a commit (this includes newly created files for example). To answer your question, you do not have to clean your `linux-tkg` folder with the first two commands you did (if you did not commit anything on your own copy of `linux-tkg`) : those extra files that the script sometimes leave get overwritten and normally deleted every time it ends (for whatever reason, on success and failure).

Hope this answers your question ?
