### ISSUE TITLE
CacULE RDB terrible performance

### ISSUE THREAD

**Issue by undeadbydawn** [Frogging-Family/linux-tkg#431]
The CacULE scheduler is great. RDB is not. It causes very noticable lag and stuttering in games and would be far better set to No in defaults until that radically improves

**Comment by ptr1337** [comment]
Personally i dont face that issues, but i currently dont use tkg. 
Did you played with different sysctl settings ? In general cacule(rdb) depends much on the hardware, and general it is suggested to play with different settings which suits to your hardware. 

Cacule wont be improved currently, since the creator of it dont have the motivation/time for it anymore. I keep it maintained and updated to the kernel updates currently.

**Comment by undeadbydawn** [comment]
No, I simply played games after compiling kernels (tkg-cacule wwith graysky zen3, e/fsync) with and without RDB, and the difference was stark. Silky smooth without, constant heavy stuttering with, all other settings identical
Damned shame CacULE isn't being developed since its easily the best I've used (5600X/5700XT) - you have my deep personal gratitude for maintaining it thus far.

**Comment by RyanHakurei** [comment]
@undeadbydawn You can try the TaskType scheduler which is allegedly the successor to Cacule. I am waiting for support to be added to the customization file so I can try it out (I know I can likely patch it in manually, but I don't want to mess with it right now)
https://github.com/hamadmarri/TT-CPU-Scheduler

**Comment by ptr1337** [comment]
TT will be also only maintained for LTS Kernerls. I try to keep that also up for upcoming kernels!

**Comment by undeadbydawn** [comment]
> > The CacULE scheduler is great. RDB is not. It causes very noticable lag and stuttering in games and would be far better set to No in defaults until that radically improves
> 
> From my experience it has to do with `sched_interactivity_factor`. If I set it to a low value (125 instead of 32678 for example) the stuttering and lag in games goes away. However this prevents you from being able to play games while you're having high CPU load.
> 
> Changing the interval from 19 to any other value barely helps. From some threads I've seen disabling autogroup scheduling seems to solve it but I personally don't think it's a good idea as autogroup scheduling helps CFS for desktop workloads a lot.
> 
> Another thing you can try is the older RDB patches (though I am not sure if they will work with mainline kernel as they're roughly 5 months old.

it's been fine since simply opting not to use RDB.
I may go back to pds when cacule properly dies, but I'm wary of the initial launch issues it caused (games refusing to run until I'd gone back to mainline, launched them once, then gone back to pds). TKG-Cacule has displayed no such quirks and has been easily my most performant kernel
