### ISSUE TITLE
CacULE patch is skipped when building on Fedora

### ISSUE THREAD

**Issue by wolfw3** [Frogging-Family/linux-tkg#437]
While building kernel 5.16.9, I selected the CacULE scheduler which downloaded fine but then I caught this in the output:
``Skipping patch cacule-5.16.patch...
         (unavailable for this kernel version)
``

It also didn't provide any configuration options for CacULE, so it seems like the patch is just being skipped for no reason? I tried this again on Arch and it worked perfectly fine.

**Comment by AdelKS** [comment]
Hello, there are two `cacule` patches (depending on the kernel version) and only one needs to be applied, the code applies both knowing that one of them won't be available (because we're lazy):

```shell
 -> Skipping patch cacule-5.16.patch...
         (unavailable for this kernel version)
 -> Applying cacule patch
```

So everything is alright (provided that you see the second line, which I think you do)
