### ISSUE TITLE
Additional CPU families patch does not apply anymore?

### ISSUE THREAD

**Issue by Slaviusz** [Frogging-Family/linux-tkg#438]
I've noticed after building 5.16.8 kernel with BMQ  scheduler that CPU family is set to `generic-x86` - probably as a falback after `zen2` option was not found when applying config from my `custom.myfrag` file. I had a look and it seems the additional CPU family patches are not being applied, at least to 5.16.latest. I've been searching commit messages but did not find a mention of this patch removal.

Is this a bug/regression?

Thanks for your help.

**Comment by AdelKS** [comment]
You are right, will fix that in few minutes, thanks for the report !

**Comment by Slaviusz** [comment]
Thank you for your awesome work!
