### ISSUE TITLE
linux-tkg not installing on arch linux

### ISSUE THREAD

**Issue by Abhs15** [Frogging-Family/linux-tkg#440]
Hello i have just installed arch linux and wheni try and install this tkg-pds it gives me and error like this 
An error was encountered applying patches. It was logged to the prepare.log file.
  -> Applying Glitched PDS patch
/home/genos/Downloads/git/linux-tkg/linux-tkg-config/prepare: line 385: patch: command not found

i have installed tkg-pds before on my previous setup and it worked fine its was very fast too so what seems to be the problem here is there a dependency i have to install to fix this i have missed?
here is the log file

**Comment by AdelKS** [comment]
you need to install the `patch` package

**Comment by Snoop05** [comment]
Whole `base-devel` group in fact :)

**Comment by AdelKS** [comment]
> Whole base-devel group in fact :)

that cannot be added to dependencies in the PKGBUILD right ?

**Comment by Abhs15** [comment]
tnx so much guys worked

**Comment by netbospl** [comment]
> > Whole base-devel group in fact :)
> 
> that cannot be added to dependencies in the PKGBUILD right ?

Groups of packages like base-devel wouldn't work by adding it, all packages in the group would have to be added one by one. But all packages in this group could potentially be added but to be honest, base-devel group packages are in some sense 'must have to be able to build packages' at least from my linux daily driving experience so far.
