### ISSUE TITLE
Kernel build default is PREEMPT - even if not changed in customization.cfg. Affects 5.16.X-5.17RC.X

### ISSUE THREAD

**Issue by Tilde88** [Frogging-Family/linux-tkg#443]
On kernels 5.16-5.17, the default build (without changes to customization.cfg), always builds a preemptive kernel.

Tracing the tkg-config, I found that config.x86_64 in 5.16 and 5.17 directories has "CONFIG_PREEMPT_BUILD=y" , whereas in 5.15, 5.14, and probably others, that line doesn't even exist.

It is notable that this line is above some commented lines, leading me to believe that "CONFIG_PREEMPT_BUILD=y" was supposed to be "#CONFIG_PREEMPT_BUILD=y", but just missing the comment. Possible that anyone running 5.16-5.17 is running a PREEMPT kernel. 

Confirmed on a clean download.

**Comment by Tilde88** [comment]
> 

Ok got it. Sorry

**Comment by Tilde88** [comment]
> A preemptible kernel should be good for responsiveness, so we are still all good anyway thinking

I see.

I am having issues with passthrough occasional KP, seemingly because of this. How can I not make it build as such? "5.17.0-rc4-246-tkg-pds #1 TKG SMP PREEMPT" is the default and even removing the aforementioned line in the config did not change this.

**Comment by AdelKS** [comment]
You do not have to touch any file: run `make xconfig` when you are prompted to at the end, then search for  `PREEMPT` (there's a search menu item), and untick that. then you can compile a kernel without that.

**Comment by Tilde88** [comment]
ah thats what i was wondering, if it was only a menuconfig edit, tyvm!

BTW, i checked, and sure enough, the default manjaro kernels are now PREEMPT!
thanks!
