### ISSUE TITLE
Build fails on Void GNU/Linux

### ISSUE THREAD

**Issue by treuks** [Frogging-Family/linux-tkg#448]
While trying to compile the kernel on Void Linux, I got the following error messages:

```
/usr/bin/ld: /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/libnghttp2.a(nghttp2_map.o): warning: relocation against `stderr@@GLIBC_2.2.5' in read-only section `.text'
/usr/bin/ld: /usr/lib64/gcc/x86_64-unknown-linux-gnu/10.2.1/../../../../lib64/libnghttp2.a(nghttp2_map.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1551: libcurl.la] Error 1
make[2]: Leaving directory '/builddir/curl-7.79.1/lib'
make[1]: *** [Makefile:1360: all] Error 2
make[1]: Leaving directory '/builddir/curl-7.79.1/lib'
make: *** [Makefile:1262: all-recursive] Error 1
=> ERROR: curl-7.79.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:15
```

The only changes that I have done to the configuration file were:	
```
_processor_opt="ivybridge"
_configfile="running-kernel"
```

Tried to compile the 5.16.11 Kernel, with the PSD Scheduler and GCC 

I'm not sure what you would need to diagnose this, so if you need to ask me for something else, please do.

**Comment by AdelKS** [comment]
Unfortunately Void lacks an active maintainer and cannot be entirely self contained in this repository. You can go with "generic" install and that should work, if you are using grub.

**Comment by treuks** [comment]
Thank you, I will attempt to do so and close the issue if no such errors occur.

**Comment by treuks** [comment]
After installing the dependancies, there were no issues. Closing the issue.
