### ISSUE TITLE
ERROR: Cannot find LILO.

### ISSUE THREAD

**Issue by smartsyncing** [Frogging-Family/linux-tkg#449]
Whenever I install it using the 'Generic Install' option I get this error and the kernel does not show up in GRUB. I'm using Void Linux and GRUB

**Comment by AdelKS** [comment]
Can you give the entire output that you get on your terminal, after the compilation is done ?

**Comment by smartsyncing** [comment]
Is there a log or do I need to rebuild the kernel? Sorry for the stupid question.

**Comment by AdelKS** [comment]
It is not a stupid question. As of now you need to rebuild and install the kernel if you have already closed the terminal you used. That is actually something I'll look into again in the near future as I didn't find a short an elegant way to do it

**Comment by AdelKS** [comment]
It is not a stupid question. As of now you need to rebuild and install the kernel if you have already closed the terminal you used. That is actually something I'll look into again in the near future as I didn't find a short an elegant way to do it.

Just attach the entire log from the moment you run the command `install.sh install`

**Comment by smartsyncing** [comment]
I tried to install LILO, to fix the error but this just gave me another error about the config file, after a little research I need a script called 'installkernel' which I can't find on Void. Here is the error I got: (I didn't see any other errors.)

`sh ./arch/x86/boot/install.sh 5.16.12-tkg-bmq \
	arch/x86/boot/bzImage System.map "/boot"
Fatal: Cannot open: /etc/lilo.conf
make: *** [arch/x86/Makefile:298: install] Error 1`

**Comment by AdelKS** [comment]
It shouldn't be using LILO, it's a bootloader too afaik, so something needs to be edited to make it know that it's Grub that's going to be used... Hm... Let's see

**Comment by smartsyncing** [comment]
Yes, I noticed. It seems to call it in the installer if it can't find the 'installkernel' script.

**Comment by AdelKS** [comment]
Can you attach the output of `ls -ll /boot`

**Comment by smartsyncing** [comment]
```
-rw-r--r-- 1 root root  6236658 Mar  6 16:22 System.map
-rw-r--r-- 1 root root  6236658 Mar  6 13:59 System.old
-rw-r--r-- 1 root root   245332 Feb  1 17:20 config-5.15.19_1
-rw-r--r-- 1 root root   245370 Feb  8 18:31 config-5.15.22_1
-rw-r--r-- 1 root root   245370 Feb 16 16:03 config-5.15.24_1
-rw-r--r-- 1 root root   245370 Mar  2 13:44 config-5.15.26_1
drwxr-xr-x 3 root root     4096 Jan  1  1970 efi
drwxr-xr-x 1 root root       72 Mar  6 15:38 grub
-rw------- 1 root root 68339090 Feb  5 10:54 initramfs-5.15.19_1.img
-rw------- 1 root root 68335593 Feb 11 21:14 initramfs-5.15.22_1.img
-rw------- 1 root root 68336958 Feb 18 12:22 initramfs-5.15.24_1.img
-rw------- 1 root root 68353077 Mar  6 10:36 initramfs-5.15.26_1.img
-rw------- 1 root root 12317857 Mar  6 12:41 initramfs-5.16.12-tkg-bmq.img
-rw-r--r-- 1 root root  9077920 Mar  6 16:22 vmlinuz
-rw-r--r-- 1 root root  9536000 Feb  1 17:20 vmlinuz-5.15.19_1
-rw-r--r-- 1 root root  9561440 Feb  8 18:31 vmlinuz-5.15.22_1
-rw-r--r-- 1 root root  9561344 Feb 16 16:03 vmlinuz-5.15.24_1
-rw-r--r-- 1 root root  9568160 Mar  2 13:44 vmlinuz-5.15.26_1
-rw-r--r-- 1 root root  9077984 Mar  6 13:59 vmlinuz.old
```

Linux TKG vmlinuz isn't there, even if I regenerate grub config.

**Comment by AdelKS** [comment]
Actually, please uninstall LILO and attach the asked output again, that warning message is not relevant

**Comment by smartsyncing** [comment]
It's actually the same, except it says it can't find LILO, but sure, give me a little while.

**Comment by AdelKS** [comment]
Yes please, and give me again what's in the `/boot` I think I know what's happening. The kernel simply is called `vmlinuz` and it is replacing the current `vmlinuz` with `vmlinuz.old`. I had that issue before and I needed to rename `vmlinuz` to something like `bak.vmlinuz` so it the script uses another naming scheme

**Comment by smartsyncing** [comment]
So, should I try to rename the vmlinuz file to the kernel name and see what happens?

**Comment by smartsyncing** [comment]
This.. seemed to work, but now my resolution is completely wrong. Can't set it any higher, I think it's a nvidia driver issue.

**Comment by AdelKS** [comment]
Yes exactly ! I'm glad to learn that it worked out well and even Nvidia compiled without issues ! This is something I have never tested before.
