### ISSUE TITLE
Application of cacULE & suggested configs 5.4

### ISSUE THREAD

**Issue by nutterpc** [Frogging-Family/linux-tkg#450]
As my computer graphics card only supports 5.4 (it does what i want, so it's fine), i've noticed the script does not properly find the cacULE patch from the repository & apply it, needing a little finessing to get it to apply

Is it possible for this to be remedied and also have an option for the suggested settings from the dev himself applied before kernel compilation?

https://raw.githubusercontent.com/hamadmarri/cacule-cpu-scheduler/master/scripts/apply_suggested_configs.sh

I've managed to get it to successfully download the patch, apply it and also found a way to get the settings to apply, but it's relevant to my machine. So I'm happy to forward the configs so it could be applied to the base script for others to be able to use

**Comment by Tk-Glitch** [comment]
We are already applying the relevant config changes. Most of what's listed in there is terrible and will break a large number of configurations, which is undesirable. Regarding the patchset itself I guess something moved again as it used to work fine.
