### ISSUE TITLE
Kernel Patch 5.16.13 Bad Checksum

### ISSUE THREAD

**Issue by fatalgoth** [Frogging-Family/linux-tkg#452]
Checksum for kernel 5.6.13 is (now?):

`aaa5555a903f794fb753f35427781b608d72ea34993c018ae1289037376037a0`

as shown at kernel.org ->

` curl -s https://cdn.kernel.org/pub/linux/kernel/v5.x/sha256sums.asc | grep patch-5.16.13.xz
aaa5555a903f794fb753f35427781b608d72ea34993c018ae1289037376037a0  patch-5.16.13.xz`

Current PKGBUILD lists it as:

`d58cbfc41bf8672b0ce9c9f129578c18bfecbdeb4684c581e191345cb2aa95f1`

Which causes the build to fail during makepkg.

**Comment by talzahr** [comment]
Same from a git pull. Did a clean git clone and still shows up. Ran makepkg with --skipinteg but having the build error as per issue [451](https://github.com/Frogging-Family/linux-tkg/issues/451)
