### ISSUE TITLE
Add MGLRU patches

### ISSUE THREAD

**Issue by Edu4rdSHL** [Frogging-Family/linux-tkg#456]
Hello, I wonder if it's possible to get the MGLRU patches in the linux-tkg kernel. The benefits are overall performance and better memory management, [here is](https://www.phoronix.com/scan.php?page=news_item&px=Linux-MGLRU-v9-Promising) a better explanation.

In the v9 of the patch, the objections that Torvalds made were fixed, here's the patchset link: https://lore.kernel.org/lkml/20220309021230.721028-1-yuzhao@google.com/T/

Thanks in advance.

Ed

**Comment by subanz** [comment]
There already is an LRU community patch you can add before building, here is one for 5.16 for example.

https://github.com/Frogging-Family/community-patches/tree/master/linux516-tkg

**Comment by B3HOID** [comment]
> There already is an LRU community patch you can add before building, here is one for 5.16 for example.
> 
> https://github.com/Frogging-Family/community-patches/tree/master/linux516-tkg

That doesn't mean that it wouldn't be a good idea to make it as part of the base patchset.

**Comment by jeois** [comment]
Please consider adding this to the standard patch set.  According to testers, it's very useful and stable enough.

**Comment by qumaciel** [comment]
I'd also vote for this!

**Comment by pongo1231** [comment]
Already been added as an option

https://github.com/Frogging-Family/linux-tkg/commit/a94830eb4a8ef1818fa67ac6aa054740e0977bfe

**Comment by Edu4rdSHL** [comment]
Thanks for the update, closing.
