### ISSUE TITLE
Patch file name changed

### ISSUE THREAD

**Issue by mengshouer** [Frogging-Family/linux-tkg#459]
https://github.com/Frogging-Family/linux-tkg/blob/a7843dd8c561f48462dee15586505475a26ce1d6/install.sh#L227

The source repository has changed the filename and needs to be updated。

**Comment by karimrir1** [comment]
+1 this up, Happened to me too while using makepkg.

**Comment by Blazingi** [comment]
https://github.com/Frogging-Family/linux-tkg/pull/460 will fix this.
