### ISSUE TITLE
Error when installing on Pop!_OS

### ISSUE THREAD

**Issue by Hiammat** [Frogging-Family/linux-tkg#46]
While installing on Pop!_OS I came across this error:

error: include/uapi/linux/vt.h: leak CONFIG_NR_TTY_DEVICES to user-space
  HDRINST usr/include/linux/libc-compat.h
make[6]: *** [scripts/Makefile.headersinst:63: usr/include/linux/vt.h] Error 1
make[6]: *** Waiting for unfinished processes ....
make[5]: *** [Makefile:1227: headers] Error 2
make[4]: *** [scripts/Makefile.package:87: intdeb-pkg] Error 2
make[3]: *** [Makefile:1463: intdeb-pkg] Error 2
make[2]: *** [debian/rules:9: binary-arch] Error 2
dpkg-buildpackage: Errore: fakeroot -u debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1463: deb-pkg] Error 2
 -> exit cleanup done

**Comment by AdelKS** [comment]
Hello!

You should put `misc_adds` to `false` for the script to work, it seems that the script needs to be even more clear.

**Comment by Tk-Glitch** [comment]
I have now set the option to false by default on the non-Arch path to prevent this.
https://github.com/Frogging-Family/linux-tkg/commit/e71dced34b9cacf8bb7009c40ee70d71295aeaf5

**Comment by AdelKS** [comment]
I was about to PR that same change, great minds think alike.

**Comment by Tk-Glitch** [comment]
Considered as fixed :frog: 
Closing
