### ISSUE TITLE
How do i pick a particular kernel version of choosing (5.16.0 in this case )

### ISSUE THREAD

**Issue by thecountrox** [Frogging-Family/linux-tkg#465]
Why : Because any kernel above that breaks audio input on my Realtek ALC236 (always says mic is unplugged even tho i have a combo jack) yes im sure this is a global kernel issue since every distro ive tried so far (fedora , endeavour , mx linux , pop os ) would work my mic and after update would go poof , also I am planning on opening an issue in kernel.org

**Comment by AdelKS** [comment]
Yes please report the bug upstream. From what I have seen kernel devs are more responsive in the mailing list. There's a whole section in their docs to explain which mailing list to contact.

To answer your question:
- if you are not running Arch: simply modify the top of `linux-tkg-config/prepare` and change the subversion of your kernel of chosing.
- If you are running Arch, you have to simply comment out the patch file that bumps the kernel subversion from 5.xx to 5.xx.y and its related Sha sum. Project C patches will probably fail for 5.16, so you'll have to use CFS

**Comment by thecountrox** [comment]
Okay! , since I posted this issue I went ahead and compiled linux tkg bmq 5.15.26 (as it was one of the predefined options) and im not sure what happened but the audio issue still persisted , I think its because of maybe one of the patches that either got added to 5.15.26 or earlier versions that wasnt present in (im using artix at the moment , but using the downgrade bash script to download the kernel pacakge from the ALA which means im following the arch's kernel builds + patches) arch's kernel 5.16 but is present in 5.16.1 , another thing to note : arch did not push a kernel 5.15.26 (they stopped with 5.15.13 or maybe thats all there is on the ALA and moved to 5.16) also another thing , kernel 5.16.1 fixed my external monitor resolution issue where the console was on a lower resolution than my screen's and was only fixed when i finally launched Xorg and set it with xrandr (or use a settings daemon) interesting thing is : it was fixed in tkg 5.15.26 as well  (strange, maybe those patches were taken from 5.16+ ???? or maybe they came with 5.15.13+ and was omitted on the 5.16 build and readded on 5.16.1? idk. 

Sorry for the really long post : if something isnt clear please do not hesitate to ask :smile: 
conslusion : arch 5.16.0 didnt have resolution fix nor audio problems but arch 5.16.1 broke audio and fixed resolution but tkg 5.15.26 broke audio and fixed resolution

**Comment by Tk-Glitch** [comment]
It's very usual to see changes in newer kernels backported to older branches, so that's likely what happened here.
You can checkout this commit https://github.com/Frogging-Family/linux-tkg/commit/64f7cf7ff3174a30cca539d181afb47872ffb188 to get the closest to 5.16.0, which is 5.16 RC6 (I was away from home with christmas and the new year so we basically skipped 5.16.0 to jump to 5.16.1). It also sets 5.15 branch to 5.15.11.

**Comment by thecountrox** [comment]
I will try compile 5.16.0 tkg and report back , verifying this theory

**Comment by thecountrox** [comment]
![image](https://user-images.githubusercontent.com/74064922/159149316-5a99fbb0-22a5-4ba0-a5ba-41e45aefbc30.png)
i tried looking around in the said repo but uh :sob:

**Comment by Ann1kaB** [comment]
> ![image](https://user-images.githubusercontent.com/74064922/159149316-5a99fbb0-22a5-4ba0-a5ba-41e45aefbc30.png) i tried looking around in the said repo but uh 😭

the patch name changed, at the end its 5.15-5.16 now.

**Comment by thecountrox** [comment]
![Uploading image.png…]()
yes that worked! , now time to wait 20mins , will post as soon as I can

**Comment by thecountrox** [comment]
![image](https://user-images.githubusercontent.com/74064922/159153591-14bfe463-5743-490c-b4c2-039ac1942220.png)
oh yes I can confirm that indeed worked!
my mic is working as intended and the resolution fix is not there, Now I think @Tk-Glitch 's theory is right.
Any suggestions on how to report this to the upstream linux kernel maintainers?

**Comment by AdelKS** [comment]
> Any suggestions on how to report this to the upstream linux kernel maintainers?

You need to read this: https://docs.kernel.org/admin-guide/reporting-issues.html

You need to isolate at least which subversion bump broke your setup, you already have this figured out. You can continue and actually try and find the specific commit by "bisecting" : there are let's say 1000 commits between 5.16.0 and 5.16.1: you try the middle one, if it works, the middle of the upper half, if it doesn't, the middle of the lower half. Repeat till you find the culprit. This will help the kernel people understand exactly what's wrong. You probably have to do this for both your mic issue and resolution issue, separately... x)

Then if you can find relevant logs on why things don't work (if there are related errors in `journalctl`), then give a full spec of your computer. If I remember well you need to find which mailing list to contact. Everything should be written in the link above.
