### ISSUE TITLE
Any plans to provide a linux-next option?

### ISSUE THREAD

**Issue by QushyQushy** [Frogging-Family/linux-tkg#466]
Hello, are there any plans to provide a linux-next option in customization.cfg/PKGBUILD?
I have complied 5.17-rc8 but I have no net on my laptop which uses a Mediatek WiFi chip. Linux-next works just fine though.
I have tried compiling linux-next by cheating the names of the tar.gz t no avail. The build fails at some point during compilation.
Thanks in advance for any replies. :)

**Comment by AdelKS** [comment]
Linux rc releases are already as fresh and buggy as one can barely safely run on one's machine with sensitive data. 

I suggest to simply obtain the specific change for your WiFi chip as a patch that you'd put into your user patches folder

**Comment by AdelKS** [comment]
I'm closing this issue, feel free to comment here and we will reopen it if needed :smile:
