### ISSUE TITLE
Incorrect subversion from rc to stable

### ISSUE THREAD

**Issue by Daedalusspacegames** [Frogging-Family/linux-tkg#468]
The logic to provide the subversion after a release candidate appears to be bugged, current version of 5.17 reporting as 5.17.17 (obviously leading to a 404 when trying to download the patch file) :wink:

**Comment by RodoMa92** [comment]
Fixed in #469, as soon as it is merged it will work again :P

**Comment by AdelKS** [comment]
Ah If frogged up something apparently. It would've been too good to be true xD

**Comment by Tk-Glitch** [comment]
Closing as it's been fixed
