### ISSUE TITLE
Building from git fails on 5.17 final kernel

### ISSUE THREAD

**Issue by Slaviusz** [Frogging-Family/linux-tkg#470]
Using `install.sh` script fails to fetch 5.17 final kernel release at the moment because remote git repos (both kernel.org and googlesource.com) do not have ref named `refs/heads/linux-5.17.y`.
I'll keep this open as a placeholder until this is fixed in the repos (hopefully).

``` -> First initialization of the linux source code git folder
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /root/linux-tkg/linux-src-git/.git/
 -> Switching to linux-5.17.y
 -> 5.17.y branch doesn't locally exist, shallow cloning...
fatal: couldn't find remote ref linux-5.17.y```

**Comment by Slaviusz** [comment]
I was thinking if this is the case in each case a `z.x.0` kernel is release the `refs/heads/linux-z.x.y` ref will be missing until first patch is released?
In that case we should probably rather rely on `vZ.X` tag for `.0` kernels?

**Comment by AdelKS** [comment]
No no it's not, it will come online during this day

**Comment by AdelKS** [comment]
The branch is here now :D

**Comment by Slaviusz** [comment]
Works without a hitch! Thanks.
