### ISSUE TITLE
Fails to fetch patch-5.17.0 as it does not exist

### ISSUE THREAD

**Issue by colourfuloctopus** [Frogging-Family/linux-tkg#472]
Attempting to build with the Void instructions fails to fetch patch-5.17.0 (it does not exist). The correct name seems to exclude the 0. 

`=> ERROR: linux517-tkg-pds-5.17.0_22: failed to fetch patch-5.17.0.xz.`

https://cdn.kernel.org/pub/linux/kernel/v5.x/patch-5.17.xz exists. 
https://cdn.kernel.org/pub/linux/kernel/v5.x/patch-5.17.0.xz: does not exist.

**Comment by Ann1kaB** [comment]
Should be fixed now
