### ISSUE TITLE
invalid signature

### ISSUE THREAD

**Issue by PenguinDOOM** [Frogging-Family/linux-tkg#475]
```
error: vmlinuz-5.17.0-tkg-pds has invalid signature
error: you need to load the kernel first
```
I signed vmlinuz but I get this message and can't boot.

**Comment by PenguinDOOM** [comment]
Needed a proper signature.
Now I can boot.
![Screenshot from 2022-03-25 00-29-05](https://user-images.githubusercontent.com/50603637/159952463-c58c9a01-1e72-4fc8-9918-e1ccbe9e1658.png)
These sites were helpful.
[https://wiki.ubuntu.com/UEFI/SecureBoot/KeyManagement/KeyGeneration](https://wiki.ubuntu.com/UEFI/SecureBoot/KeyManagement/KeyGeneration)
[https://gauravsohoni.wordpress.com/2020/08/19/secure-boot-signing-kernel-files-in-ubuntu/](https://gauravsohoni.wordpress.com/2020/08/19/secure-boot-signing-kernel-files-in-ubuntu/)
![Screenshot from 2022-03-25 00-36-15](https://user-images.githubusercontent.com/50603637/159955238-ac9252cf-9cfc-4189-9ae5-7250964272b5.png)

**Comment by alou-S** [comment]
@PenguinDOOM Would be a good idea to close this issue don't you think?
