### ISSUE TITLE
Build fail with 5.17.0 & LLVM

### ISSUE THREAD

**Issue by adamgibbo** [Frogging-Family/linux-tkg#479]
Build failing on 5.17.0 & LLVM with full LTO.

Attached error.txt and customization.cfg (txt)
[Error.txt](https://github.com/Frogging-Family/linux-tkg/files/8351436/Error.txt)
[customization.txt](https://github.com/Frogging-Family/linux-tkg/files/8351437/customization.txt)

**Comment by ptr1337** [comment]
Use llvm 15 or thin lto. It's a known issue and there is already a issue open. 

See here:

https://github.com/Frogging-Family/linux-tkg/issues/446

**Comment by AdelKS** [comment]
Try again now, I could build Full LTO kernel 5.17.3 with Clang 14.0.0

**Comment by AdelKS** [comment]
Fix confimed in #446
