### ISSUE TITLE
overdrive fix missing for 5.9

### ISSUE THREAD

**Issue by aufkrawall** [Frogging-Family/linux-tkg#48]
Hello,
just dropping a note that the patch to fix overdrive with 5.9-rc1 still seems to be required, but _misc_adds="true" doesn't apply it.

Thanks!

**Comment by Tk-Glitch** [comment]
I haven't had much time to play with 5.9 yet :frog:

**Comment by aufkrawall** [comment]
The commits that caused it to break have been reverted.

**Comment by aufkrawall** [comment]
I was mistaken, we still need this patch for overdrive to work with 5.9: https://patchwork.freedesktop.org/patch/381849/

**Comment by AdelKS** [comment]
Can you enlighten me on what's "overdrive" ? Thank you !

**Comment by aufkrawall** [comment]
To allow overclocking/undervolting with amdgpu. It has regressed with 5.9 mainline vs. 5.8.

**Comment by AdelKS** [comment]
Oh I see! Thank you, I will need that too. I haven't tried overclocking yet on 5.9

**Comment by terencode** [comment]
The revert shouldn't be needed for 5.9.1 as it has been applied: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.9.y&id=ffdf9f8550ee675d4270bbaa5721a6f3116d137e
