### ISSUE TITLE
obligatory bcachefs update pester

### ISSUE THREAD

**Issue by Sukid** [Frogging-Family/linux-tkg#487]
Still haven't learned how to make the patchset myself :( but bcachefs on 5.16.* is ready now. bcachefs-tools updated to need it, from what it looks like.

**Comment by AdelKS** [comment]
I don't see a v5.16 branch ? https://evilpiepirate.org/git/bcachefs.git :thinking:

**Comment by Sukid** [comment]
Oh oops. I really should have checked that, but linux-bcachefs-git on the aur is working so maybe it's master?

**Comment by AdelKS** [comment]
Indeed it is.

Thanks to @openglfreak's knowledge, here's how you can obtain patches for bcachefs, this gives you the patch from the v5.16 tag till latest commit on master :

https://evilpiepirate.org/git/bcachefs.git/patch/?id=HEAD&id2=v5.16

And on github, you can do this 

https://github.com/koverstreet/bcachefs/compare/df0cc57e057f18e44dac8e6c18aba47ab53202f9...master.patch

Where `df0cc57e057f18e44dac8e6c18aba47ab53202f9` is the sha1 of the v5.16 tag commit.

Now you can open your own PRs !

**Comment by Sukid** [comment]
Excellent, thank you!!! Will def be doing that!
