### ISSUE TITLE
page_alloc error on build

### ISSUE THREAD

**Issue by wamuu-sudo** [Frogging-Family/linux-tkg#489]
![Capture d’écran du 2022-04-04 10-37-25](https://user-images.githubusercontent.com/92715832/161506503-9b954a92-acd8-49f7-ad97-552a222fb52c.png)

**Comment by wamuu-sudo** [comment]
Same error on Gentoo OpenRC

**Comment by Dormanil** [comment]
Can also confirm that issue with the regular arch pkgbuild.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/30be4c4bc586f2253a040112c2241db42c8d577e

**Comment by Dormanil** [comment]
Many thanks!
