### ISSUE TITLE
Arch unable to boot when > 5.17.1-249

### ISSUE THREAD

**Issue by wazlecracker** [Frogging-Family/linux-tkg#496]
Using BTRFS on LUKS and I'm unable to get past the encrypt hook on boot up when using a kernel newer than 5.17.1-249: 
![IMG_20220409_155454](https://user-images.githubusercontent.com/45174508/162626373-2b19b553-de25-4d44-b002-21f8f38f3b23.jpg)

I've been building with linux-tkg for about 2 months now without encountering this issue.

[My customization.cfg](https://github.com/Frogging-Family/linux-tkg/files/8459293/customization.txt)
[My modprobed.db](https://github.com/Frogging-Family/linux-tkg/files/8459294/modprobed.db.txt)

Am I missing something?

**Comment by AdelKS** [comment]
I think some relevant information is in your `sudo journalctl -b -1`, which gives what happenned during the boot that didn't work (the before last boot, given by `-b -1`) attach that let's check :thinking:

**Comment by AdelKS** [comment]
Oh nevermind I am stupid, it cannot save the journal since the luks partition didn't get unlocked. Maybe you can get some good information in the emergency shell

**Comment by AdelKS** [comment]
Disable `modprobed-db` and retry, I have a feeling some module name changed.

**Comment by wazlecracker** [comment]
The emergency shell uses busybox, correct? Haven't messed with that before to know what commands to use to dig around.

**Comment by wazlecracker** [comment]
> Disable `modprobed-db` and retry, I have a feeling some module name changed.

Building right now.

**Comment by wazlecracker** [comment]
That seems to have worked, modprobed picked up some new modules:
```
Modprobed-db v2.45

172 modules currently loaded per /proc/modules
182 modules are in /home/user/.config/modprobed.db

New module(s) detected:
nvme
nvme_core
xt_comment
xt_mark

186 modules are now saved in /home/user/.config/modprobed.db
```

**Comment by wazlecracker** [comment]
Is there a way to preemptively detect new modules that would affect me?

**Comment by AdelKS** [comment]
The recommended approach is to boot arch's kernel first, update the database, then compile linux-tkg with it. In practice, do that only when you cannot boot xD

**Comment by AdelKS** [comment]
Keep me updated if it boots with `modprobed-db` enabled with those new modules added !

**Comment by wazlecracker** [comment]
Yes! Re-built the kernel with modprobed enabled & the new modules and things seem to be working fine now.
