### ISSUE TITLE
5.17 and modprobeddb, not bootable without nvme module added

### ISSUE THREAD

**Issue by xDShot** [Frogging-Family/linux-tkg#499]
Reposting from https://github.com/graysky2/modprobed-db/issues/16

Starting from 5.17 _modprobed-db store_ doesn't add _nvme_ module when it should. I had to manually add the module into `~/.config/modprobed.db` in order to make system bootable from NVMe SSD.

I build the kernel with _modprobeddb="true" for Arch Linux.

**Comment by AdelKS** [comment]
I see that it got fixed on the other side, good!
