### ISSUE TITLE
Use ACS override patch failed

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#5]
Use ACS override patch?
    https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Bypassing_the_IOMMU_groups_.28ACS_override_patch.29
    > N/y : y
patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #1 succeeded at 3480 (offset 290 lines).
patching file drivers/pci/quirks.c
Hunk #1 succeeded at 3544 (offset 172 lines).
Hunk #2 FAILED at 4613.
1 out of 2 hunks FAILED -- saving rejects to file drivers/pci/quirks.c.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/linux-tkg/commit/19b042e8d29bfcb2ee85e8d075a395aa9256cfe8
