### ISSUE TITLE
patch-5.17.5.xz FAILED validity check

### ISSUE THREAD

**Issue by undeadbydawn** [Frogging-Family/linux-tkg#505]
getting this error every time. Tested with CacULE and PDS

**Comment by ptr1337** [comment]
Just update the checksums or pull these changes in:

https://github.com/Frogging-Family/linux-tkg/pull/504

**Comment by undeadbydawn** [comment]
Successfully built & installed the code from jnines repo. Cheers

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/e02bb7ad34b0be090229d9480855b552bd5b2d65
