### ISSUE TITLE
New, unset kernel option breaking Chaotic-AUR builds

### ISSUE THREAD

**Issue by dr460nf1r3** [Frogging-Family/linux-tkg#512]
**Describe the bug**
 - OS: Archlinux
 - What happens: A new kernel option appeared which requires user input. Our toolbox does not allow user input, which effectively breaks our kernel builds. 
 - Here the [logfile of tkg-bmq](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-bmq-generic_v3.log), although it doesn't really help (just stops at the required input)

**Supposed solution**
Add this new option to the kernel configuration.

**Comment by Edu4rdSHL** [comment]
@Tk-Glitch can this fix be applied to -lts kernels? They're having the same problem.

**Comment by dr460nf1r3** [comment]
@Tk-Glitch LTS kernel builds are still failing due to this, we would very much like to provide them as well to our users :)
