### ISSUE TITLE
Alderlake options in _processor_opt missing (configuration file)

### ISSUE THREAD

**Issue by Ghibbi64** [Frogging-Family/linux-tkg#516]
I'm trying to configure the config file before, i'm stuck at _processor_opt because there isn't my cpu, i can use native_intel but it says that it's raccomanded to select a specific cpu architecture from the list above.
# Intel CPUs : "mpsc"(P4 & older Netburst based Xeon) "atom" "core2" "nehalem" "westmere" "silvermont" "sandybridge" "ivybridge" "haswell" "broadwell" "skylake" "skylakex" "cannonlake" "icelake" "goldmont" "goldmontplus" "cascadelake" "cooperlake" "tigerlake"

**Comment by Tk-Glitch** [comment]
The comment wasn't updated in the cfg file, but `alderlake` is actually supported. I'll update the list.
