### ISSUE TITLE
MuQSS Build problems

### ISSUE THREAD

**Issue by nutterpc** [Frogging-Family/linux-tkg#526]
Every single time i try to build *any* kernel with MuQSS, it fails with the following error:

error: include/uapi/linux/sched.h: leak CONFIG_SCHED_MUQSS to user-space

Having looked around, I've since found a way to resolve this, is there a way to implement this in the linux-tkg scripts?

https://github.com/zen-kernel/zen-kernel/commit/6aefea555ae66883483540d43c2024acecf61599#diff-5fc844f6c95b41c802ec9b55b32f3f6f1531bed68ca92169f42fde4fe075f4ed

Tested on 5.4 so far, and works

Will test others over coming days

**Comment by Tk-Glitch** [comment]
Sure we can do that.
