### ISSUE TITLE
5.17.xxx TT Build issue

### ISSUE THREAD

**Issue by nutterpc** [Frogging-Family/linux-tkg#528]
Found as i go to build a secondary kernel to have on my system i can swap between, and noticed that TT refuses to build:

 -> Switching to linux-5.17.y
  linux-5.17-kernel.org
 -> 5.17.y branch exists locally, updating...
Switched to branch 'linux-5.17-kernel.org'
Your branch is up to date with 'kernel.org/linux-5.17.y'.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), 808 bytes | 808.00 KiB/s, done.
HEAD is now at e960d7349 Linux 5.17.11
 -> Checking out latest release: v5.17.11
Note: switching to 'v5.17.11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e960d7349 Linux 5.17.11
 -> Setting version...
 -> Using Arch patches
--2022-05-30 14:06:55--  https://raw.githubusercontent.com/graysky2/kernel_compiler_patch/master/more-uarches-for-kernel-5.17%2B.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25738 (25K) [text/plain]
Saving to: '/home/nutterpc/linux-tkg/more-uarches-for-kernel-5.17%2B.patch’

/home/nutterpc/linux-tkg/more-uarches-for-kernel-5. 100%[===================================================================================================================>]  25.13K  --.-KB/s    in 0.008s  

2022-05-30 14:06:55 (3.17 MB/s) - '/home/nutterpc/linux-tkg/more-uarches-for-kernel-5.17%2B.patch’ saved [25738/25738]

 -> Applying graysky's cpu opts patch
 -> Applying clear linux patches
 -> Applying glitched base patch
 -> Applying misc additions patch
 -> Applying patches for WRITE_WATCH support in Wine
 -> Applying patches for WRITE_WATCH support in Wine
**curl: option --output-dir: is unknown
curl: try 'curl --help' or 'curl --manual' for more information**
 -> exit cleanup done

Not sure of which file that's in, causing it

**Comment by nutterpc** [comment]
_msg="Applying TT patch"
    if [ "${_distro}" = "Void" ]; then
      if [[ $_basever = 515 ]]; then
        curl --output-dir "$wrksrc" -o "tt.patch" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/TT/0001-tt-r3.patch"
      elif [[ $_basever = 517 ]]; then
        curl --output-dir "$wrksrc" -o "tt.patch" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt.patch"
      else
        curl --output-dir "$wrksrc" -o "tt.patch" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt-${_basekernel}.patch"
      fi
      tkgpatch="$wrksrc/tt.patch" && _tkg_patcher

Something in that it doesn't like

**Comment by nutterpc** [comment]
If i change the curl --output-dir to the wget -P, when building, it gives this

 -> Skipping patch %s...
         (unavailable for this kernel version)

That's when it goes to apply the TT patch

**Comment by Daedalusspacegames** [comment]
Very strange… what version of curl do you have installed? The `--output-dir` option was added to curl in version 7.73.0, so it's possible the version you have installed is too old.
When I wrote the PR to include TT, I used curl rather than wget to leverage its `-o` option (for which, best I can tell, there is no equivalent in wget) to keep the file name consistent across versions and enable the use of only one “_tkg_patcher” line.

Making the following changes to `linux-tkg-config/prepare` should enable the build script to work temporarily.
```bash
_msg="Applying TT patch"
     if [ "${_distro}" = "Void" ]; then
       if [[ $_basever = 515 ]]; then
         wget -P "$wrksrc" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/TT/0001-tt-r3.patch"
       elif [[ $_basever = 517 ]]; then
         wget -P "$wrksrc" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt.patch"
       else
         wget -P "$wrksrc" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt-${_basekernel}.patch"
       fi
       tkgpatch="$wrksrc/0001-tt-r3.patch" && _tkg_patcher
       tkgpatch="$wrksrc/001-tt.patch" && _tkg_patcher
       tkgpatch="$wrksrc/001-tt-${_basekernel}.patch" && _tkg_patcher
```

As I am not a maintainer, I will leave it up to them on how to call this bug

**Comment by Daedalusspacegames** [comment]
Gotcha, yeah, that's too old. ~~For some reason I thought you were on Void, it's like 3am for me I should prolly go to bed ;P~~

Since you're on Mint, the lines to change would be:
```bash
else
      if [[ $_basever = 515 ]]; then
         wget -P "$srcdir" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/TT/0001-tt-r3.patch"
      elif [[ $_basever = 517 ]]; then
         wget -P "$srcdir" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt.patch"
      else
         wget -P "$srcdir" "https://raw.githubusercontent.com/ptr1337/kernel-patches/master/${_basekernel}/sched/0001-tt-${_basekernel}.patch"
      fi
      tkgpatch="$srcdir/0001-tt-r3.patch" && _tkg_patcher
      tkgpatch="$srcdir/0001-tt.patch" && _tkg_patcher
      tkgpatch="$srcdir/0001-tt-${_basekernel}.patch" && _tkg_patcher
```

Apologies for the confusion

**Comment by nutterpc** [comment]
-> Using Arch patches
--2022-05-30 17:30:32--  https://raw.githubusercontent.com/graysky2/kernel_compiler_patch/master/more-uarches-for-kernel-5.17%2B.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25738 (25K) [text/plain]
Saving to: '/home/nutterpc/linux-tkg/more-uarches-for-kernel-5.17%2B.patch’

/home/nutterpc/linux-tkg/more-uarches-for-kernel-5. 100%[===================================================================================================================>]  25.13K  --.-KB/s    in 0.06s   

2022-05-30 17:30:33 (394 KB/s) - '/home/nutterpc/linux-tkg/more-uarches-for-kernel-5.17%2B.patch’ saved [25738/25738]

 -> Applying graysky's cpu opts patch
 -> Applying clear linux patches
 -> Applying glitched base patch
 -> Applying misc additions patch
 -> Applying patches for WRITE_WATCH support in Wine
 -> Applying patches for WRITE_WATCH support in Wine
--2022-05-30 17:30:33--  https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.17/sched/0001-tt.patch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175138 (171K) [text/plain]
Saving to: '/home/nutterpc/linux-tkg/0001-tt.patch’

0001-tt.patch                                       100%[===================================================================================================================>] 171.03K  --.-KB/s    in 0.1s    

2022-05-30 17:30:33 (1.49 MB/s) - '/home/nutterpc/linux-tkg/0001-tt.patch’ saved [175138/175138]

 -> Skipping patch %s...
         (unavailable for this kernel version)
 -> Applying TT patch
 -> Skipping patch %s...
         (unavailable for this kernel version)

Using your suggested "bugfix patch"

**Comment by nutterpc** [comment]
I've had great success on my workstation with Cacule, so when i heard the dev behind it made TT, i was keen to see how it went on my machine:

Lenovo Thinkstation C30 (Dual Xeon 6C/12T Xeon) - Total of 12C/24T
32Gb RAM
nVidia Quadro K2200 4Gb

Does plenty good enough for me for now :) later this year I'm upgrading to the 12C/24T E5 Xeons & 64Gb RAM. Will be a beast

**Comment by nutterpc** [comment]
Sadly it didn't build, failed right at the end. Just went through the basic configs and then left out menuconfig, it gave me this as it was finishing:

  LD      .tmp_vmlinux.kallsyms1
ld: kernel/sched/core.o: in function `sched_init':
(.init.text+0x4f0): undefined reference to `load_balance_mask'
ld: (.init.text+0x566): undefined reference to `select_idle_mask'
make[3]: *** [Makefile:1155: vmlinux] Error 1
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1539: deb-pkg] Error 2
make clean

Ah well, I'll stick to bmq for now :)

**Comment by Tk-Glitch** [comment]
Looks like the tt patchset upstream rebase is incomplete. I've had to modify Project C patchset a bit for pds and bmq not to hit that specific compilation error on 5.18. I might need to backport those to 5.17 :frog:

**Comment by Tk-Glitch** [comment]
Since this isn't a patch we offer ourselves and 5.17 has been EOL'd for some time now, closing.
