### ISSUE TITLE
[Feature request] Add Cachy Linux CPU Scheduler.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/linux-tkg#53]
https://www.phoronix.com/scan.php?page=news_item&px=Cachy-Linux-Scheduler

Cachy Is The Latest Effort To Provide A Better Linux CPU Scheduler.

**Comment by AdelKS** [comment]
Interesting, the dev seems to be trying it for Overwatch on his vid. It seems that it's still at its beginnings ? Have you given it a try ?

**Comment by brenix** [comment]
I applied this as a user patch atop the other tkg patches as a test and it seems to be working well for both desktop responsiveness and gaming. I definitely notice the slight differences in comparison to other schedulers. Having this as another scheduler option would be a nice to have!

**Comment by Tk-Glitch** [comment]
I'm not impressed by Cachy so far, compared to BMQ/PDS/MuQSS. I'm okay adding it as a community patch for sure :)

**Comment by Tk-Glitch** [comment]
Added for 5.8.y with https://github.com/Frogging-Family/community-patches/commit/253417450e507f49790cbea17f077d497c1e45a0

**Comment by Kerrung** [comment]
How do I enable Cachy in customization.cfg ?

**Comment by Tk-Glitch** [comment]
@Kerrung Add `cachy-5.8.3.mypatch` to `_community_patches=""` in your kernel 5.8 config, then select CFS when building.
