### ISSUE TITLE
5.18-tkg-cacule hangs on boot

### ISSUE THREAD

**Issue by undeadbydawn** [Frogging-Family/linux-tkg#531]
tested on 5.18.0 and 5.18.1. Boot hangs on Loading initial ramdisk

I'm using greysky zen3 (5600X) optimisation, all other options at config default
kernel functions perfectly using cfs

**Comment by OneOfOne** [comment]
I can confirm.

**Comment by Tk-Glitch** [comment]
It's a specific issue with cacule. Since we're not providing the patchset, we'll disable explicit support for it in the 5.18 submenu while waiting for a fix upstream.

**Comment by ptr1337** [comment]
Yes, cacule is currently broken. Checking for a fix.

**Comment by undeadbydawn** [comment]
Cool. I'm currently testing TT, which is working perfectly - so thanks for adding that option

**Comment by undeadbydawn** [comment]
New updated patch still won't launch.
I've mentioned this on the patch thread, posting here for the record

**Comment by ptr1337** [comment]
> New updated patch still won't launch. I've mentioned this on the patch thread, posting here for the record
I did compiled linux-cachyos-cacule cacule-rdb cacule, and every kernel is booting.

Patches which were used can be found here:
https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos-cacule/PKGBUILD#L169

If youre on arch, you can add the keyring of the cachyos repo and then just download the kernel, install and test it. I got several from users that its fine now.
Also I do personally currently run cacule:

```❯ uname -a
Linux ptr1337-cachyos 5.18.1-4-cachyos-cacule-lto #1 SMP PREEMPT_DYNAMIC Thu, 02 Jun 2022 05:07:32 +0000 x86_64 GNU/Linux```

regards.

**Comment by ptr1337** [comment]
Its fixed. I did not watched at the commit to the correct kernel patch link, missed to update the cacule-scheduler repo and just had in my kernel-patches repo updates.
https://github.com/CachyOS/cacule-cpu-scheduler/commit/6430b698ef233ee6df205ae509d8a9bc5099c99b

**Comment by undeadbydawn** [comment]
> Its fixed. I did not watched at the commit to the correct kernel patch link, missed to update the cacule-scheduler repo and just had in my kernel-patches repo updates. [CachyOS/cacule-cpu-scheduler@6430b69](https://github.com/CachyOS/cacule-cpu-scheduler/commit/6430b698ef233ee6df205ae509d8a9bc5099c99b)

Confirmed. Kernel now launches.
Closing issue
