### ISSUE TITLE
CentOS 7 build?

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/linux-tkg#536]
not really a bug. more like a question. is it possible to build this kernel for centos 7? when i use fendora for the selection i get the following

Use ACS override patch?
https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Bypassing_the_IOMMU_groups_.28ACS_override_patch.29
    > N/y : n
 -> Patching Fsync support

Enable android modules for use with Anbox?
https://github.com/anbox/anbox
    > N/y : n
linux-tkg-config/prepare: line 1420: mapfile: -d: invalid option
mapfile: usage: mapfile [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]
 -> exit cleanup done

is there something special i need to do? this is a fresh install. on a kvm.

 i wanted to test this kernel out on my kernel out on my clearos gateway/router that is centos 7 based.

any help would be greatful..

thanks.

**Comment by AdelKS** [comment]
Given that the router is running Ancient os 7 xD, probably `mapfile` didn't use to have same CLI interface, you can workaround that by setting `_config_fragments="false"` in the `customization.cfg` file.  You fixed the issue you had with git being too old ? Hopefully you can build it with this.

**Comment by rchris494** [comment]
yes. i realized that git way way to old. so i manually upgraded it. along with gcc. trying to build with an old system is almost not worth the effort. everything is so far out of date i'm surprised anything even works. i will try that config you mentioned later today.

**Comment by rchris494** [comment]
thanks for the help. that worked, but there is so many other things that are missing to get the kernel to install. it's like trying to get windows 10 software to install on windows 3.1. i was hoping for a little bit better driver selection for this stupid r8125b network card. along with tkg performance. i will probably have to edit the .config file and remove stuff i don't need.
