### ISSUE TITLE
anbox modules

### ISSUE THREAD

**Issue by logan001** [Frogging-Family/linux-tkg#537]
Archlinux, kernel 5.18.2 compiles fine but waydroid services fail to load ashmem modules. with 5.17 it works

does kvm_amd disable to start on boot has anything to do with anbox? i can load it without any problem manually but it stop to autostart on boot around the time i started to try anbox (5.17.8 or something)

**Comment by Zeioth** [comment]
I'm using waydroid on 5.18.2, which requires the anbox modules. Very likely it's not tkg related.

What's the specific error you are finding? On my end I had to edit '/var/lib/waydroid/waydroid_base.prop' with 'ro.hardware.gralloc=default' and that made it work (cuz my 6700XT gpu is not supported yet).

**Comment by Edu4rdSHL** [comment]
> Archlinux, kernel 5.18.2 compiles fine but waydroid services fail to load ashmem modules. with 5.17 it works
> 
> does kvm_amd disable to start on boot has anything to do with anbox? i can load it without any problem manually but it stop to autostart on boot around the time i started to try anbox (5.17.8 or something)

ashmem was removed **from upstream kernel**, use memfd.

**Comment by logan001** [comment]
i see.  thank you
