### ISSUE TITLE
Debian build fail due debian/certs/debian-uefi-certs.pem

### ISSUE THREAD

**Issue by iWeaker4you** [Frogging-Family/linux-tkg#54]
When I compile it I get that problem, but in my experience, it is only leaving empty
CONFIG_SYSTEM_TRUSTED_KEYS = ""
But whenever I leave it empty both in the .config, .oldconfig and when compiling, that field is filled in again with "debian / certs / debian-uefi-certs.pem"
and does not allow to finish your compilation.

**Comment by AdelKS** [comment]
I haven't tried any Debian based distro other than Ubuntu. Do you have enough knowledge to fix this and PR a change ?

I have found this reference: https://kernel-team.pages.debian.net/kernel-handbook/ch-common-tasks.html#s-common-building

> you reuse a Debian kernel config file, you may need to disable module signing (scripts/config --disable MODULE_SIG) or enable signing with an ephemeral key (scripts/config --set-str MODULE_SIG_KEY certs/signing_key.pem).

**Comment by iWeaker4you** [comment]
@AdelKS I could already compile it, I had to empty it again just when it was filled again and before the necessary packages were created for compilation, I do not understand why it is filled, if before executing install.sh I empty them, and when executing it it is filled, I don't understand if install.sh process downloads it again.

**Comment by AdelKS** [comment]
I understand better now. It is filled again because `install.sh` resets the Linux kernel sources then copies the `.config` file from the kernel version you are currently running, which has that variable filled. It is possible to change that yes, though do you have any idea why it's not working? Since Debian has that filled by default it seems then.

**Comment by iWeaker4you** [comment]
@AdelKS  I already found a solution, in a moment I apply a PR to solve it
