### ISSUE TITLE
Bcachefs patch didn't get applied on version 5.17 and 5.18. Also get Error on 5.15

### ISSUE THREAD

**Issue by neptalactone** [Frogging-Family/linux-tkg#542]
- I'm using Arch Linux as the base OS
- I pick some configuration on customization.cfg, especially the support for bcachefs.
- In the shell output of applying patches, i notice it didn't apply bcachefs patch. i tried it on both version 5.17 and 5.18
- Then i decided to try kernel version 5.15. In there i noticed bcachefs patch got applied but after choosing ticks option, it throws and error and said i can see on logs/prepare.log.txt.
    -   "An error was encountered applying patches. It was logged to the prepare.log.txt file."
- This is the line that said the error on bcachefs:
```
 ### Applying 0008-5.15-bcachefs.patch... ###
patching file block/bio.c
Hunk #2 FAILED at 1284.
Hunk #3 succeeded at 1370 (offset 4 lines).
Hunk #4 succeeded at 1430 (offset 4 lines).
1 out of 4 hunks FAILED -- saving rejects to file block/bio.c.rej
patching file block/blk-core.c
Hunk #1 succeeded at 215 (offset 1 line).
patching file drivers/block/loop.c
Hunk #1 succeeded at 1405 (offset -7 lines).
patching file drivers/md/bcache/Kconfig
patching file drivers/md/bcache/Makefile
patching file drivers/md/bcache/bcache.h
patching file drivers/md/bcache/super.c
Hunk #1 succeeded at 2911 (offset 1 line).
patching file drivers/md/bcache/util.h
```
- I then tried using kernel version 5.10, all went smoothly. the kernel successfully build, and after adding 'bcachefs' to mkinitcpio.conf according to bcachefs-tools-git package on aur, it didn't give any error, i can boot to the kernel just fine, and i can create and mount partition with bcachefs.

**Comment by ptr1337** [comment]
If tkg will merge it then probably, if not I mean into the userpatches.
I dont use linux-tkg personally but should work

**Comment by neptalactone** [comment]
Ah i see, i still want to try it tho, how i get to use it as userpatch?

**Comment by neptalactone** [comment]
Ah, i see, didn't see it before. Thank you very much, I'll try it
