### ISSUE TITLE
==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.

### ISSUE THREAD

**Issue by JoneKone** [Frogging-Family/linux-tkg#547]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?
 Ubuntu 20.04
 - A clear and concise description of what the bug is.
 Error
 - Attach the contents of your logs folder by drag & dropping each file into this message.
 
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9019102/prepare.log.txt)

```
2022-06-30 13:49:58 (8,05 MB/s) - ‘/home/jonekone/git/linux-tkg/more-uarches-for-kernel-5.17%2B.patch’ saved [25738/25738]

 -> Applying graysky's cpu opts patch
 -> Applying clear linux patches
 -> Applying glitched base patch
 -> Applying misc additions patch
 ==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.
 -> Applying patches for WRITE_WATCH support in Wine
 -> Applying patches for WRITE_WATCH support in Wine
 -> Applying PDS base patch
 -> Applying prjc PDS/BMQ agressive ondemand governor patch
 -> Applying Glitched PDS patch
 -> Using archlinux's default config file for kernel 5.18
 -> Using 4ms round robin interval
 -> Patching Fsync support
 -> Setting config
```

**Comment by Tk-Glitch** [comment]
This was fixed with https://github.com/Frogging-Family/linux-tkg/commit/aa672987b2daa8f915ac93aeb430eb8cd3408487
Please run `git pull` in your linux-tkg dir to get the update.
