### ISSUE TITLE
PKGBUILD: line 890: schedtool: command not found

### ISSUE THREAD

**Issue by spinktvis** [Frogging-Family/linux-tkg#549]
Seems a make dependency is not declared in the pkgbuild and it is thus complaining about the missing schedtool during build.

This is on Arch Linux.

**Comment by AdelKS** [comment]
Hello, thanks for your report. This is intended, see https://github.com/Frogging-Family/linux-tkg/issues/398. But maybe we can hide this error message so everyone is happy :thinking:

**Comment by spinktvis** [comment]
Thanks for the quick reply, closing this since it's known.
