### ISSUE TITLE
Game freezing under Cacule

### ISSUE THREAD

**Issue by undeadbydawn** [Frogging-Family/linux-tkg#558]
This not exhaustively tested:
I've had horrendous stuttering with CacULE 5.18.4 & 5, mostly in Stray. Full 5-second pauses in action. I also had a couple of hard crashes and my desktop just refuse to appear after quitting.
Tried with pds, no issues at all. Perfect performance
5600X/5700XT, all options as standard

**Comment by Tk-Glitch** [comment]
That's typically why I'll never use CacULE. I'm not a fan of its performance and I prefer plain CFS to it in all cases. I'm using PDS as my main scheduler btw :frog:

**Comment by B3HOID** [comment]
> This not exhaustively tested: I've had horrendous stuttering with CacULE 5.18.4 & 5, mostly in Stray. Full 5-second pauses in action. I also had a couple of hard crashes and my desktop just refuse to appear after quitting. Tried with pds, no issues at all. Perfect performance 5600X/5700XT, all options as standard

Have you checked whether RDB is enabled or not?

Also this is very weird as the CacULE patch doesn't change all that much. Did CFS receive any changes on 5.18?

**Comment by ptr1337** [comment]
@B3HOID 

Actually I do just adjust the patch to the kernel version, but that is it. It does not get changes in it function.

Actually I cant report such issue's as he is reporting, even with different workloads, games, ... . I do also run a zen3 5900x, so there should be not much difference.
For some people it runs well, and for some maybe not. 

The CFS changed where not big with 5.18, and will be also not with 5.19.

**Comment by undeadbydawn** [comment]
> > This not exhaustively tested: I've had horrendous stuttering with CacULE 5.18.4 & 5, mostly in Stray. Full 5-second pauses in action. I also had a couple of hard crashes and my desktop just refuse to appear after quitting. Tried with pds, no issues at all. Perfect performance 5600X/5700XT, all options as standard
> 
> Have you checked whether RDB is enabled or not? (Should be disabled)
> 
> Also this is very weird as the CacULE patch doesn't change all that much through each kernel version (it merely gets resynced/ported). Did CFS receive any changes on 5.18?

Yes. RDB was disabled as standard at my request, funnily enough.

**Comment by undeadbydawn** [comment]
> That's typically why I'll never use CacULE. I'm not a fan of its performance and I prefer plain CFS to it in all cases. I'm using PDS as my main scheduler btw frog

I'm really liking pds now. The issues I used to have with it have vanished, so it's all sunshine & roses

**Comment by undeadbydawn** [comment]
> @B3HOID
> 
> Actually I do just adjust the patch to the kernel version, but that is it. It does not get changes in it function.
> 
> Actually I cant report such issue's as he is reporting, even with different workloads, games, ... . I do also run a zen3 5900x, so there should be not much difference. For some people it runs well, and for some maybe not.
> 
> The CFS changed where not big with 5.18, and will be also not with 5.19.

it's no longer actively developed and has broken a few times recently, so I'm moving on as of now and won't be trying it again. It's cool though as pds is working just fine
