### ISSUE TITLE
Various warnings: vmlinux.o: warning: objtool: 

### ISSUE THREAD

**Issue by spinktvis** [Frogging-Family/linux-tkg#563]
Not even sure if this is a real issue, but better be safe. When compiling the latest kernel, 5.19, on Arch, the following warnings are displayed;

```
vmlinux.o: warning: objtool: entry_SYSCALL_compat+0x0: ANNOTATE_NOENDBR on ENDBR
vmlinux.o: warning: objtool: sme_enable+0x82: unreachable instruction
vmlinux.o: warning: objtool: smack_inode_setsecurity.cold+0x11: relocation to !ENDBR: smack_inode_setsecurity+0x172
```

Never seen this before, is this something to be concerned about? My Google Fu didn't provide any adequate answers, hopefully somebody more knowledgeable can shed some light.

**Comment by Tk-Glitch** [comment]
It's just a result of finer warnings with GCC 12.1 afaik. It happens on a regular untouched build as well as current Arch kernel. Nothing to be too concerned about.

**Comment by spinktvis** [comment]
Learned something new, thank you for the insight, closing this.
