### ISSUE TITLE
Elan trackpad not working

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [Frogging-Family/linux-tkg#566]
**Describe the bug**
 - Which OS do you encounter the bug on?

Archlinux

my trackpad doesn't work and is not detected even in /proc/bus/input/devices, i tried to disable every option i can in customisazion.cfg. i was able to reproduce the bug on 2 amd laptop, but not on the intel one i tried(i don't know the brand of the intel laptop's trackpad) 

- Attach the contents of your logs folder by drag & dropping each file into this message.

[dmesg.txt](https://github.com/Frogging-Family/linux-tkg/files/9277100/dmesg.txt)

**Comment by Tk-Glitch** [comment]
That's not something you can fix through the .cfg, it's a defconfig issue. If that trackpad works on regular Arch kernel, the driver is likely disabled in there and needs to be enabled. I just updated our defconfig with Arch's 5.19 in testing repos, that might fix your issue.

https://github.com/Frogging-Family/linux-tkg/commit/8dd345ff84aba0ab0c51d29985636a58effc0c36

**Comment by Tk-Glitch** [comment]
There could also be a regression with 5.19 but let's consider that's not it :frog:

**Comment by Marc-Pierre-Barbier** [comment]
thanks im going to try that. and if it doesn't work i will also try with 5.18.16

**Comment by Marc-Pierre-Barbier** [comment]
It worked thanks :+1:
