### ISSUE TITLE
5.15 "Applying TT Patch Error"

### ISSUE THREAD

**Issue by compicat** [Frogging-Family/linux-tkg#568]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug** 
I am trying to compile 5.15-tkg kernel with TT scheduler to use "High Hz Patch". As you can see below, it is giving error during applying TT patch. I ve added "prepare log". It is adding "TT high Hz Patch" without issue. 
 
- Which OS do you encounter the bug on?
Manjaro

 - A clear and concise description of what the bug is.
 As an addition to description, this is is just happening at 5.15 compiling. I ve handled 5.19 TT compiling without an issue.
 
- Attach the contents of your logs folder by drag & dropping each file into this message.

[a.txt](https://github.com/Frogging-Family/linux-tkg/files/9311524/a.txt)

[x.txt](https://github.com/Frogging-Family/linux-tkg/files/9311525/x.txt)

**Comment by Tk-Glitch** [comment]
Unlike for PDS/BMQ and legacy schedulers, we are not providing TT/CacULE patches. Those are offered by https://github.com/ptr1337/kernel-patches and downloaded at build time from their repo. @ptr1337 may want to update the patchsets for current 5.15.y. Else I'll simply remove support for TT on 5.15.

**Comment by compicat** [comment]
Thanks for detailed reply.

**Comment by Tk-Glitch** [comment]
> Thanks for detailed reply.

You're welcome!

**Comment by ptr1337** [comment]
I can take a watch. So far I know does @hamadmarri wanted to support LTS version, so maybe he is doing it. But I think he dont have much time right now

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/blob/master/5.15/TT/0001-tt-5.15.patch

**Comment by compicat** [comment]
> https://github.com/CachyOS/kernel-patches/blob/master/5.15/TT/0001-tt-5.15.patch

It is working like a charm. Thank you. Is it possible a fix for this community patch too?

https://github.com/Frogging-Family/community-patches/blob/afaf2b99e59b1325f543ee38038c2ee88812f32b/linux515-tkg/lru_5.15.mypatch

**Comment by ptr1337** [comment]
> > https://github.com/CachyOS/kernel-patches/blob/master/5.15/TT/0001-tt-5.15.patch
> 
> It is working like a charm. Thank you. Is it possible a fix for this community patch too?
> 
> https://github.com/Frogging-Family/community-patches/blob/afaf2b99e59b1325f543ee38038c2ee88812f32b/linux515-tkg/lru_5.15.mypatch

https://github.com/CachyOS/kernel-patches/blob/43f2ca41ac2afd736149bb8c76cf4d73ba1a8ae3/5.15/lru_5.15.patch

Did added one, patches fine on the latst 5.10.60
Ill PR is later to the community patches

**Comment by compicat** [comment]
> > > https://github.com/CachyOS/kernel-patches/blob/master/5.15/TT/0001-tt-5.15.patch
> > 
> > 
> > It is working like a charm. Thank you. Is it possible a fix for this community patch too?
> > https://github.com/Frogging-Family/community-patches/blob/afaf2b99e59b1325f543ee38038c2ee88812f32b/linux515-tkg/lru_5.15.mypatch
> 
> https://github.com/CachyOS/kernel-patches/blob/43f2ca41ac2afd736149bb8c76cf4d73ba1a8ae3/5.15/lru_5.15.patch
> 
> Did added one, patches fine on the latst 5.10.60 Ill PR is later to the community patches

amazing, thank you. handling by editing prepare. Thanks again for prompt reply and actions.

**Comment by ptr1337** [comment]
@Tk-Glitch 

Would you may update the link for tt ?

**Comment by Tk-Glitch** [comment]
Whoops. Done.

**Comment by compicat** [comment]
> Whoops. Done.

Community patch link is updated, but fixed TT patch is still not updated in prepare if i am not mistaken. Thanks in advance.

**Comment by Tk-Glitch** [comment]
Forgot to push. Fixed.
