### ISSUE TITLE
PDS/BMQ on Kernels 5.18.18 and 5.19.2 fail

### ISSUE THREAD

**Issue by jhu54** [Frogging-Family/linux-tkg#573]
Using Linux Mint 21, gcc 11.2 and 5.19.1-tkg-bmq kernel.
Successfully compile the 6.0-rc1 kernel with cfs scheduler. 5.19.2 compiles using the cfs scheduler. If I select either bmq or pds, on either 5.18.18 or 5.19.2, compilation fails at the same spot:

  CC [M]  fs/xfs/scrub/agheader_repair.o
  CC [M]  fs/xfs/scrub/bitmap.o
  CC [M]  fs/xfs/scrub/repair.o
  AR      fs/built-in.a
  LD [M]  fs/xfs/xfs.o
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
make: *** [Makefile:1555: deb-pkg] Error 2
make clean
  CLEAN   arch/x86/crypto
  CLEAN   arch/x86/entry/vdso
  CLEAN   arch/x86/purgatory
  CLEAN   arch/x86/tools
  CLEAN   arch/x86/realmode/rm
  CLEAN   arch/x86/kernel/cpu

Have tried all other option combinations to rule them out, it just selection of bmq/pds leads to the same error, same spot on both kernels. Have tried compiling on 5.15 stock Mint kernel and using _configfile="running-kernel" with the same results.

**Comment by gh0stxx** [comment]
I'm getting the same problem. I'm not on the system right now but from memory it was complaining about missing some includes in ../../fs/

**Comment by ptr1337** [comment]
Well, @sirlujan did a fast fix for the patch.
Compiled well with linux-cachyos.
Check it out here: https://github.com/CachyOS/kernel-patches/blob/master/5.19/sched/0001-prjc.patch

**Comment by robson-66** [comment]
> Well, @sirlujan did a fast fix for the patch. Compiled well with linux-cachyos. Check it out here: https://github.com/CachyOS/kernel-patches/blob/master/5.19/sched/0001-prjc.patch

Thanks a lot it solves the problem, and the construction is going well.

**Comment by veganvelociraptor** [comment]
I can confirm the same error.

**Comment by TechXero** [comment]
How do I include patch ?

**Comment by sirlucjan** [comment]
> I can confirm the same error.

Use the patch from CachyOS. It should work, as it has already been confirmed. We are now testing with @ptr1337 an improved version of this patch and if it works, we will send you the link. 



> How do I include patch ? I dunno how sorry

Forgive my impertinence, but as the creator of the Arch fork, how can you not know this? How do you develop the system? I don't mean to insult you, I'm just consumed with curiosity about your working methodology.

**Comment by TechXero** [comment]
@sirlucjan 

> Forgive my impertinence, but as the creator of the Arch fork, how can you not know this? How do you develop the system? I don't mean to insult you, I'm just consumed with curiosity about your working methodology.

Well I am not a developer at all. But here is not the place to argue that. I build my own fork with existing scripts with my own tweaks. You don't have to be a dev to do that.. And I been doing it for almost 2 years.. 

E.O.D ... Now how to apply patch ?

**Comment by robson-66** [comment]
Go to the above page, select raw display, copy and paste to `0009-prjc_v5.19-r0.patch` and you also need to add` SKIP` in the checksums for the patch.

**Comment by TechXero** [comment]
> 0009-prjc_v5.19-r0.patch

There is no `0009-prjc_v5.19-r0.patch` I did search xD

**Comment by sirlucjan** [comment]
Here you are: https://github.com/CachyOS/kernel-patches/tree/master/5.19/sched
I said I didn't want to argue, I was just plain curious. No worries, I'm not going to criticize. 
@robson-66 
Adding SKIP is not a very good idea. It is better to use the command ```updpkgsums```

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/5.19/0009-prjc_v5.19-r0.patch

This patch you need to change locally...

**Comment by TechXero** [comment]
> May its better until TKG will update it as soon there is a fix from upstream prjc.

Building successfully now thanks.. Will also wait for upstream fix ;)

**Comment by gh0stxx** [comment]
Thanks it worked, just replaced contents of 0009-prjc_v5.19-r0.patch with the updated patch and just manually changed the sha to the new file in pkgbuild in the 519 section

**Comment by sirlucjan** [comment]
We will update the prjc patch soon - it will include a full rebase with changes in 5.19.2 and some new features - including support for MGLRU. If anyone is willing, I will share the link earlier.

**Comment by robson-66** [comment]
>  @robson-66 Adding SKIP is not a very good idea. It is better to use the command `updpkgsums`

Yes, I know using `SKIP` is not the best idea, but seeing the OP experience it is the best solution for him.

**Comment by jhu54** [comment]
Thx - the patch applied in git here has allowed compilation with 5.19.2 kernel and bmq/pds options selected. Will try the kernel to make sure it boots and there are no further issues before closing this.
Again thanks for the help from everyone here.
