### ISSUE TITLE
5.19.1 Build error

### ISSUE THREAD

**Issue by TechXero** [Frogging-Family/linux-tkg#574]
**Describe the bug**
Getting error on Arch based distro (my Own)
Here's my [My Custom Config](https://notes.xerolinux.xyz/?3a4f828c264f6001#9oDaT3uWsn3FQMfjZ9MdJkYZiy9YVBVM6HASFcGgque8)

I get this error 
```
kernel/sched/alt_core.c:46:10: fatal error: ../../fs/io-wq.h: No such file or directory
```

**Comment by ptr1337** [comment]
See here:
https://github.com/Frogging-Family/linux-tkg/issues/573#issuecomment-1219282453

Should fix it.
