### ISSUE TITLE
compiler errors with gcc and clang, default options

### ISSUE THREAD

**Issue by jayarmstrong** [Frogging-Family/linux-tkg#576]
Probably a novice error but I can't solve it.

If I choose gcc, I get the following errors:
```
 -> Configuration done.
 -> Enabled ccache
 -> Building kernel RPM packages
  SYNC    include/config/auto.conf.cmd
gcc: unknown compiler
scripts/Kconfig.include:44: Sorry, this compiler is not supported.
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:629: syncconfig] Error 2
make: *** [Makefile:731: include/config/auto.conf.cmd] Error 2
make: *** [include/config/auto.conf.cmd] Deleting file 'include/generated/autoconf.h'
  SYNC    include/config/auto.conf.cmd
gcc: unknown compiler
scripts/Kconfig.include:44: Sorry, this compiler is not supported.
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:629: syncconfig] Error 2
make: *** [Makefile:731: include/config/auto.conf.cmd] Error 2
 -> exit cleanup done
```
If I choose clang, I get:
```
 -> Configuration done.
 -> Enabled ccache
 -> Building kernel RPM packages
  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/basic/fixdep
ccache: error: SLOPPINESS: unknown sloppiness: "locale"
make[2]: *** [scripts/Makefile.host:95: scripts/basic/fixdep] Error 1
make[1]: *** [Makefile:565: scripts_basic] Error 2
make: *** [Makefile:731: include/config/auto.conf.cmd] Error 2
  SYNC    include/config/auto.conf.cmd
  HOSTCC  scripts/basic/fixdep
ccache: error: SLOPPINESS: unknown sloppiness: "locale"
make[2]: *** [scripts/Makefile.host:95: scripts/basic/fixdep] Error 1
make[1]: *** [Makefile:565: scripts_basic] Error 2
make: *** [Makefile:731: include/config/auto.conf.cmd] Error 2
 -> exit cleanup done
```

openSUSE Leap 15.4
gcc 11 and 12
clang 13 and 14
default config (5.19.2, etc)

[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9389507/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9389508/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9389509/system-info.txt)

**Comment by ptr1337** [comment]
Im not sure, but may try to disable ccache

**Comment by jayarmstrong** [comment]
> Im not sure, but may try to disable ccache

After disabling it in the shell with `export CCACHE_DISABLE=1` the script still calls it.

What about disabling the gcc compiler check? I'm modifying the scripts in /linux-src-git/scripts/ but my edits are overwritten every time I run the install.

**Comment by jayarmstrong** [comment]
I was able to resolve the clang errors by adding `sloppiness = file_macro` option in /root/.ccache/ccache.conf and installing `lld`.

This results in the same "unknown compiler" error but with clang now:
```
-> Configuration done.
 -> Enabled ccache
 -> Building kernel RPM packages
  SYNC    include/config/auto.conf.cmd
clang: unknown compiler
scripts/Kconfig.include:44: Sorry, this compiler is not supported.
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[1]: *** [Makefile:629: syncconfig] Error 2
make: *** [Makefile:731: include/config/auto.conf.cmd] Error 2
```

**Comment by Tk-Glitch** [comment]
What's the output of `gcc -v`?
Also you'll probably want to run `sudo zypper install -t pattern devel_basis` to get basic essential tools to build stuff if not done already.

**Comment by AdelKS** [comment]
Have you tried putting `_noccache="true"` in the `customization.cfg` file instead? This definitely looks cache related.

**Comment by jayarmstrong** [comment]
> Have you tried putting `_noccache="true"` in the `customization.cfg` file instead? This definitely looks cache related.

That fixed the error and got it compiling. Thank you!
