### ISSUE TITLE
Arch 5.19.3 build failure

### ISSUE THREAD

**Issue by phoropter** [Frogging-Family/linux-tkg#577]
**Describe the bug**
Which OS do you encounter the bug on?
 -  Arch Linux

 - When attempting to build with modprobe-db for 5.19.3 I get the following error:
```
LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
AR      drivers/gpu/built-in.a
AR      drivers/built-in.a
GEN     .version
CHK     include/generated/compile.h
LD      vmlinux.o
vmlinux.o: warning: objtool: entry_SYSCALL_compat+0x0: ANNOTATE_NOENDBR on ENDBR
vmlinux.o: warning: objtool: sme_enable+0x82: unreachable instruction
vmlinux.o: warning: objtool: smack_inode_setsecurity.cold+0x11: relocation to !ENDBR: smack_inode_setsecurity+0x172
MODPOST vmlinux.symvers
MODINFO modules.builtin.modinfo
GEN     modules.builtin
CC      .vmlinux.export.o
LD      .tmp_vmlinux.btf
BTF     .btf.vmlinux.bin.o
LD      .tmp_vmlinux.kallsyms1
KSYMS   .tmp_vmlinux.kallsyms1.S
AS      .tmp_vmlinux.kallsyms1.S
LD      .tmp_vmlinux.kallsyms2
KSYMS   .tmp_vmlinux.kallsyms2.S
AS      .tmp_vmlinux.kallsyms2.S
LD      vmlinux
BTFIDS  vmlinux
FAILED: load BTF from vmlinux: Invalid argument
make: *** [Makefile:1170: vmlinux] Error 255
make: *** Deleting file 'vmlinux'
==> ERROR: A failure occurred in build().
```
[Here is my customization.cfg](https://github.com/Frogging-Family/linux-tkg/files/9419327/customization.cfg.txt)

I had no issues building 5.19.2 with the same set up. Any insight as to how to solve this?

**Comment by phoropter** [comment]
Never mind. Saw some similar issues after searching around that suggested memory running out might be an issue, so changed my `/etc/makepkg.conf` to build in `/tmp` without success, then commented the option out and ran the build again with success.

**Comment by Tk-Glitch** [comment]
It will need 22-24GB free to build in `/tmp`, and it doesn't like using swap somehow. So unless you have 32GB and not too much going on eating RAM, it's best to build on-disk.

**Comment by abrasmag3** [comment]
I have this issue with 5.19.16, with near identical config, but it doesn't build, either in /tmp (which makes sense, i don't have enough ram) or on disk in the local repo.

Could you give any more information on how you solved this?

**Comment by phoropter** [comment]
I couldn't build for 5.19.16 either, so i just moved to 6 and that built fine.

**Comment by Tk-Glitch** [comment]
Downgrade pahole to 1.23. 1.24 broke building lower than 6.0.

**Comment by ptr1337** [comment]
> Downgrade pahole to 1.23. 1.24 broke building lower than 6.0.

How did arch built then the linux-lts, it was built after the upgrade of pahole?
