### ISSUE TITLE
Wrong git branch used for 5.9RC

### ISSUE THREAD

**Issue by Sjoeborg** [Frogging-Family/linux-tkg#58]
The RC for 5.9 lives in branch "master" https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
This causes an error when the script tries to clone the branch linux-5.9.y
The install script should clone the master branch if the user wants to compile the RC

Line 114 in the install script reads
`git clone --branch linux-$_basekernel.y --single-branch --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git linux-${_basekernel}`

could be

`git clone --branch master --single-branch --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git linux-${_basekernel}`

**Comment by AdelKS** [comment]
Yes we are aware if that, the script is there when 5.9 gets released :)

To work, it needs some more work than just changing the branch, if you are willing to make the changes and test them out on Ubuntu, Fedora and Suse you are welcome!

**Comment by AdelKS** [comment]
@Tk-Glitch Why did you add the "Bug" label, is it because I don't like to see "Bug" as a label and thus implement a script that handles RC kernels ? xD

**Comment by Sjoeborg** [comment]
Sorry, I didn't add it explicitly. I think it got added as default. Thank
your for the answer anyhow!

**Comment by AdelKS** [comment]
Hello @Sjoeborg, 

The label hasn't been added by you, but by @Tk-Glitch :D 
For your issue, the other kernels works with install.sh. I may implement the script that handles rc kernels in the future :P

**Comment by Tk-Glitch** [comment]
@AdelKS Let's say it was more for me to see it better. It's technically a broken implementation, but since it's there in 5.9rc.. :frog: Don't get stressed out about it. If I'm happy with the centralization of linux-tkg it'll become necessary anyway so the fix for RCs might land at the same time. Tarballs aren't all that bad :stuck_out_tongue:

**Comment by AdelKS** [comment]
You are working on centralization ? :D 

You know what, I will implement the RC script. It will be the same for all RC versions.
