### ISSUE TITLE
failure occurred in build()

### ISSUE THREAD

**Issue by Co3co** [Frogging-Family/linux-tkg#581]
When trying to build the kernel with a custom config file (one that i made with menuconfig/xconfig), i get a build error. Right before the error, it tries to compile some `built-in.a` file. Here are some of the last few compilations when trying to build the kernel before it gave me an error:

```
  AR      mm/built-in.a
  AR      fs/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```

```
  LD [M]  crypto/crypto_simd.o
  AR      crypto/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```

```
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```

```
  AR      mm/built-in.a
  AR      fs/built-in.a
  LD [M]  fs/btrfs/btrfs.o
  CC      arch/x86/kernel/cpu/capflags.o
  AR      arch/x86/kernel/cpu/built-in.a
  AR      arch/x86/kernel/built-in.a
  AR      arch/x86/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```

```
  LD [M]  fs/btrfs/btrfs.o
  AR      fs/built-in.a
  CC      arch/x86/kernel/cpu/capflags.o
  AR      arch/x86/kernel/cpu/built-in.a
  AR      arch/x86/kernel/built-in.a
  AR      arch/x86/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...
```
I also got an error that didn't end on `*built-in.a`:
```
  CC [M]  net/mac80211/pm.o
  CC [M]  net/mac80211/rc80211_minstrel_ht.o
  CC [M]  net/mac80211/rc80211_minstrel_ht_debugfs.o
  LD [M]  net/mac80211/mac80211.o
==> ERROR: A failure occurred in build().
    Aborting...
```
Building the kernel works when i set `_configfile` to `running-kernel`, so i'm guessing it's caused by an option in my custom config, but i'm not sure. I tried redoing the entire config (and used xconfig instead of menuconfig), this time not disabling nearly as many options, but it still gives me a build error. I use Artix Linux.

Here's the output. Though, it doesn't seem very useful, as it didn't record the compile process.
[output.log](https://github.com/Frogging-Family/linux-tkg/files/9457512/output.log)

**Comment by Tk-Glitch** [comment]
The actual error happens earlier on. The exit error will only show up once all other threads are done with what they were doing when the error happened. If you have a hard time finding it in the output by yourself, please try to capture the whole terminal output to a file (and attach that if needed).

**Comment by Co3co** [comment]
Ah, i never watched the build process all the way through, so i never noticed the real error message. The error was caused by a redefinition of `flush_smp_call_function_queue()`, which i fixed by enabling `CONFIG_SMP`.
Thank you very much for your help, and sorry for creating a non-tkg-related issue.
