### ISSUE TITLE
Req: Change URL in PKGBUILD

### ISSUE THREAD

**Issue by xiota** [Frogging-Family/linux-tkg#586]
Currently the url points to kernel.org.  It should point here, to [github/Frogging-Family/linux-tkg](https://github.com/Frogging-Family/linux-tkg), which is the source of the patches.

**Comment by Tk-Glitch** [comment]
99.99% of the code you compile is still from kernel.org :frog:
A link to here could be added to pkgdesc I guess. Prebuilt are not offered by ourselves outside of here anyway, but yeah indeed, there's no way to get here through a package found randomly without an actual search.

**Comment by xiota** [comment]
> Prebuilt are not offered by ourselves outside of here anyway

[Chaotic-AUR](https://github.com/chaotic-aur/packages) is building this package.

> yeah indeed, there's no way to get here through a package found randomly without an actual search.

That's the issue.  It should be made easier to find the source.  Also, many (but maybe not all) Arch linux packages have the url pointing to the website or git repository responsible for the patches.  For instance, `extra/linux-zen`:
```
Repository      : extra
Name            : linux-zen
Version         : 5.19.7.zen2-1
Description     : The Linux ZEN kernel and modules
Architecture    : x86_64
URL             : https://github.com/zen-kernel/zen-kernel/commits/v5.19.7-zen2
Licenses        : GPL2
Groups          : None
Provides        : VIRTUALBOX-GUEST-MODULES  WIREGUARD-MODULE  KSMBD-MODULE  VHBA-MODULE  UKSMD-BUILTIN
Depends On      : coreutils  kmod  initramfs
Optional Deps   : wireless-regdb: to set the correct wireless channels of your country
                  linux-firmware: firmware images needed for some devices
Conflicts With  : None
Replaces        : None
Download Size   : 185.80 MiB
Installed Size  : 186.25 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Mon Sep 5 11:33:28 2022
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by Tk-Glitch** [comment]
However, the zen kernel offers a patched-up source, which isn't our case. Replacing the kernel.org URL by a frogging family github one would make things more confusing as we aren't under GPL2 license on our end, and you can totally build a vanilla kernel with our scripts. The solution that would make the most sense without being too confusing I guess is to add our URL to pkgdesc.
