### ISSUE TITLE
./install.sh: line 304: syntax error near unexpected token `schedtool'

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/linux-tkg#588]
**Describe the bug**
 - Which OS do you encounter the bug on? debain bookworm/sid
 - A clear and concise description of what the bug is.
 - schedtool is already the newest version (1.3.0-4)
 - the only thing i can think of is something changed in schedtool.

./install.sh: line 304: syntax error near unexpected token `schedtool'

 - Attach the contents of your logs folder by drag & dropping each file into this message.
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9532005/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9532007/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9532009/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9532011/system-info.txt)

**Comment by Tk-Glitch** [comment]
Looks like https://github.com/Frogging-Family/linux-tkg/issues/580
