### ISSUE TITLE
Void Linux - zlib not found

### ISSUE THREAD

**Issue by nwvh** [Frogging-Family/linux-tkg#589]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?
 - Void Linux
 - 
 - A clear and concise description of what the bug is.
 - The zlib tarball was not found
 - 
 - Attach the contents of your logs folder by drag & dropping each file into this message.
```
  http://www.zlib.net/zlib-1.2.11.tar.gz: Not Found
=> ERROR: zlib-1.2.11_4: failed to fetch zlib-1.2.11.tar.gz.
```
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

**Comment by Tk-Glitch** [comment]
See https://github.com/Frogging-Family/linux-tkg/issues/491

The template provided by `https://github.com/Hyper-KVM/void-packages/` is outdated, but the generic install will work.
