### ISSUE TITLE
Diffconfig pathing issue

### ISSUE THREAD

**Issue by jnines** [Frogging-Family/linux-tkg#602]
Running menuconfig/nconfig/xconfig, making a change, and trying to create a fragment fails with `/home/jason/.local/bin/git/tkg/linux-tkg/linux-tkg-config/prepare: line 1767: /home/jason/.local/bin/git/tkg/linux-tkg/scripts/diffconfig: No such file or directory
`.  That line is `"${prev_pwd}/scripts/diffconfig" -m "${prev_pwd}.config.orig" "${prev_pwd}/.config" > "$_diffconfig_name"`

I had to change it to `"${prev_pwd}/linux-src-git/scripts/diffconfig" -m "${prev_pwd}/linux-src-git/.config.orig" "${prev_pwd}/linux-src-git/.config" > "$_diffconfig_name"` to get it to work.  I didn't submit a PR as 1) I don't know if it's something weird on my end, I wiped/re-cloned the git, and 2)if it is an actual issue I'd guess there's possibly something somewhere else that needs to be changed

**Comment by AdelKS** [comment]
Ah yeah that's probably not on your end only, I assume you are in Arch.

**Comment by jnines** [comment]
Yes it is sorry for not mentioning that.

**Comment by AdelKS** [comment]
I think your change is correct, would you mind opening a PR with that ? :D
