### ISSUE TITLE
Winesync Issue

### ISSUE THREAD

**Issue by compicat** [Frogging-Family/linux-tkg#604]
Thanks for great work again. Winesync is unfortunately not working after last cli changes. Can you please check? It was working with state change before. My kernel is 5.15.69, it is not working with new compile of 5.15.70. Thanks in advance.

**Comment by AdelKS** [comment]
Hello, thanks for your kind message and report. Hopefully I'll be able to have a look at this this weekend:D

**Comment by Iglu47** [comment]
I submitted the required changes, should be fixed soon.

**Comment by compicat** [comment]
Thank you.

**Comment by compicat** [comment]
Thanks for great work again. Update about this, situation is still there at stagingwine-fsync-winefsync (fsync support was must for winesync for staging builds) trio. It was working before with wine-tkg-git staging builds. Now, it is only working with plain builds without fsync.

**Comment by Iglu47** [comment]
I can't repro. `wine-tkg-staging-fsync-git 7.18.r4.g0ea57a02-327` with fastsync was builded without problems. cfg and prepare.log would be helpful.
