### ISSUE TITLE
Kernel isnt installed after the install.sh script

### ISSUE THREAD

**Issue by Tuerpe** [Frogging-Family/linux-tkg#609]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?
 - A clear and concise description of what the bug is.
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

Hey,

its my first time building a kernel so it could be it is just my fault.

After compiling the kernel i got asked if i want to insatll it. I typed yes and after that the script said installation successfull.

I rebooted and didnt saw the kernel. Tried to install it manually (kernel, kernel-devel, kernel-headers) and this was the output:

Last metadata expiration check: 2:51:49 ago on Sat 01 Oct 2022 07:37:21 AM CEST.
Error: 
 Problem: problem with installed package kernel-devel-matched-5.19.11-200.fc36.x86_64
  - package kernel-devel-matched-5.19.11-200.fc36.x86_64 requires kernel-devel = 5.19.11-200.fc36, but none of the providers can be installed
  - package kernel-devel-matched-5.17.5-300.fc36.x86_64 requires kernel-devel = 5.17.5-300.fc36, but none of the providers can be installed
  - cannot install both kernel-devel-5.19.12_tkg_bmqtuerpe-1.x86_64 and kernel-devel-5.19.11-200.fc36.x86_64
  - cannot install both kernel-devel-5.19.12_tkg_bmqtuerpe-1.x86_64 and kernel-devel-5.17.5-300.fc36.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)

hostnamectl:
Icon name: computer-desktop
         Chassis: desktop 🖥
      Machine ID: 9a3fe95d51c44bc99c3294b5253bc62e
         Boot ID: 5f397ea47a57448b91eb49d04b3bf033
Operating System: Fedora Linux 36 (Workstation Edition)
     CPE OS Name: cpe:/o:fedoraproject:fedora:36
          Kernel: Linux 5.19.11-200.fc36.x86_64
    Architecture: x86-64
 Hardware Vendor: System manufacturer
  Hardware Model: System Product Name

It would be nice to know what the issue was, but mainly i wrote this for evaluating if it was my fault or if the script should get updated.

If you need any further information ill be happy to provide it.

Thx

**Comment by AdelKS** [comment]
Hello,

I took the time to figure out things: the package `kernel-headers` produced by our script isn't useful, so you can skip that. Also, to install them by hand, make sure that wildcards do not catch more packages than the tkg rpms. Tell me if that fixes your issue

**Comment by AdelKS** [comment]
While testing stuff in a Fedora VM, I see that you are hitting with this issue because your probably use Nvidia, I will see if I can do something so nvidia can be installed for official kernels without conflicting with ours.

**Comment by AdelKS** [comment]
Please try the PR #610 and confirm it solves your issue. Please delete the RPMS folder entirely first.

**Comment by Tuerpe** [comment]
Hey,
unfortunately i run into massive issues (or incompetence) with booting the kernel. got balckscreen, no tty sessions open, no ssh available, sometimes even screens didnt get signal. took me a whole day to revert it, because i tried to revert my settings but it didnt help. Treid different boot options because it was said that the nvidia drivers are the issue.
I followed this guide https://www.if-not-true-then-false.com/2015/fedora-nvidia-guide/?amp=1 but totally messed up.

But i dont think its tkg related.

So because i cant test it with the old kernel or my old setup i think the issue can be closed. If i try it in future i could relate to this and can give feedback but for now im fed up with trying my own kernels :D 

but thanks for taking the time to fix it

Greetings Tuerpe

**Comment by W3sG** [comment]
I recently got the exact same problem as described in the original post for this issue (and same as Issue #513) , after you already had applied PR #610. I tracked in down and it seems your patch 0013-fedora-rpm.patch is out of sync with the latest changes in the mkspec file that it modifies in the source tree, and so is not applying the entire patch. I created my own .mypatch file that I applied during the configuration, and the problem went away. 

I don't see how NVIDIA makes a difference here, it seems the RPMs should be failing to install on all Fedora, but I do happen to have NVIDIA proprietary drivers as akmod, which works fine.

Github is not letting me attach that file type even if it is .patch, so I'm pasting below. I could edit your patch file as a PR, but I don't know if you want the extra context lines in the diff that I am using, seems like either 1 or 3 lines could fail depending on what kind of changes mkspec makes next time. This is my custom diff that goes on top of yours, just adding the changes that did not get applied by git apply of 0013-fedora-rpm.patch. I can also post as a different issue if you want.

diff --git a/scripts/package/mkspec b/scripts/package/mkspec
index c6ba418..e819aba 100755
--- a/scripts/package/mkspec
+++ b/scripts/package/mkspec
@@ -39,7 +39,7 @@ EXCLUDES="$RCS_TAR_IGNORE --exclude=*vmlinux* --exclude=*.mod \
 #  $S: this line is enabled only when building source package
 #  $M: this line is enabled only when CONFIG_MODULES is enabled
 sed -e '/^DEL/d' -e 's/^\t*//' <<EOF
-	Name: kernel
+	Name: kernel
 	Summary: The Linux Kernel
 	Version: $__KERNELRELEASE
 	Release: $(cat .version 2>/dev/null || echo 1)
@@ -51,6 +51,7 @@ $S	Source: kernel-$__KERNELRELEASE.tar.gz
 	$PROVIDES_DRM
 	Provides: kernel = %{version}
 	Provides: kernel-uname-r = %{version}
+	Provides: installonlypkg(kernel) = %{version}
 	# $UTS_MACHINE as a fallback of _arch in case
 	# /usr/lib/rpm/platform/*/macros was not included.
 	%define _arch %{?_arch:$UTS_MACHINE}
@@ -63,8 +64,8 @@ $S	Source: kernel-$__KERNELRELEASE.tar.gz
 	%package headers
 	Summary: Header files for the Linux kernel for use by glibc
 	Group: Development/System
-	Obsoletes: kernel-headers
 	Provides: kernel-headers = %{version}
+	Provides: installonlypkg(kernel) = %{version}
 	%description headers
 	Kernel-headers includes the C header files that specify the interface
 	between the Linux kernel and userspace libraries and programs.  The
@@ -75,8 +76,11 @@ $S	Source: kernel-$__KERNELRELEASE.tar.gz
 $S$M	%package devel
 $S$M	Summary: Development package for building kernel modules to match the $__KERNELRELEASE kernel
 $S$M	Group: System Environment/Kernel
+$S$M	Provides: kernel-devel = %{version}
+$S$M	Provides: kernel-devel-uname-r = %{version}
+$S$M	Provides: installonlypkg(kernel) = %{version}
 $S$M	AutoReqProv: no
-$S$M	%description -n kernel-devel
+$S$M	%description devel
 $S$M	This package provides kernel headers and makefiles sufficient to build modules
 $S$M	against the $__KERNELRELEASE kernel package.
 $S$M

**Comment by AdelKS** [comment]
Hello, these issue should be fixed by now, at least after the recent commits, please reopen if the issue persists. I will be more reactive to fix them.
