### ISSUE TITLE
Build fail  5.8 Project C / PDS 

### ISSUE THREAD

**Issue by leucome** [Frogging-Family/linux-tkg#61]
Tried build kernel 5.8 Project C / PDS on Manjaro with option for Zen cpu and Fsync.   I get many error related to Numa and then it fail.

 LD [M]  drivers/gpu/drm/nouveau/nouveau.o
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.btf
ld: kernel/fork.o: in function `__put_task_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:754: undefined reference to `task_numa_free'
ld: kernel/fork.o: in function `free_signal_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:731: undefined reference to `sched_autogroup_exit'
ld: kernel/fork.o: in function `copy_signal':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:1607: undefined reference to `sched_autogroup_fork'
ld: kernel/fork.o: in function `free_signal_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:731: undefined reference to `sched_autogroup_exit'
ld: kernel/exit.o: in function `do_exit':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/exit.c:817: undefined reference to `sched_autogroup_exit_task'
ld: kernel/sys.o: in function `ksys_setsid':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/sys.c:1200: undefined reference to `sched_autogroup_create_attach'
ld: kernel/sched/alt_core.o: in function `perf_trace_sched_move_numa':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:494: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `perf_trace_sched_numa_pair_template':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: /mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `trace_event_raw_event_sched_move_numa':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:494: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `trace_event_raw_event_sched_numa_pair_template':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o:/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: more undefined references to `task_numa_group_id' follow
ld: mm/memory.o: in function `do_numa_page':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/memory.c:4100: undefined reference to `task_numa_fault'
ld: mm/mempolicy.o: in function `mpol_misplaced':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2538: undefined reference to `should_numa_migrate_memory'
ld: mm/mempolicy.o: in function `check_numabalancing_enable':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2772: undefined reference to `set_numabalancing_state'
ld: /mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2777: undefined reference to `set_numabalancing_state'
ld: mm/huge_memory.o: in function `do_huge_pmd_numa_page':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/huge_memory.c:1548: undefined reference to `task_numa_fault'
ld: fs/exec.o: in function `__do_execve_file':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/exec.c:1935: undefined reference to `task_numa_free'
ld: fs/proc/base.o: in function `sched_autogroup_show':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/base.c:1483: undefined reference to `proc_sched_autogroup_show_task'
ld: fs/proc/base.o: in function `sched_autogroup_write':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/base.c:1514: undefined reference to `proc_sched_autogroup_set_nice'
ld: fs/proc/array.o: in function `task_state':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/array.c:171: undefined reference to `task_numa_group_id'
  BTF     .btf.vmlinux.bin.o
tag__check_id_drift: subroutine_type id drift, core_id: 1127, btf_type_id: 1125, type_id_off: 0
libbpf: Unsupported BTF_KIND:0
btf_elf__encode: btf__new failed!
free(): double free detected in tcache 2
scripts/link-vmlinux.sh: line 137: 3932212 Aborted                 (core dumped) LLVM_OBJCOPY=${OBJCOPY} ${PAHOLE} -J ${1}
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
make: *** [Makefile:1139: vmlinux] Error 1
  DESCEND  objtool
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.btf
ld: kernel/fork.o: in function `__put_task_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:754: undefined reference to `task_numa_free'
ld: kernel/fork.o: in function `free_signal_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:731: undefined reference to `sched_autogroup_exit'
ld: kernel/fork.o: in function `copy_signal':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:1607: undefined reference to `sched_autogroup_fork'
ld: kernel/fork.o: in function `free_signal_struct':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/fork.c:731: undefined reference to `sched_autogroup_exit'
ld: kernel/exit.o: in function `do_exit':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/exit.c:817: undefined reference to `sched_autogroup_exit_task'
ld: kernel/sys.o: in function `ksys_setsid':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/kernel/sys.c:1200: undefined reference to `sched_autogroup_create_attach'
ld: kernel/sched/alt_core.o: in function `perf_trace_sched_move_numa':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:494: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `perf_trace_sched_numa_pair_template':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: /mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `trace_event_raw_event_sched_move_numa':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:494: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o: in function `trace_event_raw_event_sched_numa_pair_template':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: undefined reference to `task_numa_group_id'
ld: kernel/sched/alt_core.o:/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/./include/trace/events/sched.h:526: more undefined references to `task_numa_group_id' follow
ld: mm/memory.o: in function `do_numa_page':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/memory.c:4100: undefined reference to `task_numa_fault'
ld: mm/mempolicy.o: in function `mpol_misplaced':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2538: undefined reference to `should_numa_migrate_memory'
ld: mm/mempolicy.o: in function `check_numabalancing_enable':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2772: undefined reference to `set_numabalancing_state'
ld: /mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/mempolicy.c:2777: undefined reference to `set_numabalancing_state'
ld: mm/huge_memory.o: in function `do_huge_pmd_numa_page':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/mm/huge_memory.c:1548: undefined reference to `task_numa_fault'
ld: fs/exec.o: in function `__do_execve_file':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/exec.c:1935: undefined reference to `task_numa_free'
ld: fs/proc/base.o: in function `sched_autogroup_show':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/base.c:1483: undefined reference to `proc_sched_autogroup_show_task'
ld: fs/proc/base.o: in function `sched_autogroup_write':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/base.c:1514: undefined reference to `proc_sched_autogroup_set_nice'
ld: fs/proc/array.o: in function `task_state':
/mnt/4TB/Downloads/Tk-Glitch/PKGBUILDS/linux-tkg/linux58-tkg/src/linux-5.8/fs/proc/array.c:171: undefined reference to `task_numa_group_id'
  BTF     .btf.vmlinux.bin.o
tag__check_id_drift: subroutine_type id drift, core_id: 1127, btf_type_id: 1125, type_id_off: 0
libbpf: Unsupported BTF_KIND:0
btf_elf__encode: btf__new failed!
free(): double free detected in tcache 2
scripts/link-vmlinux.sh: line 137: 3956455 Aborted                 (core dumped) LLVM_OBJCOPY=${OBJCOPY} ${PAHOLE} -J ${1}
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
make: *** [Makefile:1139: vmlinux] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

**Comment by Tk-Glitch** [comment]
Hopefully fixed with https://github.com/Frogging-Family/linux-tkg/commit/cce2723e11e0207bf2b196fcea4f99c9968ee24b

**Comment by leucome** [comment]
Yes, it's working.

**Comment by D3SOX** [comment]
Still not working for me. Idk if it's the same issue. Using Ryzen Desktop, PDS, AMD Zen 2, fsync
```
  LD [M]  net/ieee802154/ieee802154_socket.ko
  LD [M]  net/ipv4/ah4.ko
  LD [M]  net/ife/ife.ko
  LD [M]  net/ipv4/esp4.ko
  LD [M]  net/ipv4/esp4_offload.ko
  LD [M]  net/ipv4/fou.ko
  LD [M]  net/ipv4/gre.ko
  LD [M]  net/ipv4/inet_diag.ko
  LD [M]  net/ipv4/ip_gre.ko
  LD [M]  net/ipv4/ip_tunnel.ko
  LD [M]  net/ipv4/ip_vti.ko
  LD [M]  net/ipv4/ipcomp.ko
  LD [M]  net/ipv4/ipip.ko
  LD [M]  net/ipv4/netfilter/arp_tables.ko
  LD [M]  net/ipv4/netfilter/arpt_mangle.ko
  LD [M]  net/ipv4/netfilter/arptable_filter.ko
  LD [M]  net/ipv4/netfilter/ip_tables.ko
  LD [M]  net/ipv4/netfilter/ipt_CLUSTERIP.ko
  LD [M]  net/ipv4/netfilter/ipt_ECN.ko
  LD [M]  net/ipv4/netfilter/ipt_REJECT.ko
  LD [M]  net/ipv4/netfilter/ipt_SYNPROXY.ko
  LD [M]  net/ipv4/netfilter/ipt_ah.ko
  LD [M]  net/ipv4/netfilter/ipt_rpfilter.ko
  LD [M]  net/ipv4/netfilter/iptable_filter.ko
  LD [M]  net/ipv4/netfilter/iptable_mangle.ko
  LD [M]  net/ipv4/netfilter/iptable_nat.ko
  LD [M]  net/ipv4/netfilter/iptable_raw.ko
  LD [M]  net/ipv4/netfilter/iptable_security.ko
  LD [M]  net/ipv4/netfilter/nf_defrag_ipv4.ko
  LD [M]  net/ipv4/netfilter/nf_dup_ipv4.ko
  LD [M]  net/ipv4/netfilter/nf_flow_table_ipv4.ko
  LD [M]  net/ipv4/netfilter/nf_log_arp.ko
  LD [M]  net/ipv4/netfilter/nf_log_ipv4.ko
ld: drivers/staging/rtl8723bs/r8723bs.ko: final close failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ipv4/netfilter/ipt_rpfilter.ko] Error 1
make[2]: *** Waiting for unfinished jobs....
  LD [M]  net/ipv4/netfilter/nf_nat_h323.ko
make[2]: *** [scripts/Makefile.modfinal:41: drivers/staging/rtl8723bs/r8723bs.ko] Error 1
ld: fs/afs/kafs.ko: final close failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/afs/kafs.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/atm/atm.ko] Error 1
ld: final link failed: ldNo space left on device: final link failed: 
No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ipv4/netfilter/ipt_CLUSTERIP.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/bluetooth/rfcomm/rfcomm.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfsd/nfsd.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfs/nfsv4.ko] Error 1
ld: net/ieee802154/ieee802154.ko: final close failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ieee802154/ieee802154.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/dsa/dsa_core.ko] Error 1
ld: net/core/pktgen.ko: final close failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/core/pktgen.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ipv4/netfilter/arp_tables.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/ocfs2/ocfs2.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/dccp/dccp.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/bridge/bridge.ko] Error 1
ld: net/can/j1939/can-j1939.ko: final close failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/can/j1939/can-j1939.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/cifs/cifs.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfs/nfs.ko] Error 1
ld: net/ceph/libceph.ko: final close failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ceph/libceph.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/bluetooth/bluetooth.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/batman-adv/batman-adv.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/btrfs/btrfs.ko] Error 1
ld: final link failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/xfs/xfs.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] Error 1
make[1]: *** [scripts/Makefile.modpost:117: __modpost] Error 2
make: *** [Makefile:1360: modules] Error 2
  DESCEND  objtool
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
Kernel: arch/x86/boot/bzImage is ready  (#1)
  LD [M]  drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko
  LD [M]  drivers/staging/rtl8723bs/r8723bs.ko
  LD [M]  fs/afs/kafs.ko
  LD [M]  fs/btrfs/btrfs.ko
  LD [M]  fs/cifs/cifs.ko
  LD [M]  fs/nfs/nfs.ko
  LD [M]  fs/nfs/nfsv4.ko
  LD [M]  fs/nfsd/nfsd.ko
  LD [M]  fs/ocfs2/ocfs2.ko
  LD [M]  fs/xfs/xfs.ko
  LD [M]  net/atm/atm.ko
  LD [M]  net/batman-adv/batman-adv.ko
  LD [M]  net/bluetooth/bluetooth.ko
  LD [M]  net/bluetooth/rfcomm/rfcomm.ko
  LD [M]  net/can/j1939/can-j1939.ko
  LD [M]  net/bridge/bridge.ko
  LD [M]  net/ceph/libceph.ko
  LD [M]  net/core/pktgen.ko
  LD [M]  net/dccp/dccp.ko
  LD [M]  net/dsa/dsa_core.ko
  LD [M]  net/ieee802154/ieee802154.ko
  LD [M]  net/ipv4/netfilter/arp_tables.ko
  LD [M]  net/ipv4/netfilter/ipt_CLUSTERIP.ko
  LD [M]  net/ipv4/netfilter/ipt_rpfilter.ko
ld: net/bluetooth/rfcomm/rfcomm.ko: final close failed: No space left on device
ld: net/can/j1939/can-j1939.ko: final close failed: No space left on device
ld: net/ipv4/netfilter/arp_tables.ko: final close failed: ld: final link failed: No space left on device
No space left on device
ld: final link failed: No space left on device
  LD [M]  net/ipv4/netfilter/nf_nat_pptp.ko
make[2]: *** [scripts/Makefile.modfinal:41: net/atm/atm.ko] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.modfinal:41: net/bluetooth/bluetooth.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/bluetooth/rfcomm/rfcomm.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/can/j1939/can-j1939.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/ipv4/netfilter/arp_tables.ko] Error 1
  LD [M]  net/ipv4/netfilter/nf_nat_snmp_basic.ko
ldld: : final link failed: net/dsa/dsa_core.ko: final close failed: No space left on device
No space left on device
ld: net/ieee802154/ieee802154.ko: final close failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/dsa/dsa_core.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/ieee802154/ieee802154.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/ceph/libceph.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: fs/xfs/xfs.ko] Error 1
/bin/sh: line 0: printf: write error: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/ipv4/netfilter/nf_nat_snmp_basic.ko] Error 1
make[2]: *** Deleting file 'net/ipv4/netfilter/nf_nat_snmp_basic.ko'
ld: final link failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/dccp/dccp.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfs/nfs.ko] Error 1
ld: final link failed: No space left on device
ld: final link failed: No space left on device
ld: final link failed: No space left on device
ld: final link failed: No space left on device
ld: final link failed: make[2]: *** [scripts/Makefile.modfinal:41: fs/ocfs2/ocfs2.ko] Error 1
No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: net/batman-adv/batman-adv.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfs/nfsv4.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: fs/afs/kafs.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: net/bridge/bridge.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: fs/nfsd/nfsd.ko] Error 1
ld: final link failed: No space left on device
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: fs/btrfs/btrfs.ko] Error 1
make[2]: *** [scripts/Makefile.modfinal:41: fs/cifs/cifs.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: drivers/staging/rtl8723bs/r8723bs.ko] Error 1
ld: final link failed: No space left on device
make[2]: *** [scripts/Makefile.modfinal:41: drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] Error 1
make[1]: *** [scripts/Makefile.modpost:117: __modpost] Error 2
make: *** [Makefile:1360: modules] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by AdelKS** [comment]
@D3SOX as the error messages show, you filled up your partition to the max the script can't continue because there isn't any space left.

**Comment by D3SOX** [comment]
> @D3SOX as the error messages show, you filled up your partition to the max the script can't continue because there isn't any space left.

Oops just now I have also seen it but thanks anyway

**Comment by AdelKS** [comment]
No worries! Time to buy an extra Samsung M2 SSD PCI4 😎

**Comment by D3SOX** [comment]
> No worries! Time to buy an extra Samsung M2 SSD PCI4

Yes I already plan to buy an M.2 soon.
But I made the mistake to make my root partition too big
![image](https://user-images.githubusercontent.com/24937357/92408901-27baab00-f13f-11ea-9e45-84f746e86303.png)

**Comment by leucome** [comment]
Ho! by the way.  The resulting kernel is not working properly on my computer.  It freeze when the computer idle.  By example when I browse the internet or edit text file.  If I keep the computer busy with a game it  work fine.    Maybe it's an issue with a power saving feature.

There was a kernel that had the exact same behaviours on my computer last years and it went away the next update. So it is maybe it's an already known issue.

 I'm not so sure what to look for to diagnose that kind of behaviours.  I guess there is probably a system log somewhere that may hold more clue to what happens during the event or before. 

I tired this... 
journalctl -p3 --no-hostname --no-pager | grep lockup
Sep 07 18:16:13 kernel: watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [ksysguardd:45623]
   

So for now I reverted back to 5.8.7-10.

I may try  the BMQ and CFS version to to see if it also happens with these.

**Comment by AdelKS** [comment]
@leucome Can you have a look at [this issue](https://gitlab.com/alfredchen/linux-prjc/-/issues/8) to see if it's related ? This is probably an upstream bug you have encountered. You may be able to help out there :D
