### ISSUE TITLE
Why the _timer_freq(Timer frequency) is now default to 1000Mhz?

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#611]
I'm just curious. I'm using the `cfs` schedule. It used to be 500Mhz, which seems to be the middle ground between overhead and throughput.

**Comment by Ann1kaB** [comment]
Read this commit https://github.com/Frogging-Family/linux-tkg/commit/3bfe0af94592cd97a72c2317c32f62a640b11213

**Comment by rizzini** [comment]
Thank you!
