### ISSUE TITLE
Error applying patches when building kernel 6.0.

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#612]
It doesn't seem to be critical tho.. The compilation continues after the error is presented. I'm ignoring it. I created this issue just for you to be aware.
`==> ERRO: An error was encountered applying patches. It was logged to the prepare.log.txt file.`

[prepare.log.txt](https://pastebin.com/qJuWJ6vQ):
```
patching file tools/testing/selftests/Makefile
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file tools/testing/selftests/Makefile.rej
```

**Comment by Iglu47** [comment]
Thanks for the report, this is very useful as I can't use all versions at once (especially on bleeding edge)
