### ISSUE TITLE
[Feature Request] make kernel name match kernel RPM package version on Fedora

### ISSUE THREAD

**Issue by ktheticdev** [Frogging-Family/linux-tkg#617]
_Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !_
I searched both in the issues and pull requests section and didnt find anyone talking about it.

**Describe the feature**
Right now TKG kernel versioning on Fedora would be like `<version>` (e. g. if kernel is compiled with BORE scheduler and LLVM, the kernel version is `6.0.0_tkg_bore_llvm`. However, this makes kernel incompatible with building kmods manually as they require the kernel to be named exactly the same as the RPM version (thus, kernel version in specified case should rather be `6.0.0_tkg_bore_llvm-1.x86_64` instead of `6.0.0_tkg_bore_llvm`). I guess that it's Fedora-specific, that is why it's better not to do this way on other Linux distros.

**Comment by Tk-Glitch** [comment]
Would changing line 265's `EXTRAVERSION="${_extra_ver_str}"` to `EXTRAVERSION="${_extra_ver_str}-1.x86_64"` in `install.sh` do?
@AdelKS Your comment `# Replace dashes with underscores, it seems that it's being done by binrpm-pkg` creates doubt somehow.

**Comment by ktheticdev** [comment]
> > Would changing line 265's EXTRAVERSION="${_extra_ver_str}" to EXTRAVERSION="${_extra_ver_str}-1.x86_64" in install.sh do?
> 
> Unfortunately I do not think so, it will just add that spurious `-1.x86_64` I'd say, though maybe it checks if it's there first ? But `akmod-nvidia` compiled without issues, how do you compile "manually" kernel modules @ktheticdev ?

By compiling manually I meant building kmod package using kmod specs. The nvidia driver's kmod spec requires `kernel-uname-r` package version to match `uname -r` respectively. As I have spotted, stock Fedora kernels are versioned the same way as the package is.

**Comment by ktheticdev** [comment]
Actually works fine with kernel with `kernel-uname-r` package provided. Closing the issue.
