### ISSUE TITLE
Is there a way to build with pmadv_ksm() system call? https://codeberg.org/pf-kernel/uksmd

### ISSUE THREAD

**Issue by rizzini** [Frogging-Family/linux-tkg#619]
I'm testing @SoongVilda [archlinux-performance](https://github.com/SoongVilda/archlinux-performance) repo, which sound great. Although, I inted to stick with your custom kernel, which lack the [pmadv_ksm()](https://codeberg.org/pf-kernel/uksmd) system call. Is there a way I could build TKG custom kernel with it?

**Comment by ptr1337** [comment]
Just include the patch into tkg

**Comment by rizzini** [comment]
That's right! I don't know why that didn't occur to me. Shame.. Thanks.

**Comment by rizzini** [comment]
For future reference.. Here is the patch: https://gitlab.com/sirlucjan/kernel-patches/-/raw/master/5.19/ksm-patches/0001-ksm-patches.patch?inline=false. It's for 5.19, but it works with the kernel 6, but I'm guessing they'll release a patch for it soon enough.
