### ISSUE TITLE
Kernels `5.19.1-268-tkg-pds` and `6.0.1-270-tkg-pds` Don't Load User Applications Properly

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#625]
**Describe the bug**
 - Which OS do you encounter the bug on? - Arch Linux
 - A clear and concise description of what the bug is:
Launching any application (and KDE Plasma) takes unusually long to launch properly; about 1 or 2 minutes or so?

Probably unrelated but I can't be sure:
- https://github.com/ValveSoftware/steam-for-linux/issues/8738
I had reported a bug to Valve about 5.19 and 6.0.1 not being able to properly load `steamwebhelper` for Steam; I don't know if this is related, but it might be?

 - Attach the contents of your logs folder by drag & dropping each file into this message:
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9769039/system-info.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9769040/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9769043/prepare.log.txt)

- Kernel config and `linux-tkg.cfg` (from `~/.config/frogminer`):
[kernelconfig.new.txt](https://github.com/ValveSoftware/steam-for-linux/files/9768982/kernelconfig.new.txt)
[linux-tkg config.zip](https://github.com/ValveSoftware/steam-for-linux/files/9768999/linux-tkg.zip)

Also, my PKGBUILD has this at the top to change my `makepkg.conf` to remove potential interferences (besides the CFLAGS):
```bash
PACMAN_AUTH=(doas)

options+=(!lto)

CC=gcc
CXX=g++
LD=ld
AR=""
NM=""
AS=""
RANLIB=""
STRIP=""
OBJCOPY=""

OBJC=""

CFLAGS="-march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -minline-all-stringops -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fstack-protector-strong -fcf-protection"
CXXFLAGS="${CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="${LDFLAGS/-static/}"
```

**Comment by Tk-Glitch** [comment]
I cannot reproduce the issue on my end.

**Comment by ThisNekoGuy** [comment]
Even with the same configuration?
I don't understand how this wouldn't be reproducible when I can do it for at least two separate kernels consistently :v

I had started a discussion about this some time ago but no one ever responded:
- https://github.com/Frogging-Family/linux-tkg/discussions/572

I had suspected that `INIT_ALL_STACK_ZERO` or something like it might have been responsible but...
not picking it says that it can introduce memory vulnerabilities...

**Comment by Tk-Glitch** [comment]
Keep in mind I will never test against custom configuration as it's simply not viable. I'm offering a default config that's tested for a reason (and even then, I'm only running my tests against three platforms most of the time: x58 with a xeon x5660, z370 with a 8086k and b550 with a 5950x). Anybody can change the kernel config and CFLAGS and break everything, that's not manageable. If you can reproduce the issue with https://github.com/Frogging-Family/linux-tkg/releases/tag/v6.0.1 then we can search for something to fix.

**Comment by ThisNekoGuy** [comment]
Alright, I'll try from there, then

**Comment by ThisNekoGuy** [comment]
Seems to be alright; guess it must've been something I did wrong... I'll close.
