### ISSUE TITLE
[Kernel 5.17.15] `sha256.c:(.text.unlikely+0xc)`: undefined reference to `fortify_panic`

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#626]
**Describe the bug**
 - Which OS do you encounter the bug on? - Arch Linux
 - A clear and concise description of what the bug is:
The bug is a compilation error with `sha256.c`, where the compiler claims there's an undefined reference to `fortify_panic`.
Additionally, the line above has a message about `ld` but I'm unsure if that's an error or not; but the above-mentioned definitely is and I don't know why.
```make
  . . .
  LD [M]  drivers/infiniband/hw/hfi1/hfi1.o
  DESCEND objtool
  DESCEND bpf/resolve_btfids
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  LD      arch/x86/purgatory/purgatory.chk
ld: arch/x86/purgatory/purgatory.ro: in function `memzero_explicit.part.0':
sha256.c:(.text.unlikely+0xc): undefined reference to `fortify_panic'
make[2]: *** [arch/x86/purgatory/Makefile:74: arch/x86/purgatory/purgatory.chk] Error 1
make[1]: *** [scripts/Makefile.build:550: arch/x86/purgatory] Error 2
make[1]: *** Waiting for unfinished jobs....
  AR      virt/lib/built-in.a
  CC [M]  virt/lib/irqbypass.o
  CC      arch/x86/pci/i386.o
  AR      virt/built-in.a
  . . .
```
 - Attach the contents of your logs folder by drag & dropping each file into this message.
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9769615/system-info.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9769616/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9769617/prepare.log.txt)

- Kernel config and `linux-tkg.cfg` (from `~/.config/frogminer`):
[kernelconfig.new.txt](https://github.com/Frogging-Family/linux-tkg/files/9769628/kernelconfig.new.txt)
[linux-tkg.zip](https://github.com/Frogging-Family/linux-tkg/files/9769630/linux-tkg.zip)

Also, my PKGBUILD has this at the top to change my `makepkg.conf` to remove potential interferences (besides the CFLAGS):
```bash
PACMAN_AUTH=(doas)

options+=(!lto)

CC=gcc
CXX=g++
LD=ld
AR=""
NM=""
AS=""
RANLIB=""
STRIP=""
OBJCOPY=""

OBJC=""

CFLAGS="-march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -minline-all-stringops -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fstack-protector-strong -fcf-protection"
CXXFLAGS="${CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="${LDFLAGS/-static/}"
```

**Comment by Tk-Glitch** [comment]
Are you using hardened (didn't seem so)?

Couldn't reproduce the issue here (default config & Arch's default makepkg.conf): 
```
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "linux517-tkg-pds-headers"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
  -> exit cleanup done

==> Finished making: linux517-tkg-pds 5.17.15-270 (jeu. 13 oct. 2022 22:06:33)
  -> exit cleanup done
```

**Comment by ThisNekoGuy** [comment]
I wasn't using hardened but this was sort of like issue https://github.com/Frogging-Family/linux-tkg/issues/625 where an old config was being used and updated with `olddefconfig` and something probably went wrong somewhere; I'll take your example as working and the problem just being my own fault for not doing the "top-down"  approach of using the included default config in the repo and working from there
