### ISSUE TITLE
Missing CPU schedulers for 6.0.2

### ISSUE THREAD

**Issue by italoghost** [Frogging-Family/linux-tkg#631]
**Describe the bug**
 - Which OS do you encounter the bug on? 
Arch Linux

 - A clear and concise description of what the bug is.
Since 6.0.1 there is no option to compile the kernel with pds or bmq schedules. Even if I change the "customization.cfg", it tells me that it is not available.

![image](https://user-images.githubusercontent.com/48540550/196692357-b67bf9fb-1aa4-4fbc-a6c3-dc6533e87966.png)

**Comment by robson-66** [comment]
You need to edit the prepare file in line 300, delete
```_avail_cpu_scheds = ("cfs" "tt" "bore")```
and add
``` _avail_cpu_scheds = ("cfs" "pds" "bmq" "cacule" "tt" "bore")```

**Comment by Tk-Glitch** [comment]
They were disabled due to bugs. The project C developer haven't updated the patchset for 6.0 just yet, so we were shipping a user's rebase which he wasn't too sure about. Since PDS and BMQ are among the most popular CPU schedulers we offer, offering buggy versions of them didn't feel too good.

**Comment by italoghost** [comment]
@Tk-Glitch So is it better to wait to the updated patchset? I am asking this because there is a pds and a bmq version on the releases page.

**Comment by Tk-Glitch** [comment]
The release was already building when I disabled them.
See https://github.com/Frogging-Family/linux-tkg/commit/d60046d9fb565bb70992c821905aff18a18d43f9

I couldn't reproduce the stability issues reported on my own machine, so you might be fine. But in case you face hangs or random reboots, that would most likely be it.

**Comment by italoghost** [comment]
Thank you, guys! 

I am experiencing some strange behavior since the kernel 6.0.0 pds: my computer seems to lose the input signal from the screen and from the mouse and keyboard, as they stop working. But the computer is still working, as I can hear the sounds just fine (the first time this happened I was on call with friends).

Is this behavior related to the stability issues that were reported?

**Comment by Tk-Glitch** [comment]
> Thank you, guys!
> 
> I am experiencing some strange behavior since the kernel 6.0.0 pds: my computer seems to lose the input signal from the screen and from the mouse and keyboard, as they stop working. But the computer is still working, as I can hear the sounds just fine (the first time this happened I was on call with friends).
> 
> Is this behavior related to the stability issues that were reported?

Very likely. Test CFS out and see I guess 😅

**Comment by Melechtna** [comment]
thing is, even with cfs I get the "blank screen" issue any time I wake from sleep, so I don't think it's PDS

**Comment by seankhl** [comment]
I am also getting some issues with PDS on 6.0.0. I faced some black screen issues and lockups, not frequent but definitely present.

I also have separate issues of waking from sleep on all kernels and schedulers since changing to an RX 6600, so I just don't put my computer to sleep for the time being until the issue is resolved.

**Comment by Melechtna** [comment]
> I am also getting some issues with PDS on 6.0.0. I faced some black screen issues and lockups, not frequent but definitely present.
> 
> I also have separate issues of waking from sleep on all kernels and schedulers since changing to an RX 6600, so I just don't put my computer to sleep for the time being until the issue is resolved.

I've honestly never had a lock up that wasn't self inflicted with any scheduler, only exception being bmq and tts, which I haven't tested, which includes pds, which I'm currently using without issue aside from the sleep thing

**Comment by Everest10** [comment]
> You need to edit the prepare file in line 300, delete `_avail_cpu_scheds = ("cfs" "tt" "bore")` and add ` _avail_cpu_scheds = ("cfs" "pds" "bmq" "cacule" "tt" "bore")`

are you serious ? lol

**Comment by Melechtna** [comment]
> > You need to edit the prepare file in line 300, delete `_avail_cpu_scheds = ("cfs" "tt" "bore")` and add ` _avail_cpu_scheds = ("cfs" "pds" "bmq" "cacule" "tt" "bore")`
> 
> Are you serious ? lol. Delete this comment. There is still time.

That's how I'm on Kernel 6.0 with PDS currently.

**Comment by robson-66** [comment]
> Are you serious ? lol. Delete this comment. There is still time.
I am not trying to persuade anyone to edit the `prepare`. But I only gave a way to be able to build `bmq` and `pds`, because on some machines it works fine.

**Comment by robson-66** [comment]
> > Are you serious ? lol. Delete this comment. There is still time. 
>
I am not trying to persuade anyone to edit the `prepare`. But I only gave a way to be able to build `bmq` and `pds`, because on some machines it works fine.

**Comment by Everest10** [comment]
> > > Are you serious ? lol. Delete this comment. There is still time.
> 
> I am not trying to persuade anyone to edit the `prepare`. But I only gave a way to be able to build `bmq` and `pds`, because on some machines it works fine.

I'm waiting for pds and bmq too, but your comment to just change one line in the installation code do create a bypass like is not the proper solution.
