### ISSUE TITLE
EFI_STUB support gone‽

### ISSUE THREAD

**Issue by chipshopness** [Frogging-Family/linux-tkg#634]
Somewhere  between 6.0.3 and 6.0.5  CONFIG_EFI_STUB disappeared (for me anyway) and I can no longer build a bootable kernel. It's there in config.x86_64 but has vanished in kernelconfig.new. I can't enable it in menuconfig as it doesn't appear there; ISTR it should be under EFI runtime service support when that's enabled. Making a config fragment containing `CONFIG_EFI_STUB=y` doesn't work nor ` _configfile="running-kernel"` in customization.cfg. This is on Ubuntu 22.04.

[kernelconfig.new.zip](https://github.com/Frogging-Family/linux-tkg/files/9890763/kernelconfig.new.zip)

**Comment by ptr1337** [comment]
> Somewhere between 6.0.3 and 6.0.5 CONFIG_EFI_STUB disappeared (for me anyway) and I can no longer build a bootable kernel. It's there in config.x86_64 but has vanished in kernelconfig.new. I can't enable it in menuconfig as it doesn't appear there; ISTR it should be under EFI runtime service support when that's enabled. Making a config fragment containing `CONFIG_EFI_STUB=y` doesn't work nor ` _configfile="running-kernel"` in customization.cfg. This is on Ubuntu 22.04.
> 
> [kernelconfig.new.zip](https://github.com/Frogging-Family/linux-tkg/files/9890763/kernelconfig.new.zip)

This is a issue when building with llvm-git. Apply this patch to fix it:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=33806e7cb8d50379f55c3e8f335e91e1b359dc7b

This is the llvm commit, which breaks EFI_STUB:
https://github.com/llvm/llvm-project/commit/d1ad006a8f64bdc17f618deffa9e7c91d82c444d

**Comment by chipshopness** [comment]
Thank you. That was indeed it. It seems to already be fixed in 6.0.6.
