### ISSUE TITLE
Missing CPU schedulers on older versions.

### ISSUE THREAD

**Issue by tuantran1632001** [Frogging-Family/linux-tkg#635]
There is already a report about missing schedulers on 6.0.x at #631 and I understand the reason. However, as I choose an older version like v5.15.76, the only scheduler available is CFS.  Does this suppose to happen?

![Screenshot_20221031_050326](https://user-images.githubusercontent.com/68230358/198903702-ec5bcda2-b5d0-4521-b035-c5dbd34c9a78.png)

![Screenshot_20221031_050405](https://user-images.githubusercontent.com/68230358/198903704-2ae2ffac-0194-40c3-9c7e-2fa8ccf35db1.png)

**Comment by Tk-Glitch** [comment]
No that's not supposed to happen. I also cannot reproduce the issue on my end, neither with an empty `_cpusched` variable nor with it set to `pds`.
I also tested an incorrect value to trigger the "not available" prompt (in case the issue came from the formatting in your .cfg), but got correct fallback listing as well 🤔 :
```
  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
        0) v6.1-rc3
      > 1) v6.0.6
        2) v5.15.76
        3) v5.10.152
        4) v5.4.221
        5) Another (no longer maintained upstream)
[0-5]: 2
    Selected: v5.15.76
==> WARNING: Your cpusched selection ( test ) is not available for the selected kernel version.
==> WARNING: Please select another
  -> Which CPU sched variant do you want to build/install?
  -> Project C (pds) / BMQ (bmq) is usually a good balance for gaming.
  -> Select "cfs" (linux kernel's default) if unsure.
      > 0) Project C / PDS
        1) Project C / BMQ
        2) CacULE
        3) TT (TaskType)
        4) CFS (Completely Fair Scheduler) Linux kernel's default
[0-4]:
```

The check is defined here: https://github.com/Frogging-Family/linux-tkg/blob/a380d532bc85013c120b1d689a07367afc0e026b/linux-tkg-config/prepare#L272-303

**Comment by tuantran1632001** [comment]
After diffing my config with customization.cfg and testing each option, I found the issue occur if `_preempt_rt` is set. I set it to test it when 6.0.0 was new and I had to switch back to CFS. From the warning, I thought that if I chose a different scheduler then that option would be ignored. Seem like that is not the case.

**Comment by Tk-Glitch** [comment]
Oh yeah that option enforces CFS only as it's not compatible with most alternative cpuscheds (I guess BORE would be the exception).

**Comment by Alastair0100** [comment]
it seems BFQ is supported too https://aur.archlinux.org/packages/linux-rt-bfq-dev

**Comment by ptr1337** [comment]
> it seems BFQ is supported too https://aur.archlinux.org/packages/linux-rt-bfq-dev

bfq is a disk I/O Scheduler...
