### ISSUE TITLE
Patch incorrectly zipped

### ISSUE THREAD

**Issue by Alastair0100** [Frogging-Family/linux-tkg#637]
- Which OS do you encounter the bug on? 
 Arch
- A clear and concise description of what the bug is.

Seems to be that the format of the zip of the patch is wrong and its messing up the script.
`gzip: /home/computer/Desktop/linux-tkg/src/patch-5.15.32-rt39.patch.gz: not in gzip format`

![image](https://user-images.githubusercontent.com/40572266/199818399-2deb9f00-15a4-4236-8246-7bc303370060.png)

 - Attach the contents of your logs folder by drag & dropping each file into this message.

[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9932440/system-info.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9932441/prepare.log.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9932442/customization.cfg.txt)

**Comment by Tk-Glitch** [comment]
Fixed by https://github.com/Frogging-Family/linux-tkg/commit/8316a6970af3ad51edd2fb4b0a23fa5d2adbeb17
