### ISSUE TITLE
ERROR: An error was encountered applying patches

### ISSUE THREAD

**Issue by TechXero** [Frogging-Family/linux-tkg#638]
**Describe the bug**
 - Which OS do you encounter the bug on? => Arch

Build failing. Attached are the logs..
 
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9943959/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9943960/system-info.txt)

Customization file

[linux-tkg.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9943962/linux-tkg.cfg.txt)

Thanks

**Comment by ptr1337** [comment]
> **Describe the bug**
> 
> * Which OS do you encounter the bug on? => Arch
> 
> Build failing. Attached are the logs..
> 
> [prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/9943959/prepare.log.txt) [system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/9943960/system-info.txt)
> 
> Customization file
> 
> [linux-tkg.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/9943962/linux-tkg.cfg.txt)
> 
> Thanks

https://github.com/Frogging-Family/linux-tkg/pull/639
