### ISSUE TITLE
`exit_cleanup()` at end of `./install.sh config` breaks the source tree

### ISSUE THREAD

**Issue by imaami** [Frogging-Family/linux-tkg#64]
I had trouble trying to build linux58-tkg on Debian with:

```
cd linux58-tkg &&
./install config &&
cd linux-5.8 &&
make bindeb-pkg
```

(The last line is how I build all my kernels normally.)

Build failed due to missing headers and files. Which files specifically were missing isn't relevant here, because they're obviously deleted by `exit_cleanup()` in `linux58-tkg/linux58-tkg-config/prepare` at the end of `./install.sh config`.

The cleanup on exit is apparently done with the assumption that the compilation itself has finished by that point, but that's not true when `install.sh` is used only for patching and configuring.

**Comment by imaami** [comment]
After disabling the EXIT trap build succeeded.

**Comment by AdelKS** [comment]
It's very weird that the exit cleanup touches files inside the kernel git folder. I will investigate.

**Comment by AdelKS** [comment]
I fixed it, I will PR it. Thanks for reporting!
