### ISSUE TITLE
bcachefs mount is not working. Debian. Kernel 5.15/5.19/6.0

### ISSUE THREAD

**Issue by ViktorsBaikers** [Frogging-Family/linux-tkg#640]
Long story short.

OC: Debian 11

Tried to build 3 different versions of kernel 5.15/5.19/6.0.

I can make an everything till mount command.

Once I'm trying to mount  with the command "mount -t bcachefs /dev/sdb1:/dev/sda1 /mnt"

I do enable the patch from the conf file. 

I'm getting an error message like this:

`mount: /mnt: wrong fs type, bad option, bad superblock on /dev/sdb1:/dev/sda1, missing codepage or helper program, or other error.`

From dmesg i can get:

`[ 2722.873414] bcachefs (/dev/sdb1): error reading default superblock: Unsupported superblock version 23 (min 9, max 23)`

This does not happen if I do compile the original bcachefs kernel.

**Comment by ptr1337** [comment]
Probably the patch needs to get updated once again, or the config needs differnt options. I haven't used bcachefs since long time.

I'll tomorrow update the bcachefs patch. Also be sure to use a up2date bcachefs-tools

**Comment by ViktorsBaikers** [comment]
@ptr1337 Strange that it happens even to the latest kernel. 

bcachefs-tools is avaliable in upstream, so it's not an issue + as i mentioned before everything is fine with original bcachefs kernel. Will wait form your message to test it once again :)

**Comment by ptr1337** [comment]
> @ptr1337 Strange that it happens even to the latest kernel.
> 
> bcachefs-tools is avaliable in upstream, so it's not an issue + as i mentioned before everything is fine with original bcachefs kernel. Will wait form your message to test it once again :)

I just updated 5.15 and 6.0 now, since 5.19 is EOL there is no need for.
https://github.com/Frogging-Family/linux-tkg/pull/641

**Comment by ViktorsBaikers** [comment]
> > @ptr1337 Strange that it happens even to the latest kernel.
> > bcachefs-tools is avaliable in upstream, so it's not an issue + as i mentioned before everything is fine with original bcachefs kernel. Will wait form your message to test it once again :)
> 
> I just updated 5.15 and 6.0 now, since 5.19 is EOL there is no need for. #641

I will check and get back with the result :)

**Comment by ViktorsBaikers** [comment]
Can confirm. It works on 6.0 kernel @ptr1337 

Maybe you could give me advice on how to create that patch by myself and from where I can take the source to build the patch? So i could maintain so it would be up to date not only for me, but also for the community!

**Comment by ptr1337** [comment]
> Can confirm. It works on 6.0 kernel @ptr1337
> 
> Maybe you could give me advice on how to create that patch by myself and from where I can take the source to build the patch? So i could maintain so it would be up to date not only for me, but also for the community!

Sure, Ill try to keep them already up2date, but you are welcome :+1: 
Clone a stable kernel git tree, add as remote https://github.com/koverstreet/bcachefs
Them merge the "master" tree (if mainline kernel) into the latest stable kernel release. Then format the patch with git :)
