### ISSUE TITLE
[Feature request] Add support for linux 4.19

### ISSUE THREAD

**Issue by Alastair0100** [Frogging-Family/linux-tkg#643]
Hello.

I think it would be good to add support for linux 4.19. Im using old graphics card but the driver is 396 and so none of the kernals on linux tkg currently support it (5.3 and under according to nvidia-all)
. Looking on https://www.kernel.org/. It appears the latest closest LTS kernal is 4.19 (also the kernal version under the lowest support kernal on tkg right now it seems)
This kernal is still supported it appears, and so for more compatibility on hardware I think this is good addition.

Thanks for reading.

**Comment by ptr1337** [comment]
Actually which kind of benefit does bring you the nvidia driver against nouveau?

**Comment by Alastair0100** [comment]
> Actually which kind of benefit does bring you the nvidia driver against nouveau?

nouveau give really low gaming performance. And so not good for gamers.

**Comment by Alastair0100** [comment]
> The 390xx drivers does support kernels until 5.19

nvidia-all states 5.3 or under and 5.1 or under is recommended. I also tried building it on 5.15 and got error. Should I close this issue and open an issue on nvidia all?

**Comment by ptr1337** [comment]
Actually every kernel under 6.0 should work, dkms does also compile with 6.0 but there it seems it has a xorg issue.
I have some users, which use this driver and it works well.

Checkout the thread in the arch aur, and you will see on the feedback, that newer kernels are also working.
Also you will find some patches for the nvidia driver there.

https://aur.archlinux.org/packages/nvidia-390xx-dkms

**Comment by Alastair0100** [comment]
> Actually every kernel under 6.0 should work, dkms does also compile with 6.0 but there it seems it has a xorg issue. I have some users, which use this driver and it works well.
> 
> Checkout the thread in the arch aur, and you will see on the feedback, that newer kernels are also working. Also you will find some patches for the nvidia driver there.
> 
> https://aur.archlinux.org/packages/nvidia-390xx-dkms

just confirmed the version on aur works thanks. If no one else wants Linux 4.19 I guess il close this issue?

**Comment by Tk-Glitch** [comment]
396 series is abandoned but 390 series isn't, so that's what you should use on fermi GPUs these days indeed. However, nvidia-all doesn't offer support for 390 series since the project was initially created for Vulkan dev drivers (to help with DXVK testing and fixing), and fermi doesn't support Vulkan.
I guess we could make it more obvious since 396 series also supported fermi.
