### ISSUE TITLE
6.0.x bcachefs patches can cause build failures depending on kernel config options

### ISSUE THREAD

**Issue by Kangie** [Frogging-Family/linux-tkg#645]
## Describe the bug
 - Which OS do you encounter the bug on? Gentoo (6.0.8 kernel)
### A clear and concise description of what the bug is
When patching a kernel with the 6.0 bcachefs patchset and using a fully-featured kernel config (e.g. fedora) a situation may be encountered where `CONFIG_MEAN_AND_VARIANCE` is selected as both builtin and as a module due to unit test dependencies. This results in the following build failure:

```
ERROR: modpost: missing MODULE_LICENSE() in lib/math/mean_and_variance_test.o
ERROR: modpost: "fast_divpow2" [lib/math/mean_and_variance_test.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:128: modules-only.symvers] Error 1
make: *** [Makefile:1766: modules] Error 2
```

```
Symbol: MEAN_AND_VARIANCE [=y]
Type  : tristate
Defined at lib/math/Kconfig:19
Selected by [y]:
  - BCACHEFS_FS [=y] && BLOCK [=y]
Selected by [m]:
  - MEAN_AND_VARIANCE_UNIT_TEST [=m] && RUNTIME_TESTING_MENU [=y] && KUNIT [=m]
```

This can be resolved by deselecting the unit tests (etc.)

According to [the LKML](https://lore.kernel.org/lkml/YpPjqC+kVLIBpNlq@shaak/) this is likely a defect in the Makefile and/or Kconfig that allows this to occur.

Also appears in the bcachefs sources 'master'; reported upstream.

**Comment by AdelKS** [comment]
I guess this is old enough to close, given bcachefs is now in-tree in newer linux kernel versions etc...
