### ISSUE TITLE
Linux 6.1.0-rc5 does not compile with current BORE patch 

### ISSUE THREAD

**Issue by Slaviusz** [Frogging-Family/linux-tkg#648]
Current version of BORE patch from Cacule seems invalid as it produces syntactic errors on compile, more specifically https://github.com/CachyOS/kernel-patches/blob/master/6.1/sched/0001-bore.patch#L114 introduces unclosed `#else` directive.

A workaround is to use provided patch saved in e.g. `linux61-tkg-userpatches/61_bore_fix.mypatch` when building.
[61_bore_fix.txt](https://github.com/Frogging-Family/linux-tkg/files/10003499/61_bore_fix.txt)

**Comment by ptr1337** [comment]
Fixed with:
https://github.com/CachyOS/kernel-patches/commit/b526eba3b162ec1394d34427b8f5155f4e3968af

**Comment by ptr1337** [comment]
Since the sched_wakeup_granularity_load_fraction implementation has issues with sleep, it got reverted.

**Comment by Slaviusz** [comment]
I can confirm compilation now succeeds.
