### ISSUE TITLE
Unable to build linux-tkg on Void Linux Musl

### ISSUE THREAD

**Issue by Blaxsz** [Frogging-Family/linux-tkg#655]
- Void Linux Musl
 - Not possible to build linux-tkg on x86_64 musl
 - Void Linux install procedure on readme

**Comment by Tk-Glitch** [comment]
The Void procedure is broken these days. The template wasn't updated by its creator for a while and you should instead use the generic approach as a fallback.

**Comment by devraza** [comment]
It's probably a good idea to add a note about the Void Linux install procedure in the README.md, to prevent so many issues from opening.
