### ISSUE TITLE
[Feature request] Add amd_pstate=guided profile to 6.1 kernel

### ISSUE THREAD

**Issue by Slaviusz** [Frogging-Family/linux-tkg#661]
amd_pstate=guided is new profile for amd_pstate cpu-freq driver resulting in better CPU utilisation, higher clocks, more frequent core boosts at the expense of slightly higher CPU usage. 

Current amd_pstate=passive implementation has its drawbacks and performs worse than acpi cpu-freq driver. On the other hand the amd_pstate=guided is on par and in many cases better than acpi.

For now it has to be implicitly activated using `amd_pstate=guided` kernel param after applying the patch.

More resources:
[Article @phoronix.com](https://www.phoronix.com/news/AMD-P-State-Guided-Auto)
[Patch files@lore.kernel.org](https://lore.kernel.org/linux-pm/20221207154648.233759-1-wyes.karny@amd.com/)

I have implemented it as `.mypatch` file you can put in `linux61-tkg-userpatches`. You can find the file in the attachments.
[61_pstate_guided_autonomous.zip](https://github.com/Frogging-Family/linux-tkg/files/10184577/61_pstate_guided_autonomous.zip)

**Comment by ptr1337** [comment]
Did you tested the patch?

I have compiled yesterday a 6.1 kernel with this patch included, and tested the schedutil gov as the patch creator did. It was really awful with my 5900x, it did just stuck at 570 Mhz when using the schedutil gov.

Using the performance gov performed completly similar to the amd-pstate active performance.

I would suggest way more to implement the amd-pstate-epp driver, which does bring a great benefit compared to the amd-pstate=passive driver.

The scaling works way better, performance is same or better then with acpi/amd-pstate.

**Comment by Slaviusz** [comment]
Hi,

I indeed tested the patch but with performance governor only (my kernel default). That's why I probably did not notice any issues so far. In my benchmarks on R9 5950X acpi vs. pstate=guided I achieved much better performance in `phoronix-test-suite/stress-ng`. 

| Kernel | Forking | Context Switching | System V Message Passing |
| --- | --- | --- | --- |
| 6.1-rc8-bore-llvm-acpi | 66235.54 | 16357136.11 | 32748840.43 |
| 6.1-rc8-bore-llvm-pstate_guided | 69114.54 | 16768055.88 | 38759838.22 |

**Comment by ptr1337** [comment]
I have not looked into the patch much, but I guess it should work more well with the schedutil gov as he is pointing.
Also you should test amd-pstate(passive) performance against amd-pstate-guided performance.

Anyways, I can just suggest the amd-pstate-epp driver, it improves the scaling a lot.
To change between the preferences you need to use the powersave gov and then change them like that:
` echo power | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference`

**Comment by Slaviusz** [comment]
I just tested with schedutil governot and it's terrible. Even during phoronix benchmarks it's not leaving 750MHz clock. Turbo boost seems non-existent with this patch. Well, it has a long road ahead (planned is to merge it in 6.3 kernel window).
In the meanwhile I will test proposed `amd-pstate-epp`. Thanks for the hint.

**Comment by Slaviusz** [comment]
Here again, with comparison to `amd_pstate=passive`:


| Kernel | Forking | Context Switching | System V Message Passing |
| --- | --- | --- | --- |
| 6.1-rc8-bore-llvm-acpi | 66235.54 | 16357136.11 | 32748840.43 |
| 6.1-rc8-bore-llvm-pstate_guided | 69114.54 | 16768055.88 | 38759838.22 |
| 6.1-rc8-bore-llvm-pstate_passive | 65406.99 | 16420531.96 | 33320511.46 |

**Comment by Slaviusz** [comment]
Please disregard the benchmarks. I found out the performance changes with time after kernel boot.

I re-did the benchmarks and there is next-to-none difference to acpi driver. Given the fact the schedutil governor is broken, at the moment it's probably not worth merging this in.

**Comment by ptr1337** [comment]
I wrote the maintainer of the patch. 
He found the issue with ZEN3 systems. ZEN4 was not affected from it. He will update the patch soon.

**Comment by ptr1337** [comment]
@Slaviusz 

Please check this patch, if schedutil is working fine now. I were in contact with the maintainer he got it finally today so far fixed on my side.
https://github.com/CachyOS/kernel-patches/commit/cbf7fcda4ab93ec7aae0562aab38ddb6c05ca08e

Performance seems to be a bit better then amd-pstate-epp.

**Comment by Slaviusz** [comment]
Will test it sometime later, thank you.

**Comment by Slaviusz** [comment]
After some phoronix stress-ng testing applied to 6.1.0-tkg-bore-llvm:

|governor | Forking | Context Switching | System V Message Passing |
| --- | --- | --- | --- |
| performance | 69,225.5 | 15,726,125.25 | 34,884,062.76 |
| schedutil | 67,005.98 | 15,601,039.53 | 33,127,599.36 |

However, schedutil governor now acts indistinguishable from performance. I fired up CoreFreq and package power consuption is the same with both governors (~35W idle). Even with schedutil governor the minimal frequency does not drop below 3,6 GHz (just like with performance).

**Comment by ptr1337** [comment]
At me the scaling works fine. It acts same as it does with the amd-pstate passive and schedutil.
![image](https://user-images.githubusercontent.com/70081076/208661356-3089ea2d-2d2d-4d16-a994-eade99529a44.png)

**Comment by Slaviusz** [comment]
![image](https://user-images.githubusercontent.com/30972602/208662324-5eedc314-700e-4b78-908f-b1b73ddbaf58.png)
![image](https://user-images.githubusercontent.com/30972602/208662604-ac04365c-3a79-4968-b8ea-54fc0cb7bcec.png)

**Comment by ptr1337** [comment]
![image](https://user-images.githubusercontent.com/70081076/208663205-e832e306-b402-4557-9ece-a629ad52a128.png)
Works well here, when in idle. But I write him about that
