### ISSUE TITLE
Kernel won't install on Nobara

### ISSUE THREAD

**Issue by Faugus** [Frogging-Family/linux-tkg#669]
Do you want to install the new Kernel ? Y/[n]: Y
Last metadata expiration check: 0:05:03 ago on qua 21 dez 2022 11:09:17.
Error: 
 Problem: problem with installed package kernel-devel-matched-6.0.14-201.fsync.fc36.x86_64
  - package kernel-devel-matched-6.0.13-201.fsync.fc36.x86_64 requires kernel-devel = 6.0.13-201.fsync.fc36, but none of the providers can be installed
  - package kernel-devel-matched-6.0.14-201.fsync.fc36.x86_64 requires kernel-devel = 6.0.14-201.fsync.fc36, but none of the providers can be installed
  - cannot install both kernel-devel-6.0.14_tkg_pds-1.x86_64 and kernel-devel-6.0.13-201.fsync.fc36.x86_64
  - cannot install both kernel-devel-6.0.14_tkg_pds-1.x86_64 and kernel-devel-6.0.14-201.fsync.fc36.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
 -> exit cleanup done

**Comment by KagoraTheGrindcoreAddict** [comment]
In your customization.cfg file, is winesync set to true?

I'm pretty sure Nobara ships with a winesync patched kernel and only 1 winesync kernel can be installed at a time so you would have to uninstall the default Nobara kernel (PLEASE DO NOT DO THIS unless you really know what you're doing or even better, how to recover from having no bootable kernels installed)

Personally I stopped using winesync just from the hassle of kernel juggling alone and I have not found a single game I play that benefits from the patch.
