### ISSUE TITLE
Questions about patches

### ISSUE THREAD

**Issue by FabseGP** [Frogging-Family/linux-tkg#671]
Is there a reason why we can't both have bcachefs-patches and mglru enabled at the same time? I couldn't find any issues (created by users here) related to that

Also, have you thought about adding the gcc-lto patch? 
https://github.com/sirlucjan/kernel-patches/tree/master/6.1/gcc-lto-patches-all

**Comment by ptr1337** [comment]
> Is there a reason why we can't both have bcachefs-patches and mglru enabled at the same time? I couldn't find any issues (created by users here) related to that
> 
> Also, have you thought about adding the gcc-lto patch? https://github.com/sirlucjan/kernel-patches/tree/master/6.1/gcc-lto-patches-all

Cause the patch conflicted each other when mglru was not merged 6.0 or lower.
MGLRU got merged with 6.1 and bcachefs is patching well with it. I have yesterday added the patchset.
The warning in the customization.cfg is just for kernel lower then 6.1.

I have tested the gcc lto patches for a while and also support them, but actually they are not correctly working if DEBUG/BTF is enabled. The build will fail with it enableld.
Also there was so far no performance benfit from them after bunch of benchmarks.

The gcc lto patches are very unstable right now. You better should wait for newer ones.
