### ISSUE TITLE
Cannot reinstall kernel after being installed once (version downgrade)

### ISSUE THREAD

**Issue by FGD-Garuda** [Frogging-Family/linux-tkg#674]
Hello,

I use a custom kernel name (linux-tkg-bore-amd) for all my versions.

I keep a few folders of older kernel versions I compile and whenever I need to rollback I just enter that folder and issue `makepkg -si`, then it asks if I want to install that specific old kernel and kernel images and it installs by replacing the previous version. Super simple and clean.

Last time I did that was a couple of months ago. Now I try to do it again and install 6.0.7 over 6.1.1. When I run `makepkg -si`, instead of installing the 2 *.zst image files it starts a download from the repo and displays the updated list of available kernel to compile. Currently:

~~~
-> External configuration file /xfs/git/tkg-bore-amd.cfg will be used and will override customization.cfg values.
-> Which kernel version do you want to install?
> 0) v6.1.1
1) v6.0.15
2) v5.15.85
3) v5.10.161
4) v5.4.228
5) Another (no longer maintained upstream)
~~~

I don't want to compile again a different version  I just want to reinstall the 2 image files that are in the folder.

I tried the following:

~~~
cd /xfs/git/linux-tkg-${kernel_flavor}
sudo cp -R . /usr/src/linux-tkg-${kernel_flavor}
cd /usr/src/linux-tkg-${kernel_flavor}
sudo make modules_install
sudo make install
sudo dracut --force --hostonly --kver $_kernelname $_dracut_options
sudo grub-mkconfig -o /boot/grub/grub.cfg 
~~~

But when I type `sudo make modules_install` I get the error `make *** No rule to make target 'modules_install'.  Stop.`

I get the same issues with `./install.sh install`

I am not good enough to manually troubleshoot this, just pointing out that the very simple way of reinstalling older compiled versions no longer works and I don't know how to do it again.

1- Can such a reinstall feature be brought back? It is extremely handy when you test stuff.
2- If it cannot, how do I reinstall manually?

Content of `linux-tkg` folder:

~~~
drwxr-xr-x    - root 27 Dec 19:39  .git
drwxr-xr-x    - root 27 Dec 19:22  .github
drwxr-xr-x    - root 27 Dec 19:22  linux-src-git
drwxr-xr-x    - root 27 Dec 19:22  linux-tkg-config
drwxr-xr-x    - root 27 Dec 19:22  linux-tkg-patches
drwxr-xr-x    - root 27 Dec 19:39  logs
drwxr-xr-x    - root 27 Dec 19:22  pkg
drwxr-xr-x    - root 27 Dec 19:22  src
.rw-r--r--  193 root 27 Dec 19:22  .gitignore
.rw-r--r-- 242k root 27 Dec 19:22  bore-amd_config.x86_64
.rw-r--r-- 1.1k root 27 Dec 19:39  current_env
.rw-r--r--  17k root 27 Dec 19:22  customization.cfg
.rwxr-xr-x  17k root 27 Dec 19:22  install.sh
.rw-r--r-- 242k root 27 Dec 19:22  kernelconfig.new
.rw-r--r--  64M root 27 Dec 19:22  linux-tkg-bore-amd-6.0.7-272-x86_64.pkg.tar.zst
.rw-r--r--  29M root 27 Dec 19:22  linux-tkg-bore-amd-headers-6.0.7-272-x86_64.pkg.tar.zst
.rw-r--r--  11k root 27 Dec 19:22  PKGBUILD
.rw-r--r--  13k root 27 Dec 19:22  README.md
~~~

Thanks!!

**Comment by AdelKS** [comment]
Hello! 

You do not need to go through `makepkg` to install Arch packages, use `sudo pacman -U [package name]` instead.

Cheers !

Adel

**Comment by FGD-Garuda** [comment]
Oh boy I feel so stupid for asking! Never thought of looking at pacman for this.

Works like a charm, of course. 👍 :)
