### ISSUE TITLE
5.15.86 Fsync Patch (Happy New Year Everyone)

### ISSUE THREAD

**Issue by compicat** [Frogging-Family/linux-tkg#675]
First of all, happy new year everyone.

Fsync patch is not patching with last lts release 5.15.86. It is is still ok with 5.15.85

Thanks in advance and thanks for great work again.

**Comment by Rydgel** [comment]
I get a patching error with 6.1.2 as well

**Comment by ptr1337** [comment]
> I get a patching error with 6.1.2 as well
> 
> ```
> ### Applying 0012-misc-additions.patch... ###
> patching file drivers/hid/hid-quirks.c
> Hunk #1 succeeded at 498 (offset 20 lines).
> patching file drivers/cpufreq/Kconfig
> Hunk #1 succeeded at 72 (offset 1 line).
> Hunk #2 succeeded at 84 (offset 2 lines).
> patching file drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c
> patching file drivers/gpu/drm/i915/gem/i915_gem_mman.c
> patching file drivers/gpu/drm/i915/i915_gem_evict.c
> patching file drivers/gpu/drm/i915/i915_gem_evict.h
> patching file drivers/gpu/drm/i915/i915_vma.c
> patching file drivers/gpu/drm/i915/selftests/i915_gem_evict.c
> patching file kernel/futex/core.c
> Reversed (or previously applied) patch detected!  Skipping patch.
> 3 out of 3 hunks ignored -- saving rejects to file kernel/futex/core.c.rej
> ```
> 
> (Seems like this a part of this patch landed in the Linux repo and is not needed anymore?)

https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/6.1/0012-misc-additions.patch#L317-L412

That part needs to be removed.

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/linux-tkg/pull/677
