### ISSUE TITLE
Automatically create a build folder in _kernel_work_folder

### ISSUE THREAD

**Issue by Elendil211** [Frogging-Family/linux-tkg#685]
The current behavior is, that the the folder that is configured in `_kernel_work_folder` is directly used for building. I don't think that this is very intuitive. 

For example, if I set `_kernel_work_folder="/tmp"`, it will try to remove everything in `/tmp`, and then fail with an obscure error that some file is not present.

Moreover, this behavior is very dangerous if the user sets it to something like `/home/user`.

A better solution would be, to automatically create a folder like `linux-tkg-build`, or something like that. So if the user sets `_kernel_work_folder="/tmp"`, the folder `/tmp/linux-tkg-build` would automatically be created. 

This would avoid confusion, as well as lost files and a broken system.

**Comment by AdelKS** [comment]
Agreed! Thanks @Elendil211 and @Tk-Glitch
