### ISSUE TITLE
Silverblue 37 - bricked boot after rolling back to default kernel

### ISSUE THREAD

**Issue by ghost** [Frogging-Family/linux-tkg#688]
After building `6.1.4_tkg_pds` and installing it with `rpm-ostree override replace kernel-6.1.4_tkg_pds-1.x86_64.rpm` on Silverblue 37, I've been using it for a couple days and life was good. Today I wanted to move back to the default kernel with `rpm-ostree override reset kernel` - seemed like the ostree deployment went through just as expected, but after `systemctl reboot` I'm thrown into emergency mode with the following:

```
sulogin: cannot open password database
Reloading system manager configuration
Starting default target
systemd-logind.service: Failed to connect stdout to the journal socket, ignoring: Connection refused
```

Any ideas what could be happening? Thank you!

**Comment by mystrdat** [comment]
It seems my issue was related to SELinux, [this comment](https://github.com/Frogging-Family/linux-tkg/issues/383#issuecomment-1013332774) fixed it for me.

**Comment by ryanmusante** [comment]
Are your SELinux file contexts set ? Did you run restorecon after the compile?

**Comment by mystrdat** [comment]
Restorecon on the rpm? I didn't, file contexts otherwise seem working as per default on Silverblue. I must say I didn't dabble in SELinux much yet before having this issue, what would be the correct process you are suggesting @ryanmusante ? Thanks for the help!

**Comment by trgeiger** [comment]
This isn't something obvious, but never run restorecon on Silverblue or other rpm-ostree distributions: https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_running_restorecon

That link includes troubleshooting steps that should fix your issue, I've run into them with other alternative kernels and this fixed it.

**Comment by AdelKS** [comment]
Hello please try #848 to see if we are good now

**Comment by AdelKS** [comment]
We will consider this issue as fixed since we have the correct config options to have a working SELinux. Feel free to reopen if ever.
