### ISSUE TITLE
make[4]: *** [scripts/Makefile.build:500: drivers] Error 2

### ISSUE THREAD

**Issue by JoneKone** [Frogging-Family/linux-tkg#689]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
Debian
idk

```
  CC [M]  drivers/staging/iio/meter/ade7854.o
  CC [M]  drivers/staging/iio/resolver/ad2s1210.o
  CC [M]  drivers/staging/iio/meter/ade7854-i2c.o
  CC [M]  drivers/staging/iio/meter/ade7854-spi.o
  LD [M]  drivers/staging/ks7010/ks7010.o
  LD [M]  drivers/staging/qlge/qlge.o
make[4]: *** [scripts/Makefile.build:500: drivers] Error 2
make[3]: *** [Makefile:1992: .] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:80: deb-pkg] Error 2
make: *** [Makefile:1636: deb-pkg] Error 2
 -> exit cleanup done
```

 - Attach the contents of your logs folder by drag & dropping each file into this message.
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/10407136/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/10407137/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/10407138/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/10407139/system-info.txt)

**Comment by Tk-Glitch** [comment]
```
976181: // Thread model: posix
976181: // Supported LTO compression algorithms: zlib zstd
976181: // gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
976181: // 
976181: // during GIMPLE pass: fre
976181: // drivers/media/pci/cx18/cx18-i2c.c: In function ‘init_cx18_i2c’:
976181: // drivers/media/pci/cx18/cx18-i2c.c:300:1: internal compiler error: Segmentation fault
976181: //   300 | }
976181: //       | ^
976181: // Please submit a full bug report,
976181: // with preprocessed source if appropriate.
976181: // See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
```
That's not a bug from us. If you have any CPU or RAM overclock, try with lower values.

**Comment by JoneKone** [comment]
It's a server on Hetzner. It has been static since .. year 2007.

**Comment by Tk-Glitch** [comment]
Hopefully you got it fixed, but yeah, nothing we can do about that.

**Comment by JoneKone** [comment]
get it fixed.

**Comment by Tk-Glitch** [comment]
I searched a bit and found out that the issue was reported upstream. It's a GCC10 bug which is triggered by a change between 6.1.0 and 6.1.2.

Here's a revert patch for the change triggering that bug [fb3d88ab354b.myrevert.txt](https://github.com/Frogging-Family/linux-tkg/files/10418448/fb3d88ab354b.myrevert.txt) (remove the `.txt` at the end of the filename and drop it inside the `linux-tkg/linux61-tkg-userpatches/` dir - create it if needed). That should allow the compilation to succeed with your GCC10 build.

**Comment by Tk-Glitch** [comment]
That being said, if possible, update your GCC to v11 or v12 :frog:

**Comment by JoneKone** [comment]
thank you for your help :)

**Comment by Tk-Glitch** [comment]
You're welcome!
