### ISSUE TITLE
Arch Linux is reverting a patch in 6.1.5. Shall this be copied to linux-tkg?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#691]
The new Arch package 6.1.5-arch2 is reverting a patch to fix a stability issue with amdgpu:
 _"Revert "drm/display/dp_mst: Move all payload info into the atomic state" "_

https://github.com/archlinux/linux?signed#tag=v6.1.5-arch2

https://github.com/archlinux/linux/commit/7c4fed4d2afd27d7acb8835f8e79f49c99c03cdf

I am wondering if linux-tkg should do the same. What is your policy on this?

**Comment by Tk-Glitch** [comment]
Yes we'll do the same until the regression is fixed or the revert merged
