### ISSUE TITLE
Question: What is the relationship between cachyos and linux-tkg?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#698]
linux-tkg is pulling a couple of patches from cachyos and I also found a cachyos-builder which is pointing to the linux-tkg repository:

https://github.com/Jeoshua/linux-cachyos-builder

Is cachyos somehow involved in linux-tkg or vice versa? 
Is there any remarkable difference between the cachyos kernels https://github.com/CachyOS/linux-cachyos and the linux-tkg kernel?

**Comment by ptr1337** [comment]
> linux-tkg is pulling a couple of patches from cachyos and I also found a cachyos-builder which is pointing to the linux-tkg repository:
> 
> https://github.com/Jeoshua/linux-cachyos-builder
> 
> Is cachyos somehow involved in linux-tkg or vice versa? Is there any remarkable difference between the cachyos kernels https://github.com/CachyOS/linux-cachyos and the linux-tkg kernel?

The repo above has nothing to do with linux-tkg. I think there wanted someone create on tkg based system with cachyos patches.
We provide a "kernel-manager" (https://github.com/CachyOS/kernel-manager) where you have the ability to install kernels from repos or also configure your own kernel based on cachyos.
Screenshots can be found here:
https://wiki.cachyos.org/en/home/kernel-manager

Actually linux-tkg is basically fetching some patches from us (CachyOS), like the BORE and TT Scheduler.
Besides that I am also contributing and helping a bit at linux-tkg

**Comment by mabod** [comment]
ok. So what is the reason for having the cachyos kernel instead of linux-tkg? Which patches you want to have in cachyos which are not in linux-tkg or, the other way round, are there any patches in linux-tkg which you dont want to see in cachyos.

For me it is very difficult to pick my kernel choice and your answer has the potential to greatly improve my decision making process ;-)

**Comment by ptr1337** [comment]
> ok. So what is the reason for having the cachyos kernel instead of linux-tkg? Which patches you want to have in cachyos which are not in linux-tkg or, the other way round, are there any patches in linux-tkg which you dont want to see in cachyos.
> 
> For me it is very difficult to pick my kernel choice and your answer has the potential to greatly improve my decision making process ;-)

Actually just test it yourself.
linux-cachyos does have way more upstream patches, where linux-tkg is a bit more conservative. Using upstream patches can bring also a regression.

If you need upstream features, like amd-pstate-epp, amd-pstate-guided, zstd 1.5.2 API, ... use linux-cachyos otherwise use linux-tkg.
linux-cachyos is maintained by @sir_lucjan and me. Also linux-cachyos is currently only available for arch and fedora based distros, where linux-tkg is working at mostly every distro.

Just test it on your own and then make your decision - that it

**Comment by mabod** [comment]
Thanks a lot. That helps.
