### ISSUE TITLE
Opensuse script problem and suggestion

### ISSUE THREAD

**Issue by d3vilguard** [Frogging-Family/linux-tkg#699]
From what I recon the automated script should build a package, install it, rebuild dracut and update grub. Well the last two were not done when using the script on Tumbleweed. Bottom commands need to be executed. 

sudo dracut --kver VERSION
example:
sudo dracut --kver 6.3.1_tkg_cfs-ga83b81b7392d

and update grub after

sudo grub2-mkconfig -o /boot/grub2/grub.cfg

**Comment by AdelKS** [comment]
the `grub` and `dracut` parts are done only if you are using the `Generic` approach. The RPM one stops at installing the RPM, and the package manager is responsible for the initramfs and grub 🤔

**Comment by d3vilguard** [comment]
Well did 3-4 compiles before it struck me what the deal was, so zypper doesn't to grub and dracut.

**Comment by Vistaus** [comment]
Are you sure it's sudo mkinitrd? Because Tumbleweed on my PC says that that command is not found.

**Comment by d3vilguard** [comment]
> Are you sure it's sudo mkinitrd? Because Tumbleweed on my PC says that that command is not found.

I really don't think you should be installing custom kernels if you can't figure out how to regenerate initramfs. 

It was mkinitrd for ages on opensuse. Recently in an update we switched to dracut. Use dracut.

**Comment by Vistaus** [comment]
Dracut did the job and I'm now booted into the tkg kernel!

**Comment by d3vilguard** [comment]
> Dracut did the job and I'm now booted into the tkg kernel!

Nice! And I have updated the original post so people can find the answer easier.

**Comment by fosspill** [comment]
Thank you guys for posting about this!

Just a week or so ago I started having to do this on Fedora too. Been working fine without it until now, but now running dracut seems to be needed for whatever reason.

**Comment by Tk-Glitch** [comment]
The recent changes I pushed (yesterday and today) regarding Suse TW support should fix packaging, dkms support and automated installation.
