### ISSUE TITLE
Not supported by GCC-10 ?

### ISSUE THREAD

**Issue by HougeLangley** [Frogging-Family/linux-tkg#7]
I used mostlyportable-gcc build GCC-10, Using this one build linux-tkg kernel and reboot my system. System black screen and no anything information.

**Comment by Tk-Glitch** [comment]
If you're on nvidia, keep in mind you need to build/rebuild your nvidia driver modules with the same GCC toolchain used for the kernel, or if you're using dkms, to make sure dkms is using your mostlyportable toolchain to build modules. This also means that if you have other kernels installed that weren't built with the same GCC, dkms will fail to build modules for them.

For dkms, adding your mostlyportable paths to `/etc/dkms/framework.conf` is a possible solution.
```
CUSTOM_GCC_PATH="/your/mostlyportable/gcc/dir"
PATH=${CUSTOM_GCC_PATH}/bin:${CUSTOM_GCC_PATH}/lib:${CUSTOM_GCC_PATH}/include:${PATH}
```

If you're on AMD/Intel, I have yet to build my own kernel with GCC10 so it's fully untested 🐸 
I'll do that soon.

**Comment by HougeLangley** [comment]
Thank you for your information. 

I am on Nvidia.

**Comment by HougeLangley** [comment]
No luck, 

I have been added 

```
CUSTOM_GCC_PATH="/your/mostlyportable/gcc/dir"
PATH=${CUSTOM_GCC_PATH}/bin:${CUSTOM_GCC_PATH}/lib:${CUSTOM_GCC_PATH}/include:${PATH

```
in /etc/makepkg.conf and /etc/dkms/framework.conf and build kernel and Nvidia successed. But reboot system still black screen.

**Comment by Tk-Glitch** [comment]
Built myself a few kernels with GCC10 to try (5.6.y, 5.7rc4 and 5.7rc5) and sure enough none of them boots. Considering only 5.7rc5 got some actual GCC10 fixes/workaround so far I would simply avoid using GCC10 for now.

**Comment by HougeLangley** [comment]
Thanks

**Comment by Tk-Glitch** [comment]
I got more data convincing me that the kernel is not yet in shape for GCC10. There are pending fixes coming our way. I'll be testing a few things to hopefully get rid of the huge blocker, at least.

**Comment by HougeLangley** [comment]
Thanks, I will try

**Comment by HougeLangley** [comment]
Working, Thanks again.
