### ISSUE TITLE
No option for coffee lake patches

### ISSUE THREAD

**Issue by XxRiKxX** [Frogging-Family/linux-tkg#705]
I am on arch and have a intel i5-9400f. During installation, when it asked to select cpu, there was no option for 9th gen cpus

**Comment by ptr1337** [comment]
Coffee Lake should be skylake as march.
Just check with:
`gcc -Q -march=native --help=target|grep -m1 march=`

**Comment by XxRiKxX** [comment]
do I need to compile again? I selected the native intel

**Comment by ptr1337** [comment]
> do I need to compile again? I selected the native intel

No, you dont

**Comment by XxRiKxX** [comment]
thanks
