### ISSUE TITLE
futex_waitv is already on kernels 5.16+, is the fsync patch still needed?

### ISSUE THREAD

**Issue by Patola** [Frogging-Family/linux-tkg#706]
Prior to opening this bug report, I have even asked Collabora about the fsync patch (see the bottom of the post): https://www.collabora.com/news-and-blog/blog/2023/02/17/the-futex-waitv-syscall-gaming-on-linux/#qcom1805

**Describe the bug**
 - Which OS do you encounter the bug on?
 Arch Linux

 - A clear and concise description of what the bug is.
 Use of a patch that might be deprecated on newer kernels (the fsync patch)
  
 - Attach the contents of your logs folder by drag & dropping each file into this message.
No need, the bug is just that kernel 5.16 and superior already have the futex_waitv() function, and thus the fsync patch seems either redundant or deprecated.

* I didn't attach logs because for this kind of bug report it doesn't seem to be needed *

**Comment by Tk-Glitch** [comment]
The fsync patch we offer on 5.16+ is a compat fix for prior to futex_waitv implementations. If you wanted to use legacy fsync (from proton 5.13 for example), you wouldn't be able to with 5.16+ futex_waitv alone. We offer no additional fsync related patch besides that one on 5.16+.

**Comment by Iglu47** [comment]
```
One reason these kernels still carry it might be to support older Proton builds.
Although, It's unlikely someone still uses these several years old Proton builds.
Most likely somebody just fogot to remove it from those kernels.
```
No, these patches are not "forgotten". They were left on purpose to ensure compatibility with older Proton builds. TkG patches are optional, so it's always possible to disable this for local builds.

Hope should be more clear now after https://github.com/Frogging-Family/linux-tkg/commit/d6388295382d9fea2ee701074143a60af5ffd31c:

- ["futex_waitv backports"](https://github.com/andrealmeid/futex_waitv_patches) have always been for 5.15 (or less) kernels only,
and are safely ignored from 5.16 onwards.

- `FUTEX_WAIT_MULTIPLE (opcode 31)` is now named "Fsync Legacy". This is the initial version of Fsync that only older stable versions of Valve Proton (4.11, 5.0 and 5.13) can work with.
If you don't supply public kernel builds, or you're pretty sure you won't be using such old versions of Proton, you can turn this off.

- "futex2" is a [DEPRECATED](https://github.com/Frogging-Family/linux-tkg/pull/345#issuecomment-961126151) interface, which will remain in linux-tkg only as history.
(don't touch `_fsync_futex2="false"`. Except if you know exactly what you are doing)

**Comment by Tk-Glitch** [comment]
Closing
