### ISSUE TITLE
Message from linux 6.2

### ISSUE THREAD

**Issue by robson-66** [Frogging-Family/linux-tkg#707]
Today I built linux-tkg 6.2, and in journalctl there was an entry in red with content
```
13:23:52 pc kernel: psi: inconsistent task state! task=9:kworker/u8:0 cpu=0 psi_flags=0 clear=1 set=4
```
I do not know what it means.

**Comment by ptr1337** [comment]
Are you using pds/bmq?
I think its a issue from the prjc patchset.
Disabling PSI should help

**Comment by robson-66** [comment]
> Używasz pds/bmq?
Yes, pds.

**Comment by ptr1337** [comment]
Yes, disable PSI in your config then the issue should be fixed. Its a known issue with prjc

**Comment by robson-66** [comment]
But where should I edit customization.cfg? Because I don't see anything related to PSI.

**Comment by robson-66** [comment]
OK, I disabled PSI in config.x86_64 and after rebuilding the message is no longer displayed.
Thanks for providing the solution.
