### ISSUE TITLE
Packaging deb fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by chipshopness** [Frogging-Family/linux-tkg#71]
Packaging deb fails on Ubuntu 20.04

    error: include/uapi/linux/vt.h: leak CONFIG_NR_TTY_DEVICES to user-space
    HDRINST usr/include/scsi/fc/fc_gs.h 
    make[6]: *** [scripts/Makefile.headersinst:63: usr/include/linux/vt.h] Error 1
    make[6]: *** Waiting for unfinished jobs....
    make[5]: *** [Makefile:1254: headers] Error 2
    make[4]: *** [scripts/Makefile.package:87: intdeb-pkg] Error 2
    make[3]: *** [Makefile:1491: intdeb-pkg] Error 2
    make[2]: *** [debian/rules:9: binary-arch] Error 2
    dpkg-buildpackage: error: fakeroot -u debian/rules binary subprocess returned exit status 2
    make[1]: *** [scripts/Makefile.package:77: deb-pkg] Error 2
    make: *** [Makefile:1491: deb-pkg] Error 2

It did work previously, as I've `5.8.5-tkg-pds` built on Sept 2.

5.7 and 5.9 also fail.

**Comment by AdelKS** [comment]
Hello!

Please retry with `_misc_adds=false` in `customization.cfg` and see if it fixes it. If it doesn't I will fix it asap.

**Comment by chipshopness** [comment]
That fixed it. Thanks.
