### ISSUE TITLE
Error applying patches

### ISSUE THREAD

**Issue by Andreiva13** [Frogging-Family/linux-tkg#712]
On 6.2.2 I got this error:
`-> Applying Glitched PDS patch`
`==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.`
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/10885915/prepare.log.txt)

**Comment by ptr1337** [comment]
Probably introduced by https://github.com/Frogging-Family/linux-tkg/compare/e1372ce04b21...ee6cc74e03bb

Maybe try to revert the commit and check if it works again. The prjc patch needs to be rebased against that, or these needs to be removed.

**Comment by Andreiva13** [comment]
Reverting [ee6cc74e03bb4911d2a7a90be5ccd74bb21dbf4a](https://github.com/Frogging-Family/linux-tkg/commit/ee6cc74e03bb4911d2a7a90be5ccd74bb21dbf4a) fixed this

**Comment by Rydgel** [comment]
Same with Bore

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/linux-tkg/pull/713

**Comment by TURING-V2** [comment]
applied pr #713 still fail
 * ERROR: sys-kernel/gentoo-sources-6.2.2::gentoo failed (prepare phase):
 *   patch -p1  failed with /etc/portage/patches/sys-kernel/gentoo-sources-6.2.2/0005-glitched-pds.patch

**Comment by dinckelman** [comment]
BORE patches also fail to apply on 6.2.2 with the following [log](https://termbin.com/nlnxr)

**Comment by ptr1337** [comment]
> BORE patches also fail to apply on 6.2.2 with the following [log](https://termbin.com/nlnxr)

I think that should be fixed with the above PR. But actually TKG should revert most of the added patches above, since they hardly conflict with other schedulers, which is not nice.
