### ISSUE TITLE
Feature request: tpm: disable hwrng for fTPM on some AMD designs

### ISSUE THREAD

**Issue by road2react** [Frogging-Family/linux-tkg#714]
The patch is located here: https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-tpmdd.git/commit/?id=ffe4a34b29aa672f1fa05f49a7e4c3ea4ab4e12f

This would fix a problem caused by AMD's fTPM firmware, but is not yet in the main upstream branch. This patch would backport the fix to an already-stable version.

**Comment by ptr1337** [comment]
Hi, 

the patch is already in the “fixes” patchset and branch (GitHub.com/cachyos/Linux)

**Comment by vinibali** [comment]
this has been already merged into 6.1:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.1.y&id=dc64dc4c80ae03a03221eb2e366e061b7074fae0
and 6.2:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.2.y&id=e143354b441786c4f356f7c9b1852bc723dbd81b
