### ISSUE TITLE
 kernel 6.2.2 doesn't support UEFI handover

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#715]
I have installed the kernel 6.2.2_pds but at boot the system say : kernel doesn't support UEFI handover. 
How to fix it ?

OS: Fedora 37

**Comment by ptr1337** [comment]
I already told TKG at the Discord to consider to enable EFI_HANDOVER_PROTOCOL, but this is offically deprecated.
Anyways, arch did also enable it now again, to avoid issues.

So, just enable EFI_HANDOVER_PROTOCOL at the config, and it is fixed.

**Comment by Everest10** [comment]
> 

Where can I find this option in the config submenus  ?

**Comment by Everest10** [comment]
> I already told TKG at the Discord to consider to enable EFI_HANDOVER_PROTOCOL, but this is offically deprecated. Anyways, arch did also enable it now again, to avoid issues.
> 
> So, just enable EFI_HANDOVER_PROTOCOL at the config, and it is fixed.

Where can I find this option in the config submenus ?

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/1f3a417ff7e9acd56b72413edc1d6ecf401a6e8c
