### ISSUE TITLE
new config option: SND_HDA_CTL_DEV_ID

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#717]
With kernel 6.1.16 and 6.2.3 a new config option is introduced: SND_HDA_CTL_DEV_ID
It is undefined in linux-tkg right now.

From the change.log:

```
commit f716ca292a7d1808d4135273bbdca093da195831
Author: Jaroslav Kysela <perex@perex.cz>
Date:   Thu Feb 2 10:20:13 2023 +0100

    ALSA: hda: Fix the control element identification for multiple codecs
    
    [ Upstream commit d045bceff5a904bd79d71dede9f927c00ce4906f ]
    
    Some motherboards have multiple HDA codecs connected to the serial bus.
    The current code may create multiple mixer controls with the almost
    identical identification.
    
    The current code use id.device field from the control element structure
    to store the codec address to avoid such clashes for multiple codecs.
    Unfortunately, the user space do not handle this correctly. For mixer
    controls, only name and index are used for the identifiers.
    
    This patch fixes this problem to compose the index using the codec
    address as an offset in case, when the control already exists. It is
    really unlikely that one codec will create 10 similar controls.
    
    This patch adds new kernel module parameter 'ctl_dev_id' to allow
    select the old behaviour, too. The CONFIG_SND_HDA_CTL_DEV_ID Kconfig
    option sets the default value.
    
    BugLink: https://github.com/alsa-project/alsa-lib/issues/294
    BugLink: https://github.com/alsa-project/alsa-lib/issues/205
    Fixes: 54d174031576 ("[ALSA] hda-codec - Fix connection list parsing")
    Fixes: 1afe206ab699 ("ALSA: hda - Try to find an empty control index when it's occupied")
    Signed-off-by: Jaroslav Kysela <perex@perex.cz>
    Link: https://lore.kernel.org/r/20230202092013.4066998-1-perex@perex.cz
    Signed-off-by: Takashi Iwai <tiwai@suse.de>
    Signed-off-by: Sasha Levin <sashal@kernel.org>
```

**Comment by compicat** [comment]
I m asking as a noob. I ve just compiled 6.2.3-tkg kernel. It stucks during restart or shutdown. Same with cachyos variations too @ptr1337 
6.2.2 does not have this issue.
This thing can be reason?

Thanks in advance.

**Comment by ptr1337** [comment]
> I m asking as a noob. I ve just compiled 6.2.3-tkg kernel. It stucks during restart or shutdown. Same with cachyos variations too @ptr1337 6.2.2 does not have this issue. This thing can be reason?
> 
> Thanks in advance.

On 6.2.3 we have this config option set. So, there should be all good.
6.2.3 was got a lot of commits, its really a question if its just cuz this config option.

**Comment by mabod** [comment]
> On 6.2.3 we have this config option set. 


I was checking package `linux62-tkg-cfs-headers-6.2.3-273-x86_64.pkg.tar.zst `
provided here: https://github.com/Frogging-Family/linux-tkg/releases/tag/v6.2.3

It has it not set:

```
# CONFIG_SND_HDA_CTL_DEV_ID is not set
```

And the option is also not set in 

https://github.com/Frogging-Family/linux-tkg/blob/v6.2.3/linux-tkg-config/6.2/config.x86_64

**Comment by ptr1337** [comment]
> > On 6.2.3 we have this config option set.
> 
> I was checking package `linux62-tkg-cfs-headers-6.2.3-273-x86_64.pkg.tar.zst ` provided here: https://github.com/Frogging-Family/linux-tkg/releases/tag/v6.2.3
> 
> It has it not set:
> 
> ```
> # CONFIG_SND_HDA_CTL_DEV_ID is not set
> ```
> 
> And the option is also not set in
> 
> https://github.com/Frogging-Family/linux-tkg/blob/v6.2.3/linux-tkg-config/6.2/config.x86_64
> 
> EDIT: And not setting this option is actually recommended:
> 
> ```
> config SND_HDA_CTL_DEV_ID
> 	bool "Use the device identifier field for controls"
> 	depends on SND_HDA_INTEL
> 	help
> 	  Say Y to use the device identifier field for (mixer)
> 	  controls (old behaviour until this option is available).
> 
> 	  When enabled, the multiple HDA codecs may set the device
> 	  field in control (mixer) element identifiers. The use
> 	  of this field is not recommended and defined for mixer controls.
> 
> 	  The old behaviour (Y) is obsolete and will be removed. Consider
> 	  to not enable this option.
> ```
He pointed to CachyOS.

Just look here, arch does also not enable it:
https://github.com/archlinux/svntogit-packages/commit/63322e2da65db5b826f2914f9eb91a54d5584a81

I don't send a PR to linux-tkg at all on config stuff, after the recent config related changes just got ignored. Not sure why, but I keep me away from config related stuff on linux-tkg :)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/2b5eda796817b9fb608df08aa601bf0b39e67cb0 and https://github.com/Frogging-Family/linux-tkg/commit/f95793c534c203034ef3b67a3883419982391ebf
