### ISSUE TITLE
6.2.5 ,Patch Failed -> 0006-add-acs-overrides_iommu.patch 

### ISSUE THREAD

**Issue by TURING-V2** [Frogging-Family/linux-tkg#718]

**Comment by TURING-V2** [comment]
patch -p1 < 0006-add-acs-overrides_iommu.patch

patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #1 succeeded at 4181 (offset 991 lines).
patching file drivers/pci/quirks.c
Hunk #1 succeeded at 3375 with fuzz 2 (offset 3 lines).
Hunk #2 FAILED at 4613.
1 out of 2 hunks FAILED -- saving rejects to file drivers/pci/quirks.c.rej

**Comment by ptr1337** [comment]
Replace the patchset with this one:
https://github.com/CachyOS/linux/commit/7e29283f2c02a51ae6944185d3a603d115159545.patch

**Comment by TURING-V2** [comment]
> Replace the patchset with this one: https://github.com/CachyOS/linux/commit/7e29283f2c02a51ae6944185d3a603d115159545.patch

thanks worked!

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/2b5eda796817b9fb608df08aa601bf0b39e67cb0
