### ISSUE TITLE
kernel versions appear blank when trying install.sh on Ubuntu 18.04

### ISSUE THREAD

**Issue by webodan** [Frogging-Family/linux-tkg#721]
**Describe the bug**
 - Which OS do you encounter the bug on?
 Ubuntu 18.04 (I can't use a more recent version for this specific distro)
 - A clear and concise description of what the bug is.

Simply put, I'm trying to build 6.2 tkg-bore + 15khz patches that will allow me to deploy it into a custom setup that employs an arcade style system connected to an old CRT TV running linux + emulationstation on top of it. 

I can't select the kernel version so it will start the patching process because no versions will show up, and exiting using control+C hangs the script.

I'm attaching a picture, and the 2 logs that it generated for me to demonstrate.

![image](https://user-images.githubusercontent.com/5558017/226210438-ceacd907-9275-48ae-899e-ab23c64f2137.png)

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/11012335/customization.cfg.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/11012336/system-info.txt)

It's a completely fresh git clone of this repository, + the 15khz kernel patches that can be found [here.](https://github.com/D0023R/linux_kernel_15khz)

Somebody else had success in patching the xanmod kernel so it will do 15khz perfectly fine in such a system, so it is possible, just that the tkg scripts appear to fail for me in this specific case. It's not me, since I'm already running linux-tkg in a couple other, more standard machines, also had very good results on Debian and Ubuntu in the past.

Hopefully someone can help me. Thanks in advance.

**Comment by AdelKS** [comment]
By the looks of it, the version of `git` the Ubuntu your are using ships is too old to retrieve tags from a remote repository. Try to put "6.2" in customization.cfg and maybe with some luck it can continue 🤔

**Comment by webodan** [comment]
> `_version="6.2"`

You might be right, after doing so, the terminal gave me this:

```error: unknown option `sort=version:refname'
usage: git ls-remote [--heads] [--tags] [--refs] [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url]
                     [--symref] [<repository> [<refs>...]]

    -q, --quiet           do not print remote URL
    --upload-pack <exec>  path of git-upload-pack on the remote host
    -t, --tags            limit to tags
    -h, --heads           limit to heads
    --refs                do not show peeled tags
    --get-url             take url.<base>.insteadOf into account
    --exit-code           exit with exit code 2 if no matching refs are found
    --symref              show underlying ref in addition to the object pointed by it

Which linux distribution are you running ?
if it's not on the list, chose the closest one to it: Fedora/Suse for RPM, Ubuntu/Debian for DEB
    0) Debian
    1) Fedora
    2) Suse
    3) Ubuntu
    4) Gentoo
    5) Generic
[0-5]: 3
Selected: Ubuntu
 -> Checking out latest kernel version of 6.2
 -> Which CPU sched variant do you want to build/install?
 -> Project C (pds) / BMQ (bmq) is usually a good balance for gaming.
 -> Select "cfs" (linux kernel's default) if unsure.
  > 0) CFS (Completely Fair Scheduler) Linux kernel's default
[0-0]:```

**Comment by AdelKS** [comment]
I see, you can hack your way around `git ls-remote` if you feel adventurous. The command is just used to fetch what are the available tags. So you can do your own clone at the right version and just make the script skip that part. Or you can simply install a newer version of git, maybe there's a ppa

**Comment by webodan** [comment]
actually, I fixed it the ugly way, but I'm posting it here in case anyone is in the same predicament I am:

there's this PPA script here that updates git in [this gist post here](https://gist.github.com/YuMS/6d7639480b17523f6f01490f285da509), for the sake of preservating it i'm also pasting the script itself here:

```#!/bin/bash
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git -y
```

It seems like it's going to work, for starters, it displayed the kernel versions just fine, it is now fetching 6.2.7, and since my patches are there, it should work!

thanks for pointing out that git was the issue, its been a while since I use Ubuntu as I prefer Garuda a lot more.
