### ISSUE TITLE
[Suggestion] Make option for non arch builds in script to disable building dbg pkgs

### ISSUE THREAD

**Issue by crlink271986** [Frogging-Family/linux-tkg#724]
I'm on ubuntu Jammy selected all the defaults but running dpkg-deb to build the ubuntu debs is taking a long time (Particularly around building the debug kernel deb) can you make in the next push a change to allow disabling (override) creation of the dbg packages? thanks

**Comment by Emimendoza** [comment]
A temporary solution is to set the `CONFIG_DEBUG_INFO_NONE` to `y`. You can easily do this by making a file in the linux-tkg directory and call it something like `disabledebug.myfrag` and having this text inside of it:
```
# CONFIG_DEBUG_INFO_DWARF5 is not set
CONFIG_DEBUG_INFO_NONE=y
```
Then when the script asks you `Found config fragment disabledebug.myfrag, apply it? [y/N]` select `y` and it wont make the debug kernel deb which will save a lot of time.
