### ISSUE TITLE
New, unset kernel options: KMSAN / MICROCODE_LATE_LOADING

### ISSUE THREAD

**Issue by dr460nf1r3** [Frogging-Family/linux-tkg#726]
Hey :) New kernel options seem to have popped up: 
```
KMSAN: detector of uninitialized values use (KMSAN) [N/y/?] (NEW)
Late microcode loading (DANGEROUS) (MICROCODE_LATE_LOADING) [N/y/?] (NEW)
```
It would be nice if those could be preset. Thanks!

**Comment by AdelKS** [comment]
This issue should be fixed by now, by simply updating our config to arch's latest one. Please feel free to reopen if it's still happening (I doesn't on my machine at least)
