### ISSUE TITLE
Fedora 37 akmod cant build kernel modules for kernel 6.3

### ISSUE THREAD

**Issue by TrixieUA** [Frogging-Family/linux-tkg#729]
Kernel builds just fine but it generates kernel with this package names kernel-6.3.0_tkg_cfs_g457391b03803-1 
It install fine but akmod cant build any modules
The same thing happend when i tried to build any rc kernels but with 6.2 release one built just fine

Way to reproduce
Build kernel on Fedora 37 and try to use any akmod modules

**Comment by TrixieUA** [comment]
Saw a little fix for fedora-rpm.patch, builded kernel, sadly the same thing again, it builded kernel-6.3.0_tkg_cfs_g457391b03803-1.x86_64 and akmods failed to buld any modules

**Comment by TrixieUA** [comment]
Linux 6.3.1 is out, i tried to build it with the script and it tries to build kernel-6.3.1_tkg_cfs_ga83b81b7392d which also does not work with akmod

**Comment by TrixieUA** [comment]
Here is a log from akmods, i think it cant find kernel-devel package, but i have installed it
[530.41.03-1-for-6.3.1_tkg_cfs-ga83b81b7392d.failed.log](https://github.com/Frogging-Family/linux-tkg/files/11363416/530.41.03-1-for-6.3.1_tkg_cfs-ga83b81b7392d.failed.log)

**Comment by patlefort** [comment]
The installed version is `6.3.1_tkg_cfs_ga83b81b7392d` but the akmods build log show that it is looking for version `6.3.1_tkg_cfs-ga83b81b7392d`. Could that be the problem?

**Comment by patlefort** [comment]
A workaround is to set `CONFIG_LOCALVERSION_AUTO=n` in a `.myfrag` file, see [`_config_fragments` in `customization.cfg`](https://github.com/Frogging-Family/linux-tkg/blob/ac13936ea1e409019c040f3e8f80329f013cde4c/customization.cfg#LL299C1-L299C18).
