### ISSUE TITLE
Perhaps wrong deb filename: cannot access archive 'linux-libc-dev_6.3.0-tkg-tt*.deb': No such file or directory

### ISSUE THREAD

**Issue by ZhaoZuohong** [Frogging-Family/linux-tkg#732]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on?
 - A clear and concise description of what the bug is.
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

I'm using linux-tkg to build kernel 6.3 with TT scheduler. When installing new kernel, it says

```
dpkg: error: cannot access archive 'linux-libc-dev_6.3.0-tkg-tt*.deb': No such file or directory
```

In `DEBS` directory, there are 4 debs:

- linux-headers-6.3.0-tkg-tt_6.3.0-1_amd64.deb
- linux-image-6.3.0-tkg-tt_6.3.0-1_amd64.deb
- linux-image-6.3.0-tkg-tt-dbg_6.3.0-1_amd64.deb
- linux-libc-dev_6.3.0-1_amd64.deb

Maybe the filename of linux-libc-dev package is wrong?

**Comment by AdelKS** [comment]
Which shell are you using ? it looks like the `*` is not getting expanded to actual package names, please retry with `bash` just to see :thinking:

**Comment by ZhaoZuohong** [comment]
I have just tried again with bash from Debian 11's repository. The final install step failed again:

```plaintext
dpkg: error: cannot access archive 'linux-libc-dev_6.3.4-tkg-tt*.deb': No such file or directory
```

In `DEBS` directory, the deb file includes libc is `linux-libc-dev_6.3.4-1_amd64.deb`.

I have tried linux-tkg with other CPU schedulers before. The deb filename generated in the past were:

- `linux-libc-dev_6.1.29-tkg-pds-1_amd64.deb`
- `linux-libc-dev_6.2.10-tkg-bore-1_amd64.deb`

But when I use the 6.3 series with TT scheduler, the name of libc-dev packages are:

- `linux-libc-dev_6.3.0-1_amd64.deb`
- `linux-libc-dev_6.3.3-1_amd64.deb`
- `linux-libc-dev_6.3.4-1_amd64.deb`

I will try other linux versions with different CPU schedulers tomorrow and report results then.

**Comment by joshgiesbrecht** [comment]
I'm having this same issue.

Note that the * expansion wouldn't work as shown above because it's looking for

`linux-libc-dev_6.3.0-tkg-tt*.deb`

while the actual file that's being built for libc-dev doesn't include the `-tkg' part of the filename like the other .deb files do.
