### ISSUE TITLE
Several erros trying to compile Linux 6.3.4-tkg-pds for fedora 38

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#735]
OS Fedora 38 current: 6.2.16_tkg_pds
_numadisable="true"

 -> Configuration done.
 -> Enabled ccache
 -> Building kernel RPM packages
  SYNC    include/config/auto.conf
  UPD     include/config/kernel.release
  UPD     .tmp_HEAD
  ARCHIVE linux.tar.gz
sh ./scripts/package/mkspec >./kernel.spec
============================ WARNING ============================
Your working tree has diff from HEAD, and also untracked file(s).
Please make sure you did 'git add' for all new files you need in
the source package.
=================================================================
rpmbuild --define '_topdir /home/dom/linux-tkg//linux-src-git/linux-tkg-rpmbuild' --target x86_64-linux -bs kernel.spec \
--define='_smp_mflags %{nil}' --define='_sourcedir rpmbuild/SOURCES' --define='_srcrpmdir .'
Building target platforms: x86_64-linux
Building for target x86_64-linux
warning: source_date_epoch_from_changelog set but %changelog is missing
Wrote: ./kernel-6.3.1_tkg_pds_ga83b81b7392d-1.src.rpm

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing
rpmbuild --define '_topdir /home/dom/linux-tkg//linux-src-git/linux-tkg-rpmbuild' --target x86_64-linux -rb kernel-6.3.1_tkg_pds_ga83b81b7392d-1.src.rpm \
--define='_smp_mflags %{nil}'
Installing kernel-6.3.1_tkg_pds_ga83b81b7392d-1.src.rpm
Building target platforms: x86_64-linux
Building for target x86_64-linux
warning: source_date_epoch_from_changelog set but %changelog is missing
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.vxREV4
+ umask 022
+ cd /home/dom/linux-tkg//linux-src-git/linux-tkg-rpmbuild/BUILD
+ cd /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILD
+ rm -rf linux

-------------------------------------------------------------------------------------------------------

                from ./include/linux/pagewalk.h:5,
                 from fs/proc/task_mmu.c:2:
fs/proc/task_mmu.c: In function 'clear_refs_write':
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1329:33: note: in expansion of macro 'min'
 1329 |                         start = min(start, -1) & PAGE_MASK;
      |                                 ^~~
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1330:31: note: in expansion of macro 'min'
 1330 |                         end = min(end, -1) & PAGE_MASK;
      |                               ^~~
  AS      arch/x86/entry/vdso/vdso32/system_call.o
  CC      fs/crypto/bio.o

-------------------------------------------------------------------------------------------------------

                 from ./include/linux/pagewalk.h:5,
                 from fs/proc/task_mmu.c:2:
fs/proc/task_mmu.c: In function 'clear_refs_write':
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1329:33: note: in expansion of macro 'min'
 1329 |                         start = min(start, -1) & PAGE_MASK;
      |                                 ^~~
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1330:31: note: in expansion of macro 'min'
 1330 |                         end = min(end, -1) & PAGE_MASK;
      |                               ^~~
  AS      arch/x86/entry/vdso/vdso32/system_call.o
  CC      fs/crypto/bio.o
  AR      fs/verity/built-in.a
  CC      fs/proc/inode.o

-------------------------------------------------------------------------------------------------------

  LD      arch/x86/purgatory/purgatory.ro
In file included from ./include/linux/kernel.h:26,
                 from ./arch/x86/include/asm/percpu.h:27,
                 from ./arch/x86/include/asm/preempt.h:6,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:56,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/mm.h:7,
                 from ./include/linux/pagewalk.h:5,
                 from fs/proc/task_mmu.c:2:
fs/proc/task_mmu.c: In function 'clear_refs_write':
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1329:33: note: in expansion of macro 'min'
 1329 |                         start = min(start, -1) & PAGE_MASK;
      |                                 ^~~
./include/linux/minmax.h:20:35: warning: comparison of distinct pointer types lacks a cast
   20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                                   ^~
./include/linux/minmax.h:26:18: note: in expansion of macro '__typecheck'
   26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~
./include/linux/minmax.h:36:31: note: in expansion of macro '__safe_cmp'
   36 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~
./include/linux/minmax.h:67:25: note: in expansion of macro '__careful_cmp'
   67 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~
fs/proc/task_mmu.c:1330:31: note: in expansion of macro 'min'
 1330 |                         end = min(end, -1) & PAGE_MASK;
      |                               ^~~
  LD      arch/x86/purgatory/purgatory.chk

-------------------------------------------

  CC [M]  fs/dlm/lowcomms.o
  CC      arch/x86/kernel/probe_roms.o
mm/page_alloc.c: In function 'rmqueue_bulk':
mm/page_alloc.c:3141:31: warning: unused variable 'last_mod' [-Wunused-variable]
 3141 |         int i, allocated = 0, last_mod = 0;
      |                               ^~~~~~~~
mm/page_alloc.c:3140:20: warning: unused variable 'can_resched' [-Wunused-variable]
 3140 |         const bool can_resched = !preempt_count() && !irqs_disabled();
      |                    ^~~~~~~~~~~
  CC      mm/shuffle.o
  CC [M]  fs/nls/nls_koi8-r.o
  CC [M]  fs/netfs/iterator.o

-------------------------------------------

  CC [M]  fs/xfs/scrub/rtbitmap.o
  AR      fs/built-in.a
  CC [M]  fs/xfs/scrub/quota.o
  CC [M]  fs/xfs/scrub/agheader_repair.o
  CC [M]  fs/xfs/scrub/bitmap.o
  CC [M]  fs/xfs/scrub/repair.o
  LD [M]  fs/xfs/xfs.o
make[2]: *** [Makefile:2028: .] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Ut4rwn (%build)

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Ut4rwn (%build)
make[1]: *** [scripts/Makefile.package:69: rpm-pkg] Error 1
make: *** [Makefile:1659: rpm-pkg] Error 2
 -> exit cleanup done

**Comment by AdelKS** [comment]
Closing  this issue, we keep the latest one #751
