### ISSUE TITLE
problem boot

### ISSUE THREAD

**Issue by pipes80-collab** [Frogging-Family/linux-tkg#736]
I'm having trouble booting with refind, basically I would need the initramfs files for me to be renamed without too many signs -, mine is named initramfs-linux63-tkg-bmq-fallback.img and initramfs-linux63-tkg-bmq.img, named in this way refind fails to boot the system and hangs me

**Comment by jnines** [comment]
Are you letting refind search through bootloaders or are you setting manual stanzas?  It works fine for me with the latter.

```
menuentry "TKG 6.3" {
    volume   "TKG"
    icon     /EFI/refind/themes/metal/img/TKG.png
    loader   /vmlinuz-linux63-tkg-pds
    initrd   /initramfs-linux63-tkg-pds.img
    options  "root=PARTUUID=249ef0d9-477d-0545-9cfd-565217414599 rw rootflags=subvol=@ initrd=amd-ucode.img processor.max_cstate=5 acpi_enforce_resources=lax module.sig_enforce=1"
  	submenuentry "Boot using fallback initramfs" {
    		initrd /initramfs-linux63-tkg-pds-fallback.img
	}
    submenuentry "Boot to terminal" {
        add_options "systemd.unit=multi-user.target"
    }
}
```

Beyond that there's a config setting:
```
#### SPESHUL OPTION ####

# If you want to bypass the stock naming scheme and enforce something else (example : "linux") - Useful for some bootloaders requiring manual entry editing on each release.
# !!! It will also change pkgname - If you don't explicitely need this, don't use it !!!
_custom_pkgbase=""

```

**Comment by pipes80-collab** [comment]
thanks for this advice i will try but i doubt it will work because i use more custom kernels and i need a method to rename vmlinuz

**Comment by jnines** [comment]
If you set `_custom_pkgbase="tkgbmq"` you will get `vmlinuz-tkgbmq`, `initramfs-tkgbmq.img`, and `initramfs-tkgbmq-fallback.img`

**Comment by pipes80-collab** [comment]
Problem solved, thanks
