### ISSUE TITLE
Project C patch not working with kernel 6.3.1

### ISSUE THREAD

**Issue by Tatsh** [Frogging-Family/linux-tkg#737]
The patch works fine with 6.3.0 but fails with a lot of errors for 6.3.1. I am using the patch files on Gentoo where normally most of the patches work fine as long as they are updated.

**Comment by whitehara** [comment]
You can try a new patch 'prjc_v6.3-r1.patch' from original site:

https://gitlab.com/alfredchen/projectc/-/blob/master/6.3/prjc_v6.3-r1.patch

This new patch worked fine for me.

**Comment by Tatsh** [comment]
Not for me though I do have a series of patches that come before it. I put it in the same place as it would have been if it came from this project. It seems it has less issues but still does not apply fully. Basically it needs a rebase.

**Comment by Tatsh** [comment]
Never mind. Gentoo is already applying this patch with `USE=experimental` so getting it here is unnecessary.
