### ISSUE TITLE
Does not boot (no error message, boot just hangs forever)

### ISSUE THREAD

**Issue by obj-obj** [Frogging-Family/linux-tkg#742]
The kernel doesn't boot at all after compiling on my desktop PC, but works fine on my laptop. The config file is the same on both of them, apart from the CPU architecture and core count

Weird thing is, it was booting fine on my desktop PC for a while, and then stopped working without me changing anything. I've tried recompiling a few times since then, but it doesn't seem to have helped

Mainly just need help troubleshooting

**Comment by ptr1337** [comment]
> The kernel doesn't boot at all after compiling on my desktop PC, but works fine on my laptop. The config file is the same on both of them, apart from the CPU architecture and core count
> 
> Weird thing is, it was booting fine on my desktop PC for a while, and then stopped working without me changing anything. I've tried recompiling a few times since then, but it doesn't seem to have helped
> 
> Mainly just need help troubleshooting

There were some reports that if setting the CPU architecture to a exact one, they were not able to boot.
Its a question if this is a issue from the patch itself or from the compiler, since someone reported that clang is working fine.

Try to put a generic-Vx one and check again, these one are commonly working fine.

**Comment by obj-obj** [comment]
I'll try compiling with native instead of a set arch then, I was *going* to do that but the comments in the config file advised against it

**Comment by obj-obj** [comment]
Nope, still doesn’t boot

**Comment by obj-obj** [comment]
Even with it set to `generic`, no luck

**Comment by obj-obj** [comment]
The issue was that I had some `CFLAGS` set globally (and I assumed they wouldn't affect the package)
