### ISSUE TITLE
Arch/Amd Zen3 -- Fail to Compile

### ISSUE THREAD

**Issue by Unhall0w3d** [Frogging-Family/linux-tkg#743]
on Arch Linux I am encountering an error compiling the linux-tkg kernel against the latest 6.3 (option 0) on an AMD Ryzen 7 5800X using the options for Zen3. No Anbox, no ACS patch. I understand that disabling numa in the customization.cfg will bypass issues compiling the kernel, however, when I went that route I had issues running a game on one monitor and youtube video on the other. I had consistent lockups within 5 minutes a few times in a row and rolled back to 6.2.14.

I have not attempted to compile against a generic type, I (maybe incorrectly) understand there are optimizations related to compiling against your particular architecture type. I have attached the last section of shell output when the error occurrs, and attached requested logs.

**Describe the bug**
 - Which OS do you encounter the bug on?

OS: ArcoLinux (Arch)
Kernel: 6.2.14-273-tkg-bmq
CPU: AMD Ryzen 7 5800X (16) @ 3.600GHz

 - A clear and concise description of what the bug is.
 <ommitted logs>
  CC [M]  drivers/gpu/drm/nouveau/nv50_fence.o
  CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp2_transition.o
  CC [M]  drivers/gpu/drm/nouveau/nv84_fence.o
  CC [M]  drivers/gpu/drm/nouveau/nvc0_fence.o
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  LD [M]  drivers/gpu/drm/nouveau/nouveau.o
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a

  AR      built-in.a
  AR      vmlinux.a
  LD      vmlinux.o
vmlinux.o: warning: objtool: hyperv_init+0x40d: unreachable instruction
  OBJCOPY modules.builtin.modinfo
  GEN     modules.builtin
  MODPOST Module.symvers
ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] Error 1
make: *** [Makefile:1980: modpost] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done

  -> compilation time :

real	19m7.041s
user	261m47.973s
sys	24m44.182s

 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/11471067/customization.cfg.txt)

[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/11471065/system-info.txt)

[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11471123/shell-output.log.txt)

[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11471066/prepare.log.txt)

**Comment by Tk-Glitch** [comment]
Did you pull since https://github.com/Frogging-Family/linux-tkg/commit/6c9383631daac3877e698fedc82a018dd4ee78e7

I checked the generated config and mlx5 is definitely disabled, which fixes that specific issue you're hitting.
