### ISSUE TITLE
BORE scheduler seems unavailable in 6.3

### ISSUE THREAD

**Issue by FGD-Garuda** [Frogging-Family/linux-tkg#745]
Hello,

Since 6.3.0 (and today I tried with 6.3.2) the BORE scheduler does not seem to be available anymore.

I use custom `_EXT_CONFIG_PATH` and choose BORE by default in it.
Since it's not available, the manual installer pops-up this:

~~~
-> Which kernel version do you want to install?
0) v6.4-rc2
> 1) v6.3.2
2) v6.2.15
3) v6.1.28
4) v6.0.19
5) v5.15.111
6) v5.10.179
7) v5.4.242
8) Another (no longer maintained upstream)
[0-8]: 1
Selected: v6.3.2
==> WARNING: Your cpusched selection ( bore ) is not available for the selected kernel version.
==> WARNING: Please select another
-> Which CPU sched variant do you want to build/install?
-> Project C (pds) / BMQ (bmq) is usually a good balance for gaming.
-> Select "cfs" (linux kernel's default) if unsure.
> 0) CFS (Completely Fair Scheduler) Linux kernel's default
1) Project C / PDS
2) Project C / BMQ
3) TT (TaskType) 
~~~

I use `makepkg -si` under Arch to start the compile process.

While searching for this behavior (I don't know if it's an issue or cuz BORE will no longer be available for some reason) I came across this thread https://github.com/Frogging-Family/linux-tkg/issues/723

Not sure if it's related and what to do next.

Thanks

**Comment by ptr1337** [comment]
It is just not enabled in the script yet. You can just enable it, patching should work fine.

**Comment by ptr1337** [comment]
Same counts for the TT Scheduler. I updated all patches

**Comment by FGD-Garuda** [comment]
Oh that's interesting, I didn't know something was required in the patches.
Can you backtrack a little, which patch/script needs to be updated using which data in it?

Like in here?
https://github.com/Frogging-Family/linux-tkg/tree/master/linux-tkg-patches/6.3

**Comment by ptr1337** [comment]
> Oh that's interesting, I didn't know something was required in the patches.

Hi,

The TT and BORE Scheduler gets fetched from https://github.com/CachyOS/kernel-patches .

You just need to modify the prepare file here:
https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/prepare#L288-L290

You can do a PR if you want to.

**Comment by FGD-Garuda** [comment]
> You just need to modify the prepare file here:
> https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/prepare#L288-L290

OMG! That's as easy as drinking a beer! 🍺 
I am now even able to compile RCs with BORE. Not saying it's best, it's for testing purposes (all RCs are to me anyway).

I learned something great today, thank you so much! 👍

**Comment by redglobuli** [comment]
https://github.com/Frogging-Family/linux-tkg/pull/747
