### ISSUE TITLE
Failed compile in Artix

### ISSUE THREAD

**Issue by ArchBtw8683** [Frogging-Family/linux-tkg#746]
I tried compiling the kernel on Artix, changing the configfile for it to work on non-systemd distros as said.

[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11506407/prepare.log.txt)

Error message wasn't in the logs file, just in case.

vmlinux.o: warning: objtool: hyperv_init+0x40d: unreachable instruction
  OBJCOPY modules.builtin.modinfo
  GEN     modules.builtin
  MODPOST Module.symvers
  CC      .vmlinux.export.o
  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      .tmp_vmlinux.btf
  BTF     .btf.vmlinux.bin.o
  
btf_encoder__encode: btf__dedup failed!
Failed to encode BTF
  LD      .tmp_vmlinux.kallsyms1
  NM      .tmp_vmlinux.kallsyms1.syms
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  NM      .tmp_vmlinux.kallsyms2.syms
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  BTFIDS  vmlinux
libbpf: failed to find '.BTF' ELF section in vmlinux
FAILED: load BTF from vmlinux: No data available
make[1]: *** [scripts/Makefile.vmlinux:35: vmlinux] Error 255
make[1]: *** Deleting file 'vmlinux'
make: *** [Makefile:1252: vmlinux] Error 2
==> ERROR: A failure occurred in build().

**Comment by ptr1337** [comment]
You need to install pahole 1.25 for 6.3

**Comment by ArchBtw8683** [comment]
It worked.
