### ISSUE TITLE
No bcachefs modules in version 6.2 and higher

### ISSUE THREAD

**Issue by pog5** [Frogging-Family/linux-tkg#748]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on? Any
 - A clear and concise description of what the bug is. The bcachefs patch is not present on kernel versions 6.2 and 6.3
 - Attach the contents of your logs folder by drag & dropping each file into this message. (unneeded)
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

**Comment by ptr1337** [comment]
I have added for 6.3 bcachefs in this PR:
https://github.com/Frogging-Family/linux-tkg/pull/749
