### ISSUE TITLE
Does this linux fork add any security patches?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#75]
Hello there,
I would like to know if this kernel also adds some security patches or just some for high performance. Thanks for your answer.
PS Very nice work you all did there

**Comment by FLGX06** [comment]
This is not actually a fork of Linux but rather an installer/packager of Linux which makes it simple to build and patch. You can use hardened kernel config if that's what you meant by security patches but you have to CFS CPU scheduler. You can find some customization options in [customization.cfg](https://github.com/Frogging-Family/linux-tkg/blob/master/linux58-tkg/customization.cfg) and modify them. Also yes, you can get higher performance by changing some options in `customization.cfg` such as changing CPU scheduler **might** help or make things worse, but that depends on your hardware.
You might also want to take a look at [community-patches](https://github.com/Frogging-Family/community-patches) which you can add to `customization.cfg` to `_community_patches` if you know what are you doing

**Comment by Axilot** [comment]
Ah okay. So Linux-tkg is actually linux but with some patches regarding performance? How is the performance compared to linux-zen? But i have no issues at all right now :)

**Comment by AdelKS** [comment]
All you have to do is to try for yourself for your specific use case and benchmark (if you have time) or feel (if you don't have time) :P

**Comment by FLGX06** [comment]
@Axilot The performance is affected by what options you select, which depend on your hardware as I said. Also I forgot there's zenify option which applies linux-zen patches (I think so at least). So with that option and other options customized for your hardware peformance **may** be actually better or at least the same as on linux-zen unless you set something your hardware doesn't like

**Comment by Axilot** [comment]
I already configured some stuff in the configuration depending on my hardware. Are the zenify options included into the config file? But i think ive enabled something with zen in its name.

**Comment by FLGX06** [comment]
> I already configured some stuff in the configuration depending on my hardware. Are the zenify options included into the config file? But i think ive enabled something with zen in its name.

There's an option called `_zenify` which is enabled by default in `customization.cfg`

**Comment by Axilot** [comment]
Ah okay, thanks!
