### ISSUE TITLE
`skylake` and `skylakex`?

### ISSUE THREAD

**Issue by Impeta** [Frogging-Family/linux-tkg#750]
I have a Kaby Lake processor, and I would like to use your own handmade kernels and patches, though I stumbled upon both these micro-architectures whose descriptions are nowhere to be explained across your Github repository and issues. Could you please tell me what are their differences? Which one should I really pick, if I have a 9th gen. Kaby Lake processor? Cheers in advance!

**Comment by jnines** [comment]
SkylakeX were HEDT parts, Intel's high-end for desktops/workstations that used the 2066 socket.  I'm guessing everything that wasn't HEDT in that era is thought of as Skylake as they were constantly refreshed during that time.

**Comment by AdelKS** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Kaby_Lake) shows that it's a Skylake architecture (on the summary on the right). The patches for microarchitectures is from here https://github.com/graysky2/kernel_compiler_patch and they do not list 7th gen on their README, which is to be expected, all good now !
