### ISSUE TITLE
Trying to compile the kernel 6.3.4 with error :((

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#751]
I'm fedora 38 user and trying to compile the kernel 6.3.4 pds and get this error. how to fix it ?

sh ./scripts/package/mkspec >./kernel.spec
============ WARNING ===========
Your working tree has diff from HEAD, and also untracked file(s). Please make sure you did 'git add' for all new files you need in the source package.
===============================
rpmbuild --define '_topdir /home/dom/linux-tkg//linux-src-git/linux-tkg-rpmbuild' --target x86_64-linux -bs kernel.spec \
--define='_smp_mflags %{nil}' --define='_sourcedir rpmbuild/SOURCES' --define='_srcrpmdir .'
Construindo plataformas de destino: x86_64-linux
Construindo para o destino x86_64-linux
warning: source_date_epoch_from_changelog set but %changelog is missing
Gravou: ./kernel-6.3.4_tkg_pds_g17f2d782f18c-1.src.rpm

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

**Comment by Everest10** [comment]
Could someone please comment on this issue?

**Comment by AdelKS** [comment]
Hello,

I'm here to comment ! Isn't this issue the same as the one you opened in #738 ?

**Comment by Everest10** [comment]
> Hello,
> 
> I'm here to comment ! Isn't this issue the same as the one you opened in #738 ?
> 
> PS: oh and also #735 thinking Please keep it to one issue if these are all the same problem.
> 
> PPS: please follow the issue template and attach the logs in the 'logs' folder, simply by dragging and dropping them into your message. People then will be able to have a look when possible, if possible.
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/11587389/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11587390/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11587391/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/11587392/system-info.txt)

OK. Here is the log files ...

**Comment by AdelKS** [comment]
Okay now we have all the information we need, here's the error that's been happening on your end:
```
make[5]: *** No rule to make target 'kernel/sched/alt_core.o', needed by 'kernel/sched/built-in.a'.  Stop.
make[4]: *** [scripts/Makefile.build:494: kernel/sched] Error 2
make[3]: *** [scripts/Makefile.build:494: kernel] Error 2
make[3]: *** Waiting for unfinished jobs....
```

And weirdly enough, it looks the `rpm-pkg` target is patching some files
```
+ umask 022
+ cd /home/dom/linux-tkg//linux-src-git/linux-tkg-rpmbuild/BUILD
+ cd /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILD
+ rm -rf linux
+ /usr/lib/rpm/rpmuncompress -x /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/SOURCES/linux.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd linux
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ cp /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/SOURCES/config .config
+ patch -p1
patching file Documentation/admin-guide/kernel-parameters.txt
patching file Documentation/admin-guide/sysctl/kernel.rst
patching file Makefile
patching file arch/x86/Kconfig.cpu
patching file arch/x86/Makefile
patching file arch/x86/include/asm/vdso/processor.h
patching file arch/x86/include/asm/vermagic.h
patching file block/elevator.c
patching file drivers/Makefile
patching file drivers/cpufreq/Kconfig
patching file drivers/cpufreq/cpufreq_ondemand.c
patching file drivers/cpufreq/intel_pstate.c
patching file drivers/hid/hid-quirks.c
patching file drivers/idle/intel_idle.c
patching file drivers/infiniband/core/addr.c
patching file drivers/input/evdev.c
patching file drivers/pci/pci.c
patching file fs/dcache.c
patching file fs/proc/base.c
patching file fs/proc/internal.h
patching file fs/proc/task_mmu.c
patching file include/asm-generic/resource.h
patching file include/linux/mm.h
patching file include/linux/pageblock-flags.h
patching file include/linux/pagemap.h
patching file include/linux/sched.h
patching file include/linux/sched/deadline.h
patching file include/linux/sched/prio.h
patching file include/linux/sched/rt.h
patching file include/linux/sched/topology.h
patching file include/linux/user_namespace.h
patching file include/linux/wait.h
patching file init/Kconfig
patching file init/Makefile
patching file init/init_task.c
patching file kernel/Kconfig.hz
patching file kernel/Kconfig.preempt
patching file kernel/cgroup/cpuset.c
patching file kernel/delayacct.c
patching file kernel/exit.c
patching file kernel/fork.c
patching file kernel/locking/rtmutex.c
patching file kernel/locking/rwsem.c
patching file kernel/sched/Makefile
patching file kernel/sched/build_policy.c
patching file kernel/sched/build_utility.c
patching file kernel/sched/cpufreq_schedutil.c
patching file kernel/sched/cputime.c
patching file kernel/sched/debug.c
patching file kernel/sched/fair.c
patching file kernel/sched/idle.c
patching file kernel/sched/pelt.c
patching file kernel/sched/pelt.h
patching file kernel/sched/rt.c
patching file kernel/sched/sched.h
patching file kernel/sched/stats.c
patching file kernel/sched/stats.h
patching file kernel/sched/topology.c
patching file kernel/sched/wait.c
patching file kernel/sysctl.c
patching file kernel/time/hrtimer.c
patching file kernel/time/posix-cpu-timers.c
patching file kernel/trace/trace_selftest.c
patching file kernel/user_namespace.c
patching file mm/huge_memory.c
patching file mm/page-writeback.c
patching file mm/page_alloc.c
patching file mm/vmscan.c
patching file net/ipv4/Kconfig
patching file net/ipv4/inet_connection_sock.c
patching file net/ipv4/tcp.c
patching file net/sched/Kconfig
patching file scripts/package/mkspec
patching file scripts/setlocalversion
```

I think that is not supposed to happen, @whitehara is it doing the same on your end  ?

**Comment by whitehara** [comment]
> I think that is not supposed to happen, @whitehara is it doing the same on your end ?

I'm not using the install.sh script for my package. I use the patches only. So I don't have my install.sh result.
But I think it is OK, because mkspec generates the diff.patch and it is applied during the rpmbuild.


```
make[5]: *** No rule to make target 'kernel/sched/alt_core.o', needed by 'kernel/sched/built-in.a'.  Stop.
make[4]: *** [scripts/Makefile.build:494: kernel/sched] Error 2
make[3]: *** [scripts/Makefile.build:494: kernel] Error 2
make[3]: *** Waiting for unfinished jobs....
```

I think this is caused by missing of "CONFIG_SCHED_ALT=y"
Please check generated config. (Maybe /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/SOURCES/config )

**Comment by Everest10** [comment]
> > I think that is not supposed to happen, @whitehara is it doing the same on your end ?
> 
> I'm not using the install.sh script for my package. I use the patches only. So I don't have my install.sh result. But I think it is OK, because mkspec generates the diff.patch and it is applied during the rpmbuild.
> 
> ```
> make[5]: *** No rule to make target 'kernel/sched/alt_core.o', needed by 'kernel/sched/built-in.a'.  Stop.
> make[4]: *** [scripts/Makefile.build:494: kernel/sched] Error 2
> make[3]: *** [scripts/Makefile.build:494: kernel] Error 2
> make[3]: *** Waiting for unfinished jobs....
> ```
> 
> I think this is caused by missing of "CONFIG_SCHED_ALT=y" Please check generated config. (Maybe /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/SOURCES/config )

There is no folder or file ../sources/config

![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/cf2bf1c5-4c09-4db5-8dba-8aa62e1285ed)

**Comment by whitehara** [comment]
> @whitehara There is no folder or file ../SOURCES/config

Oh, is it cleared?
Maybe you can try to find .config file in the BUILD dir, like this:
`
find /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/ -type f -name .config
`

**Comment by Everest10** [comment]
> > @whitehara There is no folder or file ../SOURCES/config
> 
> Oh, is it cleared? Maybe you can try to find .config file in the BUILD dir, like this: `find /home/dom/linux-tkg/linux-src-git/linux-tkg-rpmbuild/ -type f -name .config`

"CONFIG_SCHED_ALT=y" was already there.

![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/0c0d2bcc-803e-405c-b1c1-acefb0fef9bb)

**Comment by whitehara** [comment]
- Do you have the file "kernel/sched/alt_core.c" in BUILD dir?
- In "kernel/sched/Makefile", do you have the line "obj-y += alt_core.o" ?

**Comment by whitehara** [comment]
> No. alt_core.c
Is it correct? Pl ease check "kernel/sched" directory.
(From the screenshot, you are checking "kernel" directory. Not the "kernel/sched" directory)

> I don't understand why you asked if I have the files. The files are not mine, they are from the github repository.

Because your error message shows it failed to compile "alt_core.c".
The file is provided by "0009-prjc_v6.3-r1.patch". And it is used by PDS ,etc.

If the "alt_core.c" is not there, you will see the error message.
And that means applying the patch was failed while running the script.

**Comment by Everest10** [comment]
> > No. alt_core.c
> > Is it correct? Pl ease check "kernel/sched" directory.
> > (From the screenshot, you are checking "kernel" directory. Not the "kernel/sched" directory)
> 
> > I don't understand why you asked if I have the files. The files are not mine, they are from the github repository.
> 
> Because your error message shows it failed to compile "alt_core.c". The file is provided by "0009-prjc_v6.3-r1.patch". And it is used by PDS ,etc.
> 
> If the "alt_core.c" is not there, you will see the error message. And that means applying the patch was failed while running the script.

b/kernel/sched/alt_core.c

alt_core.c file missing. Could be it a problem in upstream ?

**Comment by Everest10** [comment]
It's strange that fedora is already there 6.3.4, and not being able to compile tkg from 6.3

@whitehara @AdelKS @Tk-Glitch 

![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/907850f5-eebf-4d9b-88e3-6e9cae2fe4a1)

**Comment by whitehara** [comment]
> alt_core.c file missing. Could be it a problem in upstream ?

This is a problem of install.sh. It isn't updated for the new scripts in the kernel.
You already see the cause from the message below. At the top of this issue.

> ============ WARNING ===========
> Your working tree has diff from HEAD, and also untracked file(s). Please make sure you did 'git add' for all new files you need in the source package.

I posted #752 to fix the issue.
I also wrote the detail in #752.

You can try it.

**Comment by Everest10** [comment]
Fixed !
