### ISSUE TITLE
I don't see an option in CPU compiler optimizations for Zen+ Picasso CPU'S

### ISSUE THREAD

**Issue by Tmedina923** [Frogging-Family/linux-tkg#753]
Hey i have AMD Ryzen 5 3500U with Radeon Vega Mobile GFX and i didn't see any options for Zen + (Picasso) while building. I'm not sure if it's under a different name or has to be added?

**Comment by Tk-Glitch** [comment]
Zen+ is Zen. Simple as that 🐸
