### ISSUE TITLE
shows an error about missing dependencies from python-sphinx_rtd_theme during install 

### ISSUE THREAD

**Issue by IHaveAidsFromMia** [Frogging-Family/linux-tkg#756]
Encountered it on EndeavourOS, with the linux-tkg kernel 6.3.7 & 6.3.8 when trying to install dependencies but would error it out because of python-sphinx_rtd_theme and maybe others too? Not quite sure, what to do here?
![Screenshot_20230615_080536](https://github.com/Frogging-Family/linux-tkg/assets/83848485/78f33a67-9b0f-483e-8875-1adb814b0918)

**Comment by Tk-Glitch** [comment]
https://archlinux.org/packages/extra/any/python-sphinx_rtd_theme/

Looks like your pacman db is out of date. Please run `sudo pacman -Sy` then attempt to run the pkgbuild again.

**Comment by IHaveAidsFromMia** [comment]
> https://archlinux.org/packages/extra/any/python-sphinx_rtd_theme/
> 
> Looks like your pacman db is out of date. Please run `sudo pacman -Sy` then attempt to run the pkgbuild again.

i did run the command previously, but it still showed that it was "up to date" during in the morning. Now that i came back, everything is installing fine. Thanks for the help. Keep doing what your doing!
