### ISSUE TITLE
Proceed with installation? [Y/n] prompt

### ISSUE THREAD

**Issue by ryanmusante** [Frogging-Family/linux-tkg#757]
I have all options set in the customization file, however, how do you get it to bypass and answer yes to the final question without user interaction?
```
Packages (2) linux63-tkg-cfs-6.3.9-273  linux63-tkg-cfs-headers-6.3.9-273

Total Installed Size:  313.94 MiB
Net Upgrade Size:       -0.03 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by Riesi** [comment]
This prompt is not part of the tkg script. It is from makepkg, so you only have to pass `--noconfirm` to makepkg.
Something like `makepkg -si --noconfirm`.

**Comment by ryanmusante** [comment]
Thanks
