### ISSUE TITLE
Question: Which of the gentoo patches make also sense for linux-tkg?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#759]
I was thinking about compiling a gentoo kernel for my EndeavourOS, but now I am wondering which of the gentoo kernel patches would make sense for linux-tkg.

Here are the gentoo patches for kernel 6.3: https://dev.gentoo.org/~mpagano/genpatches/trunk/6.3/

Can you tell me if any of this makes sense to add to a linux-tkg kernel?

**Comment by AdelKS** [comment]
The BMQ and PDS patches in the Gentoo repo are also offered by us here too. The one that enables micro-arch optimizations too. the rest are minor fixes that probably dont matter to us, which you can pick up if you wish.

**Comment by AdelKS** [comment]
Closing this issue, feel free to reopen if you want to discuss further.
