### ISSUE TITLE
How do i update my kernel with the community patches?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#76]
Lets say ive installed the custom kernel and now i want to add some additional community patches. How would i add them without having to recompile everything?

**Comment by AdelKS** [comment]
You can't patches are code changes, so you have to recompile. By default `ccache` is used, so it won't recompile things that have been already compiled, though there's the time to look up the result in the HDD/SSD.

**Comment by Axilot** [comment]
Ah okay. Just asking cause my processor is very bad. A complete recompilation takes an hour XD

**Comment by AdelKS** [comment]
You can give a try to `modprobed-db`: when you compile the kernel with the default settings you compile a lot of modules that aren't needed for your machine. `modprobed-db` is a command you can use to store the modules currently in use in your computer, you should use it frequently for quite a few days, to cover all your use cases, then it can be used by the script here to strip the kernel from the modules you don't use, this divides the compile time by 10.

**Comment by John-Gee** [comment]
> Ah okay. Just asking cause my processor is very bad. A complete recompilation takes an hour XD

ccache helps with not doing complete recompilation every time, but you need a big enough cache for it to work fine.

**Comment by Axilot** [comment]
I know. Even with ccache it takes an hour^^
Imma close this thread now.
