### ISSUE TITLE
linux-tkg refuses to compile (?)

### ISSUE THREAD

**Issue by Impeta** [Frogging-Family/linux-tkg#762]
**Describe the bug**
 - Which OS do you encounter the bug on?
Arch Linux.
 - A clear and concise description of what the bug is.
I'm installing your kernels through the command `makepkg -si`. At some point during the compiling kernel process, it... just spits out this, jumbling itself out always:
[shell-output.log](https://github.com/Frogging-Family/linux-tkg/files/11907895/shell-output.log)
[my customization.cfg](https://github.com/Frogging-Family/linux-tkg/files/11907931/customization.txt)

These half latter lines and words aren't supposed to seen at all, are they? And funnily enough, the log doesn't include this missing line reported from my terminal:
```.config:1053:warning: override: ZSWAP_COMPRESSOR_DEFAULT_ZSTD changes choice state```

**Comment by AdelKS** [comment]
You are getting these prompts because you have `_configfile="running-kernel"` set in your `customization.cfg` file. And they're absolutely normal, especially if you are building from an older kernel (e.g. building 6.4 using 6.3)

**Comment by Patola** [comment]
And I am having the compilation problem because this old issue again:
`ERROR: modpost: "sched_numa_hop_mask" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!`

And I don't dare disabling numa. Last time I did, the kernel compiled but when booted went all haywire on me.

**Comment by Tk-Glitch** [comment]
@Patola Should be fixed with https://github.com/Frogging-Family/linux-tkg/commit/c0f8f6d68ed852625e6af309f9c7fbeccd678896

**Comment by Tk-Glitch** [comment]
Note to myself: Don't write "fixed" in an issue comment :frog:

**Comment by Patola** [comment]
> @Patola Should be fixed with [c0f8f6d](https://github.com/Frogging-Family/linux-tkg/commit/c0f8f6d68ed852625e6af309f9c7fbeccd678896)

Wow, that was fast, thank you very much. I will compile it right now and tell the results after some testing.

**Comment by Patola** [comment]
It has compiled correctly and it's running very well. Thank you again.

**Comment by ryanmusante** [comment]
He's quick and nimble
