### ISSUE TITLE
Unable to build kernel on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by joni999** [Frogging-Family/linux-tkg#763]
**Describe the bug**
 - OS: OpenSUSE Tumbleweed 20230628 
- CPU: Intel i7 13700K

I get the following error trying to install the kernel with the included install script:

```
[...]
  ZSTD    /home/joni/git/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.0_tkg_pds_g6995e2de6891-1.x86_64/lib/modules/6.4.0_tkg_pds-g6995e2de6891/kernel/net/qrtr/qrtr-tun.ko.zst
  ZSTD    /home/joni/git/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.0_tkg_pds_g6995e2de6891-1.x86_64/lib/modules/6.4.0_tkg_pds-g6995e2de6891/kernel/net/qrtr/qrtr-mhi.ko.zst
  ZSTD    /home/joni/git/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.0_tkg_pds_g6995e2de6891-1.x86_64/lib/modules/6.4.0_tkg_pds-g6995e2de6891/kernel/virt/lib/irqbypass.ko.zst
  DEPMOD  /home/joni/git/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.0_tkg_pds_g6995e2de6891-1.x86_64/lib/modules/6.4.0_tkg_pds-g6995e2de6891
depmod: ERROR: could not open directory /home/joni/git/linux-tkg/linux-src-git/linux-tkg-rpmbuild/BUILDROOT/kernel-6.4.0_tkg_pds_g6995e2de6891-1.x86_64/usr/lib/modules/99.98.6.4.0_tkg_pds-g6995e2de6891: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
make[2]: *** [Makefile:1959: modules_install] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.uTWTrl (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.uTWTrl (%install)
make[1]: *** [scripts/Makefile.package:74: rpm-pkg] Error 1
make: *** [Makefile:1660: rpm-pkg] Error 2
 -> exit cleanup done
```

I tried with kernel version 6.4.0 and 6.3.10 - same error

Logfiles:
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/11923149/system-info.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11923150/shell-output.log.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/11923153/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/11923152/prepare.log.txt)

**Comment by d3vilguard** [comment]
same since 6.3.9.

**Comment by d3vilguard** [comment]
any updates?

**Comment by AdelKS** [comment]
Hello, you probably need to do this: https://github.com/Frogging-Family/linux-tkg/issues/729#issuecomment-1565678235

**Comment by d3vilguard** [comment]
> Hello, you probably need to do this: [#729 (comment)](https://github.com/Frogging-Family/linux-tkg/issues/729#issuecomment-1565678235)

still fails

**Comment by d3vilguard** [comment]
bump

**Comment by AdelKS** [comment]
Hello, some fixes have been pushed, you should be good to go, feel free to reopen if issue persists. It works at least on my machine.

**Comment by angryce** [comment]
Experienced same issue, tried both 6.4.11 & 6.1.46.

Did notice that when building it creates lib/modules instead of usr/lib, not that 99.98 was created at all. 
Also tried the config_localversion workaround without any luck (did spot that a variable was added with it though, but figured might as well try just in case)

Sadly didn't keep the log files before I simply reinstalled another distro.

**Comment by Tk-Glitch** [comment]
`99.98.` is added by an upstream script when it detects an old (2011) version of depmod. It gets triggered on TW because they seem to be using BusyBox by default instead of GNU, which is using a custom version of depmod which isn't 100% compatible with GNU toolset, so we would need a specific hack for TW.

**Comment by AdelKS** [comment]
Can anyone who has this issue replace the package `busybox-kmod` in their machine with `kmod` and try again ?

**Comment by Tk-Glitch** [comment]
Please retest against current. Tested on a VM with success.

**Comment by angryce** [comment]
Tested with Geckolinux (newly installed & not a vm) worked perfectly fine now.
