### ISSUE TITLE
Question about the kernel's default configs, and pstates

### ISSUE THREAD

**Issue by Theslees** [Frogging-Family/linux-tkg#764]
`CONFIG_CMDLINE="intel_pstate=passive split_lock_detect=off"` is a line in the kernel's config sets the kernel parameters, is there support for amd_pstates at all? I've been trying to replace my cpusched driver with it and got a kernel panic, am I supposed to change the arguement in `CONFIG_X86_AMD_PSTATE=y` to m to make it a loadable module instead? i see that the dummy amd_pstate-ut is a module by default in the kernel's config

Im using the PKGBUILD since im on Arch linux, and im on the Cezanne platform with an AMD Ryzen 5 5600g, so I think my hardware supports it, im pretty sure.. 

For what I actually attempted to get amd_pstates to work; I tried to boot with amd_pstate=active and amd_pstate.shared_mem=1, as my kernel arguements which caused the crash, but i've also tried amd_pstate=active with another parameter meant for cpus with "Full MSR support" (i think, it did nothing anyways. i was still on the acpi-cpufreq driver)
reference;
```
--Full MSR Support--
Some new Zen3 processors such as Cezanne provide the MSR registers directly while the X86_FEATURE_CPPC CPU feature flag is set. amd-pstate can handle the MSR register to implement the fast switch function in CPUFreq that can reduce the latency of frequency control in interrupt context. The functions with a pstate_xxx prefix represent the operations on MSR registers.
--Shared Memory Support--
If the X86_FEATURE_CPPC CPU feature flag is not set, the processor supports the shared memory solution. In this case, amd-pstate uses the cppc_acpi helper methods to implement the callback functions that are defined on static_call. The functions with the cppc_xxx prefix represent the operations of ACPI CPPC helpers for the shared memory solution.
AMD P-States and ACPI hardware P-States always can be supported in one processor. But AMD P-States has the higher priority and if it is enabled with MSR_AMD_CPPC_ENABLE or cppc_set_enable, it will respond to the request from AMD P-States.
```
If im doing anything wrong I'd like to know directly, or if this post doesn't belong in here either. Either way; Thank you for reading this far.

**Comment by AdelKS** [comment]
Hello!

The default archlinux kernel config (which we use when building tkg kernels) should work just fine to have a working amd-pstate, so you don't have to change anything from linux-tkg's side.

That being said, after having a look at the [archwiki](https://wiki.archlinux.org/title/CPU_frequency_scaling) 
```
The amd_pstate CPU power scaling driver is not active by default, but can be manually enabled when using a supported CPU (Zen 2 and newer) by adding amd_pstate=passive, amd_pstate=active or amd_pstate=guided as a kernel parameter. Some motherboards might not enable the required setting in their firmware, leading to a the _CPC object is not present in SBIOS or ACPI disabled error. Change Enable CPPC from Auto to Enabled, or any similar settings in your UEFI. If they are not present, consult the vendor website for an update.
```
You did the kernel command line change in your boot kernel parameters (by changing the settings in your bootloader, you don't have to do it in linux-tkg, no need to rebuild a kernel), maybe you have to activate something in your BIOS ? But since it's a laptop probably the relevant BIOS entries are hidden :/

**Comment by Theslees** [comment]
Hey,
Thank you for letting me know what to expect, that helps alot!
I do have a weird mini ITX motherboard, (and yes, I'm even using sodimm ram slots like an ordinary laptop) 

But I enabled `CPPC CTRL`, it was under cppc) in my ASrock uefi settings, and precision boost too. I think that just means "CPPC Control"
They're under a tab in my OC menu, my bios is fully unlocked and bootable by grub

I've seen people blacklisting `initcall_blacklist=acpi_cpufreq`, but it doesn't affect anything either.. Only parameter that seemingly affects my system (causing the kernel panic) was `amd_pstate.shared_mem=1`,
I was reading through that arch wiki myself for cpu freq. scaling information

current kernel parameters; ``/boot/vmlinuz-linux64-tkg-bmq root=UUID=8ecb01a4-756e-4807-a163-c0c32c890433 rw loglevel=3 iommu=on amd_pstate=active initcall_blacklist=acpi_cpufreq``

I have alot of eufi settings set to auto, but the one I mentioned above was the only setting in my uefi firmware mentioning CPPC, 
~~I apoligize for my delayed message too i forgot to respond before i fell asleep~~

**Comment by Theslees** [comment]
Hey! Update; I added the parameters to my linuxtkg boot script directly and it worked from there! I'll close this issue now!
```[0] arch-desktop:~ joey$ sudo cpupower frequency-info
[sudo] password for joey: 
analyzing CPU 1:
  driver: amd-pstate-epp
  CPUs which run at the same hardware frequency: 1
  CPUs which need to have their frequency coordinated by software: 1
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 400 MHz - 4.46 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 400 MHz and 4.46 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 3.61 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
    Boost States: 0
    Total States: 3
    Pstate-P0:  3900MHz
    Pstate-P1:  1700MHz
    Pstate-P2:  1400MHz
[0] arch-desktop:~ joey$```

Thanks you sm your help, I lost hope and was getting ready to just mark my hardware as the issue before I opened the issue. I'll tweak my settings now to my likings, cheers ^-^

**Comment by AdelKS** [comment]
Glad it works ! You mean your rebuilt a kernel with the correct command line written in it (using that specific option in `customization.cfg` ?)

`amd_pstate.shared_mem=1` afaik is only for non-zen4 desktop CPUs, and APUs should not need it.

**Comment by Theslees** [comment]
I modified the parameters in the boot entries generated by grub directly, specifically for linuxtkg :)
