### ISSUE TITLE
new bore scheduler version

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#768]
I am using kernel 6.1 and I am wondering why linux-tkg pulls the old bore version 1.7.8 from
`https://raw.githubusercontent.com/CachyOS/kernel-patches/master/${_basekernel}/sched/0001-bore.patch`

instead of using newer bore version 2.4.1 from
`https://raw.githubusercontent.com/firelzrd/bore-scheduler/main/bore-stable/0001-linux6.1.y-bore2.4.1.patch`

I tried version 2.4.1 and the patch applies cleanly and the kernel runs without issues so far.

**Comment by ptr1337** [comment]
I will update it later the day. You can also just request at the kernel-patches repo.

**Comment by mabod** [comment]
> kernel-patches repo

where do I find that?

**Comment by ptr1337** [comment]
> > kernel-patches repo
> 
> where do I find that?

In the link above where you find the fetched patch.
Anyways:
https://github.com/CachyOS/kernel-patches/commit/7b09d433c90df1c216d8e5c8bcd6f52502440aac

**Comment by ryanmusante** [comment]
Is this also applied to kernel 6.4?

**Comment by ptr1337** [comment]
> Is this also applied to kernel 6.4?

Yes

**Comment by ryanmusante** [comment]
Is kernel.sched_bore=1 required to be set after installing? And is version 2.4.2 been included?

**Comment by ptr1337** [comment]
> Is kernel.sched_bore=1 required to be set after installing? And is version 2.4.2 been included?

No, it is not required to set this. It is as default enabled, you can use =0 to disable it.
Yes, 2.4.2 will be used, as you can see here

https://github.com/CachyOS/kernel-patches/blob/master/6.4/sched/0001-bore.patch#L163

**Comment by mabod** [comment]
This might be off topic here but I want to share it anyways:

I did some testing with the bore scheduler and it is not good in multitasking. I have a fast PC (Ryzen 9 5900X with 64 GB Ram) and I frequently have several virtual machines open with Windows11 and some other Linux guests. This is working fine with bore scheduler as long as the PC is not under stress. As soon as I put the PC under stress, e.g. compiling a linux-tkg kernel, the VM's are basically unusable. The response times for mouse and keyboard input become very, very long. This does not happen with CFS scheduler. With CFS scheduler I do not even notice that a compile job is running in the background. 

This is not good and makes the bore scheduler useless for me.

**Comment by ptr1337** [comment]
> This might be off topic here but I want to share it anyways:
> 
> I did some testing with the bore scheduler and it is not good in multitasking. I have a fast PC (Ryzen 9 5900X with 64 GB Ram) and I frequently have several virtual machines open with Windows11 and some other Linux guests. This is working fine with bore scheduler as long as the PC is not under stress. As soon as I put the PC under stress, e.g. compiling a linux-tkg kernel, the VM's are basically unusable. The response times for mouse and keyboard input become very, very long. This does not happen with CFS scheduler. With CFS scheduler I do not even notice that a compile job is running in the background.
> 
> This is not good and makes the bore scheduler useless for me.

This is probably mainly caused by the zenify values, which is tkg applying. Try to revert these and test again.
Otherwise bring a proper report to the developer of the BORE Scheduler, as you even linked the github repo.
Since BORE does actually highly improves heavly workload scenarious at various people and testers, it is weird that you face this issue.
I also have the same CPU and it dramatically improves the situation at me, when compiling kernels and multi tasking.
But I commonly don't use VMs.

https://github.com/firelzrd/bore-scheduler/blob/main/bore-stable/0002-constgran-vanilla-max.patch

Apply all default values (reverting zenfiy) and apply the above values

**Comment by mabod** [comment]
> This is probably mainly caused by the zenify values, which is tkg applying.

No. I have it disabled.

`/lib/modules/6.1.38-273.3-tkg-bore/build/.config:# CONFIG_ZENIFY is not set`





> Otherwise bring a proper report to the developer of the BORE Scheduler

I will do that.

**Comment by ryanmusante** [comment]
Thanks for notifying as my primary objective is dealing with latency. I'll probably stick to CFS in the meantime until further updates.
