### ISSUE TITLE
[Linux 6.4.4] ==> ERREUR : An error was encountered applying patches (nf_tables_api.c)

### ISSUE THREAD

**Issue by Astrobald** [Frogging-Family/linux-tkg#771]
```
  -> Applying misc additions patch
==> ERREUR : An error was encountered applying patches. It was logged to the prepare.log.txt file.
```
```
### Applying 0012-misc-additions.patch... ###
patching file drivers/hid/hid-quirks.c
Hunk #1 succeeded at 506 (offset 28 lines).
patching file drivers/cpufreq/Kconfig
Hunk #2 succeeded at 83 (offset 1 line).
patching file net/netfilter/nf_tables_api.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file net/netfilter/nf_tables_api.c.rej
patching file mm/Kconfig
```
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12102131/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12102132/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12102133/system-info.txt)

:grin:

**Comment by pppbb** [comment]
i have the issue too

**Comment by radiomike** [comment]
Looks like it's failing because that patch has now been implemented upstream. You should be OK to ignore that error. The kernel compiles and runs without issue for me so far.
