### ISSUE TITLE
Can't compile 6.1.43 BMQ: make: *** [Makefile:2012: .] Error 2

### ISSUE THREAD

**Issue by webodan** [Frogging-Family/linux-tkg#787]
On Garuda Linux (Arch-based distro), I just can't get it to build the latest 6.1.43 kernel. Tried with my own kernel config as well as untouched default settings. Always gives Error 2 both with GCC and Clang.

**Comment by rchris494** [comment]
error i get with 6.1.43 PDS on debian 12

CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp1_transition.o
  CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp2_execution.o
  CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp2_transition.o
  LD [M]  drivers/gpu/drm/nouveau/nouveau.o
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
make[3]: *** [Makefile:2012: .] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:80: deb-pkg] Error 2
make: *** [Makefile:1656: deb-pkg] Error 2
 -> exit cleanup done
