### ISSUE TITLE
Cant compile 6.1.46 bmq llvm

### ISSUE THREAD

**Issue by holyjoespb** [Frogging-Family/linux-tkg#790]
On Ubuntu, the latest kernel 6.1 releases do not compile starting with 6.1.44

...
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:30: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:30: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:30: unable to move location counter backward for: .text
ld.lld: error: SRSO function pair won't alias
make[4]: *** [scripts/Makefile.vmlinux:34: vmlinux] Error 1
make[3]: *** [Makefile:1255: vmlinux] Error 2
make[3]: *** Waiting for unfinished jobs....
...
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:80: deb-pkg] Error 2
make: *** [Makefile:1656: deb-pkg] Error 2
 -> exit cleanup done

[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12367480/system-info.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12367483/shell-output.log.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12367484/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12367485/prepare.log.txt)

**Comment by Tk-Glitch** [comment]
Upstream issue, fixed with 6.1.46 - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.46&id=d93eeac34e75ccbdbfc90005914d32518624843a

**Comment by Tk-Glitch** [comment]
Or at least it should have been. It seems to be a less severe version of the issue from your log.

**Comment by Tk-Glitch** [comment]
Ok, you're using LTO on top.
So this should be your fix: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=79cd2a11224eab86d6673fe8a11d2046ae9d2757
