### ISSUE TITLE
Build error with linux 6.4.13

### ISSUE THREAD

**Issue by pppbb** [Frogging-Family/linux-tkg#795]
Makepkg output: make: *** [Makefile:2035: .] Error 2

[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12480530/shell-output.log.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12480531/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12480532/system-info.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12480536/customization.cfg.txt)
[linux-tkg_6.4.x_BMQ.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12480548/linux-tkg_6.4.x_BMQ.cfg.txt)

**Comment by sirlucjan** [comment]
@Tk-Glitch 

You need to update PRJC patch. Here is workaround: https://gitlab.com/torvic9/linux-stable/-/commit/c32ef1413c469e3b1aa960a15ae15cf53c23e5e2

**Comment by pppbb** [comment]
`You need to update PRJC patch. Here is workaround: https://gitlab.com/torvic9/linux-stable/-/commit/c32ef1413c469e3b1aa960a15ae15cf53c23e5e2`

sorry :( don't know what to do with it(that is why i use your script).

**Comment by sirlucjan** [comment]
This was directed to the maintainer of this repository, which is why I tagged him.

**Comment by pppbb** [comment]
`This was directed to the maintainer of this repository, which is why I tagged him.`

ok. waiting for update

**Comment by Tk-Glitch** [comment]
Thanks @sirlucjan 
Both patches were needed for compilation to go through btw
