### ISSUE TITLE
6.1.50 kernel not building

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/linux-tkg#803]
**Describe the bug**
 - Which OS do you encounter the bug on?  debian bookworm

when trying to build kernel 6.1.50 tkg-PDS if fails to build. attached are the log files.

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12494193/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12494194/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12494195/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12494196/system-info.txt)

**Comment by faptaincrunch** [comment]
Same issue here. Manually mapping the config file in the customization.cfg got me further but ends up failing when trying to build the debs.

**Comment by Tk-Glitch** [comment]
cpuset changes were backported to 6.1.50 so Project C is broken. I'll port the fix asap but you can also use a different scheduler in the time being.

**Comment by faptaincrunch** [comment]
I see OP was using Prj C but I used EEVDF + BORE patch and same issue as OP. I'll try again and it if fails I can open a new issue with the proper files for a bug report.

**Comment by Tk-Glitch** [comment]
> I see OP was using Prj C but I used EEVDF + BORE patch and same issue as OP. I'll try again and it if fails I can open a new issue with the proper files for a bug report.

Then the issue is totally different indeed. Likely some dpkg BS as usual :frog:

**Comment by rchris494** [comment]
thanks
