### ISSUE TITLE
ERROR: could not set PID X to B: SCHED_BATCH - Operation not permitted error while building

### ISSUE THREAD

**Issue by insiderser** [Frogging-Family/linux-tkg#811]
**Describe the bug**
 - Which OS do you encounter the bug on? ArchLinux
 - A clear and concise description of what the bug is. I get the following error while building:
```
==> Starting build()...
  -> ccache was found and will be used
  -> Using schedtool
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
ERROR: could not set PID 88744 to B: SCHED_BATCH - Operation not permitted
==> ERROR: A failure occurred in build().
    Aborting...
```
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

[output.txt](https://github.com/Frogging-Family/linux-tkg/files/12600979/output.txt)
[linux-tkg.cfg](https://github.com/Frogging-Family/linux-tkg/files/12600992/linux-tkg.cfg.txt)

This started happening at random. I tried building with `_kernel_on_diet=true`, but my sound didn't work after booting that kernel. So I tried to recompile again with `_kernel_on_diet=false`, but this time the build fails, and so I'm stuck with `_kernel_on_diet=true`. I'm using https://archlinux.org/packages/core/x86_64/linux/ for now.

I was trying to build linux-tkg while running https://archlinux.org/packages/core/x86_64/linux/. Before that I was building linux-tkg while running linux-tkg for months, if not years, and hadn't encountered any issues like this.

**Comment by openglfreak** [comment]
@insiderser Are you using Ananicy or a similar software?

**Comment by insiderser** [comment]
@openglfreak I am using Ananicy. Stopping Ananicy seems to resolve this issue, even without https://github.com/Frogging-Family/linux-tkg/commit/995e4b862e39855db3ef5cb2a4f37647d335381e.

**Comment by openglfreak** [comment]
@Tk-Glitch Maybe ignore schedtool/ionice errors

```diff
From 5ef8d69fa9051f2f2713c8b05773258cdbbe7b11 Mon Sep 17 00:00:00 2001
From: Torge Matthies <openglfreak@googlemail.com>
Date: Wed, 13 Sep 2023 23:45:42 +0200
Subject: [PATCH] Ignore schedtool errors

---
 PKGBUILD | 13 +++++++++++--
 1 file changed, 11 insertions(+), 2 deletions(-)

diff --git a/PKGBUILD b/PKGBUILD
index c8c1cb0..59ccb06 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -125,9 +125,18 @@ build() {
   # build!
   if pacman -Qq schedtool &> /dev/null; then
     msg2 "Using schedtool"
-    #_schedtool="schedtool -B -n 1 -e ionice -n 1"
+    _schedtool="command schedtool -B -n 1"
+    _ionice="command ionice -n 1"
   fi
-  _runtime=$( time ( $_schedtool make ${_force_all_threads} ${llvm_opt} LOCALVERSION= bzImage modules 2>&1 ) 3>&1 1>&2 2>&3 )
+  _runtime=$(
+    if [ -n "$_schedtool" ]; then
+        _pid="$(exec bash -c 'echo "$PPID"')"
+        $_schedtool "$_pid" ||:
+        $_ionice -p "$_pid" ||:
+    fi
+    time ( make ${_force_all_threads} ${llvm_opt} LOCALVERSION= bzImage modules 2>&1 ) 3>&1 1>&2 2>&3
+    return $?
+  )
 }
 
 hackbase() {
-- 
2.42.0
```

**Comment by Tk-Glitch** [comment]
I'm fine with that. Thanks @openglfreak !
