### ISSUE TITLE
6.4.16 kernel not building Prj C PDS

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#812]
CC [M]  fs/xfs/scrub/dabtree.o
  CC [M]  fs/xfs/scrub/dir.o
  CC [M]  fs/xfs/scrub/fscounters.o
  CC [M]  fs/xfs/scrub/health.o
  CC [M]  fs/xfs/scrub/ialloc.o
  CC [M]  fs/xfs/scrub/inode.o
  CC [M]  fs/xfs/scrub/parent.o
  CC [M]  fs/xfs/scrub/readdir.o
  CC [M]  fs/xfs/scrub/refcount.o
  CC [M]  fs/xfs/scrub/rmap.o
  CC [M]  fs/xfs/scrub/scrub.o
  CC [M]  fs/xfs/scrub/symlink.o
  CC [M]  fs/xfs/scrub/rtbitmap.o
  CC [M]  fs/xfs/scrub/quota.o
  CC [M]  fs/xfs/scrub/agheader_repair.o
  CC [M]  fs/xfs/scrub/repair.o
  LD [M]  fs/xfs/xfs.o
make[2]: *** [Makefile:2035: .] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Q8dljg (%build)

RPM build warnings:
    source_date_epoch_from_changelog set but %changelog is missing

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Q8dljg (%build)
make[1]: *** [scripts/Makefile.package:74: rpm-pkg] Error 1
make: *** [Makefile:1662: rpm-pkg] Error 2
 -> exit cleanup done

[dom@fedora linux-tkg]$ ls
current_env        install.sh        linux-kernel.git  linux-tkg-config   logs      README.md
customization.cfg  kernelconfig.new  linux-src-git     linux-tkg-patches  PKGBUILD

OS: Fedora 38

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12601629/customization.cfg.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12601630/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12601631/system-info.txt)

**Comment by wieto** [comment]
I have the same issue on Arch linux. Perhaps related to https://github.com/Frogging-Family/linux-tkg/issues/803#issuecomment-1702645812

**Comment by tawnylure** [comment]
Having the same issue here on arch, can't build and ending with a
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12605559/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12605560/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12605561/system-info.txt)
 make file error.
Hopefully this can be resolved soon.

**Comment by tawnylure** [comment]
> Having the same issue here on arch, can't build and ending with a [customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12605559/customization.cfg.txt) [prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12605560/prepare.log.txt) [system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12605561/system-info.txt) make file error. Hopefully this can be resolved soon.

Can confirm a prj C PDS / BMQ issue, compiling kernel on another scheduler worked fine.
