### ISSUE TITLE
Rename customization.cfg to customization.default.cfg

### ISSUE THREAD

**Issue by minecrawler** [Frogging-Family/linux-tkg#813]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

done, didn't find one

**Describe the bug**
 - Which OS do you encounter the bug on? all
 - A clear and concise description of what the bug is.

Modifying the config file means that it'll enter the modified state in git. Updates to the file will always be a collision between my changes and remote origin whenever a user pulls changes.

 - Attach the contents of your logs folder by drag & dropping each file into this message. Non
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

A solution: Rename the config file to "customization.default.cfg" and have the user copy it to "customization.cfg". That way, it won't be tracked by git and changes don't collide. The script can use the default config as fallback and if there are missing or changed values in the config, it can prompt the user to upgrade their config - either automatically by script or manually.

**Comment by ch4og** [comment]
Personally, I don't see the point in adding this, since `_EXT_CONFIG_PATH=~/.config/frogminer/linux-tkg.cfg` from the standard customization.cfg makes `~/.config/frogminer/linux-tkg.cfg` take precedence over customization.cfg

**Comment by minecrawler** [comment]
Thanks for interjecting. I'm following the official documentation in the README. There's no information about `~/.config/frogminer/linux-tkg.cfg`. If that file works that way, it should be documented instead of instructing me to modify `customization.cfg` :)
