### ISSUE TITLE
eevdf patch doesn't work with gentoo-sources-6.5.3-r1

### ISSUE THREAD

**Issue by sombrae** [Frogging-Family/linux-tkg#815]
I know that non-pacman distros support is experimental, but on gentoo-sources-6.5.1, eevdf did work and patch correctly, so I was just wondering.

Here's the [complete output of `emerge --info '=sys-kernel/gentoo-sources-6.5.3-r1::gentoo'`](https://pastebin.com/d691MVaF), [the complete build log](https://pastebin.com/ZR1N3wV5) and the [output of `emerge -pqv '=sys-kernel/gentoo-sources-6.5.3-r1::gentoo'` ](https://pastebin.com/teGyHUNS).

**Comment by Tatsh** [comment]
Also having the same issue. Haven't tried to fix it yet.

**Comment by ptr1337** [comment]
Try to revert following commit:
https://github.com/Frogging-Family/linux-tkg/commit/6aab0087dfbf8ce4f26cb7028b7d279b8f5ca233

**Comment by Tatsh** [comment]
> Try to revert following commit: [6aab008](https://github.com/Frogging-Family/linux-tkg/commit/6aab0087dfbf8ce4f26cb7028b7d279b8f5ca233)
> 
> As soon the EEVDF story is sorted out, I will send a fresh PR.

I tried every version of EEVDF and it will not apply successfully. I also verified that 6.5.3-r1 does not receive a conflicting patch from Gentoo. The rej files:

`kernel/sched/sched.h.rej`:

```patch
--- kernel/sched/sched.h
+++ kernel/sched/sched.h
@@ -3487,4 +3494,7 @@ static inline void task_tick_mm_cid(struct rq *rq, struct task_struct *curr) { }
 static inline void init_sched_mm_cid(struct task_struct *t) { }
 #endif

+extern u64 avg_vruntime(struct cfs_rq *cfs_rq);
+extern int entity_eligible(struct cfs_rq *cfs_rq, struct sched_entity *se);
+
 #endif /* _KERNEL_SCHED_SCHED_H */
```

`kernel/sched/debug.c.rej`:

```patch
--- kernel/sched/debug.c
+++ kernel/sched/debug.c
@@ -347,10 +347,7 @@ static __init int sched_init_debug(void)
        debugfs_create_file("preempt", 0644, debugfs_sched, NULL, &sched_dynamic_fops);
 #endif

-       debugfs_create_u32("latency_ns", 0644, debugfs_sched, &sysctl_sched_latency);
-       debugfs_create_u32("min_granularity_ns", 0644, debugfs_sched, &sysctl_sched_min_granularity);
-       debugfs_create_u32("idle_min_granularity_ns", 0644, debugfs_sched, &sysctl_sched_idle_min_granularity);
-       debugfs_create_u32("wakeup_granularity_ns", 0644, debugfs_sched, &sysctl_sched_wakeup_granularity);
+       debugfs_create_u32("base_slice_ns", 0644, debugfs_sched, &sysctl_sched_base_slice);

        debugfs_create_u32("latency_warn_ms", 0644, debugfs_sched, &sysctl_resched_latency_warn_ms);
        debugfs_create_u32("latency_warn_once", 0644, debugfs_sched, &sysctl_resched_latency_warn_once);
```

`init/init_task.c.rej`:


```patch
--- init/init_task.c
+++ init/init_task.c
@@ -78,6 +78,7 @@ struct task_struct init_task
        .prio           = MAX_PRIO - 20,
        .static_prio    = MAX_PRIO - 20,
        .normal_prio    = MAX_PRIO - 20,
+       .latency_prio   = DEFAULT_PRIO,
        .policy         = SCHED_NORMAL,
        .cpus_ptr       = &init_task.cpus_mask,
        .user_cpus_ptr  = NULL,
```

Also Project C patch does not apply either, even without EEVDF applied first. It has a much larger set of issues.

**Comment by AdelKS** [comment]
This issue is fixed with latests patches right ?

**Comment by sombrae** [comment]
yep it is. not sure how it got fixed, but I'll take it.
