### ISSUE TITLE
Outdated patch in 'glitched-base'

### ISSUE THREAD

**Issue by sirlucjan** [Frogging-Family/linux-tkg#82]
Everything seems to indicate that this fragment is already unnecessary.

https://github.com/Frogging-Family/linux-tkg/blob/d7918fc63bd3f087a2ea11aa51db276ae5b6210f/linux58-tkg/linux58-tkg-patches/0003-glitched-base.patch#L183

https://patchwork.kernel.org/patch/9822639/

```
lucjan@archlinux ~ $ cat /sys/block/sda/device/queue_depth
32
lucjan@archlinux ~ $ cat /sys/block/sda/queue/nr_requests
64
```
In the zenkernel they also withdrew it:

https://github.com/zen-kernel/zen-kernel/commit/9646e76dda2341d1cdd3796690a1f1861ebcb1bd

**Comment by Tk-Glitch** [comment]
Thank you! I'll remove it.
