### ISSUE TITLE
Error applying BORE-EEVDF on kernel 6.5.7

### ISSUE THREAD

**Issue by Exotic0015** [Frogging-Family/linux-tkg#825]
Relevant snip from prepare.log.txt:
```
### Applying 0001-bore-eevdf.patch... ###
patching file include/linux/sched.h
Hunk #3 succeeded at 1013 (offset -1 lines).
patching file init/Kconfig
Hunk #1 succeeded at 1306 (offset 28 lines).
patching file kernel/sched/core.c
Hunk #1 succeeded at 4485 (offset -6 lines).
Hunk #2 succeeded at 4653 with fuzz 2 (offset -6 lines).
Hunk #3 succeeded at 4975 (offset -8 lines).
Hunk #4 succeeded at 10081 (offset -31 lines).
patching file kernel/sched/debug.c
patching file kernel/sched/fair.c
Hunk #5 FAILED at 817.
Hunk #6 succeeded at 829 with fuzz 2 (offset -8 lines).
Hunk #7 succeeded at 858 (offset -8 lines).
Hunk #8 succeeded at 1274 (offset -60 lines).
Hunk #9 FAILED at 5137.
Hunk #10 succeeded at 5156 (offset -63 lines).
Hunk #11 succeeded at 6638 (offset -63 lines).
Hunk #12 succeeded at 8365 (offset -63 lines).
Hunk #13 succeeded at 8379 (offset -63 lines).
2 out of 13 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
patching file kernel/sched/features.h
```
Trying to build on default customization.cfg, Fedora 39

**Comment by ptr1337** [comment]
> Relevant snip from prepare.log.txt:
> 
> ```
> ### Applying 0001-bore-eevdf.patch... ###
> patching file include/linux/sched.h
> Hunk #3 succeeded at 1013 (offset -1 lines).
> patching file init/Kconfig
> Hunk #1 succeeded at 1306 (offset 28 lines).
> patching file kernel/sched/core.c
> Hunk #1 succeeded at 4485 (offset -6 lines).
> Hunk #2 succeeded at 4653 with fuzz 2 (offset -6 lines).
> Hunk #3 succeeded at 4975 (offset -8 lines).
> Hunk #4 succeeded at 10081 (offset -31 lines).
> patching file kernel/sched/debug.c
> patching file kernel/sched/fair.c
> Hunk #5 FAILED at 817.
> Hunk #6 succeeded at 829 with fuzz 2 (offset -8 lines).
> Hunk #7 succeeded at 858 (offset -8 lines).
> Hunk #8 succeeded at 1274 (offset -60 lines).
> Hunk #9 FAILED at 5137.
> Hunk #10 succeeded at 5156 (offset -63 lines).
> Hunk #11 succeeded at 6638 (offset -63 lines).
> Hunk #12 succeeded at 8365 (offset -63 lines).
> Hunk #13 succeeded at 8379 (offset -63 lines).
> 2 out of 13 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
> patching file kernel/sched/features.h
> ```
> 
> Trying to build on default customization.cfg, Fedora 39

The EEVDF patch needs to be updated to reflect the recent changes in BORE.
I will do later today

**Comment by sirlucjan** [comment]
Please check #826

**Comment by Exotic0015** [comment]
Thanks, can confirm it fixes the issue
