### ISSUE TITLE
Hangs on Arch Linux GNOME Wayland with linux-tkg, but works fine on X11.

### ISSUE THREAD

**Issue by Kerrung** [Frogging-Family/linux-tkg#83]
Commit: https://github.com/Frogging-Family/linux-tkg/commit/77c316a6d653d7ff74bdf02b20ea756b2a026dc6

[customization.cfg.zip](https://github.com/Frogging-Family/linux-tkg/files/5359517/customization.cfg.zip)

All works fine with linux kernel from Arch Linux official repository.

AMD Radeon GPU HD 7850 with AMDGPU kernel driver, with Mesa.

**Comment by AdelKS** [comment]
Looks like something that comes from upstream, retry with `cfs` as the scheduler and see if it's the same as arch kernel.

**Comment by AdelKS** [comment]
Any news @Kerrung ? Did the recent updates fix your issue?

**Comment by Kerrung** [comment]
> Any news @Kerrung ? Did the recent updates fix your issue?

Works fine with cfs, hangs with pds.
