### ISSUE TITLE
System freeze with latest 0003-eevdf.patch update under high cpu load

### ISSUE THREAD

**Issue by WhitePeace36** [Frogging-Family/linux-tkg#830]
My System is:

OS: EndeavourOS Linux x86_64
Host: X570 AORUS MASTER -CF
Kernel: 6.5.8-273-tkg-eevdf
Uptime: 8 mins
Packages: 1640 (pacman), 9 (flatpak)
Shell: zsh 5.9
Resolution: 2560x1440
DE: Plasma 5.27.8
WM: kwin
Theme: [Plasma], Breeze [GTK2], Arc-Darker [GTK3]
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3]
Terminal: xfce4-terminal
Terminal Font: Source Code Pro 10
CPU: AMD Ryzen 7 5800X3D (16) @ 3.550GHz
GPU: AMD ATI Radeon RX 7900 XT/7900 XTX
Memory: 3381MiB / 32010MiB

I am running the latest eevdf patch d9da42be995a37fbde81f8440da65820dffdaff9 with kernel version 6.5.8-273-tkg as stated above. 

And since the patch the whole system freezes when trying to compile the new linux-tkg 6.5.9.

Didn't happen before d9da42be995a37fbde81f8440da65820dffdaff9.
Which i am running right now.

The only thing that helps is to reset the pc.

**Comment by ptr1337** [comment]
Hi,

Can you check if this is also reproduceable via stress-ng?

For example:
`stress-ng --cpu-method loop -c 128`

If it is possible, you could also try to get some logs via journalctl -b1

**Comment by WhitePeace36** [comment]
Hi,

i tested it with stress-ng like you suggested but it didn't trigger the freeze 18min into the test.

Then i stopped it and tried the kernel compilation again. There it froze after about ~5min.

here is the log of the last boot:

[last_boot.txt](https://github.com/Frogging-Family/linux-tkg/files/13169239/last_boot.txt)

**Comment by sirlucjan** [comment]
Perhaps the new EEVDF only works properly with BORE. So maybe make separate BORE+EEVDF as one patch and separate EEVDF? Before I added the new BORE, I gathered feedback from several people. Perhaps this will be the best solution?

**Comment by firelzrd** [comment]
I strongly believe that DELAY_DEQUEUE is the culprit.
DELAY_DEQUEUE should be disabled. I did so in BORE patch.

**Comment by ptr1337** [comment]
Can you try following:
```
sudo su
echo NO_DELAY_DEQUEUE > /sys/kernel/debug/sched/features
```

And then run the workload again

**Comment by WhitePeace36** [comment]
thx guys, i will try that after the dota 2 game :)

**Comment by WhitePeace36** [comment]
yeah setting NO_DELAY_DEQUEUE worked. It didn't freeze now and completed the kernel compile without issues.

**Comment by sirlucjan** [comment]
Could you try with this patch: https://github.com/Frogging-Family/linux-tkg/pull/831 ?

**Comment by WhitePeace36** [comment]
i will try it, but may take a while

**Comment by WhitePeace36** [comment]
it doesnt work and when i sudo cat /sys/kernel/debug/sched/features | grep NO_DELAY_DEQUEUE 
it also doesn't say that it is set. DELAY_DEQUEUE is still set

**Comment by sirlucjan** [comment]
Are you sure you applied the patch? You have to apply it manually. 

Look at: https://github.com/CachyOS/kernel-patches/blob/master/6.5/sched/0001-bore-eevdf.patch#L682

I have something like this in bore-eevdf and NO_DELAY_DEQUEUE detects correctly.

**Comment by WhitePeace36** [comment]
could be because, i just cloned your fork and build with the customization.cfg i use. Because i didn't know how to get the patch seperatly

**Comment by sirlucjan** [comment]
Well, then you did not apply the patch - I did not add it to the file. You have to apply it manually - probably with .mypatch extension - to be honest, I never compiled TKG kernel :D

**Comment by WhitePeace36** [comment]
nice thx :) i think i will try that tomorrow. Btw where is the big difference between borg-eevdf and eevdf ? Is borg integrated into eevdf or can you just switch between them ?

**Comment by sirlucjan** [comment]
BORE was originally an overlay for CFS. Since EEVDF will replace CFS in kernel 6.6 then BORE was adapted to that. BORE will not become part of the upstream, but is being very actively developed. 

Look at: https://github.com/firelzrd/bore-scheduler/blob/main/README.md

BORE can be turned off at any time using sysctl.

**Comment by WhitePeace36** [comment]
Thx i will look into it further tomorrow. gn8
