### ISSUE TITLE
BORE patch on linux 6.6 fails.

### ISSUE THREAD

**Issue by fsyy** [Frogging-Family/linux-tkg#833]
**Describe the bug**
 - Which OS do you encounter the bug on? Arch
 - A clear and concise description of what the bug is.:

Using BORE patch fails. 

 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

### Applying 0001-bore.patch... ###
 172   │ patching file include/linux/sched.h
 173   │ Hunk #2 succeeded at 580 (offset 3 lines).
 174   │ Hunk #3 succeeded at 1017 (offset 4 lines).
 175   │ patching file init/Kconfig
 176   │ Hunk #1 succeeded at 1306 (offset 48 lines).
 177   │ patching file kernel/sched/autogroup.c
 178   │ patching file kernel/sched/core.c
 179   │ Hunk #1 succeeded at 4495 (offset 11 lines).
 180   │ Hunk #2 succeeded at 4663 with fuzz 2 (offset 11 lines).
 181   │ Hunk #3 succeeded at 4986 (offset 12 lines).
 182   │ Hunk #4 succeeded at 10151 (offset 74 lines).
 183   │ patching file kernel/sched/debug.c
 184   │ Hunk #1 succeeded at 596 (offset 1 line).
 185   │ patching file kernel/sched/fair.c
 186   │ Hunk #2 succeeded at 69 with fuzz 2.
 187   │ Hunk #3 succeeded at 94 (offset -6 lines).
 188   │ Hunk #4 FAILED at 219.
 189   │ Hunk #5 succeeded at 374 (offset -13 lines).
 190   │ Hunk #6 succeeded at 732 (offset -13 lines).
 191   │ Hunk #7 succeeded at 752 (offset -13 lines).
 192   │ Hunk #8 succeeded at 1051 (offset -11 lines).
 193   │ Hunk #9 succeeded at 1064 (offset -11 lines).
 194   │ Hunk #10 succeeded at 1244 (offset -10 lines).
 195   │ Hunk #11 succeeded at 5165 (offset 27 lines).
 196   │ Hunk #12 succeeded at 6740 (offset 27 lines).
 197   │ Hunk #13 succeeded at 8488 (offset 42 lines).
 198   │ Hunk #14 succeeded at 8502 (offset 42 lines).
 199   │ 1 out of 14 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
 200   │ patching file kernel/sched/features.h
 201   │ Hunk #1 FAILED at 6.
 202   │ 1 out of 1 hunk FAILED -- saving rejects to file kernel/sched/features.h.rej

**Comment by fsyy** [comment]
this seems to fix the issue: https://github.com/Frogging-Family/linux-tkg/pull/832

**Comment by sirlucjan** [comment]
Yes, the new version of BORE for kernel 6.6 is again based on the upstream EEVDF, so I once again sent a proper pull request.

**Comment by sirlucjan** [comment]
Since in 6.6 the default scheduler is eevdf, there will no longer be the names bore and eevdf-bore/bore-eevdf but only one - "bore".

**Comment by BillFleming** [comment]
This can be closed now. No patch issue or running issues on any of several machines.
