### ISSUE TITLE
Why is there no cfs in avail_cpu_scheds

### ISSUE THREAD

**Issue by robson-66** [Frogging-Family/linux-tkg#836]
Is this intentional or just an oversight that cfs is disabled in the prepare file for linux 6.6

```
elif [ "$_kver" = "606" ]; then
_avail_cpu_scheds=("eevdf" "bore")
```

**Comment by ptr1337** [comment]
There is no cfs in 6.6 anymore

**Comment by sirlucjan** [comment]
> Is this intentional or just an oversight that cfs is disabled in the prepare file for linux 6.6
> 
> ```
> elif [ "$_kver" = "606" ]; then
> _avail_cpu_scheds=("eevdf" "bore")
> ```

https://www.phoronix.com/news/Linux-6.6-EEVDF-Merged

**Comment by sirlucjan** [comment]
As a result, so far there will also be no TT, BMQ and PDS.

**Comment by robson-66** [comment]
It's all clear now.
