### ISSUE TITLE
Error mkinitcpio -P

### ISSUE THREAD

**Issue by Xdavius** [Frogging-Family/linux-tkg#854]
Each kernel I compile or download, it's the same. Since release of 6.6.1
It's affecting kernel 6.5 new builds too. Kernel 6.1 isn't affected :

 
```==> Building image from preset: /etc/mkinitcpio.d/linux66-tkg-eevdf.preset: 'default'
==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux66-tkg-eevdf -g /boot/initramfs-linux66-tkg-eevdf.img --microcode /boot/amd-ucode.img --microcode /boot/intel-ucode.img
==> Starting build: '6.6.3-273-tkg-eevdf'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux66-tkg-eevdf.img'
==> WARNING: errors were encountered during the build. The image may not be complete.


==> Using default configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux66-tkg-eevdf -g /boot/initramfs-linux66-tkg-eevdf-fallback.img -S autodetect --microcode /boot/amd-ucode.img --microcode /boot/intel-ucode.img
==> Starting build: '6.6.3-273-tkg-eevdf'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [kms]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating zstd-compressed initcpio image: '/boot/initramfs-linux66-tkg-eevdf-fallback.img'
==> WARNING: errors were encountered during the build. The image may not be complete.
erreur : la commande n’a pas pu être exécutée correctement
```

**Comment by Xdavius** [comment]
Hi,
Some news.

There is a problem with wirtualbox-dkms with tkg kernel, making wirtualbox not working properly and giving an error in mkinitcpio.

thank you

**Comment by FintasticMan** [comment]
I'm getting the same issue, I'm not noticing any immediate problems though.

This is my config: [linux-tkg.cfg](https://github.com/Frogging-Family/linux-tkg/files/13679551/linux-tkg.cfg.txt)

**Comment by elgq** [comment]
In my case it happens cause I'm using modprobed, the kms hook mentioned before tries to include modules that use a function `drm_privacy_screen_register,` that function is referenced in the modules `chromeos_privacy_screen, thinkpad_acpi` that comes with a kernel vanilla installation, so I added just `thinkpad_acpi` to `./config/modprobed.db` and mkinitcpio (latest version 37.1-2) no longer shows the warning/error.

**Comment by Xdavius** [comment]
Hi.

I don't understand...
I haven't got a laptop and, using or not modprobed-db, I fall with an error.

I think this problem has begun with 6.6 and latest 6.5.xx releases, post 6.6 release...

I'm using the same 5600 with 6700 10g AMD GPU. 

The only change in my setup is a new audio dongle seenheiser to use with wireless audio headphones and mic.

And it works without problems (when I set it up correctly, but it's not linked to the kernel)

I don't know if the error mentioned got any link with original mine...

But the problem is still here, using or not modprobed-db, full compilation, or downloading directly the kernel from the release.

My friends doesn't have the problem so it might be linked to my config... But still can't find any answers...

Still using the current tkg without any problem, but the error is still here when building the initcpio

**Comment by FintasticMan** [comment]
Interesting, so it still happens when not using modprobed-db or kernel-on-diet... It was fixed for me when adding that module to the list of modules to build.

Can you try enabling the kernel-on-diet option and adding `thinkpad_acpi` to the minimal-modprobed.db file like in #862? If the error still occurs, we'll know there are 2 issues at play here.

**Comment by Xdavius** [comment]
> Interesting, so it still happens when not using modprobed-db or kernel-on-diet... It was fixed for me when adding that module to the list of modules to build.
> 
> Can you try enabling the kernel-on-diet option and adding `thinkpad_acpi` to the minimal-modprobed.db file like in #862? If the error still occurs, we'll know there are 2 issues at play here.

I will try as soon as possible on my side.

**Comment by Xdavius** [comment]
No more error !!!
Thank you @Tk-Glitch
