### ISSUE TITLE
Error when attempting to run the installer

### ISSUE THREAD

**Issue by ETJAKEOC** [Frogging-Family/linux-tkg#858]
Running Arch Linux on an AMD64 CPU

Cannot compile the TKG kernel using makepkg. I was able to compile up to 6.7-rc1 without any issues, after rc2 I have been running into an issue where "linux-tkg/src/patch-6.7-rc2-rt1.patch.gz: not in a gzip format" is downloading an HTML page that says my kernel file does not exist? I even get the same message when trying to compile 6.7-rc5. I have attempted building it using a fresh cloned repo from this github, still the issue persists. 

Log files are attached as requested, any help/information is greatly appreciated :)

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/13700763/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13700764/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13700765/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/13700767/system-info.txt)

(My custom TKG configuration file from "/home/jake/.config/frogminer/linux-tkg.cfg") [custom-linux-tkg.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/13700786/custom-linux-tkg.cfg.txt)

**Comment by Tk-Glitch** [comment]
That's RT_PREEMPT for you :frog:

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/ab584945e0c939dad50dfcca2eb674a4186f8e3e
Til next time.
