### ISSUE TITLE
fedora issue. /boot files end with .old extension

### ISSUE THREAD

**Issue by adolfotregosa** [Frogging-Family/linux-tkg#859]
I'm using fedora / nobara. 

Everything works correctly but the files that are put  to /boot have issues. 

The kernel file itself is zero bytes ?? because the actual resulting kernel file is for some reason ending in .old ??? and the actual kernel file is zero bytes?

Same for System.map / symlink, although no zero bytes it ends in .old extension.

Basically the new kernel ends with .old added to it. 
Hopefully I manage to explain it.

**Comment by adolfotregosa** [comment]
This is what I mean.
![image](https://github.com/Frogging-Family/linux-tkg/assets/7437931/2da76ec8-4d20-4f32-8322-535fa16b52b3)

**Comment by AdelKS** [comment]
Are you installing the RPMs or using the "Generic" approach? I have had these issues because files in files in the `/boot` folder trip the `make install` step because of an unexpected naming scheme.

**Comment by adolfotregosa** [comment]
sorry, didn't follow. The script at the end asks me if I want to install and I say yes . I also tried to manually install them, sudo dnf install kernel-etc-etc-etc and the results are the same, like my print.

**Comment by AdelKS** [comment]
Please attach the files in the `logs` folder of your `linux-tkg` clone, and the RPM files you tried to install

**Comment by adolfotregosa** [comment]
requested files are here:

https://tregosacloud.duckdns.org/s/tXPiJrQikrXbyKw

**Comment by AdelKS** [comment]
I did not realize the kernel's RPM was `1.2GB`, I only wanted to know what files it has in it to see if this weird install under `/boot` is in it. I will write another message after I look more into it

**Comment by AdelKS** [comment]
I don't see the file called `shell-output.log.txt` you don't have it ? You can drag and drop `.txt`, `.zip` and `tar.gz` files here by the way, the filesize limit is `25MB` though.

**Comment by AdelKS** [comment]
Okay the RPM has the correct files without the weird `.old` behavior. So here's how to fix it:
1. Uninstall the RPMS
2. Remove any files left in `/boot` from it
3. Reinstall the RPMs
And you should be good!

**Comment by adolfotregosa** [comment]
> Okay the RPM has the correct files without the weird `.old` behavior. So here's how to fix it:
> 
> 1. Uninstall the RPMS
> 2. Remove any files left in `/boot` from it
> 3. Reinstall the RPMs
> 
> And you should be good!

Does not fix it for me. I have to manually delete the zero byte files and then rename/remove the .old from the files

**Comment by adolfotregosa** [comment]
> I don't see the file called `shell-output.log.txt` you don't have it ? You can drag and drop `.txt`, `.zip` and `tar.gz` files here by the way, the filesize limit is `25MB` though.

Thats all from logs folder. Literally copied the folder as is.

**Comment by AdelKS** [comment]
> Does not fix it for me. I have to manually delete the zero byte file and then rename/remove the .old from the files

Hm... the RPM definitely does not have the `.old` files in it, it's only when it gets installed that `dnf` does this kind of thing. And usually it does that when the file already exists. I am kinda out of ideas right now :thinking:

**Comment by AdelKS** [comment]
> Thats all from logs folder. Literally copied the folder as is.

I just realized it won't be in that folder when something goes wrong, it's in the parent folder, along with the `customization.cfg` file. If you can attach it (drag & drop)

**Comment by adolfotregosa** [comment]
> > Thats all from logs folder. Literally copied the folder as is.
> 
> I just realized it won't be in that folder when something goes wrong, it's in the parent folder, along with the `customization.cfg` file. If you can attach it (drag & drop) because probably something is going wrong when making or installing that RPM

Hi. Here it is:
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13760236/shell-output.log.txt)

**Comment by AdelKS** [comment]
Thanks, I do not see anything going wrong there, how about when you install the RPM, is there some kind of warning or something ? Maybe attach what is on your console when you install the RPMs (with a clean `/boot` folder)

**Comment by adolfotregosa** [comment]
> Thanks, I do not see anything going wrong there, how about when you install the RPM, is there some kind of warning or something ? Maybe attach what is on your console when you install the RPMs (starting with a clean `/boot` folder)

New kernel with 6.7-rc7 
![image](https://github.com/Frogging-Family/linux-tkg/assets/7437931/2144d333-0363-41ff-a1ad-3d453d8d5539)

**Comment by AdelKS** [comment]
If you figured out the root cause and fixed it, please write how you did !

**Comment by adolfotregosa** [comment]
I didn't.  I git pull and tried with kernel 6.7rc8 and it worked correctly
so I assumed it was fixed and closed issue.

A sexta, 5/01/2024, 23:00, Adel Kara Slimane ***@***.***>
escreveu:

**Comment by AdelKS** [comment]
Ah haha alright then
