### ISSUE TITLE
upds is missing from tkg 5.9

### ISSUE THREAD

**Issue by justin-shepherd** [Frogging-Family/linux-tkg#86]
Upon upgrading my kernel from 5.8 to 5.9 today, I noticed my DKMS modules were recompiled but reported 5.9.0-3-tkg-cfs instead of the usual **-tkg-upds-sandybridge

Thought this might be worth mentioning as a potential oversight. Thanks in advance :-)

```
dmesg | grep -i upds 
[    0.000000] Linux version 5.9.0-3-tkg-cfs (linux-tkg-upds-sandybridge@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35) #1 TKG SMP PREEMPT Tue, 13 Oct 2020 07:37:21 +0000
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-linux-tkg-upds-sandybridge root=UUID=9c925d89-488b-49f6-8d69-35942ee2bccd rw loglevel=3 quiet nvidia-drm.modeset=1 mitigations=off
[    0.040351] Kernel command line: intel_pstate=passive BOOT_IMAGE=/vmlinuz-linux-tkg-upds-sandybridge root=UUID=9c925d89-488b-49f6-8d69-35942ee2bccd rw loglevel=3 quiet nvidia-drm.modeset=1 mitigations=off
[    1.162621]     BOOT_IMAGE=/vmlinuz-linux-tkg-upds-sandybridge
```

**Comment by FLGX06** [comment]
What does `dmesg | grep sched` say?

**Comment by justin-shepherd** [comment]
```
dmesg | grep sched
[    0.092222] rcu: RCU calculated value of scheduler-enlistment delay is 75 jiffies.
[    0.552372] io scheduler mq-deadline registered
[    0.552373] io scheduler kyber registered
[    0.552389] io scheduler bfq registered
[    0.594805] sched_clock: Marking stable (594639430, 139322)->(682131745, -87352993)

```

**Comment by Snoop05** [comment]
https://github.com/Frogging-Family/linux-tkg/blob/7ca2ea2607ed330e5ddaed89dcfbf2d088af21c6/linux59-tkg/linux59-tkg-config/prepare#L55
there is a code there to catch "wrong" selection and show a prompt (unless you explicitly set a variable to ignore it) but issue is the scheduler option numbers keep changing
They really should be like 1 for CFS (especially this one), 2 for BMQ, 3 for PDS and 4 for UPDS ....

**Comment by justin-shepherd** [comment]
> In your particular case 3 was UPDS on 5.8 and now its CFS - explicitly set as well as being valid choice

That absolutely makes sense and thanks for pointing it out.

I am using the pre-compiled package from chaotic-aur - however, I'll recompile on my own for now and notify the repo maintainer in the interim.

**Comment by PedroHLC** [comment]
:sweat_smile:  Sorry about that, for some reason the "non fallback" option didn't stopped the "invalid" upds from being built.

**Comment by PedroHLC** [comment]
Yep, for some reason "upds" was considered a valid option, because:
```
╰─λ grep nofallback /usr/share/doc/linux-tkg-bmq-broadwell/customization.cfg
_nofallback="true"
```

**Comment by BillFleming** [comment]
until tkg adds it back in "upds" is not a valid option in 5.9 tkg. You need to switch your config files over to "pds" for now.

**Comment by AdelKS** [comment]
Tkg will need to rebase upds to the new tree. And honestly, you should use PDS and report any misbehavior to its maintainer instead of using an undead code. I'm using it currently and it's working pretty well !

**Comment by PedroHLC** [comment]
> Tkg will need to rebase upds to the new tree. And honestly, you should use PDS and report any misbehavior to its maintainer instead of using an undead code. I'm using it currently and it's working pretty well !

Yeah, I agree. But would be good if `_nofallback` behaviored as expected and not fallback to `cfs` in this version too :sweat_smile:

**Comment by Tk-Glitch** [comment]
UPDS is now back from the grave for 5.9.y and 5.10rc1

https://github.com/Frogging-Family/linux-tkg/commit/3ec64c8b5e47ebac0f39fd878754c4ce2ec6a264
https://github.com/Frogging-Family/linux-tkg/commit/9d110b2c694118d60b5a537b17abaa682276a05f
