### ISSUE TITLE
Fails building. 

### ISSUE THREAD

**Issue by 32bitx64bit** [Frogging-Family/linux-tkg#865]
make[1]: *** [/home/user/linux-tkg/linux-src-git/Makefile:2037: .] Error 2
make: *** [Makefile:234: __sub-make] Error 2
==> ERROR: A failure occurred in build().

OS - Arch linux.

**Comment by 32bitx64bit** [comment]
This happens on every single version I try to compile, 6.7 R8. 6.6, 6.5... Can't get any of em to work. If anyone knows the issue, let me know.

And yes, I have base-devel installed.

**Comment by AdelKS** [comment]
Would you please follow the instructions in the issue template and attach the files requested, including the complete output in your shell ? Because that's what will contain what exactly went wrong, hopefully.

**Comment by 32bitx64bit** [comment]
I'll recompile and get those logs.

**Comment by 32bitx64bit** [comment]
Seems to have vanish... usually would've failed by now.
I'll close the issue, and reopen if it's still around.
