### ISSUE TITLE
Is bore option a bore-eevdf?

### ISSUE THREAD

**Issue by baaannnaaannn** [Frogging-Family/linux-tkg#866]
Is bore option a bore-eevdf?or just bore

**Comment by ptr1337** [comment]
> Is bore option a bore-eevdf?or just bore

Depends which kernel option. Starting with 6.6 all time eevdf-bore

**Comment by AdelKS** [comment]
I guess that's why the pipelines are failing to build the bore version

**Comment by AdelKS** [comment]
to rephrase ptr1337

 `bore` is a modification on top of the default scheduler:
- linux <= 6.5 : the default scheduler is `cfs`. `bore` is a mod of `cfs`, And `bore-eevdf` changes the default scheduler to `eevdf` before adding the mod.
- linux >= 6.6 : the default schduler is `eevdf`, and `bore` is a mod of it.
