### ISSUE TITLE
Will there be a zen3 compiler optimization when zen3 releases?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#87]

**Comment by AdelKS** [comment]
Hello! Compiler optimizations are enabled in `customization.cfg`: by using `processor_opt="native"` the compiler will select the best things it has for the CPU you are running. When GCC/LLVM will get Zen3 optimizations, they will automatically be used with  `processor_opt="native"`. Also, this kind of optimization is unnoticeable in practice.

**Comment by Axilot** [comment]
Ah okay, thanks!

**Comment by AdelKS** [comment]
Happy to have helped !
