### ISSUE TITLE
grub-mkconfig does not find kernel

### ISSUE THREAD

**Issue by DouseMouse** [Frogging-Family/linux-tkg#871]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/13938959/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13938963/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13938966/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/13938968/system-info.txt)

 - Which OS do you encounter the bug on? 
 - Gentoo
 - A clear and concise description of what the bug is. 
 - Kernel installs into  hash/6.7.0-tkg-bore/linux
 - grub-mkconfig doesnt find it
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**

**Comment by AdelKS** [comment]
From the looks of it `kernel-install` is installing to `/boot/1b47099c9ebad90e16f3338161054392/6.7.0-tkg-bore` but grub is looking for images in `/boot/vmlinuz-6.7.0-x86_64-xanmod1`. I think it would probably work if `/boot/vmlinuz-6.7.0-x86_64-xanmod1` was in the `/boot/1b47099c9ebad90e16f3338161054392` subfolder. This is not a `linux-tkg` issue per se.

**Comment by DouseMouse** [comment]
I fixed it. Also 6.6 and 6.7 can't find bore-eevds, do they use bore-cfs?

**Comment by Tk-Glitch** [comment]
No, CFS is no more, so it's just "bore".

**Comment by DouseMouse** [comment]
I added --no-machineid but dracut se
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/13956868/customization.cfg.txt)
ems to still use it.
[prepare.log.txt](https://github.com/Frogging-Family/lin
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/13956871/system-info.txt)
ux-tkg/files/13956870/prepare.log.txt)

**Comment by AdelKS** [comment]
Have you tried to move the xanmod kernel within the machine id folder in `/boot` then rerun grub ?

**Comment by AdelKS** [comment]
From the `eselect news read`

```
2024-02-01-installkernel-new-use-systemd-boot
  Title                     installkernel new USE flag systemd-boot
  Author                    Andrew Ammerlaan <andrewammerlaan@gentoo.org>
  Posted                    2024-01-30
  Revision                  1

/sbin/installkernel is a script called by the kernels 'make install' as well
as by the distribution kernels post install phase. sys-kernel/installkernel
provides two paths for installing the kernel:
- the traditional installkernel, or
- systemd's kernel-install

In sys-kernel/installkernel versions lower then 20, systemd's kernel-install
would default to the layout used for systemd-boot (layout=bls). To improve
backwards compatibility with the traditional installkernel this is no longer
the case in versions 20 and up. Instead the default layout setting when no other
USE flags are enabled is a compatibility layout similar to the traditional
installkernel (layout=compat).


User Action Required (systemd-boot users)
====================

Users of systemd-boot should:
- enable the "systemd-boot" USE flag
when upgrading to >=sys-kernel/installkernel-20.


See also: https://wiki.gentoo.org/wiki/Installkernel
```

So it looks like it was using the `layout=bls` layout, and got reverted to the `compat` layout. So you need to either upgrade, or put the `layout=compat` layout in `/etc/kernel/install.d/layout.conf`

**Comment by AdelKS** [comment]
Closing, see #883 for more information
