### ISSUE TITLE
Patch to mitigate ASLR issue with kernel 6.6

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#872]
Arch linux just released a new package linux-lts version      6.6.11-2
It contains a new patch to mitigate the issue mentioned here: https://zolutal.github.io/aslrnt/

The patch is `0003-Default-to-maximum-amount-of-ASLR-bits.patch`
And can be found here: https://gitlab.archlinux.org/archlinux/packaging/packages/linux-lts

You might want to add this to linux-tkg as well

**Comment by Tk-Glitch** [comment]
Fixed for 6.6 with https://github.com/Frogging-Family/linux-tkg/commit/8514e2952b1faf7e5069407d5df5e814b3af4a0b

Fixed for 6.7 with https://github.com/Frogging-Family/linux-tkg/commit/2029a9af58d0f4964757f622be68d84bb1bd8210
