### ISSUE TITLE
Kernel 6.7 Patching-stage Failure - sed: can't read ./kernel/sched/alt_core.c: No such file or directory

### ISSUE THREAD

**Issue by ThisNekoGuy** [Frogging-Family/linux-tkg#875]
**Describe the bug**
 - Which OS do you encounter the bug on: Gentoo (LLVM)
 - A clear and concise description of what the bug is:

Running `./install.sh install` throws a sed "file not found" error when applying initial patches for kernel 6.7

 - Attach the contents of your logs folder by drag & dropping each file into this message:

[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/13996730/system-info.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/13996731/prepare.log.txt)

```
 -> External configuration file /home/neko-san/.config/frogminer/linux-tkg.cfg will be used and will override customization.cfg values.
 -> Checking out latest kernel version of 6.7
github.com      https://github.com/gregkh/linux.git (fetch)
github.com      https://github.com/gregkh/linux.git (push)
torvalds        https://github.com/torvalds/linux.git (fetch)
torvalds        https://github.com/torvalds/linux.git (push)
googlesource.com        https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable (fetch)
googlesource.com        https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable (push)
kernel.org      https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (fetch)
kernel.org      https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git (push)
torvalds        https://github.com/torvalds/linux.git (fetch)
torvalds        https://github.com/torvalds/linux.git (push)
 -> Fetching tag: v6.7 from mirror kernel.org
remote: Enumerating objects: 125152, done.
remote: Counting objects: 100% (54086/54086), done.
remote: Compressing objects: 100% (13392/13392), done.
remote: Total 23920 (delta 19723), reused 12768 (delta 10358), pack-reused 0
Receiving objects: 100% (23920/23920), 14.41 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (19723/19723), completed with 19267 local objects.
From https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux
 * [new tag]             v6.7       -> v6.7
 -> Checking out tag: v6.7
 ->    in the work folder: /home/neko-san/linux-tkg//linux-src-git
Preparing worktree (detached HEAD 0dd3ee311)
Updating files: 100% (82438/82438), done.
HEAD is now at 0dd3ee311 Linux 6.7
Replace "libunwind" with "llvm-libunwind" ? Y/[n]:y
 -> Using Arch patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28911  100 28911    0     0   127k      0 --:--:-- --:--:-- --:--:--  127k
 -> Applying graysky's cpu opts patch
 -> Applying clear linux patches
 -> Applying glitched base patch
 -> Skipping patch 0003-glitched-base-nonrt.patch...
         (unavailable for this kernel version)
 -> RPM: fixing spec generator
 -> Applying misc additions patch
 -> Skipping patch 0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch...
         (unavailable for this kernel version)
 -> Skipping patch 0002-mm-Support-soft-dirty-flag-read-with-reset.patch...
         (unavailable for this kernel version)
 -> Skipping patch 0009-prjc_v6.7-r0.patch...
         (unavailable for this kernel version)
 -> Applying prjc PDS/BMQ agressive ondemand governor patch
 -> Skipping patch 0005-glitched-pds.patch...
         (unavailable for this kernel version)
 -> Using user-provided config file in /home/neko-san/linux-tkg/kernelconfig.new
Disable MLX5_CORE for Prjc
sed: can't read ./kernel/sched/alt_core.c: No such file or directory
 -> exit cleanup done
```

**Comment by Diskette-Guy** [comment]
Same here on Debian 12.

**Comment by ZeusThundr** [comment]
I'm experiencing the same issue running `makepkg -si` trying to compile kver: 6.7.1
`sed: can't read ./kernel/sched/alt_core.c: No such file or directory`

**Comment by befabry** [comment]
Same error on Arch

**Comment by 32bitx64bit** [comment]
Same error here. Shame.

**Comment by ptr1337** [comment]
Could you try reverting https://github.com/Frogging-Family/linux-tkg/commit/90fa1dccacc7b921b194d6559b9fb9b669c1e097 and check if it fixes it?

**Comment by 32bitx64bit** [comment]
> Could you try reverting [90fa1dc](https://github.com/Frogging-Family/linux-tkg/commit/90fa1dccacc7b921b194d6559b9fb9b669c1e097) and check if it fixes it?

Probably is, issue doesn't accrue when compiling with any other scheduler, anything Project C (BMQ + PDS) causes it.

**Comment by ptr1337** [comment]
> > Could you try reverting [90fa1dc](https://github.com/Frogging-Family/linux-tkg/commit/90fa1dccacc7b921b194d6559b9fb9b669c1e097) and check if it fixes it?
> 
> Probably is, issue doesn't accrue when compiling with any other scheduler, anything Project C (BMQ + PDS) causes it.

https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/prepare#L1189-L1196

Yes, on this part it does fail. But if it does proper patch prjc, it should sed correctly.
You can try to uncomment these tho

**Comment by ThisNekoGuy** [comment]
I reverted the commit to the one prior; it does seem to be the reason why

**Comment by ptr1337** [comment]
> I reverted the commit to the one prior; it does seem to be the reason why

https://github.com/Frogging-Family/linux-tkg/commit/843725ec7c3559e05b713f48f0a9a97a82b668e5

This one ?

**Comment by ThisNekoGuy** [comment]
Yeah, that one

**Comment by ZeusThundr** [comment]
> > I reverted the commit to the one prior; it does seem to be the reason why
> 
> [843725e](https://github.com/Frogging-Family/linux-tkg/commit/843725ec7c3559e05b713f48f0a9a97a82b668e5)
> 
> This one ?

Compiling while writing this seems to work so far. At least it started to compile unlike last time using commit #864 .

**Comment by ptr1337** [comment]
> I tried building with Linux ck - 6.

There should be something before the log.
you can also use the makepkg --log function to get proper logs.

**Comment by ZeusThundr** [comment]
> > I tried building with Linux ck - 6.
> 
> There should be something before the log. you can also use the makepkg --log function to get proper logs.

I hope this is helpfull in someway as I would like to be able to successfully compile linux 6.7.1. I tried compiling with the lastest commit [d32e8bd](https://github.com/Frogging-Family/linux-tkg/commit/d32e8bdb05701311abab20491552487dd5937f1f)
makepgk --log [prepare.log](https://github.com/Frogging-Family/linux-tkg/files/14008371/linux67-tkg-pds-llvm-6.7.1-273-x86_64-prepare.log)

**Comment by ZeusThundr** [comment]
> > > > I tried building with Linux ck - 6.
> > > 
> > > 
> > > There should be something before the log. you can also use the makepkg --log function to get proper logs.
> > 
> > 
> > I hope this is helpfull in someway as I would like to be able to successfully compile linux 6.7.1. I tried compiling with the lastest commit [d32e8bd](https://github.com/Frogging-Family/linux-tkg/commit/d32e8bdb05701311abab20491552487dd5937f1f) makepgk --log [prepare.log](https://github.com/Frogging-Family/linux-tkg/files/14008371/linux67-tkg-pds-llvm-6.7.1-273-x86_64-prepare.log) Additional Notes: This might not be helpful but might be worth mentioning. I do not run sudo on my machine I have uninstalled sudo. I currently use opendoas and dracut on arch.
> 
> Just use sudo like a normal person? Also that isn't that latest commit. Also this has been closed, as its solved now.

Their is good reason not to use sudo and use opendoas instead, but besides that point I was actually using the latest commit as I git checkouted the master branch before trying to compile. Upon running git status I am actually on the latest commit [8313f01](https://github.com/Frogging-Family/linux-tkg/commit/8313f0163f89bfe49ebdf5b0352767697648fa22) as one would expect after running `git checkout master`. I didn't expect their to be multiple commits so sudden and assumed that the latest commit was the one was the one this issue was closed with as of the writing of my previous reply. I was just trying to provide what was asked of me I will be updated my previous message to avoid further confusion.

**Conclusion:** Use sudo instead of opendoas when trying to compile linux-tkg as it will fail to build using `makepkg -si` otherwise on arch at least... I'm still going to switch back to opendoas as soon as it's done though.
