### ISSUE TITLE
CONFIG_PREEMPT changes from 6.6.9 to 6.6.10

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#877]
Why is does linux-tkg change the preempt settings for the lts kernel? As soon as kernel 6.6 becomes lts the config is changing.

That gives the weird behaviour that kernel 6.6.9 has this setting:

```
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
```

while kernel 6.6.10 and all following kernels have changed the settings to 
```
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set
```

This change happens as soon as kernel 6.6. is being declared as LTS kernel. I find this very confusing. Why should the linux-tkg kernel 6.6.10  have a different behavior than 6.6.9?  Why dont you keep the config stable for a consistent user experience.

Arch is doing the same config change. May be that is where linux-tkg is getting it from. Arch developers are saying that they do this change because LTS kernels are for servers and need different preemption rules. But does that argument hold for linux-tkg also? 

**EDIT:**

The kernel documentation says about CONFIG_PREEMPT:

_"Select this if you are building a kernel for a desktop or embedded system with latency requirements in the milliseconds range"._

And linux-tkg page says: 

_"[...] with a selection of patches aiming for better desktop/gaming experience"_

That sound like linux-tkg wants to have `CONFIG_PREEMPT` enabled and `CONFIG_PREEMPT_VOLUNTARY` disabled for all kernels.

**Comment by AdelKS** [comment]
The reason is rather simple: we use Arch's base config file as starting point. And we keep on following the kernel's config file when the kernel becomes lts. And the config differ when the transfer is done for a reason I ignore:

https://gitlab.archlinux.org/archlinux/packaging/packages/linux-lts/-/blob/42324ac498fe636cfce193add03da2fd36c82ca0/config

https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/2db49d4fbcda88d76a4c236ccb5a7986715d70ba/config

**Comment by Tk-Glitch** [comment]
I do agree that it's confusing and possibly undesirable, but indeed it's *only* due to pulling arch defconfig updates. We should make the PREEMPT config only bound to our own options instead of relying onto the defconfig alone for default settings.

**Comment by mabod** [comment]
This is what I thought. I believe the Arch behaviour is wrong. It does not make sense to change the config just because a certain kernel release is now LTS.

Anyways, for all those who want to keep the same user experience for all kernels I recomment kernel cmdline option `preempt=full`. This is the default kernel setting for the current Arch kernel releases and the cmdline option ensures that all LTS kernels keep that setting as well.
