### ISSUE TITLE
(Question) mypatch formatting / How to apply an extra patch set to linux-tkg

### ISSUE THREAD

**Issue by alphabitserial** [Frogging-Family/linux-tkg#878]
Hello! This is more of a question than an issue report, so please accept my apologies if it's in the wrong place. I'd like to build linux-tkg for use on my MacBook. It requires some extra patches to support hardware like the trackpad, keyboard, bluetooth/wifi, audio, etc.

The patch set is here: https://github.com/t2linux/linux-t2-patches

The readme states where to put user patches and how to enable them, but one thing I'm not clear on is the mypatch extension/format. Would I just rename the .patch files from this repo to .mypatch and place them in the directory? Or is there some format conversion I need to do?

Thanks so much for your hard work maintaining the patchsets that make linux-tkg what it is!

**Comment by AdelKS** [comment]
> Would I just rename the .patch files from this repo to .mypatch and place them in the directory?

Yep that pretty much it !

**Comment by alphabitserial** [comment]
Sweet, thank you! I'll give it a try. :grin:
