### ISSUE TITLE
Please add 6.8-rc to the options

### ISSUE THREAD

**Issue by gardotd426** [Frogging-Family/linux-tkg#880]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

I know you're incredibly busy, which is why in situations like this with wine-tkg-git and nvidia-all I always just file the PR myself to do the work for you, but I'm afraid I can't do that here because of all the linux-tkg-config stuff that needs to be added that I have no idea how to do. There are those new ntsync4 patches I want to try, that require both Wine and Kernel patchsets, and I've already successfully patched and built a wine-tkg-git build for the wine patchset, but I can't build the patched kernel required because it's based on 6.8-rc2.

The patches seem to apply to 6.7.1, but they are built on top of 6.8-rc2 at the source so obviously it'd be preferable to use what the devs are using. Also usually the new rc kernel gets added on here by around this time. If you don't have the time, don't worry about it, but these ntsync patches seem very exciting (potentially) so it'd be cool if we could get 6.8-rc2 added.  Thanks man

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/blob/master/6.7/misc/0001-ntsync.patch

There you go. Put them into the userpatch directory with mypatch ending and thats it.
Consider to compile it as built in, to avoid further problems when using ntsync.

**Comment by ptr1337** [comment]
> https://github.com/CachyOS/kernel-patches/blob/master/6.7/misc/0001-ntsync.patch
> 
> There you go. Put them into the userpatch directory with mypatch ending and thats it. Consider to compile it as built in, to avoid further problems when using ntsync.

You can use them on 6.7 and 6.8. There is no bad interactions.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/975a64b45e8116f834d9163a16e68ea5b9ce22d0
