### ISSUE TITLE
crash/freezing

### ISSUE THREAD

**Issue by Bomlex** [Frogging-Family/linux-tkg#881]
Can someone help. 
PC freezes during boot or randomly during use if you are lucky enough to get through the boot process.
Sometimes it just works perfectly.

Tried a few kernels, almost all the same problem
I think this problem started with kernel 6.4+ (for me)
Currently only "linux-amd" kernel works without crashes freezes
TKG better than the rest, but it may not start the first time

```
B650M DS3H
Ryzen 9 7950X
Radeon RX 7900 XTX
6.7.2-273-tkg-bore
Arch
```
![P_20240128_103739](https://github.com/Frogging-Family/linux-tkg/assets/10121233/08dcd447-bcf7-41f1-8034-2b9435f12634)
![P_20240128_103915](https://github.com/Frogging-Family/linux-tkg/assets/10121233/06f2b001-ffba-44c7-8719-577b11cb44b2)
![P_20240129_093809](https://github.com/Frogging-Family/linux-tkg/assets/10121233/ca8244d1-cabd-45b4-9cd2-06e3717bbe41)

**Comment by AdelKS** [comment]
This is likely a faulty RAM or corrupt filesystem: test your RAM first with memtest86, and if that's okay, you probably need to reinstall your filesystem, which one are you using?

**Comment by AdelKS** [comment]
Alright, one thing good, I'd suggest to take a live USB of Arch:
0- backup your data that you want to keep
1- run a filesystem check and repair on your root fs
2- reinstall all packages

**Comment by ptr1337** [comment]
Are you using some kind of Curve Optimizer or equal?
If yes, this could be also the reason. with the 6.6 Kernel EEVDF was introduced and a lot of curve optimizer values were not stable with eevdf anymore

**Comment by AdelKS** [comment]
Yeah that makes sense, I was about to suggest that after you try the repairs if it happens again. Good ! You can close the issue if that's all for you
