### ISSUE TITLE
Gentoo - install.sh fails to install kernel to /boot

### ISSUE THREAD

**Issue by Slaviusz** [Frogging-Family/linux-tkg#883]
On recent Gentoo running the `./install.sh install` does not successfully install the kernel to the /boot
/usr/src/kver and /lib/modules/kver is succesfully created and populated but /boot contains only temp folder used during kernel install.

Git commit: ff6599dad3ebebd31860eee8a8704bccc2680783 (HEAD -> master, origin/master, origin/HEAD)
KVER: 6.7.3-tkg-eevdf

```
gentoo ~/linux-tkg # ll /boot/
total 64M
drwxr-xr-x  6 root root 4.0K Feb  1 11:02 .
drwxr-xr-x 25 root root 4.0K Jun 10  2023 ..
-rw-r--r--  1 root root  76K Jan 22 08:28 amd-uc.img
drwxr-xr-x  3 root root 4.0K Feb  1 11:02 b670b2bc7c516770aa75bd7a615093b6
-rw-r--r--  1 root root 130K Dec 29 00:01 config-6.1.69-tkg-cfs
-rw-r--r--  1 root root 117K Jan  3 19:46 config-6.6.9-tkg-eevdf
-rw-r--r--  1 root root 118K Jan 10 10:19 config-6.7.0-tkg-eevdf
drwxr-xr-x  3 root root 1.0K Jan  1  1970 efi
drwxr-xr-x  7 root root 4.0K Jan 10 10:22 grub
-rw-------  1 root root  14M Dec 29 00:01 initramfs-6.1.69-tkg-cfs.img
-rw-------  1 root root  13M Jan  3 19:46 initramfs-6.6.9-tkg-eevdf.img
-rw-r--r--  1 root root  13M Jan 10 10:22 initramfs-6.7.0-tkg-eevdf.img
-rw-r--r--  1 root root    0 Sep 19  2021 .keep
drwxr-xr-x  3 root root 4.0K Feb  1 11:02 loader
-rw-r--r--  1 root root 2.2M Dec 29 00:01 System.map-6.1.69-tkg-cfs
-rw-r--r--  1 root root 2.2M Jan  3 19:46 System.map-6.6.9-tkg-eevdf
-rw-r--r--  1 root root 2.2M Jan 10 10:19 System.map-6.7.0-tkg-eevdf
-rw-r--r--  1 root root 5.7M Dec 29 00:01 vmlinuz-6.1.69-tkg-cfs
-rw-r--r--  1 root root 5.8M Jan  3 19:46 vmlinuz-6.6.9-tkg-eevdf
-rw-r--r--  1 root root 5.8M Jan 10 10:19 vmlinuz-6.7.0-tkg-eevdf

gentoo ~/linux-tkg # ls -lah /usr/src/
total 24K
drwxr-xr-x  6 root root 4.0K Feb  1 11:10 .
drwxr-xr-x 13 root root 4.0K Feb  8  2023 ..
-rw-r--r--  1 root root    0 Sep 19  2021 .keep
lrwxrwxrwx  1 root root   30 Feb  1 11:10 linux -> /usr/src/linux-6.7.3-tkg-eevdf
drwxr-xr-x 26 root root 4.0K Dec 29 00:01 linux-6.1.69-tkg-cfs
drwxr-xr-x 26 root root 4.0K Jan  3 19:46 linux-6.6.9-tkg-eevdf
drwxr-xr-x 26 root root 4.0K Jan 10 10:18 linux-6.7.0-tkg-eevdf
drwxr-xr-x 26 root root 4.0K Feb  1 11:10 linux-6.7.3-tkg-eevdf

gentoo ~/linux-tkg # ls -lah /lib/modules/
total 24K
drwxr-xr-x 6 root root 4.0K Feb  1 11:02 .
drwxr-xr-x 9 root root 4.0K Jan 22 10:21 ..
drwxr-xr-x 3 root root 4.0K Dec 29 00:01 6.1.69-tkg-cfs
drwxr-xr-x 3 root root 4.0K Jan  3 19:46 6.6.9-tkg-eevdf
drwxr-xr-x 3 root root 4.0K Jan 10 10:18 6.7.0-tkg-eevdf
drwxr-xr-x 3 root root 4.0K Feb  1 11:10 6.7.3-tkg-eevdf

```

LOG: https://gist.github.com/Slaviusz/4760b430363b0c537b85741fbde7e8e2

**Comment by AdelKS** [comment]
This is the relevant snippet

```
-> Installing kernel
  INSTALL /boot
Loading /usr/lib/kernel/install.conf…
layout=bls set via /usr/lib/kernel/install.conf
INITRD_GENERATOR (none) set via /usr/lib/kernel/install.conf.
UKI_GENERATOR (none) set via /usr/lib/kernel/install.conf.
Loaded /usr/lib/kernel/install.conf.
Loading /etc/machine-info…
MACHINE_ID=b670b2bc7c516770aa75bd7a615093b6 set via /etc/machine-id.
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Directory "/boot" is not the root of the file system.
Couldn't find an XBOOTLDR partition.
Failed to check file system type of "/efi": No such file or directory
File system "/boot" is not a FAT EFI System Partition (ESP) file system.
File system "/dev/sda1" is not on a GPT partition table.
Couldn't find EFI system partition, ignoring.
KERNEL_INSTALL_BOOT_ROOT autodetection yielded no candidates, using "/boot".
Using entry token: b670b2bc7c516770aa75bd7a615093b6
kernel version (6.7.3-tkg-eevdf) set via command line.
kernel image file (/usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage) set via command line.
Using ENTRY_DIR=/boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf
mkdir -p /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf
Using plugins:
  /usr/lib/kernel/install.d/00-00machineid-directory.install
  /usr/lib/kernel/install.d/10-copy-prebuilt.install
  /usr/lib/kernel/install.d/50-depmod.install
  /usr/lib/kernel/install.d/50-dracut.install
  /usr/lib/kernel/install.d/51-dracut-rescue.install
  /usr/lib/kernel/install.d/90-loaderentry.install
  /usr/lib/kernel/install.d/90-uki-copy.install
Plugin environment:
  LC_COLLATE=C.UTF-8
  KERNEL_INSTALL_VERBOSE=1
  KERNEL_INSTALL_IMAGE_TYPE=unknown
  KERNEL_INSTALL_MACHINE_ID=b670b2bc7c516770aa75bd7a615093b6
  KERNEL_INSTALL_ENTRY_TOKEN=b670b2bc7c516770aa75bd7a615093b6
  KERNEL_INSTALL_BOOT_ROOT=/boot
  KERNEL_INSTALL_LAYOUT=bls
  KERNEL_INSTALL_INITRD_GENERATOR=none
  KERNEL_INSTALL_UKI_GENERATOR=none
  KERNEL_INSTALL_STAGING_AREA=/tmp/kernel-install.staging.xU6EJA
Plugin arguments: add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(sd-executor)' as PID 2504716.
About to execute /usr/lib/kernel/install.d/00-00machineid-directory.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504717.
/usr/lib/kernel/install.d/00-00machineid-directory.install succeeded.
About to execute /usr/lib/kernel/install.d/10-copy-prebuilt.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504718.
/usr/lib/kernel/install.d/10-copy-prebuilt.install succeeded.
About to execute /usr/lib/kernel/install.d/50-depmod.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504720.
+depmod -a 6.7.3-tkg-eevdf
/usr/lib/kernel/install.d/50-depmod.install succeeded.
About to execute /usr/lib/kernel/install.d/50-dracut.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504722.
/usr/lib/kernel/install.d/50-dracut.install succeeded.
About to execute /usr/lib/kernel/install.d/51-dracut-rescue.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504723.
Skipping, 'dracut_rescue_image' not set to 'yes' in any dracut configuration file
/usr/lib/kernel/install.d/51-dracut-rescue.install succeeded.
About to execute /usr/lib/kernel/install.d/90-loaderentry.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504728.
Creating /boot/loader/entries/b670b2bc7c516770aa75bd7a615093b6-6.7.3-tkg-eevdf.conf
/usr/lib/kernel/install.d/90-loaderentry.install succeeded.
About to execute /usr/lib/kernel/install.d/90-uki-copy.install add 6.7.3-tkg-eevdf /boot/b670b2bc7c516770aa75bd7a615093b6/6.7.3-tkg-eevdf /usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage
Successfully forked off '(direxec)' as PID 2504739.
/usr/lib/kernel/install.d/90-uki-copy.install succeeded.
(sd-executor) succeeded.
```

It seems that it struggles to find your EFI partition. You are using legacy boot ?

In any case, it is installing the kernel into `/boot/b670b2bc7c516770aa75bd7a615093b6` where that code is your machine ID, Gentoo switched to doing that not too long ago as the recommended install path. Are you using GRUB ? Maybe it needs to be configured to look inside that folder.

**Comment by AdelKS** [comment]
#871 is the same issue I think

**Comment by Slaviusz** [comment]
Ah, I see. This is former physical host migrated to VM (going from EFI without secure boot to BIOS legacy boot in KVM/QEMU) using GRUB as boot loader. I may have forgotten to switch some config to disable the UEFI?

**Comment by AdelKS** [comment]
From the `eselect news read`

```
2024-02-01-installkernel-new-use-systemd-boot
  Title                     installkernel new USE flag systemd-boot
  Author                    Andrew Ammerlaan <andrewammerlaan@gentoo.org>
  Posted                    2024-01-30
  Revision                  1

/sbin/installkernel is a script called by the kernels 'make install' as well
as by the distribution kernels post install phase. sys-kernel/installkernel
provides two paths for installing the kernel:
- the traditional installkernel, or
- systemd's kernel-install

In sys-kernel/installkernel versions lower then 20, systemd's kernel-install
would default to the layout used for systemd-boot (layout=bls). To improve
backwards compatibility with the traditional installkernel this is no longer
the case in versions 20 and up. Instead the default layout setting when no other
USE flags are enabled is a compatibility layout similar to the traditional
installkernel (layout=compat).


User Action Required (systemd-boot users)
====================

Users of systemd-boot should:
- enable the "systemd-boot" USE flag
when upgrading to >=sys-kernel/installkernel-20.


See also: https://wiki.gentoo.org/wiki/Installkernel
```

So it looks like it was using the `layout=bls` layout, and got reverted to the `compat` layout. So you need to either upgrade, or put the `layout=compat` layout in `/etc/kernel/install.d/layout.conf`

**Comment by Slaviusz** [comment]
I have recompiled `sys-kernel/installkernel` with `+grub +dracut` flags and re-did `install.sh install`. This time I can see initramfs and kernel image in `/boot`. 
However I noticed the following:
* dracut ignored params from `.config` file - in my case `--lz4` and tried to use ones from `/etc`
* there's no kernel config or System map in /boot

I'm still new to this grub situation so I'm no ready to reboot and test if it actually works (this is my Docker server with no graphics card or monitor attached and downtiimes are always stressfull)

**Comment by AdelKS** [comment]
> dracut ignored params from .config file - in my case --lz4 and tried to use ones from /etc

Ah yeah that won't work anymore, you need to put it in `/etc/dracut.conf.d/something.conf` and we need to make it explicit in the readme.

> there's no kernel config or System map in /boot

Those aren't needed, I don't have them on my machine and it boots fine

**Comment by Slaviusz** [comment]
I have `compress="zstd"` in my `/etc/dracut.conf.d/compress.conf` file and I thought it's not working as resulting file was almost twice as big and doing `file /boot/initramfs-x.x.x-tkg.img` resulted in regular CPIO archive instead of zstd.
Then I found out I'm probably missing the "hostonly" option. After that the initramfs image is the same size however still the file does not idenotify it as zstd archive (as with my previous images). But I guess this has nothing to do with TKG kernel rather with `installkernel` and `dracut` and is Gentoo specific.

```file /boot/initramfs-6.7.3-tkg-eevdf.img
/boot/initramfs-6.7.3-tkg-eevdf.img: ASCII cpio archive (SVR4 with no CRC)
```
```file /boot/initramfs-6.7.0-tkg-eevdf.img
/boot/initramfs-6.7.0-tkg-eevdf.img: Zstandard compressed data (v0.8+), Dictionary ID: None
````

**Comment by AdelKS** [comment]
Yeah, check if there are no other dracut config files that change the compression algo ? Maybe dracut has a use flag ? You already have zstd installed since it worked before 🤔

**Comment by Slaviusz** [comment]
I checked everything I know of. I tried providing `--zstd` and `--compress zstd` on command line (I copied it from tkg `install.sh install` output) but still the resulting image is not zstd compressed.
However this is on me, feel free to close this issue as resulting kernel and initramfs is correct as I was able t o reboot into it yesterday without problems. Consider this issue solved.

**Comment by AdelKS** [comment]
Keep us updated if you figured out this compression issue, feel free to ask around in IRC, it looks like its @AndrewAmmerlaan who's spearheading these changes, if you can give your input, thanks!

**Comment by Slaviusz** [comment]
> That's not a temp folder, that is your machine-id folder for systemd-boot

Well, I don't use systemd-boot and I don't have respective USE flags enabled (sys-apps/systemd, sys-kernel/installkernel) so it ssems the detection mechanism is not perfect and this step should/could be skipped to save time.

> Some parameters it reads correctly from dracut.conf others are only read from dracut.conf.d. This difference is a bug in dracut.

Definitely the compress parameter is not being read from /etc/dracut/conf.d/*.conf because for me it's being ignored on sys-kernel/dracut-060_pre20240104-r2 as it produces raw CPIO archive

**Comment by AndrewAmmerlaan** [comment]
> > That's not a temp folder, that is your machine-id folder for systemd-boot
> 
> Well, I don't use systemd-boot and I don't have respective USE flags enabled (sys-apps/systemd, sys-kernel/installkernel) so it seems the detection mechanism is not perfect and this step should/could be skipped to save time.

It used to be the default, this is no longer the case (now it is only used if the `systemd-boot` flag is enabled). So the original (broken) behaviour you saw is now gone in version 20 and up.
 
> > Some parameters it reads correctly from dracut.conf others are only read from dracut.conf.d. This difference is a bug in dracut.
> 
> Definitely the compress parameter is not being read from /etc/dracut/conf.d/*.conf because for me it's being ignored on sys-kernel/dracut-060_pre20240104-r2 as it produces raw CPIO archive

Just to double check, you do have `app-arch/zstd` installed? Dracut silently falls back to gzip if it can't find the specified compressor.

**Comment by Slaviusz** [comment]
This is a VM. I have disabled all microcode support in kernel config. Moreover I use the same config and as you can see my built 6.7.0-tkg kernel has zstd compressed initramfs but 6.7.3-tkg does not.

When I manually re-run the same dracut command as used by installkernel I similarly get uncompressed initramfs.

https://gist.github.com/Slaviusz/e60d45847338c937630418c9f3b5a2e1

Even when I specifically provide cmd line parameters to use zstd compression:

```
dracut -f --verbose --kernel-image '/usr/src/linux-6.7.3-tkg-eevdf/arch/x86/boot/bzImage' --no-uefi --kver '6.7.3-tkg-eevdf' --zstd --compress zstd
```

I did `strace` of the dracut command and it is searching and finding zstd binary in the path but for some reason it's not using it.

**Comment by Slaviusz** [comment]
I have tested with `--lz4 --compress lz4` and the resulting initramfs is significantly larger (17M vs 13M) so some compression is applied but I do not understand how and where.
I tried to extract the main_archive from the initramfs with 
```
# dd if=/boot/initramfs-6.7.3-tkg-eevdf.img skip=10 of=main_archive
26489+1 records in
26489+1 records out
13562506 bytes (14 MB, 13 MiB) copied, 0.0120394 s, 1.1 GB/s
```
but that is also not compressed CPIO archive
```
# file main_archive
main_archive: data
```

**Comment by AndrewAmmerlaan** [comment]
> Thanks. I have put `early_microcode="no"` into `/etc/dracut.conf` and the result is zstd compressed initrd. Although I have to point out I did not have linux-firmware on my system (unmerged after I migrated the host to VM). Also important to note is that the resulting size of this new initrd is the same as before when reporting raw CPIO archive - 13M :(
> 

Hmm, that is a bit odd. Perhaps dracut will do this outer/inner initramfs stuff even if there is no microcode (where the outer image is then just empty I would think). This seems a bit pointless, and may be an upstream bug.

**Comment by Slaviusz** [comment]
Anyway, thank you for your help.

**Comment by AndrewAmmerlaan** [comment]
No problem.

I think this PR may be what caused this change in behaviour: https://github.com/dracutdevs/dracut/pull/2481

**Comment by AdelKS** [comment]
Thanks for chiming in @AndrewAmmerlaan !
