### ISSUE TITLE
Missing Processor Optimizations Patch or Unremoved Option in customization.cfg

### ISSUE THREAD

**Issue by VoidAndCaffeine** [Frogging-Family/linux-tkg#885]
**Describe the bug**
 - Which OS do you encounter the bug on?
   - Arch, but issue occurs with a fresh clone regardless of distro
 - A clear and concise description of what the bug is.
   - There is no Processor Optimizations patch in the patches folder and setting it in customization.cfg does not carry over to nconfig.
   - Either something happened and the patch was mistakenly deleted or it was purposefully deleted and the customization.cfg was not updated to reflect it.
 - Attach the contents of your logs folder by drag & dropping each file into this message.
   - All patches except 0013-fedora-rpm apply successfully on Arch
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/14187112/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/14187113/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/14187114/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/14187115/system-info.txt)

**Comment by Tk-Glitch** [comment]
The patch is grabbed at build time from https://github.com/graysky2/kernel_compiler_patch, and is not available for 6.8 RCs at this point in time. RCs are usually missing features against the current release, that's expected as people are working on bringing the patches when the release drops.

**Comment by ptr1337** [comment]
> The patch is grabbed at build time from https://github.com/graysky2/kernel_compiler_patch, and is not available for 6.8 RCs at this point in time. RCs are usually missing features against the current release, that's expected as people are working on bringing the patches when the release drops.

https://github.com/CachyOS/linux/commit/9e538dfed2bccde9e33df82a836e5ec3a9ac4333

Here is a rebased one.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/23197d57fd0ec21d42bfe7c2920a26bf7071315a
