### ISSUE TITLE
Fails to makefile          dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

### ISSUE THREAD

**Issue by xman0980** [Frogging-Family/linux-tkg#886]
Ubuntu 22.04    6.5.0-17-generic

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/14226526/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/14226527/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/14226529/system-info.txt)

It got right to the end, and then failed.

 AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
make[5]: *** [Makefile:2037: .] Error 2
make[4]: *** [Makefile:359: __build_one_by_one] Error 2
make[3]: *** [debian/rules:10: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:139: deb-pkg] Error 2
make[1]: *** [/home/xorcist/linux-tkg/linux-src-git/Makefile:1662: deb-pkg] Error 2
make: *** [Makefile:234: __sub-make] Error 2
 -> exit cleanup done

**Comment by AdelKS** [comment]
Hey, you forgot to attach the `full-output` txt file too so we can look into it

**Comment by xman0980** [comment]
i dont have a full-output
`` ~ cd linux-tkg
➜  linux-tkg git:(master) ✗ ls
current_env        kernelconfig.new  linux-tkg-config                       linux-upstream_6.5.13-1.dsc        minimal-modprobed.db
customization.cfg  linux-kernel.git  linux-tkg-patches                      linux-upstream_6.5.13.orig.tar.gz  PKGBUILD
install.sh         linux-src-git     linux-upstream_6.5.13-1.debian.tar.gz  logs                               README.md
➜  linux-tkg git:(master) ✗ cd logs
➜  logs git:(master) ✗ ls
customization.cfg.txt  prepare.log.txt  system-info.txt
➜  logs git:(master) ✗
```

**Comment by Tk-Glitch** [comment]
`make[7]: *** No rule to make target 'debian/canonical-revoked-certs.pem', needed by 'certs/x509_revocation_list'.  Stop.`

Okay so it's a signing issue. We could either disable signing or attempt to grab the cert from linux-sources debian package I guess.

**Comment by xman0980** [comment]
Up to you. This is my first time trying this. I'm not sure what you prefer. If you wanna be safe and fix the cert issue, thats fine, or just disable signing, I dont have a preference either way. I just appreciate the quick response.

**Comment by AdelKS** [comment]
We are supposed to already be disabling certs 🤔

**Comment by xman0980** [comment]
I no longer have the server that I had this issue on. I switched to a different one. The script installed without issue. Xeon W-1250 is extremely responsive!!! Thanks!
