### ISSUE TITLE
0012-misc-additions.patch fails to apply

### ISSUE THREAD

**Issue by FGD-Garuda** [Frogging-Family/linux-tkg#888]
**Describe the bug**
 - Which OS do you encounter the bug on?
ARCH
 - A clear and concise description of what the bug is.

During build process of 6.7 (picking up the patch change made 9h ago at the time of writing this) when patches are applied, this error pops up:
~~~
==> Starting prepare()...
-> Using Arch patches
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 28911  100 28911    0     0   120k      0 --:--:-- --:--:-- --:--:--  120k
-> Applying graysky's cpu opts patch
-> Applying clear linux patches
-> Applying glitched base patch
-> Skipping patch 0003-glitched-base-nonrt.patch...
(unavailable for this kernel version)
-> RPM: fixing spec generator
-> Applying misc additions patch
==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.
~~~

Looking at the attached log, clearly some hunks are failing.
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/14324127/prepare.log.txt)

I do not have the skills to play with these types of errors.

When removing the `0012-misc-additions.patch` file, the error clears out, of course the patch isn't integrated.
I don't know exactly what features I'm missing so I can't tell whether or not it's a valid workaround.

Do you need me to run  `makepkg [args] | tee shell-output.log`?

Thanks

**Comment by Tk-Glitch** [comment]
None of those failing hunks are part of the patch anymore, as you can see here : https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/6.7/0012-misc-additions.patch

They were removed with https://github.com/Frogging-Family/linux-tkg/commit/4d576fd59c4691b75c8a8ee7e4ea321afd76e27a and https://github.com/Frogging-Family/linux-tkg/commit/ff6599dad3ebebd31860eee8a8704bccc2680783

The ath11k part is 3 weeks old so your tree seems old. Either a modification on your end prevents pulling new changes in or you cloned through the PKGBUILDS repo and didn't run `git pull` in your linux-tkg subproject.

**Comment by FGD-Garuda** [comment]
OMG, what the ... happened here, you are correct. 3 years using the same git commands and never had a single issue, but I guess I hit some corruption this time. I have changed how to pull/re-clone so this should never happen again.

Thanks for your time!

**Comment by Tk-Glitch** [comment]
You're welcome!
