### ISSUE TITLE
Question: How to cross compile for debian?

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#890]
Hi,

my main PC is a tsrong machine running endeavouros, with linux.tkg kernel of course. My laptop is way slower and running debian testing. It is too slow for compilation jobs. Is there a way to compile the linux-tkg debian packages on my main PC with endeavouros? 

PS
I know that this project provides deb packages for the latest kernel. But I am looking for LTS kernels, 6.6 series. If you could provide deb packages for LTS too, I would not need to compile myself ;-)

**Comment by AdelKS** [comment]
Hey, the simplest way is to install docker then fire up a debian container, easy peazy
