### ISSUE TITLE
kernel source from XZ archive instead of GZ archive

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#892]
I just saw a manjaro related post on gitlab which talks about using the XZ kernel archives  instead of the GZ compressed archives to save bandwidth.

https://gitlab.manjaro.org/packages/core/linux61/-/issues/6#note_31554

The corresponding diff is:

```
-source=("https://git.kernel.org/torvalds/t/linux-${_basekernel}.tar.gz"
+source=("https://www.kernel.org/pub/linux/kernel/v6.x/linux-${_basekernel}.tar.xz"
```

I downloaded both archives. the gz archive is significantly larger than the xz archive.

```
219M linux-6.6.tar.gz
134M linux-6.6.tar.xz
```
I do not know how linux-tkg is retrieving the kernel source. But it seems to me that the XZ archiv is the more sustainable option.

**Comment by AdelKS** [comment]
We are no longer downloading archives, we use `git` now. I believe we used to download the `xz` ones.
