### ISSUE TITLE
[feature] Add amdgpu Navi 2X freeze patches for kernels 6.7+

### ISSUE THREAD

**Issue by ezkha** [Frogging-Family/linux-tkg#896]
Hello,

This is a feature request to add patches to the default list for kernels 6.7+.

These patches fix random freezes/panics on RX 6000 series GPUs and kernels 6.7.X. They are mostly reverts.

### [Patch 3](https://gitlab.freedesktop.org/drm/amd/-/issues/3142#note_2304417)

Updated for 6.7.6. Tested working on 6.7.8 and 6.7.6.

[DDL to patch](https://gitlab.freedesktop.org/drm/amd/uploads/1230755cbae3ae18419c12a2daaf8a6e/02-fix-amdgpu-freezes.patch)

### [Patch 2](https://gitlab.freedesktop.org/drm/amd/-/issues/3149#note_2290254)

Updated for 6.7.5. Untested.

[DDL to patch](https://gitlab.freedesktop.org/drm/amd/uploads/851075a0b344e5fb1b76b8957e746bdf/02-fix-amdgpu-freezes.patch)

### [Patch 1](https://gitlab.freedesktop.org/drm/amd/uploads/dbecb64a8bc857376fddbc732f37e326/02-fix-amdgpu-freezes.patch)

Original for 6.7.4. Untested.

[DDL to patch](https://gitlab.freedesktop.org/drm/amd/uploads/dbecb64a8bc857376fddbc732f37e326/02-fix-amdgpu-freezes.patch)

The whole thread where these patches can be found is [here](https://gitlab.freedesktop.org/drm/amd/-/issues/3149).
Another thread referenced [here](https://gitlab.freedesktop.org/drm/amd/-/issues/3142).

Currently using patch 3 on locally compiled linux-tkg 6.7.8 with BORE-EEVDF.
No freezes nor panics related to amdgpu thus far. Using an RX 6750 XT.

I have no idea why this still isn't pushed to the kernel mainline yet.

**Comment by ezkha** [comment]
Patches have been added. Thanks. I might try to directly do a PR next time; it would save time.

Probably unrelated but when I compiled 6.8.1-tkg with default patch selection and default EEVDF, neither my USB keyboard nor mouse would work in either TTY or Hyprland. 

journalctl shows no relevant logs except some "kernel: too many entries; ignoring [mem ADDRESS-ADDRESS]" spam in some boots.

Issue should be probably closed now regardless.

**Comment by Tk-Glitch** [comment]
If you are using modprobed-db, you might want to rebuild a full kernel. Arch's 6.8 defconfig has moved quite a few builtins to modules so the db will need to be populated with the new entries.
If you're not using modprobed-db however, that would be a valid upstream issue.
Closing this one as resolved.

**Comment by ezkha** [comment]
> If you are using modprobed-db, you might want to rebuild a full kernel. Arch's 6.8 defconfig has moved quite a few builtins to modules so the db will need to be populated with the new entries. If you're not using modprobed-db however, that would be a valid upstream issue. Closing this one as resolved.

Yes, I do use modprobed-db and this is what I suspected at first when there was no input coming through. Though when I checked the logs, I saw nothing mentionning a missing module, so I thought "whatever it'll get fixed" and just reverted to a previous TkG build.

I will wait for 6.8 to come into the Arch repos, run a `modprobed-db store` once there and rebuild. The new kernel shouldn't take long to arrive. Thanks a lot for the reply!

**Comment by DiegoNogueiraDev** [comment]
I've documented a 100% reproducible case of this on AMD Barcelo (Ryzen 7 5825U) with kernel 6.17 — 15/15 boots crashed, kernel 6.8 stable. Full data and methodology: https://github.com/DiegoNogueiraDev/kernel-617-amdgpu-freeze-bug

**Comment by Tk-Glitch** [comment]
@DiegoNogueiraDev Fixed in https://github.com/torvalds/linux/commit/f7afda7fcd169a9168695247d07ad94cf7b9798f
Update your kernel.
