### ISSUE TITLE
Full tickless with gamemode?

### ISSUE THREAD

**Issue by JustCauseWhyNot** [Frogging-Family/linux-tkg#897]
Would fulltickless offer better performance if using gamemodes pin/park cores option?

**Comment by JustCauseWhyNot** [comment]
Is tickless worth using then? Sorry if ignorant question. Thank you for your answer. Since I'm using an r7 3700x I don't believe gamemodes helpful, and my nvidia gpu oc isn't working for some unknown reason. I should probably disable gamemode then.

**Comment by Tk-Glitch** [comment]
Not really for the most part. Depending on your motherboard you might see some weird positive or negative impact with it, but on desktop it *should* be mostly irrelevant.

**Comment by JustCauseWhyNot** [comment]
Thank you for the help.
