### ISSUE TITLE
Can't install on Manjaro

### ISSUE THREAD

**Issue by ItsiaBoi** [Frogging-Family/linux-tkg#90]
When trying to install on Manjaro kernel 5.8.11-1 it give the following error:

.config: Is a directory

*** Error during writing of the configuration.

make[1]: *** [scripts/kconfig/Makefile:71: oldconfig] Error 1
make: *** [Makefile:606: oldconfig] Error 2
 -> exit cleanup done

**Comment by AdelKS** [comment]
Please give the entire process you followed starting from the `git clone`. You can put the output log of `makepkg` and your custom `customization.cfg` in separate, attached, files.

**Comment by ItsiaBoi** [comment]
If I'm not wrong these are the files that you are interested in.

[log.txt](https://github.com/Frogging-Family/linux-tkg/files/5397683/log.txt)
[customization.txt](https://github.com/Frogging-Family/linux-tkg/files/5397685/customization.txt)

**Comment by AdelKS** [comment]
Oh I see, since you are running Manjaro, you should use the installation process of Archlinux, so you do, after modifying the `customization.cfg` file:

```shell
cd to/git/repo/linux58-tkg
makepkg -si
```

For now, `install.sh` will not work for arch and manjaro

**Comment by ItsiaBoi** [comment]
Thank you for the help, makepkg -si worked just fine.

**Comment by AdelKS** [comment]
Happy to help! For the next times you want to install from git, check the files in the repository: if there's a file called `PKGBUILD` then you can use `makepkg -si` on arch and manjaro to install it.
