### ISSUE TITLE
Unable to mount NTFS partition or hard drive

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#902]
Unable to mount NTFS partition or hard drive.

Kernel: 6.8.0-tkg-pds

$ sudo mount -t ntfs-3g /dev/sdd1 /run/media/dom/<HDD>

Error: ntfs-3g-mount: mount failed: Device or resource busy

Important to fix it because we need to access storage with NTFS file system.

Operating System: Fedora Linux 39
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.0_tkg_pds (64-bit)
Graphics Platform: Wayland

**Comment by ptr1337** [comment]
Upstream kernel issue. Please report at bugzilla.

**Comment by anh0516** [comment]
Well, you're using ntfs-3g. That's the old FUSE driver. Consider using the NTFS3 kernel driver included in Linux 5.15+ via `mount -t ntfs3`.

**Comment by Tk-Glitch** [comment]
Not an issue from us. Closing.
