### ISSUE TITLE
It seems like the creation of DEB debug packages might have been re-added by mistake

### ISSUE THREAD

**Issue by user414** [Frogging-Family/linux-tkg#905]
Originally there was an issue here to remove the building of debug packages

https://github.com/Frogging-Family/linux-tkg/pull/222

That lead to this commit here

https://github.com/Frogging-Family/linux-tkg/commit/e7d97fc497148b06e07ba57fe3f6d7c4d6809c98

However later on in this commit

https://github.com/Frogging-Family/linux-tkg/commit/f0ccecfdb264eb1d333552c8301aa34f57bcc63f

It was reverted and as far as I can tell from the change logs it was not suppose to be. I think by default not building debug packages is better so I would suggest to revert to the original line of

`make ${llvm_opt} -j ${_thread_num} bindeb-pkg LOCALVERSION=-${_kernel_flavor}` 

instead or potentially added an option in the customisation file for anyone that might want them.

**Comment by AdelKS** [comment]
Hello,

The problem with the `bindeb-pkg` is that it doesn't generate the package `linux-headers-${_kernelname}*.deb` which is needed for `dkms` kernel modules (e.g. `nvidia`)

**Comment by user414** [comment]
> Hello,
> 
> The problem with the `bindeb-pkg` is that it doesn't generate the package `linux-headers-${_kernelname}*.deb` which is needed for `dkms` kernel modules (e.g. `nvidia`)

Perhaps this has changed at one point? Because when I run it with bindeb-pgk it does general the linux-headers files on my end here. Can you verify?

**Comment by AdelKS** [comment]
It looks like I reverted it because of some `winesync` shenanigans #243 I need to look into it again, it's probably fine to not support `winesync` at all for RPM and DEB distros maybe

**Comment by user414** [comment]
@AdelKS Thanks for looking into this and sharing the reference issue. I was not aware of winesync so it made for some good reading, seem to be lost in the kernel patch acceptance process for a while...

> Edit: Yeah it's because of winesync that I reverted that. You are right, bindeb-pkg and binrpm-pkg are enough. But since we are not installing the linux sources in those distros, winesync is broken actually anyway.

What would be your preference to handle this? People can do it manually it's fairly easy and such a small change can likely be automatically merged by git on future update and requires no change here. Another option is simply to change it and winesync remains broken on those platform. Otherwise, winesync can be fixed on those platform by installing the source package but adding a check in the script to see if we are being built with winesync or not, if we are not we build with bindeb-pkg otherwise we can just add the srcdeb-pkg build target and install the source package. It seems from somewhere last year the kernel maintainer did some refactoring in this commit

https://github.com/torvalds/linux/commit/31f735c65d4f4825c57620f39f2fa27aa01ac172

to insure that deb-pkg=bindeb-pkg+srcdeb-pkg.

**Comment by AdelKS** [comment]
I think I have found a good way to handle this.
