### ISSUE TITLE
Fedora 33

### ISSUE THREAD

**Issue by Aeirex** [Frogging-Family/linux-tkg#91]
I have modified the install script to work with Fedora 33, as this is not out yet - I wanted to make it easier for a contributor as Fedora 33 switches to Qt 5 as default.
[install.zip](https://github.com/Frogging-Family/linux-tkg/files/5399134/install.zip)

**Comment by h3o66** [comment]
Might be better if you want to improve it, to make a PR 🐸

**Comment by Aeirex** [comment]
Fedora 32 and below do not use qt5 the way qt is used in Fedora, I can make a pull request when Fedora 33 is released.

**Comment by h3o66** [comment]
> Fedora 32 and below do not use qt5 the way qt is used in Fedora, I can make a pull request when Fedora 33 is released.

Either that, or add a condition for the different fedora versions, that Fedora 32 still works
As Fedora 32 will be still supported a bit.

**Comment by tuxtergames** [comment]
> I have modified the install script to work with Fedora 33, as this is not out yet - I wanted to make it easier for a contributor as Fedora 33 switches to Qt 5 as default.
> [install.zip](https://github.com/Frogging-Family/linux-tkg/files/5399134/install.zip)

Its not working anymore, can you fix or tell how to modify for next branchs?
 sex out 30 11:17 tuxter@fedora:linux-tkg$ ./install.sh install
Which linux distribution are you running ?
if it's not on the list, chose the closest one to it: Fedora/Suse for RPM, Ubuntu/Debian for DEB
   1) Debian
   2) Fedora
   3) Suse
   4) Ubuntu
[1-4]: 2
 -> Installing dependencies
Última verificação de data de vencimento de metadados: 0:26:00 atrás em sex 30 out 2020 10:53:40.
O pacote fedpkg-1.39-1.fc33.noarch já está instalado.
O pacote fedora-packager-0.6.0.4-2.fc33.noarch já está instalado.
O pacote rpmdevtools-9.2-1.fc33.noarch já está instalado.
O pacote ncurses-devel-6.2-3.20200222.fc33.x86_64 já está instalado.
O pacote pesign-113-13.fc33.x86_64 já está instalado.
O pacote grubby-8.40-47.fc33.x86_64 já está instalado.
O pacote qt-devel-1:4.8.7-57.fc33.x86_64 já está instalado.
O pacote libXi-devel-1.7.10-4.fc33.x86_64 já está instalado.
O pacote gcc-c++-10.2.1-6.fc33.x86_64 já está instalado.
O pacote git-2.28.0-1.fc33.x86_64 já está instalado.
O pacote ccache-3.7.11-1.fc33.x86_64 já está instalado.
O pacote flex-2.6.4-5.fc33.x86_64 já está instalado.
O pacote bison-3.6.4-3.fc33.x86_64 já está instalado.
O pacote elfutils-libelf-devel-0.181-1.fc33.x86_64 já está instalado.
O pacote openssl-devel-1:1.1.1g-15.fc33.x86_64 já está instalado.
O pacote dwarves-1.17-4.fc33.x86_64 já está instalado.
O pacote rpm-build-4.16.0-1.fc33.x86_64 já está instalado.
Dependências resolvidas.
Nada para fazer.
Concluído!
 -> Shallow git cloning linux 
Cloning into 'linux-'...
warning: Could not find remote branch linux-.y to clone.
fatal: Remote branch linux-.y not found in upstream origin
 -> exit cleanup done

**Comment by AdelKS** [comment]
Which linux version is this ? @tuxtergames

**Comment by tuxtergames** [comment]
> > I have modified the install script to work with Fedora 33, as this is not out yet - I wanted to make it easier for a contributor as Fedora 33 switches to Qt 5 as default.
> > [install.zip](https://github.com/Frogging-Family/linux-tkg/files/5399134/install.zip)
> 
> Its not working anymore, can you fix or tell how to modify for next branchs for Fedora 33?
> sex out 30 11:17 tuxter@fedora:linux-tkg$ ./install.sh install
> Which linux distribution are you running ?
> if it's not on the list, chose the closest one to it: Fedora/Suse for RPM, Ubuntu/Debian for DEB
> 
> 1. Debian
> 2. Fedora
> 3. Suse
> 4. Ubuntu
>    [1-4]: 2
>    -> Installing dependencies
>    Última verificação de data de vencimento de metadados: 0:26:00 atrás em sex 30 out 2020 10:53:40.
>    O pacote fedpkg-1.39-1.fc33.noarch já está instalado.
>    O pacote fedora-packager-0.6.0.4-2.fc33.noarch já está instalado.
>    O pacote rpmdevtools-9.2-1.fc33.noarch já está instalado.
>    O pacote ncurses-devel-6.2-3.20200222.fc33.x86_64 já está instalado.
>    O pacote pesign-113-13.fc33.x86_64 já está instalado.
>    O pacote grubby-8.40-47.fc33.x86_64 já está instalado.
>    O pacote qt-devel-1:4.8.7-57.fc33.x86_64 já está instalado.
>    O pacote libXi-devel-1.7.10-4.fc33.x86_64 já está instalado.
>    O pacote gcc-c++-10.2.1-6.fc33.x86_64 já está instalado.
>    O pacote git-2.28.0-1.fc33.x86_64 já está instalado.
>    O pacote ccache-3.7.11-1.fc33.x86_64 já está instalado.
>    O pacote flex-2.6.4-5.fc33.x86_64 já está instalado.
>    O pacote bison-3.6.4-3.fc33.x86_64 já está instalado.
>    O pacote elfutils-libelf-devel-0.181-1.fc33.x86_64 já está instalado.
>    O pacote openssl-devel-1:1.1.1g-15.fc33.x86_64 já está instalado.
>    O pacote dwarves-1.17-4.fc33.x86_64 já está instalado.
>    O pacote rpm-build-4.16.0-1.fc33.x86_64 já está instalado.
>    Dependências resolvidas.
>    Nada para fazer.
>    Concluído!
>    -> Shallow git cloning linux
>    Cloning into 'linux-'...
>    warning: Could not find remote branch linux-.y to clone.
>    fatal: Remote branch linux-.y not found in upstream origin
>    -> exit cleanup done

fix replacing qt5 to qt-devel, but now I have another issue, even with 5.9 or 5.8 branchs.

HDRTEST usr/include/misc/pvpanic.h
  HDRTEST usr/include/misc/uacce/hisi_qm.h
  HDRTEST usr/include/misc/uacce/uacce.h
  HDRTEST usr/include/misc/xilinx_sdfec.h
  HDRTEST usr/include/xen/gntdev.h
  HDRTEST usr/include/xen/gntalloc.h
  HDRTEST usr/include/xen/evtchn.h
  HDRTEST usr/include/xen/privcmd.h
  CC [M]  kernel/kheaders.o
erro: Status de saída de /var/tmp/rpm-tmp.I0QWQB inválido (%build)


Erros na construção do RPM:
    line 20: It's not recommended to have unversioned Obsoletes: Obsoletes: kernel-headers
    Status de saída de /var/tmp/rpm-tmp.I0QWQB inválido (%build)
make[1]: *** [scripts/Makefile.package:59: rpm-pkg] Erro 1
make: *** [Makefile:1523: rpm-pkg] Erro 2
 -> exit cleanup done

 sex out 30 13:39 tuxter@fedora:

**Comment by tuxtergames** [comment]
> Which linux version is this ? @tuxtergames

Fedora 33

**Comment by AdelKS** [comment]
I meant which Kernel version have you tried compiling. I will have a look at the code.

**Comment by tuxtergames** [comment]
> I meant which Kernel version have you tried compiling. I will have a look at the code.

the last message about kernel readers, I'm trying to compile 5.8 or 5.9, got the same error of kernel-headers, I'm with stock kernel 5.8.16-300.fc33.x86_64

**Comment by Aeirex** [comment]
You can try this pull request.
https://github.com/Frogging-Family/linux-tkg/pull/105

**Comment by aranym0** [comment]
This issue also affects Fedora Rawhide. 
Aeirex's pull request does seem to fix it, the RPMs build successfully.

**Comment by Tk-Glitch** [comment]
This should be fixed now that https://github.com/Frogging-Family/linux-tkg/pull/105 has been merged. Closing.
