### ISSUE TITLE
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/': The requested URL returned error: 502

### ISSUE THREAD

**Issue by newtonsart** [Frogging-Family/linux-tkg#911]
Im trying to install the kernel. I tried using my own config and the default config. both configuration files are giving the same error. I can access the website in a browser.
Ive used this kernel for quite a while and never had this issue.
Output of the command:
```
➜  linux-tkg git:(master) ✗ ./install.sh install
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/': The requested URL returned error: 502
 -> Which kernel version do you want to install?
  > 0) 
    1) 
    2) 
    3) 
    4) 
    5) 
    6) 
    7) 
    8) Another (no longer maintained upstream)
[0-8]: ^Clinux-tkg-config/prepare: line 1935: remove_deps: command not found
```

**Comment by xray-tango** [comment]
@newtonsart Hello! I've got a temporary solution for you until the source of this issue is found.
In your `customization.cfg` change `_git_mirror=` **from** `"kernel.org"` **to** `"torvalds"`
I hope this helps!

**Comment by Hyphaed** [comment]
@xray-tango option solves the problem

**Comment by Tk-Glitch** [comment]
Should be okay with https://github.com/Frogging-Family/linux-tkg/commit/1e8000fb21c886cfd55fc570a52fed1cf06584b3 and https://github.com/Frogging-Family/linux-tkg/commit/5a1cb557149122a6dcacc10b20e4027332bdad44 as long as you leave `_git_mirror` empty.
