### ISSUE TITLE
Makefile:201: *** source directory cannot contain spaces or colons. Stop.

### ISSUE THREAD

**Issue by Hyphaed** [Frogging-Family/linux-tkg#912]
at the end of the install script when is generating the DEB packages it says

Makefile:201: *** source directory cannot contain spaces or colons. Stop.

I've tried with 6.8.2 and 6.9rc1

![Screenshot from 2024-03-27 08-23-37](https://github.com/Frogging-Family/linux-tkg/assets/19622367/f8b4e5ef-4b62-42c2-a576-ae9e790ee014)

**Comment by Tk-Glitch** [comment]
How's your path to the repo?

**Comment by AdelKS** [comment]
Any news @Hyphaed ?

**Comment by Hyphaed** [comment]
sorry... the problem was solved long ago :: yet I did not remember to tell

I do not exactly what was happening 

I remember by then the repos time to time were not reachable and I needed to change the default source where it gets the kernel from

@AdelKS  are you having this problem?

btw anyone been able to compile vmware modules for kernel 6.9?

**Comment by AdelKS** [comment]
> @AdelKS are you having this problem?

No no, just to know if that got fixed and say how you fixed it if someone else encounters the same error, very useful. Then close the issue.
