### ISSUE TITLE
version 6.8.2 not able to compile

### ISSUE THREAD

**Issue by Hyphaed** [Frogging-Family/linux-tkg#914]
I'm not being able to use the main version not either the 6.8.2 version

if I download 6.8.2 source file and I run ./install.sh I get the error:

`ferran@z590i:~/Documents/PersonalPackages/linux-tkg-6.8.2$ ./install.sh 
linux-tkg-config/prepare: line 26: 7033999ecd7b8cf9ea59265035a0150961e023ee: command not found
 ==> WARNING: kernel.org unreachable or too long to respond
Defaulting to github.com git mirror
 -> Argument not recognised, options are:
        - config : interactive script that shallow clones the linux 5.x.y git tree into the folder $_kernel_work_folder, then applies extra patches and prepares the .config file
                   by copying the one from the currently running linux system and updates it.
        - install : does the config step, proceeds to compile, then prompts to install
                    - 'DEB' distros: it creates .deb packages that will be installed then stored in the DEBS folder.
                    - 'RPM' distros: it creates .rpm packages that will be installed then stored in the RPMS folder.
                    - 'Generic' distro: it uses 'make modules_install' and 'make install', uses 'dracut' to create an initramfs, then updates grub's boot entry.
        - uninstall-help : [RPM and DEB based distros only], lists the installed kernels in this system, then gives hints on how to uninstall them manually.
 -> exit cleanup done
`

same if I clone and I do ./install.sh

Shouldn't the installer get the local sources in case of using the linux-tkg-6.8.2.zip file you've released that contains the sources?

sometimes I get this error instead: ```

ferran@z590i:~/Documents/PersonalPackages/linux-tkg_old$ ./install.sh 
 -> Argument not recognised, options are:
        - config : interactive script that shallow clones the linux 5.x.y git tree into the folder $_kernel_work_folder, then applies extra patches and prepares the .config file
                   by copying the one from the currently running linux system and updates it.
        - install : does the config step, proceeds to compile, then prompts to install
                    - 'DEB' distros: it creates .deb packages that will be installed then stored in the DEBS folder.
                    - 'RPM' distros: it creates .rpm packages that will be installed then stored in the RPMS folder.
                    - 'Generic' distro: it uses 'make modules_install' and 'make install', uses 'dracut' to create an initramfs, then updates grub's boot entry.
        - uninstall-help : [RPM and DEB based distros only], lists the installed kernels in this system, then gives hints on how to uninstall them manually.
 -> exit cleanup done

```

as you can see the mirrors are not working, none of them

yet I do not have problems accesing those domains.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable
https://github.com/gregkh/linux.git
https://github.com/torvalds/linux.git

**Comment by Tk-Glitch** [comment]
You need to give `install.sh` an argument. Either `config`, `install` or `uninstall-help`, as is explained in that "error". Please check the readme: https://github.com/Frogging-Family/linux-tkg?tab=readme-ov-file#deb-debian-ubuntu-and-derivatives-and-rpm-fedora-suse-and-derivatives-based-distributions

kernel.org currently has known issues. Other mirrors are fine but torvalds repo comes with limitations.

> Shouldn't the installer get the local sources in case of using the linux-tkg-6.8.2.zip file you've released that contains the sources?

No. The script patches upstream trees to allow the user to select its own personalization and fitting optimizations.

**Comment by Hyphaed** [comment]
thanks @Tk-Glitch 

your scripts are amazing

**Comment by Hyphaed** [comment]
thanks

btw, you could add the option to compile vmware modules after installation of the new kernel (not I really miss it, yet I guess could be an interesting option), even it needs a flag to be passed, about the tags I guess would be about getting last 5 tags or the option to specify 1 manually)

git clone https://github.com/mkubecek/vmware-host-modules
cd vmware-host-modules
git checkout tags/w17.5.1
make
make install
