### ISSUE TITLE
Define AMD_PRIVATE_COLOR

### ISSUE THREAD

**Issue by Joshua-Ashton** [Frogging-Family/linux-tkg#920]
Would be cool to have this in linux-tkg kernels

**Comment by AdelKS** [comment]
Is this for HDR ? Any drawbacks to having it on ?

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux/commit/299b81f3e619aea3ceda77d7c42842a496b34a53

Here is a patch, if you need it. Requires also enabling the CONFIG Variable.

**Comment by Andorreta** [comment]
Could you add it for 6.9 please? Thanks a lot :smile:

**Comment by Tk-Glitch** [comment]
> Could you add it for 6.9 please? Thanks a lot 😄

Done https://github.com/Frogging-Family/linux-tkg/commit/2c761595bc1de52044b052bda2610cf5197f0c22
