### ISSUE TITLE
System hangs on default config

### ISSUE THREAD

**Issue by dtomvan** [Frogging-Family/linux-tkg#921]
**Describe the bug**
 - Which OS do you encounter the bug on?

I tried this on my main machine running Arch on a fairly recent tkg-bore-llvm with preemptive rt build (6.7.0-273), and also on a clean Arch Linux installation medium. (this runs linux 6.6.3). The last version I got to successfully compile without encountering this bug follows to be 6.7.

 - A clear and concise description of what the bug is.

When I start compilation, about halfway through my pc turns of it's display and any USB peripherals. I can't get access to the system anymore unless I perform a hard reset. The RGB lighting is still running though, so a shutdown wasn't being triggered... This happens even on the default customization.cfg.

 - Attach the contents of your logs folder by drag & dropping each file into this message.

I will once I get back to the PC it happened on (I'm writing this from my phone currently). I don't suspect there's anything to be seen there, but maybe I could find something in my journalctl logs. I might try compiling a vanilla kernel instead, let's see if I'm the problem (that's probably it).

**Comment by AdelKS** [comment]
You are most probably running out of RAM, are you using the tmpfs build feature ?

**Comment by dtomvan** [comment]
No, as I said. I was using the default config, which uses the PKGBUILD-folder/src/ path to build in IIRC.

**Comment by dtomvan** [comment]
I'll retry without sccache and I'll monitor RAM usage while doing so. Just for reference, I have 16 gigs of RAM, which isn't enough for a full tmpfs kernel build, I know.

**Comment by dtomvan** [comment]
I will use the following command to track my RAM over time whilst doing compilation. To make this easier to iterate on I will use kernel_on_diet with no_ccache.

```zsh
(truncate -s0 ram-usage-over-time.log; export SECS=$(date +%s); watch -n 0.5 '(echo "T=$(( $(date +%s) - $SECS ))" ; free -h) | tee -a ram-usage-over-time.log') 2>/dev/null >/dev/null &; makepkg -s | tee shell-output.log; kill %1 
```

**Comment by dtomvan** [comment]
As you can see, just before the system crashes (about 4 minutes into the compilation, the time it takes downloading the source etc is included in the T value) I still have plenty of memory left. [exerpt from ram-usage-over-time.log with the last 10 entries or 5 seconds](http://0x0.st/Xour.log)

**Comment by dtomvan** [comment]
No luck on any journalctl logs here, the journal didn't even get to properly write to disk apparently. The last write according to `stat(1)` was at 21:32:55, but the journal doesn't cover anything around that time:

```
$ journalctl --list-boots
(snip)
IDX  BOOT ID                           FIRST ENTRY                     LAST  ENTRY
-2   bc5ef9cb7f914d1e86ecd021df31ad32  Thu  2024-04-18 15:34:22  CEST  Thu 2024-04-18 15:42:15  CEST
-1   8f815b80f1da4f59ab2d22a3a8243652  Thu  2024-04-18 16:20:12  CEST  Thu 2024-04-18 21:26:37  CEST
0    792f1e673ad94c4c96a98468510ad01a  Thu  2024-04-18 21:33:36  CEST  Thu 2024-04-18 21:41:01  CEST
```

**Comment by Tk-Glitch** [comment]
Heat? Unstable OC? Broken firmware? Dying PSU, RAM, disk? OS corruption?
Since it's an isolated case and we're not doing anything fancy it's likely one or multiple of those since the logs are unhelpful.

**Comment by dtomvan** [comment]
Hmm, you're right. But I do wonder why this happened all of a sudden (I was able to compile older versions of this project) and also why vanilla linux still works. Does linux-tkg use parallel compilation whereas torvalds/linux doesn't?

**Comment by dtomvan** [comment]
Also, if it were a kernel panic or a userland problem I would've seen that error on screen, no? So the problem definitely lies in my firm/hardware...

**Comment by dtomvan** [comment]
Memtest86 doesn't report any errors on RAM, I've reset my BIOS to "optimized defaults", `stress -c $(nproc)` doesn't cause any crashes, but still specifically `linux-tkg` causes a problem. I did try to reproduce a successful previous build with `_configfile="running-kernel"`, checked out at v6.7 but no success. I guess this cannot be reproduced at all, so you wouldn't be able to help me with this issue, or fix it. I'll close this.

**Comment by Tk-Glitch** [comment]
> Hmm, you're right. But I do wonder why this happened all of a sudden (I was able to compile older versions of this project) and also why vanilla linux still works. Does linux-tkg use parallel compilation whereas torvalds/linux doesn't?

Could be related indeed. We are by default enforcing the use of all threads available, while makepkg defaults to the `/etc/makepkg.conf` settings, which is a single thread. You can change the behavior on our end with the `_force_all_threads="true"` option set to "false" in https://github.com/Frogging-Family/linux-tkg/blob/master/customization.cfg

But yes a kernel panic or a userland problem would pop up in logs imho.
