### ISSUE TITLE
Thrown into ROOTFS with no usb control.

### ISSUE THREAD

**Issue by RealMrCactus** [Frogging-Family/linux-tkg#922]
*Before reporting an issue, please check for relevant keywords in the issues search bar, including closed issues. The solution to your issue might be there already !*

**Describe the bug**
 - Which OS do you encounter the bug on? Arch Linux
 - A clear and concise description of what the bug is. Thrown into ROOTFS with no control over it i have to turn my PSU off to turn my system off and the normal Linux kernel also has been effected as my identical displays now show one as normal and the other at 640x480 labeled as NVIDIA
 - Attach the contents of your logs folder by drag & dropping each file into this message.
**Special note for Arch users: please run `makepkg [args] | tee shell-output.log` for more logging!**
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/15044936/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15044938/prepare.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/15044939/system-info.txt)

Let me know if you would like me to do the more logging.

**Comment by RealMrCactus** [comment]
The display issue was unrelated.

**Comment by RealMrCactus** [comment]
I'm using mkinitcpio when I get home in like 6 hours I can give you the stuff you requested

**Comment by RealMrCactus** [comment]
Sorry about not getting back I've been busy but could my issue possibly be that I'm using an Nvidia GPU and I'm supposed to have a package before installing? Because all I did after it compile as far as I'm aware was run `mkinitcpio -P`

**Comment by RealMrCactus** [comment]
> You need a dkms nvidia package so the module is rebuilt against your custom kernel(s). The prebuilt distro-provided nvidia non-dkms package is built against the distro-provided kernel and thus not compatible with any other kernel. We are offering a nvidia package https://github.com/Frogging-Family/nvidia-all which defaults to dkms, but the Arch package https://archlinux.org/packages/extra/x86_64/nvidia-dkms/ will work just fine as well. If you already have the dkms package installed, then something needs fixing on our end :D

I do not I will try nvidia-dkms and see how it goes if it works I will close the thread if not I'll inform

**Comment by RealMrCactus** [comment]
Yeah dkms did not work ![RealMrCactus_20240424_211848_lmc_8.4.jpg](https://github.com/Frogging-Family/linux-tkg/assets/36554881/f192f902-482f-41db-9e47-dbc69aa7239d)

**Comment by RealMrCactus** [comment]
Mind you the normal arch kernel works so uhhh yeah after compiling I just mkinitcpio -P (after grabbing dkms of course)

**Comment by Tk-Glitch** [comment]
This looks like missing filesystem driver to me. Using the diet config or modprobed-db?

**Comment by RealMrCactus** [comment]
> This looks like missing filesystem driver to me. Using the diet config or modprobed-db?

Uhhh I dunno all I do is makepkg -si and then mkinitcpio -P

**Comment by RealMrCactus** [comment]
Hello?

**Comment by Tk-Glitch** [comment]
Please check that thread and see if it's the same issue: https://bbs.archlinux.org/viewtopic.php?id=237066
I didn't think much about that early hook warning of yours initially, but it's most definitely abnormal. The file *should* be there on Arch's kernel.

We have zero reproduction case of your issue at this point. To be fair it doesn't make much sense for our package to be the culprit here considering you're using the default defconfig (which is Arch's) along with next to no customization. So the issue is more likely related to your setup, and that warning tends to solidify that theory.
Also, which bootloader are you using?

**Comment by RealMrCactus** [comment]
> Please check that thread and see if it's the same issue: https://bbs.archlinux.org/viewtopic.php?id=237066
> I didn't think much about that early hook warning of yours initially, but it's most definitely abnormal. The file *should* be there on Arch's kernel.
> 
> We have zero reproduction case of your issue at this point. To be fair it doesn't make much sense for our package to be the culprit here considering you're using the default defconfig (which is Arch's) along with next to no customization. So the issue is more likely related to your setup, and that warning tends to solidify that theory.
> Also, which bootloader are you using?

My bad for late reply I'll check out the page you sent later today and I'm using limine

**Comment by RealMrCactus** [comment]
so i think i found my issue
![image](https://github.com/Frogging-Family/linux-tkg/assets/36554881/5e8c4a7f-94b6-45f8-8674-8a9ec27a8a94)

**Comment by RealMrCactus** [comment]
well im unsure as id like to recompile the kernel but bore isnt avail for 6.9.3 and i cant try the version im currently on 6.9.1

**Comment by RealMrCactus** [comment]
![image](https://github.com/Frogging-Family/linux-tkg/assets/36554881/0e46bc69-395e-402c-999d-7b276bbad2ce)
was the issue im just dumb lol
