### ISSUE TITLE
6.6.30lts with BORE: applying patch failed

### ISSUE THREAD

**Issue by ChillDuder** [Frogging-Family/linux-tkg#927]
Hi,

as in title. 
With latest (linux-tkg 6.8.8). Worked for all 6.6 until 6.6.30 now.

[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15194661/prepare.log.txt)
[fair.c.rej.txt](https://github.com/Frogging-Family/linux-tkg/files/15194669/fair.c.rej.txt)

With e.g. bmq, patching works fine.

Thanks for your work!

**Comment by ptr1337** [comment]
> Hi,
> 
> as in title. With latest (linux-tkg 6.8.8). Worked for all 6.6 until 6.6.30 now.
> 
> [prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15194661/prepare.log.txt) [fair.c.rej.txt](https://github.com/Frogging-Family/linux-tkg/files/15194669/fair.c.rej.txt)
> 
> With e.g. bmq, patching works fine.
> 
> Thanks for your work!

Hi, 

That is due the backports from the EEVDF Scheduler. I have already talked with the developer of BORE and he will provide soon a new patchset.
As soon it is updated, it will be directly fetched from the cachyos repos the new patch.

**Comment by ChillDuder** [comment]
Thanks for the update.
