### ISSUE TITLE
Error 2 on binrpm_pkg when building latest (no rc) on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by honeymoan** [Frogging-Family/linux-tkg#939]
### System Info

```
VERSION_ID="20240509"
PRETTY_NAME="openSUSE Tumbleweed"
```

Hey,

I'm trying to build tkg on tumbleweed latest but it fails on packaging with a Error 1 then a 2 when running binrpm_pkg.

### Logs
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/15284077/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15284078/prepare.log.txt)
[run.txt](https://github.com/Frogging-Family/linux-tkg/files/15284079/run.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/15284080/system-info.txt)

**Comment by AdelKS** [comment]
Hey can you try again with latest `linux-tkg` commit so you can have one more log file `shell-output.log.txt` ? Thanks

**Comment by not-NEKO** [comment]
maybe i got the same issue don't know much
