### ISSUE TITLE
Error while patching kernel 6.9

### ISSUE THREAD

**Issue by polq1200** [Frogging-Family/linux-tkg#942]
**Describe the bug**
 - Which OS do you encounter the bug on?
 Arch Linux (but using ./install.sh config because I only want to patch the sources)
 - A clear and concise description of what the bug is.
When I try to patch kernel 6.9 I get <code>ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.</code> during applying misc additions patch. Everything is working on 6.8.9. I did a git pull but it didn't help.
- Attach the contents of your logs folder by drag & dropping each file into this message.
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/15297492/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15297493/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/15297494/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/15297495/system-info.txt)

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/1ee2da755606f14a4ce29ba6c7e866faf7d801f9
