### ISSUE TITLE
Can't compile dpkg-buildpackage: error: make -f debian/rules binary subprocess returned exit status 2

### ISSUE THREAD

**Issue by dylanmilesmsu** [Frogging-Family/linux-tkg#946]
Using Pop!_OS, I was able to compile 6.9.0-tkg-eevdf only a few days ago. Now, however, when compiling using the same options, I first get this error

`Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file drivers/gpu/drm/amd/amdgpu/amdgpu_ttm.c.rej`

Afterwards the script runs as normal, until the very end where I get this output

`  CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp2_transition.o
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  AR      drivers/gpu/built-in.a
make[5]: *** [scripts/Makefile.build:485: drivers] Error 2
make[4]: *** [Makefile:1928: .] Error 2
make[3]: *** [debian/rules:74: build-arch] Error 2
dpkg-buildpackage: error: make -f debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:121: bindeb-pkg] Error 2
make[1]: *** [/home/bfce/linux-tkg/linux-src-git/Makefile:1550: bindeb-pkg] Error 2
make: *** [Makefile:240: __sub-make] Error 2
 -> exit cleanup done
`

Not sure what could've changed in such a short time. As a sanity check, I went back to my stock kernel and tried compiling again, but encountered the same issue.

**Comment by Tk-Glitch** [comment]
Run `git pull` in your linux-tkg dir to get the required update for the tree (https://github.com/Frogging-Family/linux-tkg/commit/1ee2da755606f14a4ce29ba6c7e866faf7d801f9)

**Comment by AdelKS** [comment]
Let's consider this solved, feel free to reopen if the same problem persists.
