### ISSUE TITLE
Can't compile linux-tkg 6.10-rc1, tarball from kernel.org works / error: * was not found in the build directory and is not a URL

### ISSUE THREAD

**Issue by palWorx** [Frogging-Family/linux-tkg#947]
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"

clang version 17.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

lib32-llvm-libs 17.0.6-2
llvm 17.0.6-5
llvm-libs 17.0.6-5

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/lto-wrapper
Ziel: x86_64-pc-linux-gnu
Konfiguriert mit: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread-Modell: posix
Unterstützte LTO-Kompressionsalgorithmen: zlib zstd
gcc-Version 14.1.1 20240522 (GCC) 
COLLECT_GCC_OPTIONS='-v' '--help' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'

########################################
########################################

  -> Fetching tag: v6.10-rc1 from mirror torvalds
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Entpacke Objekte: 100% (1/1), 560 Bytes | 560.00 KiB/s, fertig.
  -> Checking out tag: v6.10-rc1
  ->    in the work folder: /home/patrice/Downloads/Compile/Kernel/linux-tkg//linux-src-git
Bereite Arbeitsverzeichnis vor (losgelöster HEAD 1613e604d)
Aktualisiere Dateien: 100% (84946/84946), fertig.
HEAD ist jetzt bei 1613e604d Linux 6.10-rc1
==> Erstelle Paket: linux610-tkg-eevdf-llvm 6.10.rc1-273 (Mo 27 Mai 2024 20:42:31 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
==> FEHLER: * wurde nicht im build Verzeichnis gefunden und ist keine URL.
  -> exit cleanup done

It doesn't matter, if I use torvalds or empty (kernel.org) git-mirror in customization.cfg or if I choose GCC or Clang/LLVM.

**Comment by Tk-Glitch** [comment]
Initial 6.10 RC support was added with https://github.com/Frogging-Family/linux-tkg/commit/b9a5327b6c3eaaa07e97d5e2881f8ca38e3a3096

**Comment by palWorx** [comment]
An hour ago I had this:
  -> Which kernel version do you want to install?
      > 0) v6.9
        1) v6.8
        2) v6.7
        3) v6.6
        4) v6.5
        5) v6.4
        6) v6.10-rc1
        7) v5.15
        8) Another (no longer maintained upstream)

Now I cloned again and got this:
  -> Which kernel version do you want to install?
        0) v6.10-rc1
      > 1) v6.9.2
        2) v6.8.11
        3) v6.7.12
        4) v6.6.32
        5) v6.5.13
        6) v6.4.16
        7) v6.10-rc1
        8) v5.15.160
        9) Another (no longer maintained upstream)

The 0 works like a charm, so thank you.
