### ISSUE TITLE
Kernel 6.1 branch no longer shows up after latest git pull

### ISSUE THREAD

**Issue by alkamine** [Frogging-Family/linux-tkg#951]
Kernel 6.1.x is no longer lsited in compile options when makepkg -si is run on an arch system. this branch is still supported and is not EOL, yet still doesnt show even in the no longer maintained submenu. was this intentional and if so, why?

**Comment by Tk-Glitch** [comment]
Was fixed with https://github.com/Frogging-Family/linux-tkg/commit/608f348308c92d4202646eb72e8c93b10dcbb8ad https://github.com/Frogging-Family/linux-tkg/commit/9c28c505bffe42093e4b4b6385a1b1ff16c0d7a2
