### ISSUE TITLE
Install script should not try to install `grubby` on Fedora

### ISSUE THREAD

**Issue by alterNERDtive** [Frogging-Family/linux-tkg#952]
**Describe the bug**
 - Which OS do you encounter the bug on?

Fedora 40

 - A clear and concise description of what the bug is.

The install script tries to install the `grubby` package on Fedora. I am not using grub2, but systemd-boot. I cannot install grubby as it conflicts with sdubby (essentially the same thing, but for systemd-boot). Systemd-boot is an official option since Fedora 39.

Anyone using grub2 should have the `grubby` package installed anyway, just like anyone using systemd-boot should have the `sdubby` package. There is no need to try and install it during the build process.

**Comment by AdelKS** [comment]
Hey, are you able to make a PR removing it from here https://github.com/Frogging-Family/linux-tkg/blob/master/install.sh#L84 ?

**Comment by alterNERDtive** [comment]
Sure! But I probably won’t get around to doing it right away.
