### ISSUE TITLE
Can't compile linux-tkg 6.10-rc3, tarball from kernel.org works / AR drivers/gpu/built-in.a

### ISSUE THREAD

**Issue by palWorx** [Frogging-Family/linux-tkg#956]
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling

clang version 17.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

lib32-llvm-libs                17.0.6-2
llvm                                 17.0.6-5
llvm-libs                          17.0.6-5

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/lto-wrapper
Ziel: x86_64-pc-linux-gnu
Konfiguriert mit: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread-Modell: posix
Unterstützte LTO-Kompressionsalgorithmen: zlib zstd
gcc-Version 14.1.1 20240522 (GCC) 
COLLECT_GCC_OPTIONS='-v' '--help' '-mtune=generic' '-march=x86-64' '-dumpdir' 'a-'

##################################

It's me again with an RC-Kernel-Problem. If the RC-Kernels are offered but not supported, let me know and I won't bother you again!

-----------------------

git_mirror=torvalds

  CC [M]  drivers/gpu/drm/nouveau/nv50_fence.o
  CC [M]  drivers/gpu/drm/nouveau/nv84_fence.o
  CC [M]  drivers/gpu/drm/nouveau/nvc0_fence.o
  LD [M]  drivers/gpu/drm/nouveau/nouveau.o
  AR      drivers/gpu/built-in.a
make[2]: *** [scripts/Makefile.build:485: drivers] Fehler 2
make[1]: *** [/home/patrice/Downloads/Compile/Kernel/linux-tkg/linux-src-git/Makefile:1943: .] Fehler 2
make: *** [Makefile:240: __sub-make] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
  -> exit cleanup done

-----------------------

git_mirror=""

==> WARNUNG: kernel.org unreachable or too long to respond
Defaulting to github.com git mirror
  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
        0) v6.10-rc1
      > 1) v6.9.3
        2) v6.8.12
        3) v6.7.12
        4) v6.6.32
        5) v6.5.13
        6) v6.4.16
        7) v6.10-rc1
        8) v5.15.160
        9) Another (no longer maintained upstream)

Option '0' and '7' are identical (no matter what mirror). This has only been the case recently. Why?

##################################

[shell-output.log](https://github.com/user-attachments/files/15778406/shell-output.log)

**Comment by AdelKS** [comment]
Should be fixed with https://github.com/Frogging-Family/linux-tkg/commit/608f348308c92d4202646eb72e8c93b10dcbb8ad for now. I will have a look at it soon.

**Comment by palWorx** [comment]
Thank you for your quick response. Now the option '7' is displayed empty.

The build still aborts!

**Comment by palWorx** [comment]
Sorry, clicked the wrong button. Reopened again!

**Comment by AdelKS** [comment]
Please do a `git pull --autostash` and try again, I do not have issues on my end
```shell
 -> Which kernel version do you want to install?
    0) v6.10-rc3
  > 1) v6.9.3
    2) v6.8.12
    3) v6.7.12
    4) v6.6.32
    5) v6.5.13
    6) v6.4.16
    7) v6.1.92
    8) v5.15.160
    9) Another (no longer maintained upstream)
[0-9]: 0
```

**Comment by palWorx** [comment]
You are right, it only happens with git_mirror = "torvalds"

  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
        0) v6.10-rc3
      > 1) v6.9
        2) v6.8
        3) v6.7
        4) v6.6
        5) v6.5
        6) v6.4
        7) 
        8) v5.15
        9) Another (no longer maintained upstream)
[0-9]:

**Comment by Tk-Glitch** [comment]
@palWorx Fixed on torvalds mirror as well with https://github.com/Frogging-Family/linux-tkg/commit/9c28c505bffe42093e4b4b6385a1b1ff16c0d7a2
