### ISSUE TITLE
Sched_ext support patch failed kernel 6.9.7

### ISSUE THREAD

**Issue by damachine** [Frogging-Family/linux-tkg#961]
hello last kernel update i see a fail in Sched_ext support patch.
`           .---.`               `.---.
        `/syhhhyso-           -osyhhhys/`
       .syNMdhNNhss/``.---.``/sshNNhdMNys.
       +sdMh.`+MNsssssssssssssssNM+`.hMds+
       :syNNdhNNhssssssssssssssshNNhdNNys:
        /ssyhhhysssssssssssssssssyhhhyss/
        .ossssssssssssssssssssssssssssso.
       :sssssssssssssssssssssssssssssssss:
      /sssssssssssssssssssssssssssssssssss/   Linux-tkg
     :sssssssssssssoosssssssoosssssssssssss:        kernels
     osssssssssssssoosssssssoossssssssssssso
     osssssssssssyyyyhhhhhhhyyyyssssssssssso
     /yyyyyyhhdmmmmNNNNNNNNNNNmmmmdhhyyyyyy/
      smmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmms
       /dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNd/
        `:sdNNNNNNNNNNNNNNNNNNNNNNNNNds:`
           `-+shdNNNNNNNNNNNNNNNdhs+-`
                 `.-:///////:-.`
  -> External configuration file /home/damachine/.config/frogminer/linux-tkg.cfg will be used and will override customization.cfg values.
  -> Defaulting to Archlinux target

  -> Which kernel version do you want to install?
        0) v6.10-rc5
      > 1) v6.9.7
        2) v6.8.12
        3) v6.7.12
        4) v6.6.36
        5) v6.5.13
        6) v6.4.16
        7) v6.1.96
        8) v5.15.161
        9) Another (no longer maintained upstream)
[0-9]:
    Selected: v6.9.7
  -> First initialization of the linux source code git folder
Leeres Git-Repository in /home/damachine/.tkg/temp/linux-tkg/linux-kernel.git/ initialisiert
  -> Fetching tag: v6.9.7 from mirror github.com
remote: Enumerating objects: 89344, done.
remote: Counting objects: 100% (89344/89344), done.
remote: Compressing objects: 100% (82569/82569), done.
remote: Total 89344 (delta 9642), reused 23157 (delta 5856), pack-reused 0
Empfange Objekte: 100% (89344/89344), 246.05 MiB | 5.48 MiB/s, fertig.
Löse Unterschiede auf: 100% (9642/9642), fertig.
Von https://github.com/gregkh/linux
 * [neues Tag]           v6.9.7     -> v6.9.7
  -> Checking out tag: v6.9.7
  ->    in the work folder: /home/damachine/.tkg/temp/linux-tkg//linux-src-git
Bereite Arbeitsverzeichnis vor (losgelöster HEAD 12c740d50)
Aktualisiere Dateien: 100% (84341/84341), fertig.
HEAD ist jetzt bei 12c740d50 Linux 6.9.7
==> Erstelle Paket: linux-tkg 6.9.7-273 (Do 27 Jun 2024 15:01:38 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> 90-cleanup.hook gefunden
  -> cleanup gefunden
  -> config.x86_64 gefunden
  -> minimal-modprobed.db gefunden
  -> 0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch gefunden
  -> 0002-clear-patches.patch gefunden
  -> 0003-glitched-base.patch gefunden
  -> 0003-glitched-cfs.patch gefunden
  -> 0003-glitched-eevdf-additions.patch gefunden
  -> 0005-glitched-pds.patch gefunden
  -> 0006-add-acs-overrides_iommu.patch gefunden
  -> 0007-v6.9-fsync1_via_futex_waitv.patch gefunden
  -> 0007-v6.9-ntsync.patch gefunden
  -> 0009-glitched-bmq.patch gefunden
  -> 0009-prjc_v6.9-r0.patch gefunden
  -> 0012-misc-additions.patch gefunden
  -> 0013-fedora-rpm.patch gefunden
  -> 0013-optimize_harder_O3.patch gefunden
  -> 0013-suse-additions.patch gefunden
  -> 0014-OpenRGB.patch gefunden
==> Überprüfe source Dateien mit sha256sums...
    90-cleanup.hook ... Übersprungen
    cleanup ... Übersprungen
    config.x86_64 ... Übersprungen
    minimal-modprobed.db ... Übersprungen
    0001-add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by.patch ... Übersprungen
    0002-clear-patches.patch ... Übersprungen
    0003-glitched-base.patch ... Übersprungen
    0003-glitched-cfs.patch ... Übersprungen
    0003-glitched-eevdf-additions.patch ... Übersprungen
    0005-glitched-pds.patch ... Übersprungen
    0006-add-acs-overrides_iommu.patch ... Übersprungen
    0007-v6.9-fsync1_via_futex_waitv.patch ... Übersprungen
    0007-v6.9-ntsync.patch ... Übersprungen
    0009-glitched-bmq.patch ... Übersprungen
    0009-prjc_v6.9-r0.patch ... Übersprungen
    0012-misc-additions.patch ... Übersprungen
    0013-fedora-rpm.patch ... Übersprungen
    0013-optimize_harder_O3.patch ... Übersprungen
    0013-suse-additions.patch ... Übersprungen
    0014-OpenRGB.patch ... Übersprungen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
==> Beginne prepare()...
  -> Using Arch patches
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29004  100 29004    0     0  55657      0 --:--:-- --:--:-- --:--:-- 55563
  -> Applying graysky's cpu opts patch
  -> Applying clear linux patches
  -> Applying glitched base patch
  -> Skipping patch 0003-glitched-base-nonrt.patch...
         (unavailable for this kernel version)
  -> RPM: fixing spec generator
  -> Applying misc additions patch
  -> Skipping patch 0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch...
         (unavailable for this kernel version)
  -> Skipping patch 0002-mm-Support-soft-dirty-flag-read-with-reset.patch...
         (unavailable for this kernel version)
  -> Applying Glitched EEVDF additions patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  717k  100  717k    0     0  1903k      0 --:--:-- --:--:-- --:--:-- 1904k
  -> Applying Sched_ext support patch
==> FEHLER: An error was encountered applying patches. It was logged to the prepare.log.txt file.
  -> Applying Glitched CFS/EEVDF patch
  -> Using archlinux's default config file for kernel 6.9
  -> Patching O3 optimization
  -> Patching NTsync support
  -> Import OpenRGB patch`

**Comment by ptr1337** [comment]
I have synced them here:
https://github.com/CachyOS/kernel-patches/commit/8079c597f6a2f4dfb702350729bd0fab0de1e4a4

**Comment by Tk-Glitch** [comment]
Thanks Peter!
