### ISSUE TITLE
Kernel cannot reach maximum turbo boost frequency of AMD Ryzen 7 CPU

### ISSUE THREAD

**Issue by Everest10** [Frogging-Family/linux-tkg#962]
After successfully completing the CPU settings in the BIOS for Turbo Boost on the Windows 11 operating system the CPU works normally reaching the maximum Turbo Boost clock of 4.6Ghz but Linux with the 6.9.7-tkg kernel or the standard 6.9.6 kernel cannot reach the maximum Turbo Boost clock. The maximum verified by terminal and with CPU-X was 4.4Ghz.

$ cpupower frequency-info
Return: Turbo boost off.

Trying to fix with:
# sh -c "echo '1' > /sys/devices/system/cpu/cpufreq/boost"
Return: Turbo boost on but when checking in the terminal or CPU-X the maximum clock remains 4.4ghz besides not remaining persistent after logout.

Same problem happen with default kernel 6.9.6 with fsync modules installed.

btw on Windows the CPU Multiplier show 46x, on Fedora Linux with tkg kernel show 44x and sometimes 42x.

Is there a workaround to fix it ?

![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/24aeab5b-8db7-4cb8-9953-6ce6288ebcb7)

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.1
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.1
Kernel Version: 6.9.7_tkg_pds (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Manufacturer: ASUS

King regards,

**Comment by ptr1337** [comment]
How about if you set amd-pstate=active to your kernel cmdline?

Also, you could try to apply following patches, which improves the frequency calculation, when amd-pstate is suedhttps://github.com/CachyOS/kernel-patches/blob/master/6.9/0002-amd-pstate.patch

**Comment by Everest10** [comment]
> How about if you set amd-pstate=active to your kernel cmdline?
> 
> Also, you could try to apply following patches, which improves the frequency calculation, when amd-pstate is used https://github.com/CachyOS/kernel-patches/blob/master/6.9/0002-amd-pstate.patch

OK, I did it but after generating grub again nothing different happens.

![Screenshot_20240629_194905](https://github.com/Frogging-Family/linux-tkg/assets/7228207/893a927b-071a-4ca4-a4dd-a98572c9b0dc)

I can't to try add this patch because I'm not a programmer.

Best regards,

**Comment by Everest10** [comment]
> How about if you set amd-pstate=active to your kernel cmdline?
> 
> Also, you could try to apply following patches, which improves the frequency calculation, when amd-pstate is used https://github.com/CachyOS/kernel-patches/blob/master/6.9/0002-amd-pstate.patch

Around 42~44x cpu multiplier with scaling governor Performance. The expected is 46x 4600Mhz or 4.6ghz+ the turbo boost.

Now with amd-pstate in the grub kernel cmdline and patched using https://github.com/CachyOS/kernel-patches/blob/master/6.9/0002-amd-pstate.patch

![Screenshot_20240630_030431](https://github.com/Frogging-Family/linux-tkg/assets/7228207/2f75a76d-51a7-40ff-9b37-d45efab5a10e)

**Comment by Everest10** [comment]
@Tk-Glitch @ptr1337 Guys, nothing?

**Comment by ptr1337** [comment]
Actually, you are running an all core workload on linux, but being idle on windows. Likely your CPU can not hold it to keep 4.6 GHz up.

You should check in a slight workload with maximum 2 cores, how high they are boosting.

Also, sudo cpupower frequncy-info gives you out, what is the highest possible frequency.

**Comment by Everest10** [comment]
> Actually, you are running an all core workload on linux, but being idle on windows. Likely your CPU can not hold it to keep 4.6 GHz up.
> 
> You should check in a slight workload with maximum 2 cores, how high they are boosting.
> 
> Also, sudo cpupower frequncy-info gives you out, what is the highest possible frequency.

Not idle. On windows the power plan is set to high performance and the cpu multiplier go to 46x 4.6Ghz vs 44x 4.4~4.5Ghz on Linux. The Ryzen 7 5700x can't keep 4.6Ghz ?? What makes you think that? This processor can go beyond that.

**Comment by ptr1337** [comment]
> > Actually, you are running an all core workload on linux, but being idle on windows. Likely your CPU can not hold it to keep 4.6 GHz up.
> > You should check in a slight workload with maximum 2 cores, how high they are boosting.
> > Also, sudo cpupower frequncy-info gives you out, what is the highest possible frequency.
> 
> Not idle. On windows the power plan is set to high performance and the cpu multiplier go to 46x 4.6Ghz vs 44x 4.4~4.5Ghz on Linux. The Ryzen 7 5700x can't keep 4.6Ghz ?? What makes you think that? This processor can go beyond that.

Setting it to high performance just will it stick to the highest performance level. Looking on the screenshot above youre running on linux a kernel compilation, while youre in windows in idle.

You should check the cpu frequency on windows, when running prime95 or equal. Also, I have gave you also a command to check the highest possible frequency in linux, which you kinda ignore.

If you think its a linux bug, report to to bugzilla.kernel.org

**Comment by ptr1337** [comment]
Also looking into reddit, 4.3 GHz for a 5800X under all core load is very common. I think youre mixing things heavily up and do not understand how boost works.

**Comment by Everest10** [comment]
> > > Actually, you are running an all core workload on linux, but being idle on windows. Likely your CPU can not hold it to keep 4.6 GHz up.
> > > You should check in a slight workload with maximum 2 cores, how high they are boosting.
> > > Also, sudo cpupower frequncy-info gives you out, what is the highest possible frequency.
> > 
> > 
> > Not idle. On windows the power plan is set to high performance and the cpu multiplier go to 46x 4.6Ghz vs 44x 4.4~4.5Ghz on Linux. The Ryzen 7 5700x can't keep 4.6Ghz ?? What makes you think that? This processor can go beyond that.
> 
> Setting it to high performance just will it stick to the highest performance level. Looking on the screenshot above youre running on linux a kernel compilation, while youre in windows in idle.
> 
> You should check the cpu frequency on windows, when running prime95 or equal. Also, I have gave you also a command to check the highest possible frequency in linux, which you kinda ignore.
> 
> If you think its a linux bug, report to to bugzilla.kernel.org

`❯ cpupower frequency-info
analyzing CPU 0:
  driver: acpi-cpufreq
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 2.20 GHz - 4.66 GHz
  available frequency steps:  3.40 GHz, 2.80 GHz, 2.20 GHz
  available cpufreq governors: conservative ondemand userspace powersave performance schedutil
  current policy: frequency should be within 2.20 GHz and 3.40 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 3.53 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: no`

In the first topic I ran the the cpupower frequency-info. Check it.

The problem is that on Linux it is showing different results:
1. As specified by the manufacturer;
2. Displayed in the BIOS;
3. And displayed into Windows 11;

This Ryzen have three available frequency steps:  2.20 GHz, 2.80 GHz, 3.40 GHz. hardware limits: 2.20 GHz - 4.66 GHz (Turbo boost)
If on Linux the Turbo boost is Active or not it doesn't matter ever will how 4.4Ghz on turbo boost.
The instrumentation in Linux is showing different results when compared to another operating system and different from the manufacturer's maximum specification.

![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/968d5773-c7cd-467d-9a83-d97f5c41d14d)

**Comment by Tk-Glitch** [comment]
CPU boost depends on load, temps and power usage. You cannot expect a 5700X to boost to 4.6GHz+ with a heavy load like kernel compilation. Try running OCCT on Windows and you'll see your CPU throttle below boost clocks just as well, and that's fully expected. Nothing abnormal here. Closing as invalid.
