### ISSUE TITLE
[OpenSUSE] Patching Error

### ISSUE THREAD

**Issue by Lailanater** [Frogging-Family/linux-tkg#966]
**NAME="openSUSE Tumbleweed"
VERSION="20240705"**

I am unable to compile linux-tkg kernels now on OpenSUSE. While going through the `./install.sh install` script command eventually there is an error logged about failed patches for OpenSUSE. I see the latest commit made a change for OpenSUSE so I tried to revert that commit locally to see if that was the culprit, but that does not seem to be the case either. It seems to fail for me period now. I have attached the logs and files mentioned in the logs, but unfortunately I'm not able to fix it myself. I am able to go through the full script, but after some time the build eventually fails and I'm assuming the culprit is due to the patching error

For convenience here is a screenshot of the errors:

 
![image](https://github.com/Frogging-Family/linux-tkg/assets/9683142/226c5ba8-fcf8-4446-98c0-9f0e6a48fa21)

![image](https://github.com/Frogging-Family/linux-tkg/assets/9683142/b2a8dee0-4d78-406c-9208-0084b1615dd3)

If there is any other information that I could provide please let me know and I would be happy to provide it.
[shell-output.log](https://github.com/user-attachments/files/16144442/shell-output.log)
[prepare.log.txt](https://github.com/user-attachments/files/16144444/prepare.log.txt)
[kernel.spec.rej.txt](https://github.com/user-attachments/files/16144450/kernel.spec.rej.txt)

**Comment by l3liss** [comment]
encountering similar issues, been compiling the last few days and everything was going well then suddenly they stopped compiling, i was on fedora doing my testing so i hopped over to my arch install and i am having the same issues.
![tkg](https://github.com/Frogging-Family/linux-tkg/assets/27566709/d73d71c1-b853-4478-9c67-5864e21fe875)

**Comment by Tk-Glitch** [comment]
@l3liss No issue in the CI for 6.9.8 on Arch so that looks suspect. Not the same issue though, so if this persists, please open a new one. Thanks !
