### ISSUE TITLE
config for 6.6 kernel needs update

### ISSUE THREAD

**Issue by mabod** [Frogging-Family/linux-tkg#972]
The config for the 6.6 kernel still has 

```
CONFIG_PREEMPT_VOLUNTARY=y
# CONFIG_PREEMPT is not set
```

but it should be similar to what kernel 6.9 has:

```
# CONFIG_PREEMPT_VOLUNTARY is not set
CONFIG_PREEMPT=y
```

Also, there are a couple of new config options which should be added:

```
Mitigations for CPU vulnerabilities (CPU_MITIGATIONS) [Y/n/?] (NEW) 
  RFDS Mitigation (MITIGATION_RFDS) [Y/n/?] (NEW) 
  Mitigate Spectre-BHB (Branch History Injection) (MITIGATION_SPECTRE_BHI) [Y/n/?] (NEW) 
Ilitek ILI9341 240x320 QVGA panels (DRM_PANEL_ILITEK_ILI9341) [N/m/y/?] (NEW) 
Analog Devices AD9467 High Speed ADC driver (AD9467) [N/m/?] (NEW) 
Analog Devices Generic AXI ADC IP core driver (ADI_AXI_ADC) [N/m/?] (NEW) 
```

**Comment by ptr1337** [comment]
I think it follows arch LTS Kernel, which uses VOLUNTARY. So I think this is fine.

**Comment by Tk-Glitch** [comment]
Regarding voluntary preemption, see https://github.com/Frogging-Family/linux-tkg/commit/04f42ae83a75c3943d0242cec775121dade9d2f1

The other config options will be updated.

**Comment by Tk-Glitch** [comment]
Fixed with https://github.com/Frogging-Family/linux-tkg/commit/8a09c0e81a32253998a060a437cce5a3585ba65f
