### ISSUE TITLE
winesync module issues with kernel 6.10

### ISSUE THREAD

**Issue by Hyphaed** [Frogging-Family/linux-tkg#973]
make -j8 KERNELRELEASE=6.10.0-tkg-full KERNEL_SOURCE_DIR=/lib/modules/6.10.0-tkg-full/build...(bad exit status: 2)
ERROR (dkms apport): binary package for winesync-dkms: @PKGVER@ not found
Error! Bad return status for module build on kernel: 6.10.0-tkg-full (x86_64)
Consult /var/lib/dkms/winesync-dkms/@PKGVER@/build/make.log for more information.
dkms autoinstall on 6.10.0-tkg-full/x86_64 succeeded for nvidia openrazer-driver v4l2loopback
dkms autoinstall on 6.10.0-tkg-full/x86_64 failed for winesync(10) winesync-dkms(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.10.0-tkg-full
   ...fail!

I guess is related to this known issues with NTSYNC (since NTSync = Winesync+Fastsync)
https://www.phoronix.com/news/Linux-6.10-NTSYNC-Broken

this option should be added as well in the customization.cfg right?
_winesync="true"
_use_fastsync="true"

I haven't seen _use_fastsync="true"  in the customization.cfg that comes with tkg, but people talk about it on NTsync github

**Comment by Tk-Glitch** [comment]
6.10's ntsync is broken/incomplete. We do not offer a patch to repair it at this point in time and no .cfg option will fix it. If you want to use ntsync you need to stay on 6.9.y or below for now.

**Comment by Tk-Glitch** [comment]
Also, fastsync is a deprecated name for ntsync, nothing more.

**Comment by Tk-Glitch** [comment]
Should be alright now after https://github.com/Frogging-Family/linux-tkg/commit/5b0c4b516b6b042ec256a953308d31aba6f32d90 and https://github.com/Frogging-Family/linux-tkg/commit/d2fda0b3b7f47ce84a869e81d472b3728704ee46

**Comment by Hyphaed** [comment]
@Tk-Glitch 

I've just tried to apply the patch (first time I try to apply user patches)

I've tried following 2 methods

1 :: Placing the patch at

./linux-tkg-patches/6.10/

2 :: Placing the patch at

./linux610-tkg-userpatches

that's the content of customization.cfg (refering to patches):

_community_patches=""
_user_patches="true"


I got same error as before

```
$ dkms autoinstall on 6.10.0-tkg-eevdf/x86_64 failed for winesync(10) winesync-dkms(10)
$ installed linux-image-6.10.0-tkg-eevdf package post-installation script subprocess returned error exit status 11

```

What I'm doing wrong?

**Comment by ptr1337** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/linux-api-headers/-/issues/2

Created issue at archlinux. Maybe heftig thinks about patching it for the headers.

**Comment by Hyphaed** [comment]
@Tk-Glitch 

I've placed 0008-ntsync.patch inside /linux-tkg-patches/6.10

yet still getting the error when compiling the kernel

dkms autoinstall on 6.10.1-tkg-eevdf/x86_64 failed for winesync(10) winesync-dkms(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.10.1-tkg-eevdf    

because of this I need to uninstall the last kernel and compile from 6.9.9

what I'm doing wrong? how I should proceed to solve it?

many thanks,
congrats for your great work
