### ISSUE TITLE
Makefile error 2 while compiling kernel 

### ISSUE THREAD

**Issue by sheikh1233** [Frogging-Family/linux-tkg#978]
[prepare.log.txt](https://github.com/user-attachments/files/16318058/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/16318060/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/16318062/system-info.txt)
[customization.cfg.txt](https://github.com/user-attachments/files/16318063/customization.cfg.txt)

On Gentoo Linux, during the compilation of the kernel, an error that states 

make[1]: *** [/home/*****/linux-tkg/linux-src-git/Makefile:1937: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2

 (Name of my home directory is censored because it has my real name), and the exit cleanup happens. The text files with all the logs are attached above. I made sure to change the _configfile to "running-kernel" like the Gentoo section says, as I am using OpenRC. This happens without configuring the kernel with menuconfig.

**Comment by sheikh1233** [comment]
This is currently happening with kernel 6.10, with all the prompts in ./install.sh set to their defaults.

**Comment by sheikh1233** [comment]
This still happens on 6.10 with ccache disabled, all the zen/liquorix patches disabled, clear linux patches disabled.

**Comment by aalhitennf** [comment]
Same, tried with 6.10 and 6.9.10. Just pressed enter on all questions to use defaults.

```
  CC [M]  drivers/gpu/drm/amd/amdgpu/../display/modules/hdcp/hdcp2_transition.o
  LD [M]  drivers/gpu/drm/amd/amdgpu/amdgpu.o
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
make[1]: *** [/home/olli/temp/linux-tkg/linux-src-git/Makefile:1921: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
  -> exit cleanup done
```

**Comment by ptr1337** [comment]
@sheikh1233 
```
  AR      usr/built-in.a
make[3]: *** No rule to make target '/var/tmp/portage/sys-kernel/gentoo-kernel-6.6.35/temp/kernel_key.pem', needed by 'certs/signing_key.x509'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  HOSTCC  certs/extract-cert
  CC      arch/x86/coco/tdx/tdx.o
  AS      arch/x86/entry/entry.o
make[2]: *** [scripts/Makefile.build:485: certs] Error 2
make[2]: *** Waiting for unfinished jobs...
```

It seems to search for keys to sign the kernel

**Comment by Tk-Glitch** [comment]
Duplicate of https://github.com/Frogging-Family/linux-tkg/issues/948

**Comment by sheikh1233** [comment]
I will close this and continue further discussion in #948 then.
