### ISSUE TITLE
Applying the "tkgpatch" resulted in a segmentation fault 

### ISSUE THREAD

**Issue by alibayeh** [Frogging-Family/linux-tkg#979]
OS: Arch
GCC: 14.1.1 20240522

Modified lines in customization.cfg:
  _distro="Arch"
  _version="6.9.10"
  _git_mirror="kernel.org"
  _menunconfig="false"
  _cpusched="eevdf"
  _rr_interval="default"
  _compileroptlevel="2"
  _processor_opt="skylake"
  _NR_CPUS_value="$(nproc)"

[prepare.log.txt](https://github.com/user-attachments/files/16322605/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/16322606/shell-output.log.txt)

Shell output:
```shell
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore : No such file or directory
patch: **** Can't rename file ./.gitignore.ogpTLyg to .gitignore/DATA/LINUX_KERNELS/linux-tkg/linux-tkg-config/prepare: line 629: 27070 Segmentation fault      (core dumped) patch -Np1 -i "$tkgpatch" >> "$_where"/logs/prepare.log.txt
==> ERROR: An error was encountered applying patches. It was logged to the prepare.log.txt file.
```

**Comment by Tk-Glitch** [comment]
Is that WSL?

**Comment by alibayeh** [comment]
> Is that WSL?

No.
The running kernel has been successfully built using the "6.9.8" version and a similar configuration.

**Comment by Tk-Glitch** [comment]
And it's segfaulting in a reproducible manner? I mean, that patch error points to some broken path/working directory, patch binary, or some wrapper conflicting and doesn't seem to have any link to what we're doing here. If it works with a different kernel version it most definitely isn't our issue. The prepare log also shows patches are applied correctly so it's not our patching function either. I've never seen such an error nor was it ever reported over years of this script's existence. It's also not reproducible on any machine I have nor our CI.

Did you play with `_kernel_work_folder` and/or `_kernel_source_folder` cfg options, possibly?
Is this some Intel 13/14th series CPU maybe?

**Comment by alibayeh** [comment]
@Tk-Glitch  I found the main reason for the issue in the logs of another process: "Too many open files." 
It seems that the system has reached its limits due to running multiple processes. 
I was just wondering why there was no relevant information in the compilation logs. 
Thank you!

**Comment by Tk-Glitch** [comment]
I definitely wouldn't have thought of that! Happy you got it fixed :)
