### ISSUE TITLE
is upds now for every kernel version a valid option?

### ISSUE THREAD

**Issue by Axilot** [Frogging-Family/linux-tkg#98]

**Comment by cajual** [comment]
Flightless Mango shows consistently higher performance with BDQ, so I'm not sure if UPDS is necessarily valid as much as there are people that don't like change.

**Comment by Axilot** [comment]
So you would recommend using BDQ over UPDS?

**Comment by AdelKS** [comment]
Are you talking about this benchmark : https://flightlessmango.com/benchmarks/rM7Rfu4swVQ ? It seems to be dependent on the game. In any case, upds should be forgotten about. TKG is not its author and has other things to do than maintaining it, especially that the original author is working on PDS.

@Axilot you should try each of them in the games you play so you know. That's the only way to know. The difference between schedulers is although marginal, ~3fps difference.

**Comment by Axilot** [comment]
Oh ok. And for just normal tasks there is not even anything to notice?

**Comment by Axilot** [comment]
Then i might stick with cfs and the included patchsets by tkglitch?

**Comment by AdelKS** [comment]
For Desktop use I don't think you will notice anything. Just try two of them out ! Try for example CFS and PDS. Use `modprobed-db` to compile faster and just to see how it works, then compile without it once you are decided.

**Comment by Axilot** [comment]
Is it reasonable to use modprobed-db or could this break some apps in the future?

**Comment by AdelKS** [comment]
If you compile with `modprobed-db` few things will probably not work, I suggested that you use so you compile faster (if that's a problem for you) so you can try the different schedulers. Then once you decide which scheduler you want, you compile without it the scheduler you want.

**Comment by Axilot** [comment]
Ah okay. Thanks :+1:

**Comment by Tk-Glitch** [comment]
UPDS is now back from the grave for 5.9.y and 5.10rc1

https://github.com/Frogging-Family/linux-tkg/commit/3ec64c8b5e47ebac0f39fd878754c4ce2ec6a264
https://github.com/Frogging-Family/linux-tkg/commit/9d110b2c694118d60b5a537b17abaa682276a05f
