### ISSUE TITLE
Conflict with linux-api-headers (6.10-1)

### ISSUE THREAD

**Issue by hanzbadua** [Frogging-Family/linux-tkg#980]
Package `linux-api-headers` cannot update from 6.8-1 to 6.10-1 due to file conflict (`linux-api-headers` claims `/usr/include/linux/ntsync.h` but is owned by tkg-built kernels)

**Comment by hartigan43** [comment]
Confirming this as well:

```
(158/158) checking for file conflicts                                                                                                                                                            [########################################################################################################################] 100%
error: failed to commit transaction (conflicting files)
linux-api-headers: /usr/include/linux/ntsync.h exists in filesystem (owned by linux610-tkg-eevdf)
Errors occurred, no packages were upgraded.
```

**Comment by s0mebodyhelpme** [comment]
Same here. Running paru -Syu on Arch yields the following:
```
error: failed to commit transaction (conflicting files)
linux-api-headers: /usr/include/linux/ntsync.h exists in filesystem (owned by ntsync-header)
Errors occurred, no packages were upgraded.
```

**Comment by Galcian79** [comment]
Same issue.

**Comment by Tk-Glitch** [comment]
> Same here except I'm using the ntsync packages from the AUR. Running paru -Syu on Arch yields the following:
> 
> ```
> error: failed to commit transaction (conflicting files)
> linux-api-headers: /usr/include/linux/ntsync.h exists in filesystem (owned by ntsync-header)
> Errors occurred, no packages were upgraded.
> ```
> 
> Does this mean the option in the customization.cfg to patch in ntsync and the aur packages are obsolete?

Yours is different as it's linked to the ntsync-header package and not ours, but yeah the header is shipped with 6.10 linux-api-headers now so you should get rid of that AUR package.

**Comment by ptr1337** [comment]
FYI, the linux-api-headers 6.10 (from arch) is differently to the one, which is provided by the patchset.
So, basically this is a half baked header.

**Comment by Tk-Glitch** [comment]
The 6.10 situation was going to be annoying for ntsync, we saw it coming. But we were doing something incorrect in our package independently of that and even for those not using ntsync the conflict would happen. That one is fixed at least.

**Comment by ptr1337** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/linux-api-headers/-/issues/2

Reported to archlinux, lets see if heftig will patch/merge it.

**Comment by GrabbenD** [comment]
**Workaround** if you're not updating the kernel:

```bash
paru -Syu --ignore linux-api-headers linux
```
