### ISSUE TITLE
RPM build error on Open Suse

### ISSUE THREAD

**Issue by PC-Heini** [Frogging-Family/linux-tkg#987]
- Which OS do you encounter the bug on?
I tried it on Open Suse Tumbleweed on my PC and on Open Suse Leap 15.6 in a VM and in a distrobox.

 - A clear and concise description of what the bug is.
Installing the dependences and compiling seemed fine but when the script tries to "package" the RPM for Suse it fails.

 - Attach the contents of your logs folder by drag & dropping each file into this message.
```
RPM build errors:
    File not found: /home/pc-heini/Downloads/custom-kernel/linux-tkg/linux-src-git/rpmbuild/BUILDROOT/kernel-6.10.2_tkg_bore-1.x86_64/usr/lib/modules/6.10.2_tkg_bore/build
make[2]: *** [scripts/Makefile.package:71: binrpm-pkg] Fehler 1
make[1]: *** [/home/pc-heini/Downloads/custom-kernel/linux-tkg/linux-src-git/Makefile:1560: binrpm-pkg] Fehler 2
make: *** [Makefile:240: __sub-make] Fehler 2
 -> exit cleanup done
```
Fehler = error in german

Links to full logs:
[customization.cfg.txt](https://github.com/user-attachments/files/16471284/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/16471285/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/16471286/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/16471287/system-info.txt)

**Comment by abrasmelin** [comment]
I am having the same error in tumbleweed.

**Comment by AdelKS** [comment]
Please install the `kmod` package and try again
