### ISSUE TITLE
ACPI BIOS Error

### ISSUE THREAD

**Issue by Hyphaed** [Frogging-Family/linux-tkg#988]
using: Kernel: 6.10.3-tkg-eevdf 

I get his error during boot:

{ 9.248480] ACPI BIOS Error (bug): Failure creating named object [\_SB.Pcee_P EG1._PRT], AE_ALREADY_EXISTS (20240322/dswload2-326)

{  @.248487] ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (262463 22/psob ject -228)

**Comment by ptr1337** [comment]
Thats a BIOS issue and needs to be fixed by your motherbaord vendor

**Comment by Tk-Glitch** [comment]
Not an issue from us. Closing.
