### ISSUE TITLE
make error (opensuse)

### ISSUE THREAD

**Issue by gamerowski** [Frogging-Family/linux-tkg#992]
i get such error after compiling on opensuse tumbleweed
![image](https://github.com/user-attachments/assets/8a7e52e9-1034-4ed2-b14c-ad898d17c5c8)
[customization.cfg.txt](https://github.com/user-attachments/files/16570669/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/16570670/prepare.log.txt)
[shell-output.log.txt](https://github.com/user-attachments/files/16570671/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/16570672/system-info.txt)

**Comment by Chillsmeit** [comment]
Just to report that I get the exact same issue in OpenSUSE Tumbleweed

**Comment by hakabe** [comment]
Same issue here. Even the install.sh fails to install build essential packages and fails on 1 precheck.
Tried with clang and gcc, different versions same result.
Tried with newest OpenSUSE Tumbleweed and Regata OS.

Waiting for the Authors to try installing this on SUSE and fix the script or remove the install option completely for SUSE.

**Comment by sekasorto93** [comment]
Same issue as above. OpenSUSE Tumbleweed.

**Comment by Everest10** [comment]
Same issue as above. Fedora 41.

**Comment by AdelKS** [comment]
By looking at [shell-ouput.log.txt](https://github.com/user-attachments/files/16570671/shell-output.log.txt) it feels like it's truncated. The compilation looks like it finishes entirely. So if it's failing it's failing at the  step where the RPMs  are made

**Comment by Everest10** [comment]
try again to compile on fedora 41 and can't, follow the logs.

[shell-output.log.txt](https://github.com/user-attachments/files/17183065/shell-output.log.txt)
[system-info.txt](https://github.com/user-attachments/files/17183066/system-info.txt)
[customization.cfg.txt](https://github.com/user-attachments/files/17183067/customization.cfg.txt)
[prepare.log.txt](https://github.com/user-attachments/files/17183068/prepare.log.txt)
